### ISSUE TITLE
printf / sprintf formatting strings with format specifiers are not always colored correctly

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4708] opened 2018-04-09 23:50 UTC
See screenshot, these formatting specifiers are not colored:

![image](https://user-images.githubusercontent.com/16015770/38528811-7c19cdf6-3c61-11e8-957e-d99fd37b51df.png)

### Repro steps

As an example, try the following code:

```f#
let frq = System.Diagnostics.Stopwatch.Frequency
let ns = 1. / float frq * 1000000000.
let µs = 1. / float frq * 1000000.
sprintf "[INIT] Timer accuracy is %i ticks/s, %5.2fns per tick, %1.5fµs per tick" frq ns µs
```

### Expected behavior

The whole of `%5.2f` and `%1.5f` should be colored in a green font (in the default dark color scheme).

### Actual behavior

See screenshot above, they arent't colored properly.

### Known workarounds

None / n/a

### Related information 

VS 2017 15.7 Update 2, Windows 7 / 10.

**Comment by cartermp** [comment] 2018-04-10 00:36
Closing as dupe of #3703

**Closed by cartermp** 2018-04-10 00:36 UTC

**Comment by abelbraaksma** [comment] 2018-04-10 07:26
Thanks, didn't see the referenced report when searching.
