### ISSUE TITLE
Unexpected type inference inconsistency

### ISSUE THREAD

**Issue by ovatsus** [Microsoft/visualfsharp#320] opened 2015-03-22 13:03 UTC
Hi,

I don't know if this is a bug or not but it seems weird.

I have something like this:

    static member CreateRecord(nameWithNS, attributes:_[], elements:_[], cultureStr) =
      let toXmlContent (v:obj) = 
          (...)
      for nameWithNS, value in attributes do
          match toXmlContent value with
          (...)
      for nameWithNS, value in elements do
          if nameWithNS = "" then
              match toXmlContent value with
              (...)
          else
              for value in toXmlContent value do
                 (...)
      
(full code [here]( https://github.com/fsharp/FSharp.Data/blob/e5e139c2bccb567497b059525a540c2a0f7c5634/src/Xml/XmlRuntime.fs#L193))

`toXmlContent` should force it's arg to be inferred as `obj` and I'm calling it both for `attributes` and `elements`. Yet the inferred types for them are not the same, one is inferred to `obj` and another to a generic type:

![image](https://cloud.githubusercontent.com/assets/738761/6769432/3a50f800-d093-11e4-9f26-598bb6273706.png)

Both F# 3.1 and 4.0 do the same

Is this a bug or am I missing some detail?

**Comment by dsyme** [comment] 2015-03-23 17:03
I'm pretty sure this is not a bug - in one branch an upcast applies, in the nother case "value"  is being used differently (e.g. in "match") and no upcast applies. But we'd need a concrete smaller repro in any case :) See CONTRIBUTING.md

**Comment by dsyme** [comment] 2015-03-23 17:03
(Closing since the question is answered, please submit a detailed isolated repro, thanks)

**Comment by ovatsus** [comment] 2015-03-23 18:42
Where is the upcast? Both the `attributes` and `elements` values are only used in pattern matching in a for expression, which infers them as A*B. And in both cases, B is only used as the argument to the `toXmlContent` function, so I really don't understand the difference

**Comment by dsyme** [comment] 2015-03-23 20:58
Could you produce a minimized standalone example to discuss? thanks!

**Comment by ovatsus** [comment] 2015-03-24 22:46
Here is the minimum repro:

    type XmlRuntime() =

      static member CreateValue(value:obj) = 
        XmlRuntime.CreateRecord([| |], [| "", value |])

      static member CreateRecord(attributes:_[], elements:_[]) =
        let toXmlContent (v:obj) = v
        for (_:string), value in attributes do
            match toXmlContent value with
            | _ -> ()
        for (_:string), value in elements do
            match toXmlContent value with
            | _ -> ()
        ()

Turns out what causes this is the caller. Which is still weird, shouldn't elements also be constraint to `string*obj[]`?

**Comment by dsyme** [comment] 2015-03-25 01:38
OK, well, this makes it clear.  In short, the call from the other member is enough to constrain the two differently.

Basically you don't get quite the same automatic generalization in the recursive scope as you would with separate bindings unless you add plenty of type annotations.   The details are in the F# language spec in somewhat excruciating detail.

I'll close this since it's by spec.

**Closed by dsyme** 2015-03-25 01:38 UTC
