### ISSUE TITLE
Type check fails in the IDE when referencing solution projects

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#3595] opened 2017-09-16 09:34 UTC
Current master:

![image](https://user-images.githubusercontent.com/1760221/30511091-25d90212-9ad2-11e7-94c7-6cdb8a3b90ec.png)

> Error	FS3160	Problem reading assembly 'C:\visualfsharp\Debug\net40\bin\FSharp.LanguageService.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1140; Id 1141; Id 1142; Id 1143; Id 1144|], Id 1146,
>  false, None))

I'm getting this in any multiple projects solution.

![image](https://user-images.githubusercontent.com/1760221/30511152-3c24a5fc-9ad3-11e7-992e-386fd5781ec1.png)

**Comment by majocha** [comment] 2017-09-16 09:41
Looks like it's the same as #3545

**Comment by cartermp** [comment] 2017-09-16 16:54
Closing as dupe of #3545

**Closed by cartermp** 2017-09-16 16:54 UTC
