### ISSUE TITLE
Strange behavior with newer compiler on very old quotations code

### ISSUE THREAD

**Issue by Rickasaurus** [Microsoft/visualfsharp#5345] opened 2018-07-17 18:03 UTC
We noticed that certain code was failing tests in visual studio 2017 but working fine on our build server. On further inspection it seems like a quoted function is producing a new different Expr tree and it's causing the code to fail.

#### Repro steps

```fsharp
let getMethod = 
    function
    | Patterns.Call (_, m, _) when m.IsGenericMethod -> m.GetGenericMethodDefinition()
    | Patterns.Call (_, m, _) -> m
    | _ -> failwith "Incorrect getMethod Pattern"

let X<'T> : 'T = Unchecked.defaultof<'T>

let tupleToKeyValue (tv: System.Tuple<'k, 'v>) = new KeyValuePair<_,_>(tv.Item1, tv.Item2)
 
// This throws on getMethod because the top level Expr is now a strangely constructed Let pattern instead of a Call as before.
let t2kv = (getMethod <@ tupleToKeyValue X @>).MakeGenericMethod(args)
```

#### Expected behavior

Gets my nice generic method because the expr is a simple call I can peel apart.

#### Actual behavior

Some strange looking let pattern:
```
(tupledArg) 
(Call (None, X, [])) 
(Let (arg00@, TupleGet (tupledArg, 0),
     Let (arg01@, TupleGet (tupledArg, 1),
          Call (None, tupleToKeyValue, [arg00@, arg01@]))))
```
#### Known workarounds

Maybe reach up inside this nest of lets to get the call? I'm not sure.

#### Related information 

Provide any related information 

* Operating system
Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
4.5.1
* Editing Tools (e.g. Visual Studio Version)
VS2017 15.7.1
Building on build server with Msbuild 14.0, will need to dig to get more info.
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity
Fairly severe, we can't update our build server until this is fixed.

**Comment by cartermp** [comment] 2018-07-17 18:08
@Rickasaurus Updated the text to remove the boilerplate and format things

**Comment by dsyme** [comment] 2018-07-19 12:55
This will be related to the somewhat problematic change with System.Tuple in F# 4.1+.  I don't think we will be looking to make any further changes here for stability reasons, so I'd just recommend changing your code to adjust for either quotation.

**Comment by cartermp** [comment] 2018-07-21 19:55
Ugh sorry you hit this @Rickasaurus

Just to add a bit more about the tuple change:

In F# 4.1, #3016 was addressed to make `System.Tuple` and F# tuples are effectively equivalent, but with a change that was source-breaking due to lacking support for `Item*`. The [RFC documenting this](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.1b/FS-1046-consistent-tuple-types.md#the-change) explains the progression in behavior. Now, the issue is addressed _and_ code that depended on `Item*` in F#-declared `System.Tuple` occurrences has also been fixed. However, this does not take code quotations into account. 

This sort of stuff is unfortunate and makes me wonder what, if any, mitigations we can have from a process standpoint for any future changes to things in F# that may not be treated ideally today.

For example, I don't think there is a policy or anything, but it is fairly well-understood by .NET developers that if you depend on something through reflection and that breaks later in life, then it's annoying but "okay" since you've knowingly stepped into the [danger zone](https://www.youtube.com/watch?v=RRU3I_o1vLc). Clearly, we don't want peoples' reflection-based code to break, but there's only so far we can go with that before it's inevitable (i.e.g, string-based method invocation).

Similarly, things like code that depends on [how the compiler generates code](https://medium.com/spektrix-engineering/how-a-micro-optimisation-in-the-net-compiler-broke-our-web-application-at-runtime-7f418e5ded90) is not something we can guarantee won't break. It's annoying and sucks when you find out older code did this, but it's somewhat expected once you find out why.

**Unfortunately**, Code Quotations venture into similar territory: by using Code Quotations, you're depending on how that F# compiler translates the quotation expression into a tree. Guaranteeing that this will never result in a break (or that we will always revert a change that breaks this) is not really possible, otherwise we'd have to basically say that once something is implemented in the compiler, it is permanent and can never change. We do have [regression tests](https://github.com/Microsoft/visualfsharp/blob/master/tests/fsharp/core/quotes/test.fsx) that can help mitigate this, but they're not going to protect against everything. At the same time, Code Quotations are useful and we don't want to outright discourage their usage.

In light of this and the various other issues in F# 4.1, I think it would be helpful to draft an official stance (policy?) on how F# evolution affects existing code. We're committed to not breaking people, but the definition of a break isn't quite clear to me nor is it clear to users of F#. Thoughts?

**Comment by Rickasaurus** [comment] 2018-07-27 15:57
I always figured since quotations were not the actual F# AST they could be considered to be safe, much like how reflection on CLR libraries is safe because of the great lengths taken to prevent them from breaking. 

I'm not actually sure how to fix this in a nice way since I'm expecting an actual tuple type. I guess the fix would be to manually construct the expression I need.

**Comment by cartermp** [comment] 2018-07-29 18:02
Closing this out (unless @dsyme wishes to keep it open).

This (among other issues) motivates a document on the F# RFC repo that describes our principles and approach to compatibility.

**Closed by cartermp** 2018-07-29 18:02 UTC
Labels: Area-Compiler, Resolution-By Design

**Comment by Rickasaurus** [comment] 2018-08-01 14:45
Could really use some help in trying to find a fix for this at least. All I need is a generic MethodInfo that takes a tuple object and returns a KeyValuePair. Do I need to re-implement in C# to represent this now?

**Comment by Rickasaurus** [comment] 2018-08-01 16:37
So oddly this works: 

```    
type TupleToKeyValueConverter () = 
        static member ToKeyValue (tv: System.Tuple<'key,'value>) = 
             new KeyValuePair<_,_>(fst tv, snd tv)

let tupleToKeyValueMethodInfo = 
            typeof<TupleToKeyValueConverter>.GetMethod("ToKeyValue")
```

The issue only occurs with functions. Thanks to Nino Floris on fpchat.

**Comment by NinoFloris** [comment] 2018-08-01 16:40
@cartermp or @dsyme I'm curious, could either of you elaborate on why this transformation is only done for **curried functions** and no other constructs?
