### ISSUE TITLE
byref<'T> returns no longer usable in F# 4.5

### ISSUE THREAD

**Issue by zpodlovics** [Microsoft/visualfsharp#5541] opened 2018-08-21 21:01 UTC
It seems that something weird is going on with the byref returns.

Please provide a succinct description of the issue.

#### Repro steps

Please consider the following example:

```fsharp
open System
open System.Threading

type A() =
    let a = [|1|]
    member this.ArrayByRef() =
        &a.[0]

[<EntryPoint>]
let main argv =
    let a = A()
    Interlocked.CompareExchange(a.ArrayByRef(), 0, 1);
    0 // return an integer exit code
```

Provide the steps required to reproduce the problem

1. Create a new console F# project, and copy the example code there.
2. Try to build it

#### Expected behavior

Compiles and works fine.

#### Actual behavior

error FS0041: No overloads match for method 'CompareExchange'. The available overloads are shown below.

#### Known workarounds

Use the older version of F# compiler? The Mono shipped F# 4.1 FSI execute it correctly:

```fsharp
Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> open System.Threading
- 
- 
- 
- type A() =
- 
-     let a = [|1|]
- 
-     member this.ArrayByRef() =
- 
-         &a.[0]
- 
- ;;
type A =
  class
    new : unit -> A
    member ArrayByRef : unit -> byref<int>
  end

>     let a = A()
- 
-     Interlocked.CompareExchange(a.ArrayByRef(), 0, 1);
- 
- ;;
val a : A
val it : int = 1

```

#### Related information 

Provide any related information 

* Operating system: Ubuntu 16.04 x86_64
* .NET Runtime, CoreCLR or Mono Version: 

```
ii  dotnet-host                                                 2.1.3-1                                                      amd64        Microsoft .NET Core Host - 2.1.3
ii  dotnet-hostfxr-2.0.7                                        2.0.7-1                                                      amd64        Microsoft .NET Core Host FX Resolver - 2.0.7 2.0.7
ii  dotnet-hostfxr-2.1                                          2.1.3-1                                                      amd64        Microsoft .NET Core Host FX Resolver - 2.1.3 2.1.3
ii  dotnet-runtime-2.0.7                                        2.0.7-1                                                      amd64        Microsoft .NET Core Runtime - 2.0.7 Microsoft.NETCore.App 2.0.7
ii  dotnet-runtime-2.1                                          2.1.3-1                                                      amd64        Microsoft .NET Core Runtime - 2.1.3 Microsoft.NETCore.App 2.1.3
ii  dotnet-runtime-deps-2.1                                     2.1.3-1                                                      amd64        dotnet-runtime-deps-2.1 2.1.3
ii  dotnet-sdk-2.1                                              2.1.401-1                                                    amd64        Microsoft .NET Core SDK 2.1.401
ii  fsharp                                                      4.1.33-0xamarin7+ubuntu1604b1                                all          functional-first programming language - compiler for the CLI
ii  libfsharp-core4.3-cil                                       4.1.33-0xamarin7+ubuntu1604b1                                all          functional-first programming language - core runtime library

```

**Comment by cartermp** [comment] 2018-08-21 21:18
This is by design, as per the spec here: https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1053-span.md#implicit-dereference-of-return-byrefs

Return byrefs in F# up until F# 4.5 were not actually fully implemented - in C# the value is implicitly dereferenced, but in F# that was never done. The feature was crippled since you couldn't produce a byref-return either; only consume them.

The resolution for your code is to use `&`:

```fsharp
Interlocked.CompareExchange(&a.ArrayByRef(), 0, 1)
```

This is the same behavior as C#: https://sharplab.io/#v2:C4LglgNgPgAgDAAhgRgHQBUAWAnApgQwBMwA7AcwG4BYAKFpgGYkAmBAQVoG9aFeEAHbGABu+YLgSlgAbQC6CAB4BnBAF4EJXAHdJJGcnmcEyBAF9qNPgh59GCPADNdwBACVcwAK7YSAIQCe7g4AFACUCEYwAOz2uE7K0nCyFGa0pvRMMKwAwhE2vHYwACwIALJheZZWfKLYCPhqGtrsYRbVfACSerjYEAD2AMYA1riEqNl9ALb8+HgAogoDmPjkuMGO9ajuXj4BQWEANAhwR8ihbXzpNKZAA===

**Comment by zpodlovics** [comment] 2018-08-21 21:18
I may be wrong, but I thing I have found a related typo here:
https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L369

Shouldn't this line also be ```type InOut() = class end``` similar to ```type Out() = class end``` and ```type In() = class end
``` and not ```type InOut = class end``` (please note the missing () constructor)

**Comment by TIHan** [comment] 2018-08-21 22:12
@cartermp is right. This is by design and something that was fully implemented in 4.5.

**Comment by cartermp** [comment] 2018-08-21 22:13
(closing as by design, which I should have done with my comment)

@zpodlovics w.r.t. the type, the lack of a default constructor doesn't matter. I think it may have just been an omission by @dsyme when implementing the module of `ByRefKinds`, but it doesn't affect `byref`s in any way.

**Closed by cartermp** 2018-08-21 22:13 UTC
Labels: Area-Compiler, Resolution-By Design

**Comment by zpodlovics** [comment] 2018-08-27 19:32
@cartermp You are right - I forgot the byref related changes introduced in F# 4.5.
