### ISSUE TITLE
incorrect management of nuget packages in .NET standard projects

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4339] opened 2018-02-11 22:19 UTC
1) Create a .NET standard 2.0 library
2) Add nuget package FSharpLu.Json

The namespace Microsoft.FSharpLu is not recognized

----

Microsoft Visual Studio Community 2017 Preview
Version 15.6.0 Preview 4.0
VisualStudio.15.Preview/15.6.0-pre.4.0+27406.0
Microsoft .NET Framework
Version 4.7.02558

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/196711/incorrect-management-of-nuget-packages-in-net-stan.html
VSTS ticketId: 565770_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment] 2018-02-14 01:59
I cannot reproduce this on 15.6 Preview 4 (F# tools 15.6.0.18013105):

![image](https://user-images.githubusercontent.com/6309070/36184177-0467864a-10e7-11e8-9f81-c7d2019b14fb.png)

Steps taken:

1. Create .NET Standard library
2. Add FSharpLu.Json via NuGet UI
3. Write code (IntelliSense picks up symbols from unopened namespaces and adds them)

```
Microsoft Visual Studio Community 2017 Preview
Version 15.6.0 Preview 4.0
VisualStudio.15.Preview/15.6.0-pre.4.0+27406.0
Microsoft .NET Framework
Version 4.7.02556
```

@francotiveron was it perhaps slow to recognize symbols for you?

**Comment by francotiveron** [comment] 2018-02-14 20:11
Something was broken on that specific project. After creating a new project and copying all the artifacts, it works now.

**Comment by cartermp** [comment] 2018-02-14 20:13
@francotiveron Thanks for the info, and I'm glad that it works for you now. I'll close this out. Please do file another issue or ping to have this re-opened if you notice it again.

**Closed by cartermp** 2018-02-14 20:13 UTC
Labels: needs repro
