### ISSUE TITLE
Quotation involving function application of tupled arguments captured incorrectly

### ISSUE THREAD

**Issue by stephen-swensen** [Microsoft/visualfsharp#575] opened 2015-08-08 06:59 UTC
This issue originates from https://github.com/SwensenSoftware/unquote/issues/114, but with a somewhat simplified example.

Consider the following quotation:
```fsharp
let coordsEqual (x1,y1) (x2,y2) =
    x1 = x2 && y1 = y2

<@ coordsEqual (1.0,1.0) (id(2.0,2.0)) @>
```
Observe the output when submitted to FSI:
```fsharp
val it : Quotations.Expr<bool> =
  Let (tupledArg, NewTuple (Value (1.0), Value (1.0)),
     Let (tupledArg,
          Call (None, Identity, [NewTuple (Value (2.0), Value (2.0))]),
          Let (x1, TupleGet (tupledArg, 0),
               Let (y1, TupleGet (tupledArg, 1),
                    Let (x2, TupleGet (tupledArg, 0),
                         Let (y2, TupleGet (tupledArg, 1),
                              Call (None, coordsEqual, [x1, y1, x2, y2])))))))
```
You can see that the quotation has been incorrectly captured: the first `tupledArg` let binding is immediately shadowed by a second `tupledArg` let binding, such that the meaning of the overall expression (when evaluated) is `coordsEqual 2.0 2.0 2.0 2.0` instead of the correct `coordsEqual 1.0 1.0 2.0 2.0`.

I have reproduced this issue in VS 2010, 2013, and 2015.

**Comment by dsyme** [comment] 2015-08-10 16:22
@stephen-swensen When I run this I get  ``(true, true, true, true, true)``.  Are you seeing that too? (Note, Variable identity is by "=" on Var objects, not by name.)

```
let coordsEqual (x1,y1) (x2,y2) =
    x1 = x2 && y1 = y2

let q = <@ coordsEqual (1.0,1.0) (id(2.0,2.0)) @>

open Microsoft.FSharp.Quotations

match q with 
| Patterns.Let(v1,e1,
   Patterns.Let(v2,e2,
    Patterns.Let(x1,Patterns.TupleGet(Patterns.Var v1a,0),
     Patterns.Let(y1,Patterns.TupleGet(Patterns.Var v1b,1),
      Patterns.Let(x2,Patterns.TupleGet(Patterns.Var v2a,0),
       Patterns.Let(y2,Patterns.TupleGet(Patterns.Var v2b,1),
        b))))))  -> (v1<>v2,v1=v1a,v1=v1b,v2=v2a,v2=v2b)
```

**Comment by dsyme** [comment] 2015-08-14 10:18
Closing this as by design pending more information

**Closed by dsyme** 2015-08-14 10:18 UTC
Labels: needs more info

**Comment by stephen-swensen** [comment] 2015-08-14 14:40
Apologies for my late response, I've been on vacation.

Yes, I get `(true, true, true, true, true)`. I falsely assumed that Var names would have analogous scoping rules to the F# language itself, thank you for clarifying.

But could we turn this issue into a feature request? Not being able to rely on variable identity by name in scope makes quotation analysis more difficult, and may be problematic for quotation processors that produce human readable code (certainly for Unquote, which does quotation -> fsharp, but possibly for an e.g. quotation -> javascript processor too).

**Comment by dsyme** [comment] 2015-08-14 16:16
Hi @stephen-swensen 

The variable names reflect source, so `(fun x -> (fun x -> (x,x))` will have two variables named `x`.  We could assign a unique identity for each variable but that would be much the same as relying on object identity, wouldn't it?

thx
don

**Comment by stephen-swensen** [comment] 2015-08-15 03:36
Absolute unique identity for variables is certainly not expected. With `(fun x -> (fun x -> (x,x))` the outer function `x` is clearly shadowed by the inner function `x` so that  `(fun x -> (fun x -> (x,x)) 2 3` evaluates to `(3, 3)` as expected. However in the original reported example, we have two (generated) variables named `tupledArg` that are in scope at the same time. That's where the confusion arises for me.

Thanks for considering, perhaps I am missing something!

**Comment by dsyme** [comment] 2015-08-15 09:07
I see - yes, it would have been better to give unique names to the tupled arguments.  However the Var type identity is still by reference, and it's possible to manufacture quotations programmatically where that's important. 

btw thanks for Unquote, Such a great library.

**Comment by stephen-swensen** [comment] 2015-08-23 21:46
Thanks, Don! Unquote has been a rewarding project for me in many ways, and I am glad it has been useful for the community. Many thanks to you too for making it all possible.

Turns out this has been no real hardship for Unquote: implementing Var reference identity was easy in the evaluator, and then through regular "re-sugaring" the non-unique tupled arg names got hidden away by the decompiler (what was the part I was most worried about).

I hadn't considered the impact on manufactured quotations, I see now how reference identity is necessary there.
