### ISSUE TITLE
FParsec intellisense is not working

### ISSUE THREAD

**Issue by buybackoff** [Microsoft/visualfsharp#5961] opened 2018-11-28 12:35 UTC
The [original repo](https://github.com/stephan-tolksdorf/fparsec/) and somewhat cleaned [one](https://github.com/buybackoff/fparsectemp) (targeting only .NET Standard 2.0 and default SDK). 

So far have no idea what's wrong, tried to minimize .fsproj file as much as possible without luck. One thing that catches the eye is that VS ignores DefineConstants, but `dotnet build` works correctly and fails without the symbol. Maybe tooling breaks on symbols. However, without this particular symbol nothing works as well.

![image](https://user-images.githubusercontent.com/489852/49152156-00f10300-f323-11e8-8916-a1f40b984eb2.png)

Tested on two machines with VS 15.9.0 and 15.8.9 + Rider 2018.3.EAP7.

**Comment by cartermp** [comment] 2018-11-28 16:46
Possible duplicate of: https://github.com/dotnet/project-system/issues/2733

But I'll still need to investigate to be sure.

**Comment by cartermp** [comment] 2018-11-28 19:30
Okay, so taking a look there are a few problems:

* Redundancy in the targets for the project and the project file
* Very complicated way to reference FSharp.Core that is likely failing
* Specifying FSharp.NET.SDK in targets, which has been deprecated for quite some time

In general, the FParsec.Common.targets file has some complicated MSBuild logic that is failing (likely in multiple places). In fact, your fork that simplifies the project file doesn't really help much since this targets file is doing a bunch of stuff that either overrides or collides with what's specified in the file.

I get the feeling that this built a long time ago when .NET Core tooling all-up was in preview.

**Comment by baronfel** [comment] 2018-11-28 19:34
@stephan-tolksdorf has made a PR already that ports the library to netstandard2.0 already: https://github.com/stephan-tolksdorf/fparsec/pull/36.
This seems to fix several of the issues mentioned, at least according to twitter.

**Comment by cartermp** [comment] 2018-11-28 19:36
Awesome! Thanks @baronfel  and @stephan-tolksdorf

**Comment by cartermp** [comment] 2018-11-28 19:36
I'll close this for now and we can discuss specific issues on the PR. We will re-open this if there are further problems.

**Closed by cartermp** 2018-11-28 19:36 UTC
