### ISSUE TITLE
No Visual F# folder in user templates

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#857] opened 2016-01-07 20:33 UTC
%UserProfile%\Documents\Visual Studio 2015\Templates\ProjectTemplates
%UserProfile%\Documents\Visual Studio 2015\Templates\ItemTemplates

I wonder why there are no Visual F# folders at these paths

**Comment by dsyme** [comment] 2016-01-08 14:51
Closing as this is not a bug report per CONTRIBUTING.md. (AFAIK the Visual F# Tools  install their things elsewhere?)

**Closed by dsyme** 2016-01-08 14:51 UTC

**Comment by xperiandri** [comment] 2016-01-08 15:17
I created folder Visual F# myself and templates dropped into it appeared in Visual F#/Visual F# in project creation dialog.
