### ISSUE TITLE
Compiler error when package reference to Language-Ext is added and used

### ISSUE THREAD

**Issue by ijsgaus** [Microsoft/visualfsharp#4165] opened 2017-12-24 08:49 UTC
#### Repro steps

https://github.com/ijsgaus/Confuse - error FS0816: One or more of the overloads of this method has curried arguments. Consider redesigning these members to take arguments in tupled form

#### Expected behavior
When remove package reference from project - all compiled without error. 

#### Actual behavior
Any of:
- descriptive error
- no error - i don't view any mistakes

**Comment by cartermp** [comment] 2018-01-02 21:20
I can repro. The steps are:

1. Open that project.
2. Note the compiler error when attempting to use the binding named `instance`.
3. Comment out or delete the `<PackageReference>` node to Language-Ext
4. Note that the compiler error is gone.

Language-Ext exposes the name `instance` without needing an `open` statement, but this is unrelated.  Renaming the value to something else (e.g., `banana`) will still result in the same issue: compiler error when the package is added; no error when it's not.

**Comment by dsyme** [comment] 2018-01-15 15:37
I suspect this is by design.

F# prohibits the use of overloading and currying - this is enforced when method overload resolution is determined.  Prior to adding the reference to ``Language-Ext`` there is no overloading of ``Sum``, but currying is used.  After adding the reference, there is now a mix of overloading and currying for ``Sum`` - at least that's what I would expect.

The solution is to stop using currying for ``Sum`` in your own code.

**Comment by dsyme** [comment] 2018-01-29 02:04
Closing as by design

**Closed by dsyme** 2018-01-29 02:04 UTC
Labels: Area-Compiler, Resolution-By Design
