### ISSUE TITLE
15.3 preview 3: FCS does not respect file ordering defined in .NET Core project files

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3260] opened 2017-06-27 07:19 UTC
![image](https://user-images.githubusercontent.com/873919/27575061-284bfbbc-5b21-11e7-921d-818c4ed947e1.png)

Code completion, tooltips, etc. don't work either.

**Comment by forki** [comment] 2017-06-27 07:24
OMG.

**Comment by realvictorprm** [comment] 2017-06-27 07:27
Epic fail :(

**Comment by rodrigovidal** [comment] 2017-06-27 07:41
Same here

**Comment by isaacabraham** [comment] 2017-06-27 08:39
Sob

**Comment by vasily-kirichenko** [comment] 2017-06-27 08:54
I checked it on both .NET Core 1.0.4 and .NET Core 2.0 preview 2: the same behavior.

**Comment by saul** [comment] 2017-06-27 09:19
Absolutely no surprise. Nobody on the .Net project team side seemed to care that we didn't have file ordering.

**Comment by saul** [comment] 2017-06-27 09:21
Also I'm pretty sure all of the issues you've raised for 15.3 should be raised in dotnet/project-system, not here. The code doesn't even live in this repo.

**Comment by dsyme** [comment] 2017-06-27 09:24
Please reopen in https://github.com/dotnet/project-system/

**Comment by enricosada** [comment] 2017-06-27 09:27
@saul it is a surprise.

UI treeview is a thing (minor priority for now).
but this is build (ok vs build not msbuild), how to get fsc args should be the same.

**Comment by vasily-kirichenko** [comment] 2017-06-27 09:28
OMG so we now depend on another thing that's controlled by people who don't care about F# at all (the first thing - Roslyn)? Very nice.

**Comment by enricosada** [comment] 2017-06-27 09:51
@vasily-kirichenko Roslyn (https://github.com/dotnet/roslyn) <> Roslyn project system (https://github.com/dotnet/roslyn-project-system).
Name is strange, but because is based on roslyn-workspaces and new CPS, but there is not a lot c# specific there.
collaborating with roslyn-ps, no issue at all. they fixed and refactored a lot for F#

**Comment by cartermp** [comment] 2017-06-27 15:52
@srivatsn Any idea where this comes from?

> but this is build (ok vs build not msbuild), how to get fsc args should be the same

Is this the remaining issues with the argument parser?

**Comment by cartermp** [comment] 2017-06-27 16:26
@Pilchie Do you think this is related to your comment here? https://github.com/Microsoft/visualfsharp/issues/3266#issuecomment-311409483

**Comment by Pilchie** [comment] 2017-06-27 16:33
@cartermp - no that should be a VS editor thing only.  Wouldn't effect build or the solution explorer.

BTW @enricosada and @vasily-kirichenko `dotnet/roslyn-project-system` was already renamed to just `dotnet/project-system`.

**Comment by srivatsn** [comment] 2017-06-27 17:14
Ya the file order in the tree doesn't affect the language service. The project system grabs the command line arguments as they are sent to the compiler (which is correct as evidenced by the build succeeding) and send that to the language service. Something's going wrong in the language service.

**Comment by enricosada** [comment] 2017-06-27 17:21
probably is the same language service bug, as reported in https://github.com/Microsoft/visualfsharp/issues/3266#issuecomment-311409483
is confirmed doesnt load command line args correctly.

@srivatsn @Pilchie @KevinRansom there is a log setting to enable/sethigher to confirm is a dupe? to see args passed to language service is enough.

**Comment by srivatsn** [comment] 2017-06-27 17:27
I just looked at the F# LS code and it seems to be getting all [source files\references etc from an IProjectSite](https://github.com/Microsoft/visualfsharp/blob/20e93a4bfeec8e0075960c9cfd0ca51fe92b473f/vsintegration/src/FSharp.LanguageService/ProjectSitesAndFiles.fs#L241) from a IProjectSite (which is the interface that the old F# PS implements) instead of getting them from the Roslyn workspaces which would get populated with all this information. I think this needs to be changed to pull from the workspace for CPS-based projects.

**Comment by Pilchie** [comment] 2017-06-27 17:40
@srivatsn and I chatted, and we think the easiest way to do this might be to create an implementation of `IProjectSite` directly in the F# language service code and implement it to ask the Roslyn `Project` objects for their references and files.  This will leave `#defines` not working right, since they don't get set in the roslyn workspace, but will be a big first step up.

@brettfo Is working on getting the latest F# bits inserted for Preview 4, but can start working on this in parallel I think.

**Comment by dsyme** [comment] 2017-06-27 17:53
> This will leave #defines not working right, since they don't get set in the roslyn workspace, but will be a big first step up.

I was wondering about the ``#defines``.  Thanks for tracking this

For completeness, some other options are relevant to on-the-fly type checking, notably these (after searching through ``CompileOps.fs``)
* ``--o`` The output assembly name (for InternalsVisibleTo)
* ``--warn/nowarn/warnon/warnaserror``
* ``--codepage`` (the input code page)
* ``--checked`` (indicates if ``open FSharp.Operators.Checked`` is implied)
* ``--mlcompatibility`` (I think never used)

Of these the output assembly name and the warnings are  by far the most important

**Comment by enricosada** [comment] 2017-06-27 17:53
@srivatsn @Pilchie as a note, why instead of parse back all the fsc arguments, the language service dont just read the [FscCommandLineArgs msbuild items](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets#L269)? is already the array splitted with fsc args.. works really well for [FSAC](https://github.com/fsharp/FsAutoComplete/] in vscode/vim/emacs.

So we dont care anymore about msbuild -> fsc task -> parse back somehow

There is no way for new `IProjectSite` to ask roslyn workspaces for that msbuild item list?

**Comment by srivatsn** [comment] 2017-06-27 18:05
That msbuild item itself is not available at this layer, however that string (the entire command line) get passed to [this method ](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.Implementation/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs,118) - right now, that method no-ops for F# since there's no CommandLineParser. However, we can implement a type that gets that and implements IProjectSite too..

**Comment by enricosada** [comment] 2017-06-27 18:16
@srivatsn just curiosity, why the `string` was choosen as parameter? also c# use an array (` CscCommandLineArgs`) so less concat+parse needed.


> However, we can implement a type that gets that and implements IProjectSite too
@srivatsn awesome, afaik (/cc @dsyme @KevinRansom), the F# compiler arguments api is the same of c#, so the `string -> IEnumerable<string>` splitter can be reused from c#
 
```
var splitArguments = CommandLineParser.SplitCommandLineIntoArguments(commandLine, removeHashComments: false);
```

the rest is pattern match on args..

but is not already implemented in https://github.com/dotnet/project-system/pull/2206  ? so just missing is that it implements IProjectSite ?

**Comment by enricosada** [comment] 2017-06-27 18:45
> --o The output assembly name (for InternalsVisibleTo)

[CommonCommandLineArguments.OutputFileName](http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/CommonCommandLineArguments.cs,b6fc61ee72fe57aa,references)?

> --codepage (the input code page)

[CommonCommandLineArguments.Encoding](http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/CommonCommandLineArguments.cs,89e19f8553c91eda,references)

> --checked (indicates if open FSharp.Operators.Checked is implied)
> --mlcompatibility (I think never used)

CompilationOptions. CompilationOptions.Features ?
> --warn/nowarn/warnon/warnaserror

[CompilationOptions. CompilationOptions.SpecificDiagnosticOptions](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/CompilationOptions.cs,701443a092cf7a50,references)

**Comment by srivatsn** [comment] 2017-06-27 19:35
The parser in the project system basically just enough to understand what's a reference and source file versus what's not. This is so that it can track changes to references and source files individually and incrementally update the language service. If any of the options change, since that's rarer, it simply tells the LS to recreate a compilation. Ideally the Project system wouldn't ever parse and understand the command line and keep it as mostly a passthrough. 

That type cannot implement IProjectSite as it's not exposed to the LS in anyway. The contract with the language service is [IWorkspaceProjectContext](https://github.com/dotnet/roslyn/blob/49be37c88d52624dd7ec5b4791be0a715426ff2f/src/VisualStudio/Core/Def/Implementation/ProjectSystem/CPS/IWorkspaceProjectContext.cs)

The reason we want to make sure files\references are added to the workspace and not just parsed into a IProjectSite in the SetOptions call is so that any Roslyn extension that works at the workspace level on documents will also work for F# - If we make everything in terms of IProjectSite then they'll have to know about IProjectSite as well.

**Comment by enricosada** [comment] 2017-06-27 20:02
thx for info @srivatsn , really appreciated

**Comment by KevinRansom** [comment] 2017-09-20 18:21
This is addressed by: https://github.com/Microsoft/visualfsharp/pull/3564

**Closed by KevinRansom** 2017-09-20 18:21 UTC
Labels: Area-IDE Language Service, bug, Urgency-Now
