### ISSUE TITLE
Reflected definitions mismatch the type of method

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#118] opened 2015-01-26 22:23 UTC
Opened at [Codeplex](https://visualfsharp.codeplex.com/workitem/101) by [toyvo](https://www.codeplex.com/site/users/view/toyvo)

We have dealt with it in WebSharper in ad-hoc ways but it seems that it comes back to bite us periodically. Would be really much better to fix this in the F# compiler. 

Problem: 

Type functions (Polymorphic forall 'T.. module-bound properties) get compiled to methods. Quotations using these functions are compiled to method calls. However, reflected definitions of these methods are different from normal methods. 

I do not know of a cheap consistent way to detect when this happens, so as to fixup the quotation to the "normal" form expected for a method. Thanks. 

DotNetFiddle with repro:  [https://dotnetfiddle.net/T2Dgwk](https://dotnetfiddle.net/T2Dgwk)
GitHub issue:  [https://github.com/fsharp/fsharp/issues/321](https://github.com/fsharp/fsharp/issues/321)

> comments
> toyvo wrote Jul 16, 2014 at 8:15 AM [x] 
> As discussed with Don Syme, the simplest fix is to simply have the F# compiler mark type functions with some attribute (SourceConstructFlags, or dedicated attribute). 

``` fsharp
 let empty<'T> = Seq<'T>

 ==>

 [<TypeFunction>]
 static member Empty<'T>() : seq<'T>
```

This would allow systems like WebSharper to distinguish this case and recover a proper quotation form.

**Comment by dsyme** [comment] 2017-02-02 14:38
I will close this as by design and we will leave things as they are. I believe WebSharper has worked around the cases where this happens.

**Closed by dsyme** 2017-02-02 14:38 UTC
Labels: Area-Compiler, bug, Urgency-Later
