### ISSUE TITLE
Struct Union Compilation Issues

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#2463] opened 2017-02-21 20:55 UTC
I've encounter several situations where compilation of struct DUs fail where I'm not sure whether this behavior is intended behavior or not, but none of them provide error messages in the compiler  

------
All of the following examples are being compiled in a single module library project where the only file is
```fsharp
namespace struct_du_cases
module test =   
    [<Struct>] type Cases = A | B 
```
------

```fsharp
[<Struct>] type Cases = A | B  // fails
```
^ this one doesn't show an error in the source but the build fails with this error message 

```
1>FSC: error FS2014: A problem occurred writing the binary 'c:\users\jared\documents\visual studio 2017\Projects\struct_du_cases\struct_du_cases\obj\Debug\struct_du_cases.dll': Error in pass2 for type struct_du_cases.test, error: Error in pass2 for type Cases, error: duplicate entry '.ctor' in method table
1>Target "_CheckForCompileOutputs" in file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" from project "c:\users\jared\documents\visual studio 2017\Projects\struct_du_cases\struct_du_cases\struct_du_cases.fsproj" (target "_CleanGetCurrentAndPriorFileWrites" depends on it):
1>Target "_CleanGetCurrentAndPriorFileWrites" in file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" from project "c:\users\jared\documents\visual studio 2017\Projects\struct_du_cases\struct_du_cases\struct_du_cases.fsproj" (target "_CleanRecordFileWrites" depends on it):
1>Target "_CleanRecordFileWrites" in file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" from project "c:\users\jared\documents\visual studio 2017\Projects\struct_du_cases\struct_du_cases\struct_du_cases.fsproj" (target "CoreBuild" depends on it):
1>Done building project "struct_du_cases.fsproj" -- FAILED.
```
The following examples that fail are all failing with the build error message above (and no compiler error in src) on both Debug and Release builds

```fsharp
[<Struct>] type Cases = A | B //fails
```

```fsharp
[<Struct>] type Cases = A of decimal | B of int // fails
```
This one actually produces a proper error message in the source, but is the message correct?

![](http://i.imgur.com/aYnbaR8.png)

```fsharp
[<Struct>] type Cases = A of a:decimal | B of int // works
```
^ Does this count as all fields within the union type having a unique name? I guess no name is unique?

```fsharp
[<Struct>] type Cases = A of a:int | B of b:int // fails
```
If you follow the error message's instruction but the fields have the same type it fails

#### Expected behavior

If these are undesired cases there should be a compiler error reported in the editor instead of fail on build. But since a case like this works

```fsharp
    [<Struct>]
    type Complex =
    | Int     of a:int
    | Float   of b:float
    | String  of c:string
    | Ints    of d:int []
    | Struct  of e:struct(int*int)
```
I'd hope the ones that aren't working should be

If they're supposed to work then I guess I expect duplicate ctors not to be produced?

#### Actual behavior

Fails on build with error message

#### Known workarounds

As long as the field name and field types are different it compiles
```fsharp
    [<Struct>] 
    type Cases =  // works
    | A of a:int8
    | B of b:int16
    | C of c:int32
    | D of d:int64
    | E of e:uint8
    | F of f:uint16
    | G of g:uint32
    | H of h:uint64
```
but as soon as you change it to 
```fsharp
    [<Struct>] 
    type Cases = // fails
    | A of a:int8
    | B of b:int8 // <- changed this one
    | C of c:int32
    | D of d:int64
    | E of e:uint8
    | F of f:uint16
    | G of g:uint32
    | H of h:uint64
```
it's back to the duplicate ctor build error

#### Related information 

VFT built off of master (+ my colorization PR)

**Comment by dsyme** [comment] 2017-02-21 21:24
I think duplicate of #1678 though with additional failing cases.  Basically we didn't test multi-case well enough - it is really ony good enough for cases where all the types are different, and non-integer, including the generic struct choice types.

**Comment by cloudRoutine** [comment] 2017-02-22 02:32
I started looking at how these struct unions decompile and it seems like changing how the internal fields of the struct are generated could fix some of this isssue

```fsharp
[<Struct>] type Cases = A of int | B of a:decimal
```
decompiles to (via ILSpy)
```csharp
[StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
public struct Cases : IEquatable<test.Cases>, IStructuralEquatable, IComparable<test.Cases>, IComparable, IStructuralComparable
{
    public static class Tags
    {
        public const int A = 0;

        public const int B = 1;
    }

    [DebuggerBrowsable(DebuggerBrowsableState.Never), DebuggerNonUserCode, CompilerGenerated]
    internal int item;

    [DebuggerBrowsable(DebuggerBrowsableState.Never), DebuggerNonUserCode, CompilerGenerated]
    internal decimal _a;

    [DebuggerBrowsable(DebuggerBrowsableState.Never), DebuggerNonUserCode, CompilerGenerated]
    internal int _tag;

    [DebuggerBrowsable(DebuggerBrowsableState.Never), DebuggerNonUserCode, CompilerGenerated]
    public int Tag
    {
        [DebuggerNonUserCode, CompilerGenerated]
        get
        {
            return this._tag;
        }
    }
```
the case with an unnamed field defaults to item, so I'm guessing the reason a DU without field names doesn't work is because it always wants to use item and it clashes? 

if prefixing the declared fieldname in the code with `_` is the convention already being used, couldn't that be done using the case names as well? Cases already enforce a unique name rule.
e.g.  
```fsharp
   [<Struct>] type Cases = A of int | B of int
```
```csharp
internal int _A;
internal int _B;
```
@ReedCopsey suggested that when all of the cases have the same type we should just store it in the same field since the tag is enough for the comparison to continue working

which would mean only one constructor would need to be generated
```csharp
[DebuggerNonUserCode, CompilerGenerated]
internal Cases(int _value, int _tag)
{
	this._value = _value;
	this._tag = _tag;
}
```
otherwise we could still use the same constructor, instead switching on the tag against the generated static class to set the appropriate field 

```csharp
public struct Cases : IEquatable<test.Cases>, IStructuralEquatable, IComparable<test.Cases>, IComparable, IStructuralComparable
{
	public static class Tags
	{
		public const int A = 0;
		public const int B = 1;
	}

        internal int _tag;
        internal int _B;
        internal int _A;

internal Cases(int _value, int _tag)
{
    this._tag = _tag;
    switch (_tag)
    {
         case Tags.A:
               this._A = _value;
         case Tags.B:
               this._B = _value;	
    }
}
```

**Comment by ReedCopsey** [comment] 2017-02-22 02:39
Sharing underlying fields would also allow the resulting type to be significantly smaller... in this case, 8 bytes instead of 12.  In larger examples I've already seen, it could be 1/10th of the size, which is huge when passing these around.

**Comment by dsyme** [comment] 2017-02-22 15:19
> @ReedCopsey suggested that when all of the cases have the same type we should just store it in the same field since the tag is enough for the comparison to continue working

Yes, that option is certainly open in the future. For unverifiable code I believe you can also use .NET union type layouts, see http://www.jasonbock.net/Article/UnionsInDotNet

**Comment by ReedCopsey** [comment] 2017-02-24 23:53
@dsyme Yes, I had considered using StructLayout - but the problem is that I don't know how you'd know whether a library was going to be used eventually in a medium trust scenario, etc - so making it unusable from non full trust scenarios seemed excessively limiting.

**Comment by dsyme** [comment] 2017-02-25 01:58
> @dsyme Yes, I had considered using StructLayout - but the problem is that I don't know how you'd know whether a library was going to be used eventually in a medium trust scenario, etc - so making it unusable from non full trust scenarios seemed excessively limiting.

As far as I can tell using .NET for partial trust execution is just not a thing any more.  .NET Core doesn't even support it. We really don't need to concern ourselves about it.  This leaves us free to use all the unverifiable tricks in the book if we wish 

There's a long discussion about this here: https://github.com/Microsoft/visualfsharp/pull/1308  No one seems to quite believe me - but I really think it's true.  The only reason not to is that we fear making mistakes in codegen

**Comment by ReedCopsey** [comment] 2017-02-27 19:33
@dsyme The other issue with using explicit layout is that it'll break down with generics - you can't use Explicit StructLayout with generic types.

**Comment by dsyme** [comment] 2017-03-14 13:50
Closing as a duplicate of #1678 (though this has additional test cases and useful discussion)

**Closed by dsyme** 2017-03-14 13:50 UTC
Labels: Area-Compiler
