### ISSUE TITLE
" can't be last char in tripple quoted string

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1364] opened 2016-07-20 12:22 UTC
![image](https://cloud.githubusercontent.com/assets/57396/16986111/3930d528-4e85-11e6-9e9d-a333caa9b8b4.png)

A triple quoted string like above can't end with a `"` and even `\"` doesn't work.

Is it a bug or just not possible to do!?

**Comment by smoothdeveloper** [comment] 2016-07-20 12:45
If this gets "fixed", we will have few places to change in this code:

https://github.com/fsprojects/Paket/blob/f5f509ace1cc58ce1f7e487c2a9f13226e5cd395/src/Paket.Core/ScriptGeneration.fs#L186

**Comment by dsyme** [comment] 2016-07-20 13:04
Strictly speaking it's according to spec I think.  But it's probably reasonable to allow any number of ``"""""""`` at the end and trim off the last three.  On first glance we would accept a PR and (very minor) spec adjustment for that.

**Comment by dsyme** [comment] 2016-11-24 18:48
closing this as it's by design

**Closed by dsyme** 2016-11-24 18:48 UTC
Labels: Feature Specification

**Comment by enricosada** [comment] 2016-11-27 21:47
@dsyme it is, but if possible can be left `up-for-grab`? 
A real work example: creating command line args where arguments should be quoted, and using `"` inside string is useful

```fsharp
sprintf """dotnet publish -c Release -out "%s" """ outDir
```

now i need to add an additional whitespace to do so. Alternative with `\"` is difficult to read

**Comment by dsyme** [comment] 2016-11-27 21:55
@enricosada I'd like to see an RFC that gives proper deep technical analysis in case we miss things.  What we have today is by design

**Comment by enricosada** [comment] 2016-11-27 22:02
@dsyme got it, thx for explaination
