### ISSUE TITLE
Go to definition, Peek definition don't work

### ISSUE THREAD

**Issue by CodEFouR** [Microsoft/visualfsharp#3288] opened 2017-06-30 04:25 UTC
#### Repro steps

1. Write some code like `List.map id [1; 2; 3]`.

2. Put the cursor on `map` and press F12.

3. The error pops up "Cannot navigate to the symbol under the caret". See the screenshot below.

#### Expected behavior

Navigate to the symbol definition (F12) or show the quick info (Alt+F12) for the definition.

#### Actual behavior

The error shows up.

#### Known workarounds

No workaround found.

#### Related information 

* Operating system: Win 10
* .NET Framework 4.6
* Visual Studio 2017 Professional with latest patch
* Visual F# Tools Latest Nightly Build 15.4.1.17062904

![default](https://user-images.githubusercontent.com/594939/27720879-242b5882-5d8f-11e7-931f-17ed6c8fb321.png)

**Comment by vasily-kirichenko** [comment] 2017-06-30 06:08
I assume you are doing it in VisualFSharp.sln or FSharp.sln solutions? If it's not the case, the behavior is right - sources for List.map is not available.

**Comment by cartermp** [comment] 2017-06-30 06:46
Closing as dupe of #1939.  There is a solid WIP PR in #2658 which is in need of a heavy rebase, but is otherwise in a good state feature-wise to merge (at least when I last tested it, which admittedly was a while ago).

**Closed by cartermp** 2017-06-30 06:46 UTC
