### ISSUE TITLE
Execute in F# Interactive broken in VS 2017 RC

### ISSUE THREAD

**Issue by dutts** [Microsoft/visualfsharp#1820] opened 2016-11-23 18:22 UTC
On a clean install of VC 2017 RC, if I open an fsx file there is no context menu option to Execute in F# Interactive and the ALT-Enter keyboard shortcut doesn't do anything.

#### Repro steps

1. Install VS 2017 RC
2. Open an .fsx file and select the code to execute
3. Right-click and see no Execute In Interaction option, or
4. Use the Alt-Enter keyboard shortcut.

#### Expected behavior

The selected code will execute in the F# Interactive window.

#### Actual behavior

Nothing.

#### Related information 

My default installation appeared to select a keyboard mapping scheme of Visual C# 2005 which didn;'t have a binding for EditorContextMenus.CodeWIndow.,ExecuteInInteractive, so I changed it to Default which has an Alt-Enter binding but still no luck.

* Operating system

Windows 10 Pro 
Version	10.0.14393 Build 14393

* Indications of severity

Unable to use F# interactive mode from .fsx scripts

**Comment by dsyme** [comment] 2016-11-23 21:51
Duplicate of #1801

**Closed by dsyme** 2016-11-23 21:51 UTC

**Comment by cartermp** [comment] 2016-11-24 01:15
Nit: this is actually a duplicate of #1598 (well, not duplicate, but the same problem).

**Comment by dutts** [comment] 2016-11-24 06:27
I'm not sure this is the same as those two other linked issues; I have no issues with intellisense and I can still execute code if I type it into the F# Interactive window. My VS 2015 install has been unaffected and continues to work as expected.

I literally have no (apparent) way of executing code from the editor in the same way I could in 2015, either by selecting the text and hitting Alt-Enter or using the right click context menu.

**Comment by cartermp** [comment] 2016-11-24 18:26
@dutts, this is the symptom of the problem in #1598, where the provider to enable Execute in Interactive is not currently implemented.  This is high on our list of bugs to fix ASAP.

**Comment by cartermp** [comment] 2016-11-24 18:32
Whoops, I meant #1633.  My bad!
