### ISSUE TITLE
Rename refactor on Active Pattern does not work

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#6055] opened 2018-12-28 11:43 UTC
Trying to rename a case on an AP does not work. You hit F2, you get the dialog up, but no references are found and no renames occur (despite the fact that the IDE correctly highlights the references when the caret is on the definition).

#### Repro steps
In the [Azure Storage Type Provider](http://fsprojects.github.io/AzureStorageTypeProvider/) project, TableRepository.fs file, I tried to rename an AP case. Screen capture below illustrates the behaviour:

![intellisense](https://user-images.githubusercontent.com/1781813/50514388-1f6f2900-0a9e-11e9-9cd0-85caf3b85866.gif)

Using 15.9.4 of VS.

**Comment by cartermp** [comment] 2018-12-28 16:41
@isaacabraham I think this is a dupe of #5581

After the project/file has been open for a while, does this still reproduce, or do you get symbols found? The rename implementation seems like it's had a timing issue for a long time and this looks like a manifestation of it.

**Comment by cartermp** [comment] 2019-04-06 16:55
@isaacabraham This no longer reproduces in VS 2019. I suspect it's related to the large amount of work that went into cleaning up how we hook up with Roslyn.

<img width="353" alt="Screen Shot 2019-04-06 at 09 54 25" src="https://user-images.githubusercontent.com/6309070/55672629-0d95e280-5852-11e9-8fbb-de9f6e8ede58.png">

**Closed by cartermp** 2019-04-06 16:55 UTC
Labels: Area-IDE Language Service, bug
