### ISSUE TITLE
VisualFsharp Tools: Solution containing F# and C# project breaks some C# tooling, even if the projects are not referencing each other

### ISSUE THREAD

**Issue by JanWosnitza** [Microsoft/visualfsharp#4796] opened 2018-04-27 08:37 UTC
When I have an F# project which references a C# project in the same solution, IntelliSense in this C# project doesn't work any more and sometimes even crashes. E.g.

- renaming classes/members
- finding references
...

#### Repro steps

1. Create a clean solution
2. Create a C# "Class Library (.NET Framework)" .NET Framwork 4.6.1
3. Create an F# "Library"
4. Add the C# project to the references of the F# project
5. Try find the references of `Class1`
6. Try rename `Class1` in the C# project

I did the steps already in [Test.zip](https://github.com/Microsoft/visualfsharp/files/1954375/Test.zip).

#### Expected behavior

Adding a C# project to the references of an F# project shouldn't destroy IntelliSense for the C# projecct.

#### Actual behavior

IntelliSense doesn't work any more.

#### Known workarounds

Don't use IntelliSense in C# or unload the F# project.

#### Related information 

I tried to reinstall VisualFsharp tools several times and also tried some nightly builds. The most current one (15.6.20180427.1) crashes VS immediately when opening the solution.

* Windows 10
* Visual Studio Professional 2017 (15.6.7)
* Visual F# Tools (15.6.0.18021307)

**Comment by cartermp** [comment] 2018-04-27 19:53
Labeling this as a regression. We haven't investigated this yet, and given that the IDE features which stop working are in the C# editor, so it's not clear if this is an issue in F# introduced in 15.6 or not.

**Comment by JanWosnitza** [comment] 2018-05-02 08:03
Hi @cartermp, I just found out, that it crashes, when you try to rename a member which is used on the F# side.

#### Repro steps (Updated)
1. Create a clean solution
1. Create a C# "Class Library (.NET Framework)" .NET Framwork 4.6.1
1. Add a static member `public static string CsMember = "C#";` to the class
1. Create an F# "Library"
1. Add the C# project to the references of the F# project
1. Use the member `CsMember` insde F#
1. Try rename `CsMember` in the C# project

Here is the updated solution from above: [Test.zip](https://github.com/Microsoft/visualfsharp/files/1966380/Test.zip)

**Comment by TIHan** [comment] 2018-07-11 23:42
After investigation in the case of using rename for C#, Roslyn will iterate over all projects to try to find that type. When it hits a F# project, it will throw because it is trying to get a `ISyntaxFactsService` from our language service which we don't have and never will. https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/FindSymbols/FindReferences/DependentTypeFinder_ProjectIndex.cs#L55

When that throws, it will cancel C#'s rename task and nothing works.

I don't think this is a regression, or at least a very recent one. Most of the code paths to get to this point haven't changed from 11 months to 2 years.

**Comment by cartermp** [comment] 2018-07-12 00:04
Closing this out as it is not an issue with the F# tools, and there is a VSTS issue for this.

**Closed by cartermp** 2018-07-12 00:04 UTC
Labels: Resolution-External
