### ISSUE TITLE
Add support for user-specific settings (e.g. ProjectName.fsproj.user)

### ISSUE THREAD

**Issue by caioproiete** [Microsoft/visualfsharp#3755] opened 2017-10-15 16:38 UTC
Some project settings are user-specific, such as the debugger options in a project (e.g. StartAction, StartProgram, etc.).

![image](https://user-images.githubusercontent.com/177608/31586821-21c738a0-b1ad-11e7-8557-29e4b75c54ee.png)

**In CSharp and in VB .NET, changing these settings will graciously create a `ProjectName.csproj.user` or `ProjectName.vbproj.user` alongside the project, to store these settings**.

FSharp projects don't follow the same behavior, and instead, save the changes inside the project itself (e.g. ProjectName.fsproj)

#### Repro steps

1. Create a new Visual F# Library

2. Open the project properties, and go to the `Debug` tab

3. Change the Start Action to "Start external program", and type in a valid path for an executable, e.g. `C:\Windows\Notepad.exe`

4. Save the project

5. Open Windows Explorer and go to the folder where the F# project is located, and notice that a `.user` file alongside the project was **not** created

6. Open the .fsproj and notice that the debug settings have been added to the project file

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
      
      <DocumentationFile>bin\$(Configuration)\$(AssemblyName).XML</DocumentationFile>
      <StartAction>Program</StartAction>
      <StartProgram>C:\Windows\Notepad.exe</StartProgram>
    </PropertyGroup>

7. Repeat steps 1 through 4, but now with a C# or VB .NET project, then open Windows Explorer and go to the folder where the C# or VB .NET project is located, and notice that the debug settings were stored in a `.user` file created alongside the project file

#### Expected behavior

Debug settings are saved in a separate `.user` file.

#### Actual behavior

Debug settings are saved in the `.fsproj` file directly. 

#### Known workarounds

I don't know of any workarounds at the moment.

#### Related information 

* Windows 10
* master branch
* .NET Runtime
* Visual Studio 2017

**Comment by dsyme** [comment] 2017-11-06 16:14
Duplicate of https://github.com/Microsoft/visualfsharp/issues/91

**Closed by dsyme** 2017-11-06 16:14 UTC
Labels: Area-IDE Project System, Feature Request
