### ISSUE TITLE
Problems using FSI on multiple namespaces in a single file

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#237] opened 2015-02-14 10:37 UTC
Somewhat related to #44. The following single (valid) .fs file with the following two dependent namespaces will not compile in FSI:

    namespace Foo
    type Name = Name of string

    namespace Bar
    open Foo
    type Person = Person of Name

with the error

    Library1.fs(7,6): error FS0039: The namespace or module 'Foo' is not defined

There doesn't seem to be a workaround for this - with #44 you could work around it within the .fsx by manually adding ``open`` statements.

**Comment by latkin** [comment] 2015-02-15 20:49
To clarify - repro is to put the above code in `code.fs`, then `#load` it from `code.fsx`.  I see this reproing back to F# 3.0

**Comment by isaacabraham** [comment] 2015-02-15 21:09
Yes, sorry, thanks for the clarification.

**Comment by isaacabraham** [comment] 2015-03-31 16:36
Hi - appreciate that there's other bugs out there that need squashing - just wondering if this one is penned in for fixing as part of the F#4 release? It's a real issue that is affecting is with a production system here in that we can't using .fsx files with our current codebase.

Not complaining if it's not - just wondering on how far up the priority list it is :-)

**Comment by latkin** [comment] 2015-03-31 17:45
I don't think anyone is looking at this one with any higher priority than any others.

FWIW I have a really terrible workaround for you, which actually probably points to the root cause.  Seems the fake `FSI_****` namespace added in interactive sessions is not being properly ignored inter-file. If you are careful you can predict its value and compensate:

```fsharp
namespace Foo
type Name = Name of string

namespace Bar

#if INTERACTIVE
open FSI_0001.Foo
#else
open Foo
#endif

type Person = Person of Name
```

**Comment by dsyme** [comment] 2015-04-10 16:55
@isaacabraham - I've prepared a fix for this here: https://github.com/Microsoft/visualfsharp/pull/359

**Comment by isaacabraham** [comment] 2015-04-10 17:22
Awesome :-) I was trying to work around that today so am looking forward to this!

**Closed** 2015-04-15 21:01 UTC
Labels: bug
