### ISSUE TITLE
Indeterministic and incompatible differences with generic method resolution between VS2010/2012 and VS2015

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#866] opened 2016-01-10 18:23 UTC
_This issue was first discussed on [StackOverflow here](http://stackoverflow.com/questions/33533647/difference-between-treatment-of-ambiguous-generic-interfaces-by-f-between-vs-20)._

TL;DR: just try the repro: [FSharpBug#866.zip](https://github.com/Microsoft/visualfsharp/files/85105/FSharpBug.866.zip)
### Description

If a class uses multiple interface inheritance in C#, the order of the declaration of the interface definitions determines whether in F# the methods are resolved correctly or incorrectly.

While that is a bug in itself, result of this resolution changed between VS2010/2012 and VS2015, leading to an incompatibility that is hard to resolve.
### Repro steps

For a full repro, open the VS2010, VS2012 or VS2015 solution and attempt to do a full build. It will fail. In each respective `Program.fs` file is a simple instruction to see the same solution with a minimal change compile successfully: [FSharpBug#866.zip](https://github.com/Microsoft/visualfsharp/files/85105/FSharpBug.866.zip)

Conditions for this bug to appear:
- Create a class lib in C#
- Create an empty base interface `Base`
- Create a generic interface inheriting from `Base`, say `IPrime`, with a generic property, say `T value`
- Create an (empty) interface, say `IFloat`, that inherits from `IPrime<T>`, with `T` defined (say `double`)
- Create an interface, say `IInt`, that inherits from the concrete interface `IFloat` _and_ from a typed `IPrime<T>`, for instance with `T` as `int`. The signature of this interface is something like `public interface IInt : IFloat, IPrime<int>`
- Create an implementation for both `IFloat` and `IInt`, say `FFloat` and `FInt` respectively
- Reference this library and try to use `FFloat` and `FInt` through their interfaces

For instance, with this inheritance in place, the following happens;

```
let g = fun (itm: Base) -> 
    match itm with
    | :? IInt as i -> i.Value |> int        // i.Value should be of type int, but is of type float
    | :? IFloat as f -> f.Value |> int      // f.Value should be of type float and is of type float
```
### Expected

Regardless how the interfaces are defined (meaning: the order of the inheritance chain), this should not influence the resolved concrete type. Furthermore, the resolution should be consistent between versions of Visual Studio and/or the compilers.
### Actual

The following list shows the weirdness of this bug:
- VS2010
  - signature `public interface IInt : IFloat, IPrime<int>` succeeds correctly
  - signature `public interface IInt : IPrime<int>, IFloat` fails with incorrect return type resolution
- VS2012
  - signature `public interface IInt : IFloat, IPrime<int>` succeeds correctly
  - signature `public interface IInt : IPrime<int>, IFloat` fails with incorrect return type resolution
- VS2015
  - signature `public interface IInt : IFloat, IPrime<int>` fails with incorrect return type resolution
  - signature `public interface IInt : IPrime<int>, IFloat` succeeds correctly
### Severity

Possibly high, as this is a compatibility issue and existing implementations (mine in this case) fail to compile after moving to a different version of Visual Studio.

Furthermore, also high because this bug has existed for quite a while (at least since VS2010) and may be the root of other more spurious errors with type resolution.

And high because if you are stuck with existing, compiled libraries, this inconsistency makes it _impossible_ (no workaround exists) to use that library.
### Version

All versions of F#, at least since VS2010. All versions of .NET. With or without RyuJIT enabled.
### Link

See also this  [StackOverflow discussion](http://stackoverflow.com/questions/33533647/difference-between-treatment-of-ambiguous-generic-interfaces-by-f-between-vs-20). 

A full repro is here: [FSharpBug#866.zip](https://github.com/Microsoft/visualfsharp/files/85105/FSharpBug.866.zip)
### Likely causes

F# seems to use the order of the inheritance declarations (i.e., how they appear in the IL) as part of the resolution process, but this does not seem like the proper way here.
### Workarounds

Stick to the declaration order of your particular compiler. In case you need to support multiple Visual Studio projects you are stuck with a complex MSBuild workaround where you will have to support multiple versions of your sources at the same time.

Arguably, a better workaround is to not use ambiguous generic interface inheritance chains, but since this is legal C# (in F# you cannot code such an inheritance chain), it should be properly supported.

In case the library with the generic interface types comes without source, I don't think a workaround exists.
### Notes

The original issue occurred in a rather large project, but the inheritance chain was much simpler. When I started creating a reproducible version, the simpler inheritance chain did not produce the compile error anymore. It is possible that other combinations of the inheritance chain can result in similar (wrong) type resolution issues.

While this repro shows how it fails compilation (to illustrate the issue), that is not always the case. In my particular case, we had a conversion class that converted the resulting value by casting. In some cases this gave strange runtime errors (unfortunately I can't remember the exception) or values that ended up empty where they should have been filled.

**Comment by dsyme** [comment] 2016-01-10 22:33
@abelbraaksma Thanks for the bug report. I notice this comment - it's good that this isn't blocking you.  

> Hmm, important detail to add: after swapping the order of the comma-separated list of interfaces, it compiles fine in VS2015, but not anymore in VS2012. Luckily we do not intend to maintain both versions. This may also point out that the cause lies in the C# 4 vs C# 5 compiler, not sure

There were changes in F# 4.0 related to multiple interface inheritance, I'd suspect those here.

**Comment by abelbraaksma** [comment] 2016-01-10 22:54
>  I notice this comment on stackoverflow

@dsyme Yes, that comment is the whole essence, the repro zip file contains this as an instruction to switch between a FAIL and a SUCCESS build.

I doubt at this moment that the C# compiler is the culprit, because I can repro the issue on all versions of both C# and F# compiler that I have at my disposal (hence the VS2010, VS2012 and VS2015 versions in the ZIP file).

> There were changes in F# 4.0 related to multiple interface inheritance, I'd suspect those here. 

Possibly, but be forewarned, this issue is older than F# 4.0. The bug was already there since 2010, F# 4.0 merely slightly changed the order of declaration that caused the bug.

**Comment by dsyme** [comment] 2017-02-02 15:59
Closing this as by design - we decided not to make any more changes in this area, finalizing on the VS2015 behavior

**Closed by dsyme** 2017-02-02 15:59 UTC
Labels: Area-Compiler, bug, Urgency-Later
