### ISSUE TITLE
Build CoreCLR support on Unix

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#336] opened 2015-03-28 04:07 UTC
It would be very useful if it was possible to build at least the non-vs specific portions of Visual FSharp Tools for CoreCLR and/or Mono on Linux and Mac.

**Comment by brodyberg** [comment] 2015-03-30 15:26
+1 

Definitely important and very likely low-hanging fruit for an interested Unix user.

**Comment by enricosada** [comment] 2015-04-01 10:43
build with xbuild on mono is easy but useless

we should align visualfsharp with the open fsharp repo ( see #262 ) the linux/mac build work and is **maintained** by community. Not add another different build system pls

roadmap to cross plat mean choose:
- a test runner, nunit?
- a build script
  - windows = bat + linux makefile is ok
  -  fake (make invoke fake) is better
- an orchestrator ( like fake? ) to run task, like run tests, etc

but **the same, not two different implementation in each repo**

there are some small differences like:

- directory `lkg` vs `lib`
- directory `.nuget` vs `FSharp.Core.Nuget.nuget`
- etc, see #262

we can add conditional, but is worth it? easier to choose a name and modify visualfsharp or openfsharp

just diff the two repo (now is easier, i removed white space noise ) and summarized the difference in #262 
some are features, like `fsc --gccerrors` , can be merged later

i can help, but need visualfsharp team and openfsharp ( @dsyme ? ) to discuss about it and choose, i dont want to waste time

**Comment by forki** [comment] 2015-04-01 10:46
there is also discussion about alignment with FCS in #334 which already uses FAKE.

**Comment by latkin** [comment] 2015-04-01 17:44
The Open Edition repo has a stable build/test/package story for mono already.  It's not clear to me why we need to duplicate that here?  Microsoft/Visual F# is not investing long-term in mono as the .NET xplat story.

CoreCLR/.NET Core is the future for .NET xplat, and the future of F# xplat at least as sponsored by Microsoft. I think that's where this repo should start moving. So yes, *nix build is pure win, but on coreclr (mono is already covered well by open edition).

**Comment by KevinRansom** [comment] 2015-04-03 01:59
@enricosada I have a few questions about your response. 1. what do you mean "useless"? Does it not work? Do the built binaries not work?    2. As it current stands there is no way to ensure that submissions to visualfsharp tools will not break the mono version of the compiler.  With a mono build and teat suite we can set up a mono based ci to ensure that contributions to the visual fsharp tools compiler work on mono.   Do you really believe that has no value?

**Comment by enricosada** [comment] 2015-04-03 09:10
There is already a working supported mono version.
We need only to align the two repo (first the xplat stuff, the new features can wait). 
Add makefile and xbuild target is useless if compile but not work, a false positive. The problem is not a compile time, is at runtime

1. mono/xbuild api is ok, so build is usually not a problem (minor thins like SymWrapper, xbuild workaround, etc).

At runtime mono has some differences:
- implementation, like string ordinal ( like [this fix on test suite](https://github.com/Microsoft/visualfsharp/commit/67829f188ed548117802ec5679063ee97b031b45#diff-5ef02aad2fb2d7331902741a45d9ac4cL107) )
- not supported or bugs ( see the `if runningOnMono` ) 
- xplat (dir separator, permission, etc)

You can check if a build is ready only with test ( for that i tried to add #90 to make the test suite run xplat, next is fsharpqa ) and manual testing. linux vs macosx is another issue.

2. i think xplat is usefull, ci too ( i added travis to openfsharp repo ). 
But *work on mono* is openfsharp repo. This mean:
- build ( mono version )
- run ( test suite e manual test )
- packaging ( fsc need the find the right bcl ) 
- people who use it, find regression (fsharp bug, mono regression) and fix it.

I am actively trying to align repo, when done the build is free, and visualfsharp can merge back fix for openfsharp repo.

For .net core ihmo is a good idea is to start now with openfsharp repo, so all xplat stuff is ready (test suite, build, etc). Btw news on .net core support?

**Comment by cartermp** [comment] 2017-08-05 05:38
Closing in favor of #2854 as it is far more comprehensive.

**Closed by cartermp** 2017-08-05 05:38 UTC
Labels: Area-CoreCLR, Contributor Pain, infrastructure
