### ISSUE TITLE
Duplicate definition errors aren't reported when other module member has errors

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#5789] opened 2018-10-18 15:06 UTC
```fsharp
let f = ignore >> ignore

let a = 123
let a = 123
```
With error in other member:
<img width="287" alt="screen shot 2018-10-18 at 18 04 46" src="https://user-images.githubusercontent.com/3923587/47164259-61425d00-d300-11e8-9d98-ae191c359e33.png">

With the member commented out:
<img width="274" alt="screen shot 2018-10-18 at 18 05 05" src="https://user-images.githubusercontent.com/3923587/47164258-61425d00-d300-11e8-982d-48294d0bf74f.png">

**Comment by dsyme** [comment] 2018-10-18 16:14
This is just how things work, I don't think we regard this as a bug.  There are several phases to analysis and error reporting and we don't guarantee to continue on to later phases if there are errors in previous phases

**Comment by cartermp** [comment] 2018-10-19 16:50
@auduchinok I added the appropriate label for this in case it gets revisited.

@dsyme do you want to keep this open despite resolving it as by design?

**Closed** 2018-10-25 10:57 UTC
Labels: Resolution-By Design, error recovery
