### ISSUE TITLE
Rename factor does not work on Record type name.

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#5520] opened 2018-08-16 10:06 UTC
In 15.8, renaming the type of a Record does not change associated type annotations:

![rename](https://user-images.githubusercontent.com/1781813/44202591-b7522300-a14c-11e8-91b6-0eaaa82abef6.gif)

**Comment by cartermp** [comment] 2018-08-16 16:09
@isaacabraham Is the file saved on disk? If so, then this is a dupe of #2204

**Comment by cartermp** [comment] 2018-08-16 16:10
So long as files are saved on disk, rename updates everything for me on my 15.8 install.

**Comment by cartermp** [comment] 2018-08-17 16:04
@isaacabraham can you confirm that this was for an unsaved file?

**Comment by cartermp** [comment] 2018-08-20 16:37
Was it a script file? Renaming like this on a "naked" script that isn't in works for me.

**Comment by cartermp** [comment] 2018-08-20 16:39
I just tested this with Open Folder > Create fsx file > Rename, and it works. Do you have something you can upload that reproduces?

**Comment by cartermp** [comment] 2018-09-15 05:50
@isaacabraham Closing this as it's been open without a repro for quite some time. If you have a reproducible scenario please report back and we can re-open it.

**Closed by cartermp** 2018-09-15 05:50 UTC
Labels: needs repro
