### ISSUE TITLE
Odd compiler error with static member constraints

### ISSUE THREAD

**Issue by estokes** [Microsoft/visualfsharp#2353] opened 2017-02-01 20:34 UTC
The following code results in
```
error FS0193: A type parameter is missing a constraint 'when ( ^A or  ^?34675) : (static member ( + ) :  ^A *  ^?34675 ->  ^?34676)'

type A< ^A when ^A: (static member (+): ^A * ^A -> ^A)
            and ^A: (static member Zero: ^A)>() =
  member inline __.ZeroPlusZero() = 
    let zero = LanguagePrimitives.GenericZero< ^A>
    zero + zero
```

However this very similar code compiles and works as expected
```
type B< ^A when ^A: (static member (+): ^A * ^A -> ^A)
            and ^A: (static member Zero: ^A)>() =
  static member inline private Add(x: 'a, y: 'a) = x + y
  member inline __.ZeroPlusZero() = 
    let zero = LanguagePrimitives.GenericZero< ^A>
    B<'A>.Add(zero, zero)
```

Obviously we can work around this problem with the second form, but it seems like the first form should work.

This is F# 4.0, 14.0.23413.0 on windows 10.

**Comment by dsyme** [comment] 2017-02-02 14:02
@estokes the warning does seem spurious.

**Comment by dsyme** [comment] 2017-02-02 14:56
Duplicate of https://github.com/Microsoft/visualfsharp/issues/385

**Closed by dsyme** 2017-02-02 14:56 UTC
Labels: Area-Compiler, bug, Urgency-Later
