### ISSUE TITLE
Appveyor Error running tests\Upload-Results.ps1

### ISSUE THREAD

**Issue by WilliamBerryiii** [Microsoft/visualfsharp#767] opened 2015-12-06 08:01 UTC
The appveyor build is throwing errors 'fileName' is null when calling Upload-Results.ps1.  Please see example from lines 3900+ here: https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1126

**Comment by WilliamBerryiii** [comment] 2015-12-06 18:17
Additionally, If this information is  important ... should the build fail if the data is not uploaded.

**Comment by enricosada** [comment] 2015-12-07 13:46
duplicate of #754

**Closed** 2015-12-07 17:17 UTC
