### ISSUE TITLE
With ReSharper active, type info is hidden from tooltips when unused values or errors are present

### ISSUE THREAD

**Issue by TeaDrivenDev** [Microsoft/visualfsharp#3056] opened 2017-05-15 22:47 UTC
### Update from @cartermp

#3547 is the same issue, except for an error rather than the unused value analyzer.

#### Repro steps

1. Create a `let` binding in F# code, leave the value unused
2. Hover over the name with the mouse pointer

#### Expected behavior

The Tooltip displays type information for the value.

![screenshot - 20170516004528](https://cloud.githubusercontent.com/assets/2247219/26082587/02f05faa-39d1-11e7-8820-b3b8b11606bc.png)

#### Actual behavior

The tooltip only says "The value is unused - Show potential fixes".

![screenshot - 20170516002837](https://cloud.githubusercontent.com/assets/2247219/26082220/291905b2-39cf-11e7-9ad7-3409450faec9.png)

#### Known workarounds

Set the caret on the name, press Ctrl-K, Ctrl-I

#### Related information 

VFT version 15.4.1.17051503

**Comment by vasily-kirichenko** [comment] 2017-05-16 04:42
@majocha it seems tooltips are broken even in master :( @TeaDrivenDev can you say in what version you saw this bug first time?

**Comment by majocha** [comment] 2017-05-16 18:13
I can't reproduce this on master :|
I'm downloading 1503 and will try.

**Comment by majocha** [comment] 2017-05-16 18:27
Can't reproduce on 1503 either. @TeaDrivenDev is this occurring randomly?

**Comment by majocha** [comment] 2017-05-16 18:49
Current master:

![tooltip](https://cloud.githubusercontent.com/assets/1760221/26122477/f35e458c-3a77-11e7-8e66-30aa2fa7d87f.gif)

As can be seen, Visual Studio puts the tooltip together from various sources asynchronously. Various parts show up independently and shouldn't interfere.
If for example `getTooltipFromRange` fails or `GetItemAsync` is very late, the displayed result could be exactly as in this issue.

**Comment by TeaDrivenDev** [comment] 2017-05-16 19:32
@majocha No, it's consistent. I don't remember ever seeing it work as in your screenshot. The type information never shows up, even on small self-contained scripts.

**Comment by TeaDrivenDev** [comment] 2017-05-16 19:51
I just checked on my other machine, and it appears to work fine there (VS 2017 Community with 17051401). It doesn't work at all on this one (VS 2017 Professional); I also suspended ReSharper (just to be sure), but that didn't change anything.

**Comment by majocha** [comment] 2017-05-16 20:08
@TeaDrivenDev thanks for the follow-up. This is mysterious. I can't think of anything that would break this between 514 and 515.

**Comment by TeaDrivenDev** [comment] 2017-05-16 20:38
@majocha It doesn't seem to be related to the versions; it still works fine on the other machine with 1604. So there appears to be something on that one system that prevents the tooltip from being updated.

**Comment by majocha** [comment] 2017-05-16 20:47
@TeaDrivenDev this bug happens on a particular configuration, and only when triggered with the mouse, not the keyboard, and only when there is also a "unused value" hint?

**Comment by TeaDrivenDev** [comment] 2017-05-16 21:17
@majocha Yes, exactly. The system in question has now updated to 1604 as well and still shows that behavior.

**Comment by majocha** [comment] 2017-05-17 07:03
Thanks, this gives me some ideas about what to look into.

**Comment by cartermp** [comment] 2017-08-05 06:06
@TeaDrivenDev Can you still reproduce this?

**Comment by TeaDrivenDev** [comment] 2017-08-05 13:29
@cartermp Yes, consistently on one machine, never on the other.

**Comment by cartermp** [comment] 2017-08-05 15:46
Hmmm.  Strange, because I haven't been able to reproduce this.  One guess is that the VS install on the machine it repros on is bad.  Have you reinstalled or repaired on that machine since seeing this?

**Comment by TeaDrivenDev** [comment] 2017-08-05 19:31
I don't think I have with VS. I have likely un- and reinstalled the F# Tools several times in that time, though.

**Comment by cartermp** [comment] 2017-08-05 20:11
If you could try reinstalling VS on that machine, that would be great.  Because this is only consistent on that machine and the F# tools have been uninstalled/reinstalled there, I suspect that something went funky on the install of VS itself.

**Comment by Pilchie** [comment] 2017-08-07 17:43
Potentially a MEF ordering issue where one thing is shown on top of the other because the order is indeterminate, and usually we get lucky?

**Comment by TeaDrivenDev** [comment] 2017-08-08 02:01
If there's anything I can do give you any kind of additional diagnostic information as "patient zero", let me know.

**Comment by bentayloruk** [comment] 2017-11-01 09:56
I have the same issue originally reported by @TeaDrivenDev, but the workaround does not work for me because Ctrl+K+I also shows the warning only.  I can't find a way to make the type information show.  I'm running the nightly.  I've included the version information and the full VS info below.  
![f -tooltip-issue](https://user-images.githubusercontent.com/189409/32269052-32002efe-bee9-11e7-8305-601d8a93e483.gif)

![image](https://user-images.githubusercontent.com/189409/32269538-91a01dc8-beea-11e7-9d1e-69fef231a3c1.png)

<details>
<summary>Full VS Version Details</summary>
Microsoft Visual Studio Professional 2017 
Version 15.4.2
VisualStudio.15.Release/15.4.2+27004.2006
Microsoft .NET Framework
Version 4.6.01590

Installed Version: Professional

Visual Basic 2017   00369-60000-00001-AA768
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA768
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA768
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.9.00809.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.50921.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30915.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GhostDoc   5.4.16325.0
GhostDoc automatically generates XML documentation comments.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2017.1.2    Build 108.0.20170428.75743
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Node.js Tools   1.4.10918.1
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

TestDriven.Net   4.0-beta3
Zero friction testing for Visual Studio

TypeScript   2.3.5.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VsVim   2.4.1.0
VsVim is a Vim emulator for Visual Studio
</details>

**Comment by vasily-kirichenko** [comment] 2017-11-01 10:01
Yes, I can reproduce it every time. It's super annoying.

**Comment by bentayloruk** [comment] 2017-11-01 10:38
It is.  I don't have any F# templates either for some reason.  I'm going to try a VS repair and then a re-install if the repair does not work.  I'll update with any change.

**Comment by bentayloruk** [comment] 2017-11-01 11:18
The tooltip and templates are now working for me.  I fixed it by downloading the VS2017 installer from MSDN, running it and selecting the repair option.  I then added back VsVim and the F# nightly config, updated to the latest nightly and all was working.  It also worked before going back to the nightly.

**Comment by bentayloruk** [comment] 2017-11-02 10:40
I spoke to soon.  VS was very unstable after doing the repair and the F# nightly configuration.  This specific issue was fixed, but VS started crashing when I tried to rename C# type members.  Therefore, I re-installed Visual Studio and configured nightlies again.  I now have the original issue back.  I only see **The value is unused** when hovering or doing Ctrl+K Ctrl+I.  In addition, VS still crashes when I try and rename a C# member.  So I've swapped one issue for two!  If anyone can advise me as to what I can do to help diagnose this, please let me know.

**Comment by cartermp** [comment] 2017-11-02 16:45
cc @Pilchie @jinujoseph for the issue with VS crashing with Inline Rename on C# members.  That definitely doesn't seem right, and the F# nightly shouldn't be messing with that.

@bentayloruk If you go to VS and click the "Report a Problem" icon in the top-right and create a new issue, the Attachments tab will have an option called "record".  This will record a trace that you can send with the feedback tool, which will allow people to see what's going on.

**Comment by cartermp** [comment] 2017-11-02 16:50
Unfortunately, I still can't reproduce this :(

Using 15.5 Preview 2.

**Comment by vasily-kirichenko** [comment] 2017-11-02 16:53
@cartermp I forget when I saw both signature and "value is unused" at the same time.

**Comment by bentayloruk** [comment] 2017-11-02 17:24
@cartermp thanks for the guidance.  I've never used that feature before!

It turns out that I don't even have to try and rename the member.  I literally just have to click on the name of it and it causes a `NullReferenceException` in `Microsoft.CodeAnalysis.Workspaces`.  I've recorded the steps and submitted it [over here](https://developercommunity.visualstudio.com/content/problem/143079/visual-studio-crash-when-click-on-c-interface-memb.html). 

Is there any easy way to flip between the nightly and the latest "official" version of F# for VS?  I could try that and confirm if the issue is present when not on the nightly.

**Comment by cartermp** [comment] 2017-11-02 17:44
@bentayloruk Unfortunately, there's no way to toggle the version of the tools.  If you run `VSIXInstaller.exe /u:VisualFSharp` from the Visual Studio Developer Command Prompt (admin mode not required, but I do it as admin anyways) then it will uninstall the nightly release.

**Comment by bentayloruk** [comment] 2017-11-02 17:58
@cartermp The uninstall is easy enough, thanks.  I uninstalled and the crash when clicking the C# member no longer happens.  The R# dialog box pops up as expected.  I'm not sure if this confirms it's anything to do with VFT or not...

**Comment by cartermp** [comment] 2017-11-02 18:18
It definitely _shouldn't_, and I'd be shocked if it did.  Regardless, @brettfo you may want to take a look at this as well...

**Comment by RinsibleElk** [comment] 2017-11-07 15:00
I'm pretty late on this but regarding the original issue, I found that suspending Resharper didn't help, however disabling Resharper fully (and restarting VS) sorted it.

**Comment by vasily-kirichenko** [comment] 2017-11-07 15:27
@RinsibleElk how have you managed to disable R#? I have it installed as part of R# Ultimate.

**Comment by bentayloruk** [comment] 2017-11-07 15:30
Thanks for the comment @RinsibleElk.  I've just disabled ReSharper and the original issue was resolved for me too (I can see the value is unused AND the type information for the value).  However, the crash on the C# member still happens.

@vasily-kirichenko I disabled ReSharper via Tools > Extensions and Updates > Installed > All > Resharper, then click Disable and restart.

**Comment by cartermp** [comment] 2017-11-07 16:30
Just to make sure we're isolating variables here: does the issue go away if you restart VS _and_ have ReSharper active?

**Comment by bentayloruk** [comment] 2017-11-07 16:37
@cartermp not for me.  The issue remains if I restart VS *and* have R# active.

**Comment by cartermp** [comment] 2017-11-07 16:43
Thanks!  @auduchinok - anyone on the JB side who might be able to see what's going on here?

**Comment by auduchinok** [comment] 2017-11-08 13:42
@cartermp Thanks for letting me know!
I've discussed the issue with a R# team member who is responsible for tooltips, we'll try to sort it out.

**Comment by auduchinok** [comment] 2017-11-10 11:26
Even though it happens when ReSharper is active, it looks like the bug is not caused by ReSharper itself but rather by just its presence in the Visual Studio component container.
ReSharper exports a class implementing `IQuickInfoSourceProvider` that may add add modify tooltips. The provider however does nothing breaking for F# files in its `AugmentQuickInfoSession`.

It looks like the actual problem is caused by `QuickInfoCommandHandlerAndSourceProvider+QuickInfoSource` that doesn't ask other providers when tooltip evaluation session (`IQuickInfoSession`) already has any element ([decompiled method](https://gist.github.com/auduchinok/3145e2098b64f2584fc5b6e49930ca55#file-quickinfocommandhandlerandsourceprovider-cs-L96-L97)).

How is it related? There's a sorted list of exported providers. When the ReSharper provider isn't exported `QuickInfoSource` goes before `SquiggleQuickInfoSource` in the list. When the provider is exported the order of these two is changed. Due to this the error/warning squiggle is being added before the type tooltip and then `QuickInfoSource` doesn't execute any other providers (so the type tooltip is never added).

It looks like adding `Order` attributes to these two providers in VS/Roslyn code will fix the issue.

**Comment by auduchinok** [comment] 2017-11-14 19:41
@cartermp Could someone on MS side check whether adding these attributes fixes the issue?

**Comment by cartermp** [comment] 2017-11-14 19:42
Whoops, missed this.  Thanks for getting this looked into, @auduchinok.

@Pilchie would you know more about this?

**Comment by Pilchie** [comment] 2017-11-14 19:50
Tagging @Jinujoseph.  @Rchande probably has the most context on QuickInfo, but isn't directly working on that right now.

@brettfo has also done some stuff in the Roslyn QuickInfoProvider.

**Comment by cmeeren** [comment] 2017-11-20 10:53
I too experience the same error when R# is enabled (even if suspended). Disabling the R# plugin and restarting VS fixes the issue. See #3518.

**Comment by bentayloruk** [comment] 2017-11-20 15:34
FYI someone has added the crash that [I mention above](https://github.com/Microsoft/visualfsharp/issues/3056#issuecomment-341382016) and reported via VS, in the Roslyn repos https://github.com/dotnet/roslyn/issues/23279.

**Comment by cartermp** [comment] 2017-11-20 15:45
@bentayloruk looks like it was migrated over from our feedback tool, since active development for Roslyn is on GitHub.

**Comment by bentayloruk** [comment] 2017-11-20 17:18
@cartermp yes.  I don't the issue on new VM with latest VS release and F# nightly, so hopefully it's sorted.  Going to try and confirm by updating VS on my broken VM.

**Comment by urbanhop** [comment] 2017-12-07 07:13
VS 2017 with Resharper.
"The value is unused" but no type info.
Resharper disabled, no change at all.
Having no type info available for variables stops me from using VS2017.

Can I disable the whole Roslyn code fix feature from F#?

**Comment by vasily-kirichenko** [comment] 2017-12-07 07:14
@urbanhop Are you sure you _disabled_ R#, not suspended?

You cannot disable the fix.

**Comment by cmeeren** [comment] 2017-12-07 07:20
I see that a few comments up, @bentayloruk reports not seeing "the issue". I don't know what the issue is, but just to be clear, I still experience missing tooltips when R# is enabled or suspended on VS15.5 and latest nightly.

**Comment by urbanhop** [comment] 2017-12-07 07:54
@vasily-kirichenko you got me. I suspended it. How can I disable it?

**Comment by cmeeren** [comment] 2017-12-07 07:55
@urbanhop  In Tools -> Extensions and updates.

**Comment by urbanhop** [comment] 2017-12-07 07:58
VS2017. Resharper disabled. Still no type info. Just "The value is unused".

Any helpful information I can provide?

**Comment by vasily-kirichenko** [comment] 2017-12-07 08:00
@urbanhop go to Tools -> Extensions and updates -> ReSharper, and disable it.

**Comment by cmeeren** [comment] 2017-12-07 08:01
Just to be sure that R# is disabled, open Tools -> Options and search for ReSharper. There should be no results.

**Comment by urbanhop** [comment] 2017-12-07 08:06
VS2017. Resharper disabled. Another restart of VS. **Type info is there**.

**Comment by urbanhop** [comment] 2017-12-07 08:14
Filed a bug report to Jetbrains/Resharper, citing this thread.

**Comment by cmeeren** [comment] 2017-12-07 08:15
@urbanhop Could you post the link?

**Comment by urbanhop** [comment] 2017-12-07 14:50
@cmeeren, Jetbrains replied to me that @auduchinok replied here above already.

**Comment by cartermp** [comment] 2017-12-07 16:48
See here: https://github.com/Microsoft/visualfsharp/issues/3056#issuecomment-344376832

This is likely an issue "further down the stack" than F# or R#. @Pilchie suspected as much [here](https://github.com/Microsoft/visualfsharp/issues/3056#issuecomment-320731248).

@urbanhop You say this:
> Having no type info available for variables stops me from using VS2017.

Just to clarify, is this _only_ when the value is unused?

**Comment by cmeeren** [comment] 2017-12-07 19:38
> Just to clarify, is this only when the value is unused

I'll let @urbanhop answer for themselves but I seem to experience this when there's any kind of warning or error. Simply put, if there's a squiggle (or unused), then only the error is shown and nothing else unless I completely disable R# (which is a drag in a mixed F#/C# solution).

**Comment by cartermp** [comment] 2017-12-07 22:38
I suspect that is some lower-level issue, then.  @jinujoseph is this something your team can look into?

In the meantime, #4074 should make the issue with unused names a bit easier to deal with. I think it's good to have the configuration either way.

**Comment by urbanhop** [comment] 2017-12-09 08:03
@cartermp : Yes the problem occurs **only when the value really *is* unused**. This is a big problem as I use VS to write *fresh* code (partly joking here) and fresh code *very very* frequently involves unused values. A fresh function with its signature just written certainly does not yet use the values passed in. So as long as you do not use the args you are not able to examine their type. But before using them I want to check which type they have. Not possible due to this issue.

**Comment by kkkmail** [comment] 2018-01-18 00:05
The stuff still does not work, no matter what I tried according to descriptions above!!! The stupid workaround is to "agree" to prefix unused value with the underscore and then, voila!, R# miracle happens and it is possible to see the type.

**Comment by cmeeren** [comment] 2018-02-01 10:25
Any update on this? I still have to completely disable ReSharper in order for the problem to disappear, which is a bit of a letdown to be honest, because it's great for my C# code (I have mixed C#/F# solutions).

**Comment by cartermp** [comment] 2018-02-01 16:16
No update. 15.6 will have the ability to turn off the analyzer as a workaround.

**Comment by cmeeren** [comment] 2018-02-01 17:10
Is there an issue/report anywhere else I could track?

**Comment by cartermp** [comment] 2018-02-01 17:31
Not at the moment, no. When we have the time, we can debug the editor to determine the root cause and route to the right team (or muck about with MEF ourselves if need be). But this is not a critical issue in our eyes, so there is no timeline for when that will happen.

**Comment by urbanhop** [comment] 2018-02-01 18:20
Just wanted to report back that with 

VS2017 15.5.6 
Visual F# 4.1   00369-60000-00001-AA903

unused variables are not reported as being unused, making the problem disappear on my side (Being able to inspect types during coding is more important to me than reminding me about unused vars). thx

**Comment by saul** [comment] 2018-02-03 17:19
@cartermp can we get someone from MS to take a look at this? If the Order attribute fixes this then it's a one line fix. None of the open source contributors have access to the code in question so we have our hands tied here...

**Comment by cmeeren** [comment] 2018-05-09 19:00
Any update on this? Especially considering the above comment by @saul that this could perhaps be a one line fix from MS if someone could just pull that string.

**Comment by realvictorprm** [comment] 2018-05-10 06:07
Pinging too, reshaped is quite much used so far I understood so possible bugs connected to it should be resolved.

**Comment by cartermp** [comment] 2018-05-10 14:48
No update at this time. QuickInfo is now fully in the editor layer, so perhaps @olegtk would know more about this: https://github.com/Microsoft/visualfsharp/issues/3056#issuecomment-343449101

**Comment by olegtk** [comment] 2018-05-10 15:44
That sounds like something @gundermanc fixed recently (only one content item in QuickInfo).

**Comment by gundermanc** [comment] 2018-05-10 16:02
The issue I fixed was with multiple errors. It's possible this is an IDE bug but what I suspect is happening is that you're encountering weirdness from Roslyn's 15.7 and earlier use of the quick info APIs. If this is the case, there should be no repro in the newest F# bits because IIRC you've already switched over to the new async quick info.

Roslyn's quick info has generally required a couple of dozen milliseconds to compute and the previous generation of quick info APIs were synchronous, so to avoid UI delays, they built a state machine inside an IQuickInfoSource.

This state machine waits for the API to request items and if there are _item_ count is zero, then

**Comment by realvictorprm** [comment] 2018-05-10 16:19
@cmeeren Can you check it please with the preview 15.8?

**Comment by cmeeren** [comment] 2018-05-10 17:44
Unfortunately it's not fixed in 15.8.

**Comment by auduchinok** [comment] 2018-05-10 17:46
@gundermanc Have you tried adding `Order` attributes to provider types as suggested in https://github.com/Microsoft/visualfsharp/issues/3056#issuecomment-343449101 so the providers order is stable?

**Comment by cmeeren** [comment] 2018-05-10 18:12
> I'm not very familiar with F#, does someone have a repro they can share?

[Repro solution.zip](https://github.com/Microsoft/visualfsharp/files/1992765/Test.zip)

**Comment by gundermanc** [comment] 2018-05-10 19:43
Took a look at the bits in the various preview builds on my box and they don't seem to contain the change to the new quick info API yet (they still use IQuickInfoProvider instead of IAsyncQuickInfoProvider):

```csharp
namespace Microsoft.VisualStudio.FSharp.Editor
{
	[ExportQuickInfoProvider("Semantic Quick Info Provider", "F#"), CompilationMapping(SourceConstructFlags.ObjectType)]
	[Serializable]
	internal class FSharpQuickInfoProvider : IQuickInfoProvider
	{
        }
}
```

@brettfo can you confirm whether or not [this change](https://github.com/Microsoft/visualfsharp/commit/a71287f96ec8709d222f13de7e67499393dec04b) has made it into any of the VS previews? I'm fairly certain it should fix this bug (see my comment above).

**Comment by saul** [comment] 2018-05-10 20:43
@gundermanc as far as I'm aware, the DLLs for the tools have the commit hash in their assembly info. You can figure out whether the DLLs you're using include that commit or not that way:

![image](https://user-images.githubusercontent.com/64654/39893238-0be587a8-549b-11e8-9068-57da5a304133.png)

If you're using the nightlies, then obviously it will already contain that commit.

If you're using one of the previews, navigate to: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp`

**Comment by brettfo** [comment] 2018-05-10 23:56
@gundermanc The async quick info changes will first appear in VS 15.8 preview 2.  If you want to use them now you can [consume the nightly packages](https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/) which are built from `master` (which has this change).

**Comment by vasily-kirichenko** [comment] 2018-05-11 07:40
15.8 preview with R#:

![image](https://user-images.githubusercontent.com/873919/39912180-88ee963e-5506-11e8-9c81-73eaa2801833.png)

15.8 preview with R# + VFT nightly:

![image](https://user-images.githubusercontent.com/873919/39912507-a27b2562-5507-11e8-85bc-23e3051740b6.png)

So, the issue has been solved 🔥

**Closed** 2018-05-11 14:14 UTC
Labels: Area-External, Urgency-Later
