### ISSUE TITLE
Visual F# shows as "2015 RC" in VS 2015 RTM

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#546] opened 2015-07-20 19:40 UTC
![image](https://cloud.githubusercontent.com/assets/873919/8785432/4b224a20-2f30-11e5-9b0f-7aa0ce027851.png)

**Comment by forki** [comment] 2015-07-20 19:41
Duplicate of #545

**Closed** 2015-07-20 19:43 UTC
