### ISSUE TITLE
FSI packaged with 3.0.100-preview3-010431 doesn't recognize System.Uri

### ISSUE THREAD

**Issue by HoraceGonzalez** [Microsoft/visualfsharp#6336] opened 2019-03-16 21:04 UTC
While using the dotnet core version of FSI in 3.0 preview 3, the type `System.Uri` doesn't seem to be recognized by default. 

#### Repro steps

1. run fsi, eg. `dotnet fsi.exe`

2. execute the following script:
```
let foo = System.Uri("https://fsharp.org")
```

#### Expected behavior

FSI interprets the code without error. 

```
> let foo = System.Uri("https://fsharp.org");;
val foo : System.Uri = https://fsharp.org/
```

#### Actual behavior

FSI outputs the following error:

```
  let foo = System.Uri("");;
  -----------------^^^

/home/stdin(3,18): error FS0039: The value, constructor, namespace or type 'Uri' is not defined.
```

#### Known workarounds

I'm not confident this is a proper workaround, but explicitly referencing `System.Private.Uri.dll` from within FSI seems to at least get rid of the error. Eg.: 

```
#r "System.Private.Uri"
```
#### Related information 

Here's my `dotnet --info`:
```
> dotnet --info                                                                                                                                                               
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/tracy/.dotnet/sdk/3.0.100-preview3-010431/

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.300 [/home/tracy/.dotnet/sdk]
  2.1.402 [/home/tracy/.dotnet/sdk]
  2.1.503 [/home/tracy/.dotnet/sdk]
  3.0.100-preview3-010431 [/home/tracy/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/home/tracy/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/home/tracy/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [/home/tracy/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/home/tracy/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/home/tracy/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [/home/tracy/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [/home/tracy/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/home/tracy/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/home/tracy/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/home/tracy/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [/home/tracy/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

PS Made some formatting edits on this comment.

**Comment by KevinRansom** [comment] 2019-03-18 17:25
@HoraceGonzalez,

yes there are a few framework types that fsi doesn't currently recognize:  this PR: is intended to address that: https://github.com/Microsoft/visualfsharp/pull/6324

However, that PR, has as a side-effect opened up a much worse bug, that I am looking at right now, and will need to fix before I can merge this one.

Kevin

**Comment by cartermp** [comment] 2019-03-18 17:43
Closing as dupe of #6215

**Closed by cartermp** 2019-03-18 17:43 UTC

**Comment by KevinRansom** [comment] 2019-03-18 17:46
@HoraceGonzalez, thanks for this report.

**Comment by HoraceGonzalez** [comment] 2019-03-19 00:07
Thanks, folks!

**Comment by hravnx** [comment] 2020-01-16 22:28
This error is still (again?) present in dotnet core 3.1.101 on macOS 10.15.2. Exact same repro steps as in the original description above.

Output from `dotnet --info` 
```
NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c
```
