### ISSUE TITLE
Values inside join query in SQLProvider wrongly marked as unused when compiled with --warnon:1182

### ISSUE THREAD

**Issue by pmbanka** [Microsoft/visualfsharp#3421] opened 2017-08-05 13:53 UTC
Reference issue in SQLProvider repo: https://github.com/fsprojects/SQLProvider/issues/439

When compiled with --warnon:1182 (unused variables flag), values inside an SQLPrivider query are marked as unused even though they are used in a join operation.

I see the same issue with F# 4.0 and F# 4.1.

#### Repro steps

Repro: https://github.com/pmbanka/sqlprovider-repro (includes the db).

```
namespace TpRepro

open FSharp.Data.Sql

module Foo =
    // https://github.com/jpwhite3/northwind-SQLite3
    let [<Literal>] resolutionPath = __SOURCE_DIRECTORY__ + @"\..\packages\System.Data.SQLite.Core\lib\net46"
    let [<Literal>] connectionString = "Data Source=" + __SOURCE_DIRECTORY__ + @"\..\Northwind_small.sqlite;Version=3"

    type sql = SqlDataProvider< 
                  ConnectionString = connectionString,
                  DatabaseVendor = Common.DatabaseProviderTypes.SQLITE,
                  ResolutionPath = resolutionPath,
                  IndividualsAmount = 1000,
                  UseOptionTypes = true >
    let ctx = sql.GetDataContext()
    
    let zz = 
        query {
            for e in ctx.Main.Employee do
            join et in ctx.Main.EmployeeTerritory on (e.Id = Some et.EmployeeId)
            join t in ctx.Main.Territory on (et.TerritoryId = t.Id)
            select t.RegionId
        } |> Seq.tryHead
```

Compiling that with --warnon:1182 shows warnings on e and et:

```
1>------ Rebuild All started: Project: TpRepro, Configuration: Debug Any CPU ------
1>	C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe -o:obj\Debug\TpRepro.dll -g --debug:full --noframework --define:DEBUG --define:TRACE --doc:bin\Debug\TpRepro.XML --optimize- --tailcalls- -r:C:\repos\sqlprovider-repro\packages\EntityFramework\lib\net45\EntityFramework.dll -r:C:\repos\sqlprovider-repro\packages\EntityFramework\lib\net45\EntityFramework.SqlServer.dll -r:C:\repos\sqlprovider-repro\packages\FSharp.Core\lib\net45\FSharp.Core.dll -r:C:\repos\sqlprovider-repro\packages\SQLProvider\lib\FSharp.Data.SqlProvider.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.ComponentModel.DataAnnotations.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Data.dll" -r:C:\repos\sqlprovider-repro\packages\System.Data.SQLite.Core\lib\net46\System.Data.SQLite.dll -r:C:\repos\sqlprovider-repro\packages\System.Data.SQLite.EF6\lib\net46\System.Data.SQLite.EF6.dll -r:C:\repos\sqlprovider-repro\packages\System.Data.SQLite.Linq\lib\net46\System.Data.SQLite.Linq.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Numerics.dll" --target:library --warn:3 --warnaserror:76 --vserrors --LCID:1033 --utf8output --fullpaths --flaterrors --subsystemversion:6.00 --highentropyva+ --sqmsessionguid:07979cb4-91ed-4e97-9350-769497170d7c --warnon:1182 "C:\Users\n635925\AppData\Local\Temp\.NETFramework,Version=v4.6.2.AssemblyAttributes.fs" TpRepro.fs 
1>C:\repos\sqlprovider-repro\TpRepro\TpRepro.fs(20,17): warning FS1182: The value 'e' is unused
1>C:\repos\sqlprovider-repro\TpRepro\TpRepro.fs(20,17): warning FS1182: The value 'e' is unused
1>C:\repos\sqlprovider-repro\TpRepro\TpRepro.fs(21,18): warning FS1182: The value 'et' is unused
1>	TpRepro -> C:\repos\sqlprovider-repro\TpRepro\bin\Debug\TpRepro.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

#### Expected behavior

No warnings

#### Actual behavior

Warnings about unused values on values that are used.

#### Known workarounds

`#nowarn`

#### Related information 

Provide any related information 

Used database: I reproduced it in both sqlite and mssql on https://www.nuget.org/packages/SQLProvider/1.1.6
Operating system: Windows 10
.NET Runtime, CoreCLR or Mono Version: .Net Framework 462 (but also didn't work on 452)

**Comment by dsyme** [comment] 2017-08-08 02:18
This is likely a duplicate of  https://github.com/Microsoft/visualfsharp/issues/422

**Comment by pmbanka** [comment] 2017-08-09 07:58
@dsyme yes, it looks like a duplicate. Should I close this issue?

**Comment by cartermp** [comment] 2017-08-09 21:03
Closing as duplicate.

**Closed by cartermp** 2017-08-09 21:03 UTC
Labels: Resolution-Duplicate
