### ISSUE TITLE
High DPI: the debug properties dialog is squished up the two data entry fields are too narrow

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#284] opened 2015-03-01 01:47 UTC
Description:  
The debug properties dialog has the data entries fields squished up.  Perhaps it is because my laptop is high DPI, but I don't think so.  It looks like it has been that way since at least VS 2013.  And Wow!!!! C# has them laid out badly too.

Expected: Debug Properties on Project Dialog to be aesthetically pleasing in it's layout.

TwitterId: @codecutterman

![bug3](https://cloud.githubusercontent.com/assets/5175830/6429081/74834a4c-bf71-11e4-97f9-ec21259bcb5d.jpg)

**Comment by forki** [comment] 2015-03-01 05:55
I can confirm. I see the same on my laptop. But also messes with other dialogs, so that might be an Windows issue.

**Comment by enricosada** [comment] 2015-03-02 09:46
i cannot repro, work ok for me. Win 7 and no high dpi.

In the screenshort, the whole debug user control is too narrow 

![74834a4c-bf71-11e4-97f9-ec21259bcb5d](https://cloud.githubusercontent.com/assets/147243/6438064/e4f3bfa0-c0c5-11e4-9fad-e6c1f1e79b6d.jpg)

the debug user control has a maxwidh 540px, maybe this is a problem with high dpi.

Btw high dpi and windows form is tricky, got bugfix til 4.5.2.
If the problem is the same of #285 , maybe is better to have a cleanup strategy instead of single bugfix (these fix the problem, but not make easier to improve the code) 
A good medium term option is an up-for-grab to convert the project view in xaml.
Using [WindowsFormHost] and [ElementHost] to easier migration, we can convert a view at time.

- easier: convert single page to xaml and embedd with [ElementHost]
- best: container control converted to xaml, page (like build/debug/etc) are embedded with [WindowsFormHost]

when are all converted, remove host and we are good to go :D. 
After the first page, the others are easy to do.

[WindowsFormHost]: https://msdn.microsoft.com/en-us/library/system.windows.forms.integration.windowsformshost(v=vs.110).aspx
[ElementHost]: https://msdn.microsoft.com/en-us/library/system.windows.forms.integration.elementhost%28v=vs.110%29.aspx

**Comment by latkin** [comment] 2015-03-02 19:21
This is due to high DPI. For VS 2013 we did a high DPI test pass and found all of these issues, but punted them since everything was technically still usable.  Would be great to fix them properly.

**Comment by KevinRansom** [comment] 2015-03-06 18:32
I'm unable to repro this on exactly the same machine.  Although it is a different build of VS and Visual F#.  I will leave this active for a bit, in case I can figure out the steps that caused it to get out of whack.  But it is probably best not to burn too many cycles on this.

**Comment by rojepp** [comment] 2015-03-07 23:41
I can repro this on my Retina Mac. Probably most new PCs going forward will have high DPI too. Most of VS works ok in high dpi but this looks clumsy. Like we don't know what we're doing. If I get a vote, I'd say it is important to fix this.

**Comment by rojepp** [comment] 2015-03-10 13:22
Easier fix might  be to remove this line (or up the number drastically, in case a low value is set by a base class). https://github.com/Microsoft/visualfsharp/blob/fac44095a8dbc7303efa9866e0e2d9dddbdeae5d/vsintegration/src/vs/FsPkgs/FSharp.Project/VB/FSharpPropPage/PropertyPages/DebugPropPage.vb#L279

**Comment by dsyme** [comment] 2017-06-20 16:51
Closing this old cosmetic bug.

**Closed by dsyme** 2017-06-20 16:51 UTC
Labels: Area-IDE Project System, bug, Urgency-Later
