### ISSUE TITLE
15.7.0 System.ValueTuple invalid reference in all projects

### ISSUE THREAD

**Issue by kspeakman** [Microsoft/visualfsharp#4861] opened 2018-05-08 20:30 UTC
Minor issue with work-around.

After upgrading from VS 15.6.x to VS 15.7.0 every F# project in my solution (15x library netstandard2.0, 5x console netcore2.0 w/ docker support added) has a yellow triangle next to the Dependencies node. The issue is that System.ValueTuple (4.3.1) is marked as an invalid reference.

![image](https://user-images.githubusercontent.com/4582668/39780548-3d348022-52d2-11e8-8787-b494ae3e6d21.png)

The .fsproj file contains no PackageReference to this package and never had. The reference cannot be removed either thru the solution explorer or thru package management (does not show as installed there). Attempting to do so results in this error:

![image](https://user-images.githubusercontent.com/4582668/39780561-4a6dac6e-52d2-11e8-8d43-d09db9fed11c.png)

The project still builds, although so far I have not used C# value tuples, so who knows.

### Workaround

A work-around that resolves the invalid reference (yellow triangle) is to install System.ValueTuple (currently 4.4.0) thru NuGet (or manually do so by adding a PackageReference node in the .fsproj file). However, this is a pain to do manually 20 times.

```xml
  <ItemGroup>
    <PackageReference Update="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>
```

### Desired behavior

Since I never explicitly referenced or used System.ValueTuple, having to add PackageReference for it is not ideal. It probably should not display as an invalid reference (or maybe at all). If packaging of it has changed for some reason, then that should be fixed during the upgrade process.

May be related: the update appears to have inserted Paket into my project as well, which I was previously not using and had to go back and remove manually. Nothing against Paket, but I wasn't ready to deal with migration to it on that project.

### Impact

Until this issue is resolved, I have to either install an unnecessary NuGet package in every single project OR I have to ignore the invalid reference icon on Dependencies. Doing the latter means I might miss real invalid reference problems, and waste time trying to solve the issue other ways.

**Comment by cartermp** [comment] 2018-05-08 23:40
Closing as duplicate of #4412 - you actually have always had a reference to SVT in the F# targets (where FSharp.Core is also defined), but it's just never surfaced until this warning in 15.7. It's benign, but the fix is quite difficult and something we punted on until a further release (likely 15.8).

> May be related: the update appears to have inserted Paket into my project as well, which I was previously not using and had to go back and remove manually. Nothing against Paket, but I wasn't ready to deal with migration to it on that project.

We don't distribute Paket in any form. I suspect this is due to an updated third-party project template. What project did you try?

**Closed by cartermp** 2018-05-08 23:40 UTC

**Comment by kspeakman** [comment] 2018-05-09 00:27
Ah sorry for dupe. I’m usually better about checking for them. Not sure how Paket came into the picture. I only used f# library (netstandard2.0), f# console (netcore2.0), and f# mstest projects. After the upgrade the paket.lock and .paket folder showed up in the list of changes for the project. Oh well, no worries. 😊

**Comment by cartermp** [comment] 2018-05-09 00:48
I just tested the MSTest project (I've tested both library and console app projects) and don't have those in the directory. There must have been something odd on your machine. Can you reproduce this?

**Comment by kspeakman** [comment] 2018-05-09 03:02
I only noticed the added files after I added the SVT 4.4.0 nuget package. But in the process of doing it 20 times, I accidentally hit “Add package” (iirc?) instead of “Manage packages”. Whatever it was called, it locked up VS and I had to kill it and restart. It was probably a Paket VS extension and hit one of its Solution Explorer extensions. I’ll double check when I get back to work tomorrow.
