### ISSUE TITLE
Nothing works on VisualFSharp.Unittests project

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3798] opened 2017-10-23 07:32 UTC
![image](https://user-images.githubusercontent.com/873919/31876973-63d8d7ae-b7dd-11e7-89a6-b8c8704f7730.png)

> Severity	Code	Description	Project	File	Line	Suppression State
Error	FS3160	Problem reading assembly 'D:\WLCR\github\visualfsharp\Debug\net40\bin\FSharp.Build.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 2792; Id 2793; Id 2794; Id 2795; Id 2796|], Id 2798,
 false, None)).	VisualFSharp.Unittests	D:\WLCR\github\visualfsharp\vsintegration\tests\unittests\UnusedOpensTests.fs	1	Active
Error	FS3160	Problem reading assembly 'D:\WLCR\github\visualfsharp\Debug\net40\bin\FSharp.Compiler.Private.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 2799; Id 2800; Id 2801; Id 2802; Id 2803|], Id 2805,
 false, None)).	VisualFSharp.Unittests	D:\WLCR\github\visualfsharp\vsintegration\tests\unittests\UnusedOpensTests.fs	1	Active
Error	FS3160	Problem reading assembly 'D:\WLCR\github\visualfsharp\Debug\net40\bin\FSharp.Editor.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 2806; Id 2807; Id 2808; Id 2809; Id 2810|], Id 2812,
 false, None)).	VisualFSharp.Unittests	D:\WLCR\github\visualfsharp\vsintegration\tests\unittests\UnusedOpensTests.fs	1	Active
Error	FS3160	Problem reading assembly 'D:\WLCR\github\visualfsharp\Debug\net40\bin\FSharp.LanguageService.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 2813; Id 2814; Id 2815; Id 2816; Id 2817|], Id 2819,
 false, None)).	VisualFSharp.Unittests	D:\WLCR\github\visualfsharp\vsintegration\tests\unittests\UnusedOpensTests.fs	1	Active
Error	FS3160	Problem reading assembly 'D:\WLCR\github\visualfsharp\Debug\net40\bin\FSharp.ProjectSystem.FSharp.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 2820; Id 2821; Id 2822; Id 2823; Id 2824|], Id 2826,
 false, None)).	VisualFSharp.Unittests	D:\WLCR\github\visualfsharp\vsintegration\tests\unittests\UnusedOpensTests.fs	1	Active
Error	FS3160	Problem reading assembly 'D:\WLCR\github\visualfsharp\Debug\net40\bin\VisualFSharp.Salsa.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 2827; Id 2828; Id 2829; Id 2830; Id 2831|], Id 2833,
 false, None)).	VisualFSharp.Unittests	D:\WLCR\github\visualfsharp\vsintegration\tests\unittests\UnusedOpensTests.fs	1	Active

**Comment by cartermp** [comment] 2017-10-23 15:20
I've noticed this in other projects as well, but I can't reproduce it (nor in the unit tests projects right now).  After a `git clean -xdf` and rebuild of everything it all worked, and hasn't stopped working since Friday for me.

cc @dsyme and @KevinRansom

**Comment by dsyme** [comment] 2017-10-25 00:14
@cartermp Sorry, I've been working on the type provider SDK and not on Visual F# IDE Tools lately...

**Comment by cartermp** [comment] 2017-12-06 06:19
I haven't seen this error in quite some time. Closing now, but re-open if you see it again.

**Closed by cartermp** 2017-12-06 06:19 UTC
Labels: needs repro
