### ISSUE TITLE
Duplicated warnings

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3314] opened 2017-07-08 06:22 UTC
https://github.com/Horusiath/Akkling/blob/master/src/Akkling/ActorRefs.fs#L209

![image](https://user-images.githubusercontent.com/873919/27983178-d640e6ec-63be-11e7-9576-e70c7bd64dcd.png)

**Comment by NatElkins** [comment] 2017-07-10 17:55
This is fixed with https://github.com/Microsoft/visualfsharp/pull/3071 .  I had made a similar issue which was closed (https://github.com/Microsoft/visualfsharp/issues/3211).

**Comment by cartermp** [comment] 2017-07-10 20:08
Closing as dupe of #3047

**Closed by cartermp** 2017-07-10 20:08 UTC
