### ISSUE TITLE
Array.Parallel uncontrollably consumes all thread from threadpool

### ISSUE THREAD

**Issue by Wkalmar** [Microsoft/visualfsharp#4725] opened 2018-04-14 12:48 UTC
Hello. 
I apologize if I've missed some basics or misidentified the root cause of an issue or confused repo.

#### Repro steps
I've created a [demo](https://github.com/Wkalmar/SokkerPlayersCrawler/tree/array-parallel-test/SokkerPlayersCrawler) to show you exactly what's happening. As you can see from the code I run `HtmlTypeProvider` to scrap some info from the HTML page in parallel using `Array.Parallel` and if scrapped data meets my criteria I send it synchronously to the file writer agent. As data which meets criteria has roughly 1 per 100 000 ratio this shouldn't cause much performance issue.
Also error handling ignores "Invalid HTML" case as there is pretty much broken links and sends to the writer agent all other exceptions.
Also, please note quite large amount of pages I try to scrap. If you test the following case on ~15,5K pages it works like a charm. But things get worse if you increase the amount.

#### Expected behavior

Output file contains URLs that meet the criteria

#### Actual behavior

At some point (depends on capabilities of the machine when you run it) file starts to be filled with "There were not enough free threads in the ThreadPool to complete the operation."

#### Known workarounds

For now, I use `PSeq` which allows restricting a degree of parallelism (as you can see from master of repo provided). Although I believe manually setting a degree of parallelism is not that robust solution.

#### Related information 

As you can induce from .fsproj I use FSharp.Core 4.4.3.0 version.
Also use VS2017 and Win10 if that helps.
Once again sorry if I've caused any inconvenience and thanks in advance!

**Comment by vasily-kirichenko** [comment] 2018-04-15 07:46
The implementation of `Array.Parallel.iter` is
```fsharp
let iter action (array : 'T[]) =
    checkNonNull "array" array
    Parallel.For (0, array.Length, fun i -> action array.[i]) |> ignore  
```
It uses a `Parallel.For` overload which does not accept a `ParallelOptions`. You can use one of those which does provide it, like https://msdn.microsoft.com/ru-ru/library/dd781401(v=vs.110).aspx and provide `ParallelOptions.MaxDegreeOfParallelism`.

**Comment by vasily-kirichenko** [comment] 2018-04-15 07:48
BTW, are you sure the whole body of `iter` is fully synchronous and does not use ThreadPool?

**Comment by vasily-kirichenko** [comment] 2018-04-15 07:53
As a side node, this type of task (parallel, possibly async, (infinite) stream processing with controlled parallelism and controlled buffering) can by _perfectly_ implemented with Akka.Streams. I highly recommend to look into it.

**Comment by vasily-kirichenko** [comment] 2018-04-15 08:44
I've made a PR to your repo to show how to use Akka.Streams https://github.com/Wkalmar/SokkerPlayersCrawler/pull/1

**Comment by abelbraaksma** [comment] 2018-04-15 16:13
Your commit serves as a good tutorial for others as well. I haven't used Akka yet, but this is a fine example that shows how easy it is to adapt existing code: )

**Comment by Wkalmar** [comment] 2018-04-19 18:55
Vasiliy, Hi again.
First of all thanks for the cool demo. Still, I'm wondering what is the best option if I don't want to specify max degree of parallelism manually? This is the reason why `Array.Parallel` was in question.

> The implementation of Array.Parallel.iter [...] uses a Parallel.For overload

I think this one suggests my incorrect usage of `Array.Parallel` as I assume that `HtmlTypeProvider.Load` is the I/O operation and it's preferable to use `async` for that case nearly the same way we use `async/await` for I/O operations in C#. It is notable how you used 'LoadAsync' instead of `Load` in your PR. Am I correct on this matter?

**Comment by vasily-kirichenko** [comment] 2018-04-19 19:08
Hi.

Yes, the root of the problem is that you call `Load`, which is blocking. I don't think `Array.Parallel` can run async functions in its `map` and `iter` (but Akka Streams - can).

About Akka Streams in general - I just find it a very good library for reliable and predictable stream processing, which is so common in any backend system (I understand it's an offtopic in this repo though). I've come to it after Linq, AsyncSeq and Hopac Streams and I'm very happy with it :)

**Comment by dsyme** [comment] 2018-04-19 21:54
I'll close this as it is not a bug in F# - though by all means keep discussing

**Closed by dsyme** 2018-04-19 21:54 UTC
