### ISSUE TITLE
[VS 2017 RC - From VSTS] type provider invalidation isn't automatic

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1803] opened 2016-11-22 06:09 UTC
**FROM VSTS:**

F# type providers are able to signal that their provided types are stale by triggering an Invalidate event. In Visual Studio 2015, this invalidation is quickly reflected in the editor, even if the code using the type provider is unchanged. However, in Visual Studio 15 the code needs to be edited before the changes are reflected.

**Comment by dsyme** [comment] 2016-11-24 18:42
This is a duplicate of https://github.com/Microsoft/visualfsharp/issues/1808 (but we should validate it after it's fixed)

**Closed by dsyme** 2016-11-24 18:42 UTC
Labels: Area-IDE Language Service, regression, Urgency-Soon

**Comment by kbattocchi** [comment] 2016-11-28 16:59
@dsyme Note that in the type provider case this issue occurs even when the invalidation is not occurring due to changes in files (e.g. with an EnvironmentVariable type provider, where invalidation is triggered by listening for operating system notifications of environment variable changes).

**Comment by dsyme** [comment] 2016-11-28 17:07
@kbattocchi Yes, though the signal is the same

1. Provider triggers Invalidate 
2. --> TcImports triggers CcusInvaldiated 
3. --> IncrementalBuilder triggers ImportedCcusInvalidated 
4. --> FSharpChexker calls ``InvalidateConfiguration`` 
5. --> FSharpChecker calls ``CheckProjectInBackground`` 
6. --> FSharpChecker eventually raises ``BeforeBackgroundFileCheck`` 
7. --> IDE receives this and requests a visual refresh of the file

The missing part is step 7
