### ISSUE TITLE
[RC3] Re-opening F# Tutorial Script opens the wrong editor, making it think it's a XAML(?) app

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2346] opened 2017-01-30 19:17 UTC
I'm not sure what's happening.

1. Install RC3 + VSIX
2. Create Tutorial project.
3. Close the Tutorial.fsx file.
4. Re-open.

**Expected:** It opens, it's colorized, and it all "works".
**Actual:** Completely changes the editor into something with "Design", "Split", and "Source" tabs at the bottom.

![fsx-reopen](https://cloud.githubusercontent.com/assets/6309070/22437659/b7439d6a-e6dd-11e6-8675-b1fc5a56da49.gif)

**Comment by majocha** [comment] 2017-01-30 20:38
@cartermp I don't know the underlying mechanism but it happens because Tutorial.fsx has `Compile` action in fsproj instead of `None`.

**Comment by majocha** [comment] 2017-01-30 21:16
I suspect it also has something to do with System.Windows.Forms reference. Removing it restores normal behavior.

**Comment by brettfo** [comment] 2017-01-30 23:08
@majocha, I was able to 'fix' the issue by setting the action to 'None' like you suggested (vs. 'Compile').  Including or excluding System.Windows.Forms didn't seem to affect anything on my machine.

**Comment by cartermp** [comment] 2017-01-30 23:17
Interesting.  The `Compile` action is necessary to be able to run the Event-handling section of the tutorial as a WinForms app, so we definitely want to keep that.

**Comment by majocha** [comment] 2017-01-31 08:34
HTML validation errors, DOCTYPE... Apparently it's some ancient HTML designer that kicks in and hangs. Didn't know Visual Studio still had one.
<img width="936" alt="2017-01-31" src="https://cloud.githubusercontent.com/assets/1760221/22457462/dc9d8b38-e797-11e6-8a89-2f55a818caa5.png">
@brettfo my bad. I can't reproduce that one either. I guess I did more than one change at a time and it was confirmation bias on my part.

**Comment by majocha** [comment] 2017-01-31 12:16
Just checked on another machine and this bug is also present on RC2 with OSS vsix built from recent master.

**Comment by majocha** [comment] 2017-01-31 12:37
OK, I've noticed yesterday that this bug is not in "naked" RC3 i.e. with the old RC2 VisualFSharp.
I've reverted e110833748a18fb603ab22b99b8bd3fac83f7871, rebuilt VIsualFSharp and reinstalled the open source vsix and the bug is gone. This is tested on RC2 only, because I don't have RC3 at hand right now.

**Comment by saul** [comment] 2017-04-20 18:48
This was fixed by #2408

**Closed** 2017-04-20 18:48 UTC
Labels: Area-IDE Project System, bug, regression, Urgency-Now
