### ISSUE TITLE
Discussion: noise in pull requests generated by dotnet-bot

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#5069] opened 2018-06-01 21:14 UTC
In this repository, looking at closed pull request, one can see a significant amount of autogenerated and merged pull requests by @dotnet-bot "Merge master to dev15.8".

It has several drawbacks:
* artificially increases the number of pull requests
* make it hard to browse history of pull requests
* more spam for people watching the repository

It feels this is something that is only useful to Microsoft internals, and could be handled directly without generating a PR, just by merging into the branch directly.

What is the reason it currently does this via PR? 

Can it be changed to just merge into the current integration branch bypassing creation of the PR?

**Comment by auduchinok** [comment] 2018-06-07 16:53
@smoothdeveloper Thank you for creating the issue. I would also mention localisation PRs.

**Comment by 0x53A** [comment] 2018-06-07 17:00
tbh, I think using PRs for that is good, if only to verify that the serverbuild is green. The issue is more with githubs all-or-nothing Watching system ...

**Comment by Pilchie** [comment] 2018-06-07 17:03
Agree that the notifications are a pain.  I've alleviated it somewhat by creating rules that move any mail with `X-GitHub-Sender: dotnet-bot` or `GitHub-Sender: dotnet-automerge-bot` in the message folders to a dedicated `bots` folder so I can bulk process them at leisure.

**Comment by smoothdeveloper** [comment] 2018-06-07 17:08
I guess Microsoft answer to that problem (and many others) is probably "email filter" 😄 

@0x53A I understand, maybe there is a way though to have those CI work from another repository, do you monitor the CI result of those PRs? How many contributors look at it?

What if dotnet-bot had forks of the repository under its account and the PR & integration checks were done there?

The main concern is the list of PRs in the repository, at this rate, the majority of the PRs will be done by bots and we will lose our jobs!

Edit: @Pilchie uses the Microsoft approved workaround!

**Comment by 0x53A** [comment] 2018-06-07 17:10
If the bot did a direct check-in and ever broke the build, everyone would complain and ask why it __didn't__ use the PR infrastructure ¯\_(ツ)_/¯

**Comment by dsyme** [comment] 2018-06-07 17:30
I'm sorry, it's obvious to anyone experienced in managing release and mainline branches that automatic merge PRs tested through CI are a fantastically good thing which make possible a rapid pace of development on the mainline branch while delivering it through to release branches.  

Closing this. Please support @brettfo and others who have put this into place and consider the ridiculous burden, slow delivery and crazy bugs we would get if we weren't automating this.

**Closed by dsyme** 2018-06-07 17:30 UTC
Labels: discussion

**Comment by 0x53A** [comment] 2018-06-07 22:34
Hm, you could tag the prs with something like 'bot'? Area-infrastructure is maybe a bit broad.

**Comment by cartermp** [comment] 2018-06-07 22:39
`Area-bot-infrastructure` perhaps?

**Comment by smoothdeveloper** [comment] 2018-06-08 02:27
@dsyme the discussion was not to detract from the usefulness or the work to get this in place which is highly valuable, but if we can find a solution, for example having those PR happen in another clone of this repository would be solve the problem as it can be watched / reviewed separately.
