### ISSUE TITLE
Error FSharp.Core in .NET Standard project

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4320] opened 2018-02-07 16:13 UTC
Visual Studio community 15.6.0 Preview 3.0 repro:

1) Create a Visual F# .NET Standard library project
2) Open nuget explorer, it shows 1 update available (FSharp.Core 4.3.0 to 4.3.3)
3) Execute Update 

Expected behaviour : no updates signalled anymore
Actual behaviour : no change (FSharp.Core update still signalled).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/193212/error-fsharpcore-in-net-standard-project.html
VSTS ticketId: 562163_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment] 2018-02-07 16:15
Related to the discussion in #4298. We'll need to update our targets files (is that accurate @KevinRansom?) to correctly react to updating FSharp.Core from the NuGet UI.

**Comment by KevinRansom** [comment] 2018-02-08 00:30
Yes, as noted here: https://github.com/Microsoft/visualfsharp/issues/4298
<snip>
5. The Manage nuget package tool built into VS does not work for FSharp.Core dotnet SDK projects and the desktop templates. Ensure that the manage nuget package tool works correctly for FSharp.Core in both. Ensure that existing projects continue to work as they do today.
</snip>

**Comment by dsyme** [comment] 2018-02-22 16:57
@cartermp Closing this as a duplicate of https://github.com/Microsoft/visualfsharp/issues/4320

**Closed by dsyme** 2018-02-22 16:57 UTC
Labels: Area-Infrastructure
