### ISSUE TITLE
Problem reading assembly '..\Debug\net40\bin\FSharp.ProjectSystem.FSharp.dll'

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3545] opened 2017-09-02 18:33 UTC
```
Error	FS3160	Problem reading assembly 'E:\github\visualfsharp\Debug\net40\bin\FSharp.ProjectSystem.FSharp.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1070; Id 1071; Id 1072; Id 1073; Id 1074|], Id 1076,
 false, None)).	VisualFSharp.Unittests	E:\github\visualfsharp\vsintegration\tests\unittests\ServiceFormatting\TestHelpers.fs	1	Active
```

![image](https://user-images.githubusercontent.com/873919/29997833-356b6352-9026-11e7-8f17-07f2def70c7d.png)

**Comment by dsyme** [comment] 2017-09-04 16:34
I have seen this.  Do you have a reliable repro?

**Comment by majocha** [comment] 2017-09-16 10:03
I can repro this on current master by referencing a library in a console app.
[Repro](https://github.com/majocha/Repro3545)

**Comment by dsyme** [comment] 2017-09-16 11:47
@majocha Thank you for the repro. Could you write out step by step instructions please?  I tried opening Library3.sln but didn't reproduce this error.

Also indicate if you have in-memory-project-references on or off (it is on by default, see Text Editor --> F# --> Performance).

@cartermp I've marked this as "fix now" since the above error should really never happen.

Thanks
Don

**Comment by majocha** [comment] 2017-09-16 12:11
@dsyme Now I had problems myself, but I think I nailed it. It appears it happens for pre-opened files only.

Repro steps

1. current master build VisualFSharp, in-memory references enabled.
2. clone repo, open solution
3. open Program.fs
4. close and reopen solution so the Program.fs gets auto loaded into editor

**Comment by abelbraaksma** [comment] 2017-09-23 17:11
@majocha, @dsyme, the repro from the previous post works reliably (using current nightly, in my case, not necessarily the same as current master). And as he said, you need to have tabs open from your previous session to receive this error.

Also, rebuilding, clean etc does not remove the error. Closing/reopening the offended tab does not resolve it either. You can see it in this vid, using the above repro:

![fsharp_issue_3545_odd_fs3160_error](https://user-images.githubusercontent.com/16015770/30775403-ea202be4-a092-11e7-8fbd-67b4a0afab76.gif)

**Comment by majocha** [comment] 2017-09-24 17:12
@abelbraaksma this should be already fixed on master.

**Comment by abelbraaksma** [comment] 2017-09-25 03:20
@majocha, I just did another `build vs`, which I believe installs this and other things into VS, but I still see the same error. Though not always, i.e. I don't get it in FSharp.sln.

**Comment by dsyme** [comment] 2017-10-02 18:45
> @majocha, I just did another build vs, which I believe installs this and other things into VS

@abelbraaksma No, ``build vs`` doesn't install into master.  See the DEVGUIDE.md for how to install the bits after you build them

**Comment by bentayloruk** [comment] 2017-10-19 10:43
This problem just happened for me too, while working on a solution with two F# libs.  I get the error:

```
FS3160	Problem reading assembly 'C:\@build\blah\source\Blah\bin\Debug\Blah.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1189; Id 1190; Id 1191; Id 1192; Id 1193|], Id 1195,
 false, None)).	Blah.Properties	C:\@build\blah\source\Blah.Properties\Properties.fs	1	Active
```

I can resolve this by closing all file windows and re-opening the solution, [as per @majocha work around](https://github.com/Microsoft/visualfsharp/issues/3545#issuecomment-329964784).  I'm not sure if this is fixed or if I have the fixed version (I *think* I'm getting nightlies), but I've included my VS info if it's any help.  

<details>
<summary>Full VS info</summary>
Microsoft Visual Studio Professional 2017 
Version 15.4.0
VisualStudio.15.Release/15.4.0+27004.2002
Microsoft .NET Framework
Version 4.6.01590

Installed Version: Professional

Visual Basic 2017   00369-60000-00001-AA768
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA768
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA768
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.9.00809.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.50921.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30915.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GhostDoc   5.4.16325.0
GhostDoc automatically generates XML documentation comments.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2017.1.2    Build 108.0.20170428.75743
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Node.js Tools   1.4.10918.1
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

TestDriven.Net   4.0-beta3
Zero friction testing for Visual Studio

TypeScript   2.3.5.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VsVim   2.4.1.0
VsVim is a Vim emulator for Visual Studio
</details>

**Comment by cartermp** [comment] 2017-11-07 16:07
See #3899 as well - @forki sees this on 15.5 Preview 3 with his own solution as well.

**Comment by forki** [comment] 2017-11-07 16:07
with paket sln and all of my private solutions.

**Comment by forki** [comment] 2017-11-07 17:01
My current assumption is is that this error is hit way more often in VS 15.5 preview 3 because there seems to be an other issue with incremental build

**Comment by forki** [comment] 2017-11-08 16:22
ok https://github.com/dotnet/project-system/issues/2945 is the reason why this issue here is triggered for me all the time

**Comment by forki** [comment] 2017-11-08 16:32
for the record: https://github.com/dotnet/project-system/issues/2945 and this bug here are two different things

**Comment by forki** [comment] 2017-11-09 07:30
so @Pilchie showed me the workaround. Disable Fast up to date check here:

https://user-images.githubusercontent.com/312835/32569417-eb69b496-c475-11e7-9d13-31a77daea421.png

**Comment by BentTranberg** [comment] 2017-11-12 08:52
I've seen FS3160 once in VS 15.4.3.

**Comment by cartermp** [comment] 2018-06-10 00:03
This no long reproduces.

**Closed by cartermp** 2018-06-10 00:03 UTC
Labels: Area-IDE Language Service, Urgency-Soon, bug
