### ISSUE TITLE
Broken Project Properties in VS 15.8

### ISSUE THREAD

**Issue by cmbrown1598** [Microsoft/visualfsharp#5555] opened 2018-08-24 17:53 UTC
#### Repro steps

Provide the steps required to reproduce the problem

In VS 2017 Professional, v15.8 with F# installed. 

File... New Project... Visual F#, selecting Library (.NET Framework)

Select any .NET framework option, and then click OK.

In new solution, right click the project and select Properties.

#### Expected behavior

Target frameworks are available and selectable. Target F# runtime is not grayed out, and installed F# runtimes are available.

#### Actual behavior

Target Framework dropdown has no available options. Target F# runtime is grayed out and unchangable.
![fsharpscreenshot](https://user-images.githubusercontent.com/1802671/44599557-92ccfb00-a78b-11e8-85ed-ce18798e5823.png)

#### Known workarounds

None

#### Related information 

* Operating system : Windows 10.0.15063
* Editing Tools (e.g. Visual Studio Version)   Visual Studio Prof. 15.8.1
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity: Medium to high.

**Comment by cartermp** [comment] 2018-08-24 18:02
Closing as duplicate of #5514, which was fixed by #5516.

**Closed by cartermp** 2018-08-24 18:02 UTC

**Comment by cmbrown1598** [comment] 2018-08-24 19:44
@cartermp Does #5516 also fix the Target F# runtime dropdown? I did not see that referenced in that fix...

**Comment by cartermp** [comment] 2018-08-24 20:09
No, that is not addressed in that PR. That is by design (and the item in the UI should just be removed). FSharp.Core is now a NuGet package in all F# templates, so if you want to target a lower F# and FSharp.Core version, you'll need to use a different NuGet package.
