### ISSUE TITLE
RC2 - Can not uninstall VisualFSharp

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#1999] opened 2016-12-12 22:27 UTC
In trying to setup a dev environment, I tried to uninstall VisualFSharp as mentioned in DevGuide:
(This worked in RC1)

```bash
VSIXInstaller.exe  /a /u:"VisualFSharp"
```

Got this error

<img width="445" alt="screenshot 2016-12-12 23 22 38" src="https://cloud.githubusercontent.com/assets/445888/21119324/5fe3a452-c0c2-11e6-8448-a060a343b775.png">

With this log:

>2016-12-12 23:22:04 - Microsoft VSIX Installer
2016-12-12 23:22:04 - -------------------------------------------
2016-12-12 23:22:04 - vsixinstaller.exe version:
2016-12-12 23:22:04 - 15.0.26009.0 built by: D15REL
2016-12-12 23:22:04 - -------------------------------------------
2016-12-12 23:22:04 - Command line parameters:
2016-12-12 23:22:04 - VSIXInstaller.exe,/a,/u:VisualFSharp
2016-12-12 23:22:04 - -------------------------------------------
2016-12-12 23:22:04 - Microsoft VSIX Installer
2016-12-12 23:22:04 - -------------------------------------------
2016-12-12 23:22:13 - Initializing Uninstall...
2016-12-12 23:22:13 - Extension Details...
2016-12-12 23:22:13 - 	Identifier         : VisualFSharp
2016-12-12 23:22:13 - 	Name               : Visual F# Tools
2016-12-12 23:22:13 - 	Author             : Microsoft.VisualFSharpTools
2016-12-12 23:22:13 - 	Version            : 15.4.1.0
2016-12-12 23:22:13 - 	Description        : Deploy Visual F# Tools templates to Visual Studio
2016-12-12 23:22:13 - 	Locale             : en-US
2016-12-12 23:22:13 - 	MoreInfoURL        : 
2016-12-12 23:22:13 - 	InstalledByMSI     : False
2016-12-12 23:22:13 - 	SupportedFrameworkVersionRange : [4.6,)
2016-12-12 23:22:13 - 
2016-12-12 23:22:13 - 	Supported Products : 
2016-12-12 23:22:13 - 		Microsoft.VisualStudio.Pro
2016-12-12 23:22:13 - 			Version : [15.0]
2016-12-12 23:22:13 - 
2016-12-12 23:22:13 - 	References         : 
2016-12-12 23:22:13 - 	Prerequisites      : 
2016-12-12 23:22:13 - 		-------------------------------------------------------
2016-12-12 23:22:13 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2016-12-12 23:22:13 - 		Name         : Visual Studio core editor
2016-12-12 23:22:13 - 		Version      : [15.0,16.0)
2016-12-12 23:22:13 - 
2016-12-12 23:22:13 - 
2016-12-12 23:22:15 - The following target products have been selected...
2016-12-12 23:22:15 - 	Visual Studio Community 2017 RC
2016-12-12 23:22:15 - 
2016-12-12 23:22:17 - Uninstalling 'Visual F# Tools', version 15.4.1.0.
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:18 - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
2016-12-12 23:22:19 - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
2016-12-12 23:22:20 - System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean markAsPackComponent)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)

**Comment by cartermp** [comment] 2016-12-12 23:00
cc @brettfo

**Comment by KevinRansom** [comment] 2016-12-14 07:48
Use VS Setup or the Tools/Extensions menu option to uninstall Visual F#.  The VSixInstaller does not work correctly.  I don't have information on whether this is a bug or a by design.

**Comment by cartermp** [comment] 2016-12-15 23:30
@KevinRansom I was able to repro this on my machine with a clean RC2 installation.  Not sure why this worked on your machine yesterday.

Log:

```
12/15/2016 3:29:19 PM - Microsoft VSIX Installer
12/15/2016 3:29:19 PM - -------------------------------------------
12/15/2016 3:29:19 PM - vsixinstaller.exe version:
12/15/2016 3:29:19 PM - 15.0.26014.0 built by: D15REL
12/15/2016 3:29:19 PM - -------------------------------------------
12/15/2016 3:29:19 PM - Command line parameters:
12/15/2016 3:29:19 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:15.0.26014.0,/appidname:Microsoft Visual Studio Community 2017 RC,/u:VisualFSharp
12/15/2016 3:29:19 PM - -------------------------------------------
12/15/2016 3:29:19 PM - Microsoft VSIX Installer
12/15/2016 3:29:19 PM - -------------------------------------------
12/15/2016 3:29:19 PM - Initializing Uninstall...
12/15/2016 3:29:19 PM - Extension Details...
12/15/2016 3:29:19 PM - 	Identifier         : VisualFSharp
12/15/2016 3:29:19 PM - 	Name               : Visual F# Tools
12/15/2016 3:29:19 PM - 	Author             : Microsoft.VisualFSharpTools
12/15/2016 3:29:19 PM - 	Version            : 15.4.1.0
12/15/2016 3:29:19 PM - 	Description        : Deploy Visual F# Tools templates to Visual Studio
12/15/2016 3:29:19 PM - 	Locale             : en-US
12/15/2016 3:29:19 PM - 	MoreInfoURL        : 
12/15/2016 3:29:19 PM - 	InstalledByMSI     : False
12/15/2016 3:29:19 PM - 	SupportedFrameworkVersionRange : [4.6,)
12/15/2016 3:29:19 PM - 
12/15/2016 3:29:19 PM - 	Supported Products : 
12/15/2016 3:29:19 PM - 		Microsoft.VisualStudio.Pro
12/15/2016 3:29:19 PM - 			Version : [15.0]
12/15/2016 3:29:19 PM - 
12/15/2016 3:29:19 PM - 	References         : 
12/15/2016 3:29:19 PM - 	Prerequisites      : 
12/15/2016 3:29:19 PM - 		-------------------------------------------------------
12/15/2016 3:29:19 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12/15/2016 3:29:19 PM - 		Name         : Visual Studio core editor
12/15/2016 3:29:19 PM - 		Version      : [15.0,16.0)
12/15/2016 3:29:19 PM - 
12/15/2016 3:29:19 PM - 
12/15/2016 3:29:23 PM - The following target products have been selected...
12/15/2016 3:29:23 PM - 	Microsoft Visual Studio Community 2017 RC
12/15/2016 3:29:23 PM - 
12/15/2016 3:29:24 PM - Uninstalling 'Visual F# Tools', version 15.4.1.0.
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64 doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.ConcurrencyCheck.X64.Resources doesn't declare a chip
12/15/2016 3:29:24 PM - Dependency Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 declares Chip=x64, but package Microsoft.VisualCpp.CodeAnalysis.Extensions.X64 doesn't declare a chip
12/15/2016 3:29:26 PM - System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean markAsPackComponent)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)
```

**Comment by cartermp** [comment] 2017-01-06 20:15
Closing in favor of#2152, as the issue is likely common, and using the command line to uninstall is not officially supported at this time (to my knowledge).

**Closed by cartermp** 2017-01-06 20:15 UTC
Labels: Area-Setup, bug
