### ISSUE TITLE
Unnecessary warning "This construct causes code to be less generic ..."

### ISSUE THREAD

**Issue by nshibano** [Microsoft/visualfsharp#1562] opened 2016-09-24 05:43 UTC
#### Repro steps
1. Compile either of these repros .

Repro 1
```
namespace Library1

type MyOption<'T>(value : 'T option) = 

    member this.Bind(f : 'T -> 'U option) = 
        let variable = MyMutableOption<'U>()
        variable.Set(Option.bind f value)
        variable.ToMyOption()

and MyMutableOption<'X>() = 
    let mutable variable = None
    member this.Set(v : 'X option) = variable <- v
    member this.ToMyOption() : MyOption<'X> = MyOption(variable)
```
Repro 2:
```
namespace Library1

type MyList<'T> (list : 'T list) = 

    member this.Choose(f : 'T -> 'U option) = 
        let accu = MyListBuilder<'U>()
        for x in list do
            match f x with 
                | Some y -> accu.Add(y)
                | None -> ()
        accu.ToMyList()

and MyListBuilder<'X>() = 

    let mutable accu = []

    member this.Add(x : 'X) = 
        accu <- x :: accu

    member this.ToMyList() : MyList<'X> = MyList<'X>(accu)
```
#### Expected behavior

Compile without warning message.
#### Actual behavior

![screen](https://cloud.githubusercontent.com/assets/16814225/18806330/7ddce4f6-8264-11e6-8953-b5e046ae8b7e.png)

Warning message "This construct causes code to be less generic than indicated by the type annotations. The type variable 'U has been constrained to be type ''X'." is reported. But 'U and 'X are used in different type definitions so they should be independent of each other.
#### Known workarounds

Renaming type variable 'X to 'U suppresses the warning.

Or, adding explicit type annotation to line 17, as below, suppresses the warning.

`
    member this.Add(x : 'X) : unit = 
`
#### Related information

Windows 10 64bit
Visual Studio 2015 Update 3

**Comment by nshibano** [comment] 2016-09-27 23:49
This is more compact repro.

```
namespace Library1

type MyOption<'T>(value : 'T option) = 

    member this.Bind(f : 'T -> 'U option) = 
        let variable = MyMutableOption<'U>()
        variable.Set(Option.bind f value)
        variable.ToMyOption()

and MyMutableOption<'X>() = 
    let mutable variable = None
    member this.Set(v : 'X option) = variable <- v
    member this.ToMyOption() : MyOption<'X> = MyOption(variable)
```
![compact](https://cloud.githubusercontent.com/assets/16814225/18895311/98635674-8553-11e6-8783-285298785a24.png)

I think the compiler should compile without warning, or give up type interference and ask for more type annotations.

There was one thing I misunderstood. I thought that type variable 'X was scoped within line 10 to 13, even after renaming it to 'U. But it wasn't. This is the screenshot after renaming. All 'U symbols in both of two types are highlighted.

![compact_rename](https://cloud.githubusercontent.com/assets/16814225/18895744/e8fa3492-8556-11e6-86cd-e06b48809f41.png)

So it is not surprising that renaming 'X to 'U changes the result.

**Comment by jack-pappas** [comment] 2016-12-05 00:08
This is a bug (IMO) and has been around for a long time. I filed a bug report on it a couple of years ago, but it was closed as a non-issue; it may have been the repro case I provided was a little too specific and unnecessarily conflated this bug with the F# value restriction (i.e., generic let-bound values).

Here's my earlier bug report:
https://visualfsharp.codeplex.com/workitem/99

Repro case (linked in that bug report, but linking again here for posterity):
https://gist.github.com/jack-pappas/48f83f6f1887fdcf7028

This bug is really non-intuitive to understand and workaround when it occurs -- it's bitten me a few times over the years -- so I'd really like to see it fixed.

**Comment by dsyme** [comment] 2016-12-05 12:53
It's certainly a nasty limitation and the error message could at least be better, asking to add full-type-signature type annotations on any members called before their point of definition.

For example, simply add "unit" as the return type of ``Set`` works here (because it enables early-generalization of ``Set``).

```


namespace Library1

type MyOption<'T>(value : 'T option) = 

    member this.Bind(f : 'T -> 'U option) = 
        let variable = MyMutableOption<'U>()
        variable.Set(Option.bind f value)
        variable.ToMyOption()

and MyMutableOption<'X>() = 
    let mutable variable = None
    member this.Set(v : 'X option) : unit = variable <- v
    member this.ToMyOption() : MyOption<'X> = MyOption(variable)
```

**Comment by dsyme** [comment] 2017-02-02 16:15
@nshibano @jack-pappas This is still considered by design I'm afraid, at least for F# 4.0/4.1.  The best thing would be to file an F# language suggestion on this. http://github.com/fsharp/fslang-suggestions.

There is a workaround in the case above by adding extra annotations to enable early generalization of methods.

**Closed by dsyme** 2017-02-02 16:15 UTC
Labels: Area-Compiler, discussion
