### ISSUE TITLE
Visual F# Nightly keeps falling out of VS 2017 Additional Extension Galleries

### ISSUE THREAD

**Issue by BentTranberg** [Microsoft/visualfsharp#3323] opened 2017-07-12 06:24 UTC
I regularly visit the Extensions and Updates dialog in my VS'es, to check for updates to VS and Visual F# Nightly.

I am frustrated by the Visual F# Nightly entry frequently disappearing from the Extensions and Updates settings / Additional Extension Galleries. It has been like this for several months. It has happened several times on my very new computer, hardly a month old. It must therefore also have happened on one or more of my other older computers in the months before that.

When I reinsert the entry for Visual F# Nightly, there are often but not always an update available to Visual F# Nightly shortly after, and this update can be a few days old sometimes, although I believe I have been using VS continuously during those days. It indicates the entry didn't drop out there and then, but earlier.

Is it possible that this happens every time I update VS? Will check when future updates come in.

I do understand that this most likely is a problem (or feature) with VS, and not Visual F# Nightly. I still choose to report it here first, because 1) this is where users of Visual F# Nightly is most likely to see my issue report, and can comment if they know something about this, and 2) there is a chance, albeit small, that somehow it has something to do with Visual F# Nightly itself.

Currently VS 2017 v15.2 (26430.15) and Nightly 15.4.1.17071101.

**Comment by cdrnet** [comment] 2017-07-12 06:51
I've seen this as well. If I remember correctly, for me it happened only on VS 2017 updates (and repairs), but not on all of them.

**Comment by cartermp** [comment] 2017-07-14 04:18
I have no idea what could cause this.  @Pilchie would you have any ideas?

**Comment by Pilchie** [comment] 2017-07-14 15:39
Presumably it happens if VS' per-user settings get reset, but I'm not sure what might be triggering that.  @aarnott - have you heard of anything like this?

**Comment by BentTranberg** [comment] 2017-07-14 16:42
Some minutes ago there was an update for Visual F# Tools to v 15.4.1.17071401, and as I expected, this did not trigger the problem. I am waiting for the next update to VS, and believe there is a good chance that that will trigger the problem, especially after reading @cdrnet 's comment.

I'd like to report one more possible issue with Nightly updates, and I report it here for the same reasons as for the first report. The nightly updates used to run automatically. They no longer do. I have to start the update manually by clicking the Update button.

![sshot-1](https://user-images.githubusercontent.com/15068882/28221567-19ff83e8-68c4-11e7-9c3f-398c3c5f4068.png)

This doesn't bother me at all, but is it supposed to be like this? It doesn't make sense to me, since the settings suggest it should still be completely automatic, and it was automatic earlier. This is what Extensions and Updates looks like:

![image](https://user-images.githubusercontent.com/15068882/28221305-142ea508-68c3-11e7-9f63-996d02946216.png)

If that's a bug, shall I file it separately? In this repo?

**Comment by AArnott** [comment] 2017-07-14 17:28
I'm afraid this isn't my area. @alexeyler may be able to help.

**Comment by AlexEyler** [comment] 2017-07-14 17:31
Thanks - this definitely sounds like a bug - I'll log it internally. @BentTranberg please loop back if you find that a VS update removes the private gallery again.

**Comment by dgriffen** [comment] 2017-07-17 17:54
@BentTranberg could you please share more information regarding any reproduction steps for this issue? We have been unable to reproduce this internally with VS 15.2.

We also believe this bug may be fixed in 15.3. If you want, you can sign up for preview builds of VS [here](https://www.visualstudio.com/vs/preview/). If you do sign up, please let us know if this fixes your issue.

**Comment by BentTranberg** [comment] 2017-07-17 18:27
I just now updated from VS 2017 v15.2 (26430.15) to VS 2017 v15.2 (26430.16). The entry for Visual F# Nightly did not vanish from the gallery. Well, at least that's some information.

@dgriffen, I don't know of any way to reproduce this. I guess the only thing I can do is to keep track of what I do in VS, so that hopefully I can tie it to some activity, or not.

Since you believe it's fixed, maybe it should be closed here to keep the noise down, but I will continue to report any findings of interest. If later it turns out not to be fixed at 15.3 or beyond, then I can grab your attention again.

**Comment by BentTranberg** [comment] 2017-07-17 18:45
The second issue I reported here - Visual F# Nightly update no longer running completely automatically - was not present in VS Preview when I upgraded the preview from 15.0.26621.2 to 15.3.26711.1. Good.

**Comment by dgriffen** [comment] 2017-07-17 19:36
@BentTranberg if the issue occurs again, please use the report a problem dialog in VS. That way we can keep the noise down in this thread and get some automated telemetry data from your VS instance. I agree that this issue should probably be closed.

**Comment by cartermp** [comment] 2017-07-17 19:46
Closing as per request.  Thanks a bunch @dgriffen and @AlexEyler!

**Closed by cartermp** 2017-07-17 19:46 UTC
Labels: Area-External, Contributor Pain
