### ISSUE TITLE
Debugging fsc is broken in VS2017.3 Preview 4

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3344] opened 2017-07-17 15:42 UTC
#### Repro steps

* Install lastest VS preview
* build.cmd debug 
* Set Fsc as startup
* Ctrl+F5

#### Expected behavior

compiler starts in new window

#### Actual behavior

![image](https://user-images.githubusercontent.com/57396/28276438-3c930970-6b17-11e7-9235-d3b976ec3470.png)

#### Known workarounds

Provide a description of any known workarounds.

**Comment by vasily-kirichenko** [comment] 2017-07-17 17:35
It seems no IDE features work either:

![image](https://user-images.githubusercontent.com/873919/28281335-686cdcd4-6b2f-11e7-8443-3dc5ea04316d.png)

**Comment by forki** [comment] 2017-07-17 17:37
@vasily-kirichenko no you just have to deinstall and freshly install VS and do the "build.cmd debug vs" dance again.

**Comment by vasily-kirichenko** [comment] 2017-07-17 17:42
:)))))))))))))))))))))))))))))))))))))))))))))

**Comment by vasily-kirichenko** [comment] 2017-07-17 17:50
I can reproduce this:

![image](https://user-images.githubusercontent.com/873919/28282005-91e9531a-6b31-11e7-9d59-38e39e4421ac.png)

**Comment by cartermp** [comment] 2017-07-17 18:05
I can repro as well, though I've no idea what the root cause is.  @KevinRansom?

**Comment by forki** [comment] 2017-07-17 19:08
Ok regarding the ctrl+F5. I reduced the command line args and then it worked. So it choked on something in the passed arguments and that made everything broken.

**Comment by dsyme** [comment] 2017-09-07 16:27
Closing as it is working fine for me now

**Comment by KevinRansom** [comment] 2017-09-07 17:06
I will see if I can repro it in a bit.

**Comment by dsyme** [comment] 2018-01-29 02:10
Closing old issue which I verified was ok

**Closed by dsyme** 2018-01-29 02:10 UTC
Labels: Area-Compiler, Contributor Pain
