### ISSUE TITLE
code context tooltip while hovering on block guidelines shows spurious directives

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2392] opened 2017-02-09 02:33 UTC
When hovering on codeblocks in the indentation guidelines, spurious directives get appended to the actual declaration which is represented.

```fsharp
#r "System.ComponentModel"

let foo () =
      () // hover the dashed guideline on the left
```

![image](https://cloud.githubusercontent.com/assets/87944/22766859/2388438a-ee78-11e6-99d9-4b11fbfd8c37.png)

![image](https://cloud.githubusercontent.com/assets/87944/22766876/35adfa00-ee78-11e6-87d1-44da9c8a1402.png)

**Comment by vasily-kirichenko** [comment] 2017-02-09 04:59
This is tooltip produced by Roslyn for the leftmost guide line. That's not a bug.

**Comment by dsyme** [comment] 2017-02-09 17:40
@smoothdeveloper ok to close this?

**Comment by cartermp** [comment] 2017-02-09 18:59
@smoothdeveloper I can't reproduce this on RC4 with your code above, but I would argue that showing `#r "System.ComponentModel"` counts as spurious information.  Is that controlled by where we place the guidelines?

**Comment by cloudRoutine** [comment] 2017-02-09 19:09
the guideline text is determined by the hidden text arg of the block structure creation method iirc, which comes from the ranges in the UAST (which has bugs) and with some adjustments I wrote to address them (which may also have bugs)

**Comment by smoothdeveloper** [comment] 2017-02-09 19:30
@dsyme & all I think this is a bug, albeit it is minor (I'm not sure yet how it affects F# files outside of scripts).

in short: why display last directive or last open namespace? the blocks should be delimited by declaration, at the root it should show module or namespace name, and inside constructs it should show a coherent nested hierarchy.

I know this involves working on the contribution @cloudRoutine did for code structure, the AST is non-obvious and it is in in no way urgent but we should keep this open to reduce chance of duplicate reports and keeping the details here so it can eventually be fixed.

**Comment by dsyme** [comment] 2017-02-10 01:38
@smoothdeveloper I'l reopen and let @cartermp and yourself decide about closing it, thanks

**Comment by dsyme** [comment] 2017-03-14 13:59
Closing this since ths issue is minor - and seems likely to be external in any case

**Closed by dsyme** 2017-03-14 13:59 UTC
Labels: Area-IDE Language Service, Urgency-Soon
