### ISSUE TITLE
Failing tests on master

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#915] opened 2016-01-29 23:36 UTC
I see the following failures on master:

fsc usage baseline files have not been updated with new response file flag
```
+++ CompilerOptions\fsc\help (NetFx40 -?) +++
PRECMD: [fsc >help40.txt -?     2>&1]
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
POSTCMD: [fsiAnyCPU --nologo --quiet --exec comparer.fsx help40.txt help40.437.1033.bsl]
Fail to execute the POSTCMD. FAIL
+++ CompilerOptions\fsc\help (NetFx40 --help) +++
PRECMD: [fsc >help40.txt --help 2>&1]
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
POSTCMD: [fsiAnyCPU --nologo --quiet --exec comparer.fsx help40.txt help40.437.1033.bsl]
Fail to execute the POSTCMD. FAIL
+++ CompilerOptions\fsc\help (NetFx40 /?) +++
PRECMD: [fsc >help40.txt /? 2>&1]
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
POSTCMD: [fsiAnyCPU --nologo --quiet --exec comparer.fsx help40.txt help40.437.1033.bsl]
Fail to execute the POSTCMD. FAIL
```

Various warning numbers don't match actual warning numbers.

```
+++ CompilerOptions\fsc\responsefile (E_responsefile_not_found.fs error if response file does not exists) +++
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
(0,0): error FS3194: Response file '@not_exists' not found in 'C:\src\latkinfsharp\tests\fsharpqa\Source\CompilerOptions\fsc\responsefile\not_exists'

*** The following necessary lines were never matched:
***	error FS3192:.+
```

```
+++ CompilerOptions\fsc\responsefile (E_responsefile_path_invalid.fs error if response file name is empty or invalid) +++
Microsoft (R) F# Compiler version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.
(0,0): error FS3195: Response file name '@' is empty, contains invalid characters, has a drive specification without an absolute path, or is too long

*** The following necessary lines were never matched:
***	error FS3193:.+
```

**Comment by enricosada** [comment] 2016-01-30 13:56
I'll fix test failures, thx @latkin

**Comment by dsyme** [comment] 2016-02-07 11:07
Here's the full list of failures in "fsharpqa" based on a run last nigh

I'm concerned about the failures in GenericComparison in particular

```
fail001		CompilerOptions\fsc\help	#  (NetFx40 -?)
fail002		CompilerOptions\fsc\help	#  (NetFx40 --help)
fail003		CompilerOptions\fsc\help	#  (NetFx40 /?)
fail004		CompilerOptions\fsc\responsefile	#  (E_responsefile_not_found.fs error if response file does not exists)
fail005		CompilerOptions\fsc\responsefile	#  (E_responsefile_path_invalid.fs error if response file name is empty or invalid)
fail006		Conformance\DeclarationElements\CustomAttributes\AttributeUsage	#  (X_AssemblyVersion01.fs)
fail007		Conformance\DeclarationElements\CustomAttributes\AttributeUsage	#  (X_AssemblyVersion02.fs)
fail008		Conformance\DeclarationElements\MemberDefinitions\MethodsAndProperties	#  (E_DuplicateProperty01.fs)
fail009		Conformance\DeclarationElements\MemberDefinitions\MethodsAndProperties	#  (E_AbstractProperties03.fs)
fail010		Conformance\DeclarationElements\MemberDefinitions\MethodsAndProperties	#  (E_AbstractAndConcereteProp.fs)
fail011		Conformance\ObjectOrientedTypeDefinitions\ClassTypes\MemberDeclarations	#  (E_PropertySetterUnit01.fs)
fail012		Conformance\ObjectOrientedTypeDefinitions\ClassTypes\MemberDeclarations	#  (E_PropertyInvalidGetterSetter01.fs)
fail013		Conformance\ObjectOrientedTypeDefinitions\ClassTypes\MemberDeclarations	#  (E_PropertySameNameDiffArity.fs)
fail014		TypeProviders\RuntimeDesignTimeAssembly\LoadingLogic	#  (NFYY)
fail015		TypeProviders\RuntimeDesignTimeAssembly\LoadingLogic	#  (NFYN)
fail016		Optimizations\GenericComparison	#  (Compare07.fs - NetFx40)
fail017		Optimizations\GenericComparison	#  (Compare10.fs - NetFx40)
fail018		Optimizations\GenericComparison	#  (Equals06.fs - NetFx40)
fail019		Optimizations\GenericComparison	#  (Equals09.fs - NetFx40)
fail020		Optimizations\GenericComparison	#  (Hash09.fs - NetFx40)
fail021		Optimizations\GenericComparison	#  (Hash12.fs - NetFx40)
```

**Comment by dsyme** [comment] 2016-02-07 11:26
After #937 the current failures will be like this:

fail014     TypeProviders\RuntimeDesignTimeAssembly\LoadingLogic    #  (NFYY)
fail015     TypeProviders\RuntimeDesignTimeAssembly\LoadingLogic    #  (NFYN)
fail016     Optimizations\GenericComparison #  (Compare07.fs - NetFx40)
fail017     Optimizations\GenericComparison #  (Compare10.fs - NetFx40)
fail018     Optimizations\GenericComparison #  (Equals06.fs - NetFx40)
fail019     Optimizations\GenericComparison #  (Equals09.fs - NetFx40)
fail020     Optimizations\GenericComparison #  (Hash09.fs - NetFx40)
fail021     Optimizations\GenericComparison #  (Hash12.fs - NetFx40)

**Comment by manofstick** [comment] 2016-02-07 23:21
I commented on this in #944 (the gist being that we should probably restore the tail calls. Agree?)

**Comment by dsyme** [comment] 2016-02-07 23:51
These are the failing tests on my machine for the "FSHARP" suite:

```
Errors and Failures

1) Failed : FSharp-Tests-Core+Printing.printing("","z.output.test.default.txt","
z.output.test.default.bsl")
2) Failed : FSharp-Tests-Core+Printing.printing("--use:preludePrintSize1000.fsx"
,"z.output.test.1000.txt","z.output.test.1000.bsl")
3) Failed : FSharp-Tests-Core+Printing.printing("--use:preludePrintSize200.fsx",
"z.output.test.200.txt","z.output.test.200.bsl")
4) Failed : FSharp-Tests-Core+Printing.printing("--use:preludeShowDeclarationVal
uesFal...","z.output.test.off.txt","z.output.test.off.bsl")
5) Failed : FSharp-Tests-Typecheck+Sigs.sigs
``

**Comment by dsyme** [comment] 2016-02-08 00:39
All failing tests should now be fixed in #944

**Comment by dsyme** [comment] 2016-02-08 17:46
I'm still seeing failing tests when running tests using the VS tets runner from VisualFSharp.sln:

* core\members\basics
* core\load-script
* negTests("neg1a")   
* negTests("neg1_a")   
* negTests("ProviderAttribute_EmptyConsume")
* negTests("providerAttributeErrorConsume")
* printing tests

I'm not sure why/if these appear to be passing outside VS.  Some of the issues seem to do with timing of output.  Will look into it and keep this thread open.

**Comment by dsyme** [comment] 2016-02-08 18:03
We're also seeing FSHARP suite failures on AppVeyor, however the AppVeyor build itself is not failing when that suite has errors....  

```
[00:33:34] 1) Failed : FSharp-Tests-Core+Interop.interop
[00:33:34] 2) Failed : FSharp-Tests-Core+Printing.printing("--use:preludePrintSize200.fsx","z.output.test.200.txt","z.output.test.200.bsl")
[00:33:34] 3) Failed : FSharp-Tests-Core+Printing.printing("--use:preludeShowDeclarationValuesFal...","z.output.test.off.txt","z.output.test.off.bsl")
[00:33:34] 4) Failed : FSharp-Tests-Core+Verify.verify
[00:33:34] 5) Failed : FSharp-Tests-Typecheck+Sigs.sigs
[00:33:34] 6) Failed : FSharp-Tests-TypeProviders+Builtin+EdmxFile.EdmxFile(FSC_BASIC)
[00:33:34] ERRORLEVEL 1 ERRORLEVEL 1
[00:33:34] 7) Failed : FSharp-Tests-TypeProviders+Builtin+EdmxFile.EdmxFile(FSC_O3)
[00:33:34] ERRORLEVEL 1 ERRORLEVEL 1
[00:33:34] 8) Failed : FSharp-Tests-TypeProviders+Builtin+EdmxFile.EdmxFile(FSC_OPT_MINUS_DEBUG)
[00:33:34] 9) Failed : FSharp-Tests-TypeProviders+Builtin+EdmxFile.EdmxFile(FSC_OPT_PLUS_DEBUG)
[00:33:34] 10) Failed : FSharp-Tests-TypeProviders+Builtin+EdmxFile.EdmxFile(FRENCH)
[00:33:34] ERRORLEVEL 1 ERRORLEVEL 1
[00:33:34] 11) Failed : FSharp-Tests-TypeProviders+Builtin+EdmxFile.EdmxFile(SPANISH)
[00:33:34] ERRORLEVEL 1 ERRORLEVEL 1
[00:33:34] 12) Failed : FSharp-Tests-TypeProviders+Builtin+EdmxFile.EdmxFile(AS_DLL)
[00:33:34] ERRORLEVEL 1 ERRORLEVEL 1
[00:33:34] 13) Failed : FSharp-Tests-TypeProviders+Builtin+SqlDataConnection.sqlDataConnection(FSC_BASIC)
[00:33:34] 14) Failed : FSharp-Tests-TypeProviders+Builtin+SqlDataConnection.sqlDataConnection(FSC_O3)
[00:33:34] 15) Failed : FSharp-Tests-TypeProviders+Builtin+SqlDataConnection.sqlDataConnection(FSC_OPT_MINUS_DEBUG)
[00:33:34] 16) Failed : FSharp-Tests-TypeProviders+Builtin+SqlDataConnection.sqlDataConnection(FSC_OPT_PLUS_DEBUG)
[00:33:34] 17) Failed : FSharp-Tests-TypeProviders+Builtin+SqlDataConnection.sqlDataConnection(FRENCH)
[00:33:34] 18) Failed : FSharp-Tests-TypeProviders+Builtin+SqlDataConnection.sqlDataConnection(SPANISH)
[00:33:34] 19) Failed : FSharp-Tests-TypeProviders+Builtin+SqlDataConnection.sqlDataConnection(AS_DLL)
[00:33:34] 20) Failed : FSharp-Tests-TypeProviders+Builtin+ODataService.oDataService(FSC_BASIC)
[00:33:34] 21) Failed : FSharp-Tests-TypeProviders+Builtin+ODataService.oDataService(FSC_O3)
[00:33:34] 22) Failed : FSharp-Tests-TypeProviders+Builtin+ODataService.oDataService(FSC_OPT_MINUS_DEBUG)
[00:33:34] 23) Failed : FSharp-Tests-TypeProviders+Builtin+ODataService.oDataService(FSC_OPT_PLUS_DEBUG)
[00:33:34] 24) Failed : FSharp-Tests-TypeProviders+Builtin+ODataService.oDataService(FRENCH)
[00:33:34] 25) Failed : FSharp-Tests-TypeProviders+Builtin+ODataService.oDataService(SPANISH)
[00:33:34] 26) Failed : FSharp-Tests-TypeProviders+Builtin+ODataService.oDataService(AS_DLL)
[00:33:34] 27) Failed : FSharp-Tests-TypeProviders+Builtin+WsdlService.wsdlService(FSC_BASIC)
[00:33:34] 28) Failed : FSharp-Tests-TypeProviders+Builtin+WsdlService.wsdlService(FSC_O3)
[00:33:34] ERRORLEVEL 1 ERRORLEVEL 1
[00:33:34] 29) Failed : FSharp-Tests-TypeProviders+Builtin+WsdlService.wsdlService(FSC_OPT_MINUS_DEBUG)
[00:33:34] 30) Failed : FSharp-Tests-TypeProviders+Builtin+WsdlService.wsdlService(FSC_OPT_PLUS_DEBUG)
[00:33:34] 31) Failed : FSharp-Tests-TypeProviders+Builtin+WsdlService.wsdlService(FRENCH)
[00:33:34] 32) Failed : FSharp-Tests-TypeProviders+Builtin+WsdlService.wsdlService(SPANISH)
[00:33:34] 33) Failed : FSharp-Tests-TypeProviders+Builtin+WsdlService.wsdlService(AS_DLL)
```

**Comment by enricosada** [comment] 2016-02-08 19:59
@dsyme some like core/member/basic are disabled in appveyor becuase of `NO_CI` in https://github.com/Microsoft/visualfsharp/blob/master/tests/test.lst

**Comment by enricosada** [comment] 2016-02-08 20:05
Ref https://github.com/Microsoft/visualfsharp/issues/813#issue-122907314

**Comment by dsyme** [comment] 2016-02-09 00:36
I think https://github.com/Microsoft/visualfsharp/pulls/948 should address all test failures.  We're getting close to having all tests passing.  core\printing will still fail on non-US culture

**Comment by dsyme** [comment] 2016-02-09 08:45
Status of CI after merging #948
* One remaining FSHARP suite failure.   ```1) Failed : FSharp-Tests-Typecheck+Sigs.sigs```
* Failures in FSHARP are still not triggering an overall failure of the build, nor uploading results correctly
* The VisualFSharp.Unittests suite is not yet run
* Overall appveyor build+test times are at around 55 minutes. (2x27min)

**Comment by enricosada** [comment] 2016-02-09 08:53
> Failures in FSHARP are still not triggering an overall failure of the build, nor uploading results correctly

i'll fix that now, pr soon

**Comment by dsyme** [comment] 2016-02-09 10:15
@enricosada it's fixed in #950 , but good to double check with #949

**Comment by enricosada** [comment] 2016-02-09 10:28
@dsyme i think the problem is another, i'll try to fix it with my pr

```batch
call RunTests.cmd %BUILD_CONFIG_LOWER% fsharp %TEST_TAGS% 

@if ERRORLEVEL 1 type testresults\fsharp_failures.log && echo Error: 'RunTests.cmd %BUILD_CONFIG_LOWER% fsharp %TEST_TAGS%' failed && goto :failure
```

with `type testresults\fsharp_failures.log` if  `fsharp_failures.log` doesnt exists, there is no `goto :failure`. the fsharp nunit runner write `FSharpNunit_Output.log`

**Comment by enricosada** [comment] 2016-02-09 10:29
btw amazing job fixing all failures, and the code cleanup in fsharp nunit :+1:

**Comment by dsyme** [comment] 2016-02-09 10:43
ok, thanks

**Comment by dsyme** [comment] 2016-02-09 11:06
@enricosada I've fixed the ``fsharp_failures.log`` problem in #950

**Comment by enricosada** [comment] 2016-02-09 11:09
@dsyme ok, closed mine

**Comment by dsyme** [comment] 2016-02-09 11:11
@enricosada A couple of comments on the test runner code for the FSHARP quite 

- Awesome job on the 1:1 translation.  It's made it feasible to track down these bugs.  I can't believe how you persevered with that: it really is a huge contribution especially in the long term

- Now that the translation is done and stable (apart from enabling it for CoreCLR) we should aim to simplify the code.  For example I spent an hour staring at some "pipe to FSI sed.fsx script" code trying to work out what was going on, and in the end replaced it with a File.ReadAllLines+String.Replace+File.WriteAllLines in 3 minutes :)   So we can likely look for similar places where we are needlessly shelling out or where we have inherited complexity we no longer need.

- It would be good to split the "sigs" test into multiple individual tests.

**Comment by enricosada** [comment] 2016-02-09 11:58
btw i think you can ask @KevinRansom to make you collaborator in appveyor, so you can cancel/stop useless builds. 
I use stop build a lot in my personal appveyor

**Comment by dsyme** [comment] 2016-02-09 17:40
Thanks @enricosada , have asked

**Comment by dsyme** [comment] 2016-02-09 17:43
We have a GREEN on master  https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1511 that includes running all FSHARP and FSHARPQA tests (apart from the relatively few "Expensive" ones)

![capture](https://cloud.githubusercontent.com/assets/7204669/12925093/93170c52-cf54-11e5-94a0-ad582727ce1e.JPG)

Am closing this!!!!

**Closed by dsyme** 2016-02-09 17:43 UTC
Labels: regression, Urgency-Now

**Comment by forki** [comment] 2016-02-09 17:58
Kudos! 

![yes](https://cloud.githubusercontent.com/assets/57396/12925551/1304111c-cf5f-11e5-87c6-aa4801e08b03.gif)
