### ISSUE TITLE
interface type parameter cannot be unit

### ISSUE THREAD

**Issue by estokes** [Microsoft/visualfsharp#836] opened 2015-12-24 18:43 UTC
type z<'A> =
        abstract member Foo: unit -> 'A

    let unit = // This is an error
        { new z<unit> with
            member __.Foo() = () }

    let string = // This is not
        { new z<String> with 
            member __.Foo() = "hello world" }

**Comment by abelbraaksma** [comment] 2015-12-25 00:54
Isn't this essentially turning a method returning a type into a method returning no type/nothingness? Comparing it with C# syntax, this would mean implementing `class Test : z<void>`, [which is illegal](http://programmers.stackexchange.com/questions/131036/why-is-void-not-allowed-as-a-generic-type-in-c)? Just meaning to say, I don't think it _should_ be possible, even though `unit` can be used more like a type in F#, after compilation `unit` becomes `void`, which is not a valid type for `GenericParam` in IL. 

Btw, the error raised is::

    > let unit = // This is an error
        { new z<unit> with
            member __.Foo() = () };;
    
              member __.Foo() = () };;
      ------------------^^^
    
    // stdin(44,19): error FS0017: The member 'Foo : unit -> unit' does not have the correct type to override the corresponding abstract method.

(if my assessment above is correct, this is not a very clear error and special-casing it seems appropriate, something like _"unit is not allowed as a generic type argument"_ perhaps?)

**Comment by bleis-tift** [comment] 2015-12-25 01:36
The following code raised no errors:

```fsharp
// The type parameter of method argument side
type z<'A> = abstract Foo: 'A -> unit

// Compiling successful
let ok = { new z<unit> with member __.Foo(()) = () }
```

**Comment by estokes** [comment] 2015-12-26 00:07
Unit is just a value type. It should not be special in this respect, I should be able to return it from a function or a method just like an int or any other value type. Obviously it's a little special, but saying that a type variable representing the return value of a method cannot be unit is taking it a bit too far. After all I can write, 

> [1;2;3] |> List.map (fun x -> printfn "%d" x);;
1
2
3
val it : unit list = [null; null; null]

I don't get a type error I get a list of unit values. Similarly when I write the above function and instantiate the type variable with unit I expect to get a method that returns unit. The current behavior seems like a bug.

**Comment by dsyme** [comment] 2016-01-08 20:29
This is a language design issue, see http://stackoverflow.com/questions/26296401/why-is-unit-treated-differently-by-the-f-type-system-when-used-as-a-generic-i for example and http://stackoverflow.com/questions/4485445/f-interface-inheritance-failure-due-to-unit/4485677#4485677 also.   

Please add an issue to http://fslang.uservoice.com if there's not one there already.

Closing as it's a language design issue, not a bug in this implementation of F#

**Closed by dsyme** 2016-01-08 20:29 UTC
