### ISSUE TITLE
System.Value.Tuple showing warn in dependencies

### ISSUE THREAD

**Issue by noelmcgrath** [Microsoft/visualfsharp#4883] opened 2018-05-11 09:49 UTC
System.Value.Tuple showing error in dependencies when I create a new f# console project(.net core)

#### Repro steps

1. Update Visual Studio to 15.7.1

2. File-> new project -> Visual F# -> Console App (>NET Core)

3. Warn shows up in Dependencies, see image

![image](https://user-images.githubusercontent.com/671790/39918527-a7817cea-5508-11e8-92b3-a49cab122977.png)

#### Expected behavior

No warns

#### Actual behavior

Warns

#### Known workarounds

Still compiles and builds but is annoying as you keep seen yellow and think there is a problem

**Comment by ChrSteinert** [comment] 2018-05-11 11:48
I see that this reference comes from `C:\Program Files\dotnet\sdk\<SDK Version>\FSharp\Microsoft.FSharp.NetSdk.props` L70 (for my Version 2.1.200)
The version of the package is fixed in L35: `<DefaultValueTuplePackageVersion>4.3.1</DefaultValueTuplePackageVersion>` - this is an "old" version without .NET Standard 2.0 support. I tried overriding it in a projects `*.fsproj` to 4.4.0 with .NET Standard 2.0 support. But I still get the warning…

Unfortunately it shows, that there is a warning, but no text anywhere to it. I would have expected this to be `NU1701` (wrong framework in the package for the project), but that does not seem to be the case here.

**Comment by cartermp** [comment] 2018-05-11 14:47
Closing as dupe of #4412

**Closed by cartermp** 2018-05-11 14:47 UTC
