### ISSUE TITLE
Build_CI2 times out from time to time

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3764] opened 2017-10-17 09:42 UTC
This makes CI unreliable

**Comment by cartermp** [comment] 2017-12-06 06:22
Closing this for now, as it I haven't seen this happen after a few rounds of updates to CI

**Closed by cartermp** 2017-12-06 06:22 UTC
Labels: Contributor Pain, infrastructure

**Comment by PatrickMcDonald** [comment] 2017-12-06 08:54
Thus is still happening as of last week

https://github.com/Microsoft/visualfsharp/pull/4038

**Comment by cartermp** [comment] 2017-12-06 16:15
We can reopen this if it reliably times out. More often than not, the issue is environmental and out of our control.
