### ISSUE TITLE
The following code prevents the compiler from terminating

### ISSUE THREAD

**Issue by LukaHorvat** [Microsoft/visualfsharp#351] opened 2015-04-09 13:14 UTC
I reported this to [fsharp](https://github.com/fsharp/fsharp/issues/401) and it was suggested I should report it here as well.

Description:
The idea was to make a function format that can return any function which's type passes a static check. The functions that are valid take parameters (arbitrarily many) of type string or int and produce either a unit or an int.
Including the checker function in another function would make sure that the type parameter is a valid function type, which would then be constructed unsafely via reflection or similar and then finally casted to the appropriate target type.

Unfortunately, this code causes the compiler to hang indefinitely (or as far as my patience extended).
This might not be a bug if it's a design decision to allow non-termination, but I'd find that strange considering my code consists only of valid language constructs.

Repro Steps:
Compile this code
```
type Switcher = Switcher

let inline checker< ^s, ^r when (^s or ^r) : (static member pass : ^r -> unit)> (s : ^s) (r : ^r) = ()

let inline format () : ^r =
    checker Switcher Unchecked.defaultof< ^r>
    () :> obj :?> ^r

type Switcher with
    static member inline pass(_ : string -> ^r) =
        checker Switcher Unchecked.defaultof< ^r>
    static member inline pass(_ : int -> ^r) =
        checker Switcher Unchecked.defaultof< ^r>
    static member inline pass(_ : unit) = ()
    static member inline pass(_ : int) = ()

[<EntryPoint>]
let main argv = 
    let res : unit = format () "text" 5 "more text" ()
    printfn "%A" res
    Console.ReadKey()
    0 // return an integer exit code
```
Severity: It's pretty bad that the compiler fails to terminate, but it's a fairly obscure use case.

Version: Visual Studio 2015 Preview, my project targets .NET Framework 4.5.3 and the runtime is F# 4.0 (FSharp.Core, 4.4.0.0)

**Comment by latkin** [comment] 2015-04-09 15:35
I can repro. Pasting the code into the editor causes VS to spin CPU indefinitely, too.

**Comment by rojepp** [comment] 2015-04-10 04:25
I can repro in Xamarin Studio on OSX, so it's not a F# 4.0 issue.

**Comment by forki** [comment] 2015-04-30 15:59
![image](https://cloud.githubusercontent.com/assets/57396/7416805/362334bc-ef62-11e4-80d1-04eb7565db31.png)

it seems the endless loop is in the Overload resolution code. Specifically the error case is rerunning the whole Overload resolution. The the new error reruns the overload resolution...

**Comment by dsyme** [comment] 2015-05-09 12:29
I've taken a look at this with a view to whether to attempt a fix (or restriction) for F# 4.0.  However, it's hard - it involves error paths during very nested overload resolution.

In any case, given where we are with the F# 4.0 RTM milestone, I haven't been able to determine a non-destabilizing fix that's appropriate at this stage. I believe this will need to be fixed at a later stage. The fix could be along the lines of a language restriction that require more complete signatures to be given in some situations, 

In this example, it's not clear if progress is being made (though slowly, which would still be an issue) or if there is actually a proper loop. @forki also took a look and may have more to share.

**Comment by forki** [comment] 2015-05-09 12:32
From my limited understanding it didn't made progress. Instead it circled
between two states.

**Comment by dsyme** [comment] 2015-05-09 12:34
See also https://github.com/Microsoft/visualfsharp/issues/395, which I'm considering a duplicate of this as I suspect the underlying causes to be the same.

**Comment by dsyme** [comment] 2016-07-18 10:55
Closing as a duplicate of https://github.com/Microsoft/visualfsharp/issues/343 (it seems the compiler is making progress, just very slowly)

**Closed by dsyme** 2016-07-18 10:55 UTC
Labels: Area-Compiler, bug, Urgency-Later

**Comment by forki** [comment] 2016-09-19 07:38
with PR 1530 applied this immediatly gives:

![image](https://cloud.githubusercontent.com/assets/57396/18625104/a079ea16-7e4c-11e6-8e0b-22eea5f3353c.png)

Is that expected? I tried to put that in https://github.com/Microsoft/visualfsharp/pull/1550

**Comment by gmpl** [comment] 2016-09-19 09:08
After analyzing and working with the Constraint Solver I'm not surprised that some samples (like this) never ends.
But after the fix I'm proposing they should.
Now, whether they end successfully or with an error is a different thing.
I need to study more this repro, but in principle I would say that if the code in the repro makes sense it should compile and if it don't then we're facing another compiler bug, similar to the ones I reported and they should be fixed in a separated pull request.

**Comment by forki** [comment] 2016-09-19 09:32
@gmpl one thing is for sure:  giving a error message immediately is better than compiler going into quasi infinite loop. So from my point of view your pr is a win for this case here.
