### ISSUE TITLE
Inline rename doesn't work against latest Roslyn bits.

### ISSUE THREAD

**Issue by brettfo** [Microsoft/visualfsharp#2303] opened 2017-01-20 00:37 UTC
VS will crash when trying to invoke the Rename command in the `vs2017-rtm` branch.

**Comment by cartermp** [comment] 2017-01-20 01:50
To add, what this means is that Inline Rename will be disabled at RTM so that we don't crash VS.  This will bring up the old experience in RC2 where a dialog popped up.  We'll be investigating why this isn't working and trying to enable it ASAP, hopefully in time to get it it into a micro-update prior to Update 1.

**Comment by forki** [comment] 2017-01-20 07:02
Please let the issue open.

**Comment by cartermp** [comment] 2017-01-20 07:25
Not sure why I closed it

**Comment by vasily-kirichenko** [comment] 2017-01-20 07:25
So:
* nobody asked VS team what version of CodeAnalysis will be shipped with RTM
* nobody even checked if a new version is available via one of NuGet sources

As NuGet packages become available after some time from a VS release which uses that version, we have no chance to ship workable VFT at all. Strategies: 
* not shipping VFT with VS at all (I mean no even old version, which is obviously does not work) and provide completely separate VSIX in a week or so after VS release
* move to the C#/VB development model - I'm absolutely sure Inline Rename works OK for these languages.  Where the hell they grabbed those new CodeAnalysis packages?

**Comment by isaacabraham** [comment] 2017-01-20 09:57
Does this mean that C# / VB team have access to the Code Analysis release before it's public? In which case why not the F# side as well?

**Comment by vasily-kirichenko** [comment] 2017-01-20 13:59
@isaacabraham Actually there is a nuget server where the packages are published every day: https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis

as you can see, the freshest current version is `2.0.0-rc4-61320-04` (we use `2.0.0-rc2`)

**Comment by vasily-kirichenko** [comment] 2017-01-20 14:00
The problem is that nobody asked Roslyn team what version is gonna be in RTM. Nobody.

**Comment by cartermp** [comment] 2017-01-27 21:31
Closing in favor of #2328

**Closed by cartermp** 2017-01-27 21:31 UTC
Labels: bug, regression
