### ISSUE TITLE
Multiline strings with sprintf cause serious compiler errors, or the editor shows errors and warnings that the compiler does not show: FS0010, FS3118, FS0001, FS0020

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3380] opened 2017-07-25 15:33 UTC
I think the video speaks for itself. In the repro section I give all the code snippets that exhibit the different errors.

![multiline strins error in vs2017p4](https://user-images.githubusercontent.com/16015770/28579403-e0319074-715c-11e7-9e19-dab77c4b8491.gif)

Except for the last one, neither the FS0001 error or the FS0020 warning show up when you compile. I.e., it compiles fine.

### Repro steps for FS0020

The following code will give "The result of this expression is implicitly ignored. Consider using 'ignore' to discard this value explicitly, e.g. 'expr |> ignore', or 'let' to bind the result to a name, e.g. 'let result = expr'."
````
// NOTE: extra indent is required to see this warning!
module Multi =
        let foo = "all of us"

        // FS0020
        let multiLineString = 
            sprintf "hello \
            world \
            here \
            we are: %s" foo
````

### Repro for FS0001

The following snippet throws "FS0001 This expression was expected to have type ''a -> 'b'  but here has type 'string'".
````
// NOTE: same as above, but block in module is one indent to the left
module Multi =
    let foo = "all of us"

    // FS0001
    let multiLineString = 
        sprintf "hello \
        world \
        here \
        we are: %s" foo
````
### Repro for FS3118 and FS0010

The following snippet throws:

* error FS0010: Unexpected identifier in binding. Expected incomplete structured construct at or before this point or other token.
* error FS3118: Incomplete value or function definition. If this is in an expression, the body of the expression must be indented to the same column as the 'let' keyword.

In the error list, both errors appear twice, once with and once without error code, but with the same text:

![image](https://user-images.githubusercontent.com/16015770/28579866-2ab7115e-715e-11e7-8c6b-304505d7193d.png)

````
module Multi =
    let foo = "all of us"

    let multiLineString = 
        sprintf "hello \
        world \
        here \
        we are\
        : %s" foo
````

### Expected behavior

None of the above should throw an error, these are valid statements.

And when the editor shows an error, it should be the same the compiler shows, but here the compiler does not show any error (in the first two scenarios). Also, the editor doubles the errors mentioned in the last repro.

### Actual behavior

As described. Errors are shown in the editor and in the error list, but not when compiling. And sometimes the compiler hiccups on such statements and throws a FS3118 and FS0010.

### Known workarounds

Don't use `printf` style statement with multiline strings. Or don't use backslashes (but that is often not feasible, as it has the beautiful benefit of killing the following whitespace, which none of the other ways for making multiline string constants exhibits).

### Related information 

Provide any related information 

* Visual Studio 2017 Preview 4, on Windows 7
* .NET 4.6
* Happens in VS 2017 with either FSharp 4.4.1.0 (either of the two public versions of it) or FSharp 4.4.0.0
* Does not happen in VS 2015 with FSharp 4.4.0.0 (cannot test with 4.4.1.0, it is not supported)

I think this is relatively severe, as it breaks existing code (in my case, I cannot compile my projects written in VS2015 with F# 4.4.0.0 when opening them in VS2017). I also think it is severe because this really isn't an error by a long shot and can confuse even experienced F# programmers.

**Comment by forki** [comment] 2017-07-25 15:47
Had the same issue in paket solution for quite a while. Never really found a way to reproduce. Always ended up blaming my environment

**Comment by abelbraaksma** [comment] 2017-07-25 18:10
@forki: I'd be interested to know whether with these repro examples it is reproducible for you? Or is this is an issue that only happens on certain specific system configurations? On my machine the repro seems consistent (albeit strangely so, as the warnings and errors seem to depend on the length of the individual parts of the broken string).

**Comment by dsyme** [comment] 2017-07-25 20:17
This is a duplicate of https://github.com/Microsoft/visualfsharp/issues/2729.  It's a PITA to fix because of the way printf format specifiers are reported to the language service.  By far the easiest workaround is to use ``"""`` strings, which I believe work correctly, and don't require ``\`` at the end of line

**Closed by dsyme** 2017-07-25 20:17 UTC

**Comment by forki** [comment] 2017-07-25 20:19
Please don't close. In paket we use """ - I have to dig up that as a repro.

Am 25.07.2017 10:17 nachm. schrieb "Don Syme" <notifications@github.com>:

**Comment by dsyme** [comment] 2017-07-25 20:28
@forki Please add the second error case to #2729 - I'm certain it's the same underlying issue.  It's possible that ``"""`` also have a problem, given the way the format specifier recovery was implemented - if you read my notes I'm not at all happy about how it was done

**Comment by abelbraaksma** [comment] 2017-07-26 15:13
> By far the easiest workaround is to use """ strings, which I believe work correctly, and don't require \ at the end of line

@dsyme: no, that won't work, because these strings will include the whitespace. The "\"-approach is for simple inline messages very useful when you would like your code neatly indented (as I do). 

That is not to say that it isn't a workaround, of course it is, but it requires cluttering your code.
