### ISSUE TITLE
Assertion when opening project properties page

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2123] opened 2016-12-29 06:52 UTC
Current master built in Debug configuration:

![image](https://cloud.githubusercontent.com/assets/873919/21538291/7cd00a78-cdac-11e6-9df6-d1aeb762d4ea.png)

**Comment by cartermp** [comment] 2017-01-03 17:16
@vasily-kirichenko I can't repro this with a simple Console App project.  Do you have a repro solution I can verify?

**Comment by dsyme** [comment] 2017-01-08 22:47
Removed the regression label as it's possible this has always been there (no one was using the debug build of the tools much prior to recent work)

**Comment by cartermp** [comment] 2017-03-15 04:49
Since we'll be moving to the new project system, I'll close this since:

a. Not a regression
b. Debug build, so it may have been there before as @dsyme says

**Closed by cartermp** 2017-03-15 04:49 UTC
Labels: Area-IDE Project System
