### ISSUE TITLE
F# 4.1 - Possible regression Op_Dynamic

### ISSUE THREAD

**Issue by mrange** [Microsoft/visualfsharp#2416] opened 2017-02-11 16:55 UTC
When upgrading to VS 2017 and F# 4.1 some of my old projects won't compile with:

> error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.

#### Repro steps

```fsharp
type OpDynamic() =
  static member ( ? ) (x, n) = x
  member x.Prop = 1

[<EntryPoint>]
let main argv = 
  let op  = OpDynamic ()
  let op2 = op?Hello.Prop
  printfn "%A" argv
  0
```
#### Expected behavior

Compilation succeed with intended behavior

#### Actual behavior

Fails with 

> error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.

#### Known workarounds

If I change:
```fsharp
  let op2 = op?Hello.Prop
```

Into
```fsharp
  let op2 = (op?Hello).Prop
```

it seems to work

Also if I change from:

```fsharp
type OpDynamic() =
  static member ( ? ) (x, n) = x
  member x.Prop = 1
```

```fsharp
type OpDynamic() =
  member x.Prop = 1

let ( ? ) x n = x
```

The reason I made `Op_Dynamic` a member function was that I hoped not to pollute the namespace with global operators. Perhaps a misguided idea.

#### Related information 

* New F# project, no changes
* Windows 10 64bit
* Visual Studio 
```
Microsoft Visual Studio Community 2017 RC
Version 15.0.26206.0 D15REL
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2017 RC   00369-50000-00000-AA988
Microsoft Visual Basic 2017 RC

Visual C# 2017 RC   00369-50000-00000-AA988
Microsoft Visual C# 2017 RC

Visual C++ 2017 RC   00369-50000-00000-AA988
Microsoft Visual C++ 2017 RC

Visual F# 4.1   00369-50000-00000-AA988
Microsoft Visual F# 4.1

ASP.NET and Web Tools 2017   15.0.30206.0
ASP.NET and Web Tools 2017

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake
```

**Comment by dsyme** [comment] 2017-02-23 21:13
@cartermp We should look into this.  I'm not aware of the specific change that would have caused this regression.....

**Comment by cartermp** [comment] 2017-02-23 22:11
Tagged and noted for blog post.  I'll see if I can get it into the known issues for the VS release notes as well.

**Comment by dsyme** [comment] 2017-04-07 10:20
@gusty,  This bug is caused by my switching of operations in  the commit https://github.com/Microsoft/visualfsharp/commit/4f89b4c872b59b0d70cef63b15e4bb91ac12cdfe when fixing  https://github.com/Microsoft/visualfsharp/issues/1306

We need to go back and review what we've done here, and perhaps revert the change

**Comment by gusty** [comment] 2017-04-07 10:29
@dsyme 
Hopefully we don't revert it, otherwise it will also be a regression now.
I would like to help to resolve this in a way we don't need to revert but I'll be out for holidays.
In the meantime let me know if you see other regressions related to this issue.

**Comment by dsyme** [comment] 2017-04-07 11:06
@gusty I submitted a tentative fix here https://github.com/Microsoft/visualfsharp/issues/2416

**Comment by dsyme** [comment] 2017-04-29 01:20
The fix for this has been merged

**Closed by dsyme** 2017-04-29 01:20 UTC
Labels: 2 - Ready, Area-Compiler, bug, regression, Urgency-Now
