### ISSUE TITLE
Selecting a non-existent file in the Solution Explorer results in a poor user experience

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2240] opened 2017-01-12 18:54 UTC
If a file within a project has been deleted at the file system level but is still listed in the fsproj, selecting that file in the Solution Explorer results in multiple errors.

#### Repro steps

1. Delete a file in a project from the file system (not from Solution Explorer)
2. Single-click the file in the Solution Explorer

#### Expected behavior

Nothing (would expect error on double click), as C# does.

#### Actual behavior

Error dialog appears saying that the file does not exist. The project node is then focused in the solution explorer. The first error dialog then reappears.

You are now free to single click the item without error dialogs.

#### Known workarounds

None.

#### Related information 

This only occurs in VS 2015 (and maybe below). I believe the reason that it doesn't error on master is because previewing is broken.

**Comment by vasily-kirichenko** [comment] 2017-02-11 18:59
I investigated the code. We could fix it, but it's better to grab fresh SharedProject code, see https://github.com/Microsoft/visualfsharp/pull/2418 I'm pretty sure it will work exactly as C#/VB project system, previewing will also be fixed. The problem is that finishing that PR is _a lot_ of work.

**Comment by vasily-kirichenko** [comment] 2017-02-12 07:20
In https://github.com/Microsoft/visualfsharp/pull/2417 the behavior is much better now:

![1](https://cloud.githubusercontent.com/assets/873919/22860366/b27ae5f2-f10c-11e6-82e5-eeca6dab26f8.gif)

**Comment by saul** [comment] 2017-02-12 10:30
@vasily-kirichenko the reason you don't want single click to show the error dialog is because if you want to **right**-click the file, it takes two attempts (because the first attempt shows the dialog). It's really annoying and I think C# does it right.

**Comment by vasily-kirichenko** [comment] 2017-02-12 13:11
Completely fixed in https://github.com/Microsoft/visualfsharp/pull/2417

**Comment by saul** [comment] 2017-02-15 07:20
@vasily-kirichenko please close

**Closed** 2017-02-15 07:21 UTC
Labels: Area-IDE Project System
