### ISSUE TITLE
[Wish] publish nightlies of FSharp.Compiler.Tools

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#2865] opened 2017-04-16 15:13 UTC
FSharp.Compiler.Tools allows you to build projects independently of any system installed compiler.

It would be great if parallel to the nightly vsix, a nightly of this package would be published somewhere, e.g. myget.

Let's take https://github.com/Microsoft/visualfsharp/issues/2730 as an example. Locally, you can install the vsix, but you don't really want to install any preview vsixs on a buildserver (and often you can't).

If there was a package of FCT with this fix available, then it could be used in the projects that hit that bug. (with the obvious caveat that a nightly is less well-tested, and may cause other regressions)

**Comment by jack-pappas** [comment] 2017-04-16 16:06
For some additional context: I mentioned in the the ``#fsharp`` Slack channel this morning that I had a bit of time to kill this morning so thought I'd do a bit of maintenance/cleanup on the unit tests for [ExtCore](https://github.com/jack-pappas/ExtCore). I haven't had much time to work on ExtCore lately, so this was the first time I'd really had a chance to work on it with VS2017. Unfortunately, it looks like there was some regression in the compiler, and now the ``ExtCore.Tests`` project won't compile due to some resolution issue which specifically affects methods in ExtCore's ``Seq`` module; the VS IDE works fine (go to definition and tooltips work), but the compiler doesn't.

In light of the issue, I suggested implementing some testing script/framework that'd provide an easy way to fetch sources (e.g. from a Github/Bitbucket repo) for a list of well-known projects and try to build them using a locally-compiled compiler build (or as @0x53A suggested, a nightly FCS nuget package). We wouldn't be looking at the compiled binaries or running them, just testing the compiler to look for regressions which caused compilation to suddenly start failing.

**Comment by dsyme** [comment] 2017-04-18 14:01
> In light of the issue, I suggested implementing some testing script/framework that'd provide an easy way to fetch sources (e.g. from a Github/Bitbucket repo) for a list of well-known projects and try to build them using a locally-compiled compiler build (or as @0x53A suggested, a nightly FCS nuget package). We wouldn't be looking at the compiled binaries or running them, just testing the compiler to look for regressions which caused compilation to suddenly start failing.

Or we just check in a whole copy of ExtCore

**Comment by 0x53A** [comment] 2017-04-25 21:53
@dsyme did you close this on purpose? I would still really like a nightly (or weekly), if it isn't too much effort to implement. =)

**Comment by dsyme** [comment] 2017-04-25 22:43
No.  Though just to note that you can get a nuget feed of FCT packages from the AppVeyor CI https://ci.appveyor.com/project/fsgit/fsharp

**Comment by 0x53A** [comment] 2017-04-25 22:50
Thanks, that looks good.
They even seem to be correctly strong-name signed, which is good, because I can't disable that on our buildservers.

**Comment by cartermp** [comment] 2019-05-01 19:07
Closing this out, as we're not planning on doing this. When we consolidate repositories a bit more we also won't be pulling this along for the ride.

**Closed by cartermp** 2019-05-01 19:07 UTC
Labels: Area-Infrastructure, Feature Request
