### ISSUE TITLE
Rename refactoring does not work across projects

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3382] opened 2017-07-25 15:43 UTC
![1](https://user-images.githubusercontent.com/873919/28580658-de5290f8-7168-11e7-9535-6e1c994ba902.gif)

What's more, referencing a symbol in another project brakes renaming it within the project where the symbol is defined.

**Comment by Pilchie** [comment] 2017-07-25 15:53
Do you have the option to not have in-memory references for P2Ps?

**Comment by cartermp** [comment] 2017-07-25 15:58
I think this is a dupe of #3033 unless something is different.

**Comment by vasily-kirichenko** [comment] 2017-07-25 16:23
2.5 months have gone. Any plans to fix this?

**Comment by vasily-kirichenko** [comment] 2017-07-25 17:27
Same on 15.3 preview 5 + VFT nightly preview.

**Comment by cartermp** [comment] 2017-07-25 17:34
Yes, we want to fix this.  But we're currently preoccupied with high-priority crash investigations and fixes, .NET Core support, #3267, and shipping.  Closing this and the other issue in favor of #3033.  I've moved your screen caps over there.

**Closed by cartermp** 2017-07-25 17:34 UTC
