### ISSUE TITLE
VS2017 project template references System.ValueTuple via nuget / packages.config

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2336] opened 2017-01-28 14:41 UTC
When creating a F# project in VS2017, a packages.config is added to the project and System.ValueTuple package is pulled from internet.

#### Repro steps

* create F# class library in VS2017

#### Expected behavior

* no packages.config
* no packages folder in the solution folder

#### Actual behavior

* packages.config file is added to the project
* a packages folder is created next to the .sln file

#### Known workarounds

remove those files

#### Related information 

C# project by default doesn't pull the reference, and gives a compile time error when I try to use tuple notation:

> error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported

I'd expect F# to be aligned on the behavior, after I do the workaround, I get this compile error (which is fine):

> The type referenced through 'System.ValueTuple`2' is defined in an assembly that is not referenced. You must add a reference to assembly 'The system type 'System.ValueTuple`2' was required but no referenced system DLL contained this type'.

![image](https://cloud.githubusercontent.com/assets/87944/22397366/23fb06c4-e570-11e6-9516-2232a9a3d481.png)

**Comment by vasily-kirichenko** [comment] 2017-01-28 14:45
I disagree. C# editor has a Code Fix action, that adds the package reference in a seconds, F# does not have it:

![image](https://cloud.githubusercontent.com/assets/873919/22397393/8c29461e-e581-11e6-9e0c-7a9977d921e9.png)

**Comment by smoothdeveloper** [comment] 2017-01-28 14:50
@vasily-kirichenko F# use reference tuples by default (that's the succint syntax), if usage of value tuple is required, adding the package or just referencing a C# project which has that reference should work without much hassle.

Having packages.config forced by default doesn't sound like a good choice to me, any time I'll add a F# project, I'll need to remove it (because it doesn't honor the fact that I'm using paket or nuget with different settings).

Eventually we will be able to integrate the same code analyzer used in C#, or make one which can also detect presence of paket.references file.

**Comment by vasily-kirichenko** [comment] 2017-01-28 14:54
Yes, we should do all these, but currently we have value tuples by default and it's ok. If you use Paket, you have to add FSharp.Core package and edit project file by hand. Removing project.json and the VT reference is not a big deal compared to that.

**Comment by dsyme** [comment] 2017-01-28 15:00
This is by design for the Visual F# Tools. The Visual F# team have made a choice to add ValueTuple support by default in the templates.  The language itself is designed so the support is optional, and the compiler is architected so it doesn't need to be activated. Other packagings of F# (e.g. Azure Notebooks, or Azure Functions or whatever) may make different choices. But for Visual F# the team have made the choice to provide the feature "on".

So I'll close this as as by design

**Closed by dsyme** 2017-01-28 15:00 UTC
