### ISSUE TITLE
The 'FSharpProjectPackage' didnot load correctly

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#6075] opened 2019-01-10 18:14 UTC
After the last update of visual studio 2017, I cannot open any longer F# based projects. I get the message in the subject and if I continue In the solution explorer the projects appear as (incompatible). Theactivity log (attached) reports:

`CreateInstance failed for package [FSharpProjectPackage]Source: 'mscorlib' Description: Could not load file or assembly 'FSharp.ProjectSystem.FSharp, Version=15.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) System.IO.FileLoadException: Could not load file or assembly 'FSharp.ProjectSystem.FSharp, Version=15.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) File name: 'FSharp.ProjectSystem.FSharp, Version=15.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---&gt; System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A) The Zone of the assembly that failed was: MyComputer at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark&amp; stackMark) at System.Activator.CreateInstance(String assemblyName, String typeName) at System.AppDomain.CreateInstance(String assemblyName, String typeName) System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A) The Zone of the assembly that failed was: MyComputer`

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/416438/the-fsharpprojectpackage-didnot-load-correctly.html
VSTS ticketId: 757235_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment] 2019-01-10 18:15
Edited to format the message.

Possible duplicate of #6053 if nightlies are involved

**Comment by cartermp** [comment] 2019-01-30 15:11
Closing as duplicate of #6053, since this is the same error as the issue with nightlies atop 15.9

**Closed by cartermp** 2019-01-30 15:11 UTC
