### ISSUE TITLE
Duplicated tabs in project properties on .NET Core 2.0

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#3513] opened 2017-08-27 21:58 UTC
![image](https://user-images.githubusercontent.com/2365592/29754278-8b9c9ac0-8b8a-11e7-8ad3-d1919fcb654f.png)

![image](https://user-images.githubusercontent.com/2365592/29754287-a54fcec4-8b8a-11e7-82b3-906d0bd5816c.png)

#### Repro steps

Try snapshotted project by link
https://www.sendspace.com/file/lmp9t0

#### Expected behavior

No duplicated tabs

#### Actual behavior

Duplicated tabs

#### Related information 

* .NET Core 2.0 RTM
* Visual Studio Enterprise 15.3.2
* Visual F# tools 15.4.1.17082301

**Comment by cartermp** [comment] 2017-08-28 16:13
@KevinRansom Is this something we control, or is this a project system repo issue?

**Comment by cartermp** [comment] 2017-09-08 01:35
cc @tannergooding

**Comment by cartermp** [comment] 2018-02-14 18:24
This does not occur anymore with VS 15.5 or 15.6. Closing, but please do ping to re-open if you see it in those versions of VS.

**Closed by cartermp** 2018-02-14 18:24 UTC

**Comment by xperiandri** [comment] 2018-02-14 22:53
So which version has been fixed? 15.5.6 behaves the same with duplicated tabs

**Comment by cartermp** [comment] 2018-02-14 22:57
This is fixed in 15.5 and 15.6 preview - I verified it this morning. What version of the VF# tools do you have?

**Comment by xperiandri** [comment] 2018-02-14 23:02
15.4.1.17110401

**Comment by cartermp** [comment] 2018-02-14 23:34
That's the same I have (released version). Weird.

Testing the SAFE bookstore app:

![image](https://user-images.githubusercontent.com/6309070/36233788-7bd5cc90-119c-11e8-8732-aa97a86a14b5.png)
![image](https://user-images.githubusercontent.com/6309070/36233795-8312b266-119c-11e8-8d9c-3620feab70e8.png)

The link to your project doesn't work anymore. Is it something you can share?

**Comment by xperiandri** [comment] 2018-02-14 23:41
Try my updated repro https://github.com/xperiandri/azure-functions-fsharp-examples

**Comment by xperiandri** [comment] 2018-02-15 01:15
![image](https://user-images.githubusercontent.com/2365592/36236354-5ad6e814-11fe-11e8-9914-cd9a27f59dcc.png)

Same thing in 15.6 Preview 5.0 with project above

**Comment by cartermp** [comment] 2018-02-15 06:09
So strange. Note that the solution using paket will not build in VS:

```
Error occurred while restoring NuGet packages: The operation failed as details for project PaketFunctions could not be loaded.
1>------ Build started: Project: PaketFunctions, Configuration: Debug Any CPU ------
1>PaketFunctions -> C:\Users\Phillip Carter\Downloads\azure-functions-fsharp-examples-master (1)\azure-functions-fsharp-examples-master\8-paket\PaketFunctions\bin\Debug\netstandard2.0\bin\PaketFunctions.dll
1>C:\Users\Phillip Carter\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.0-beta2\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(16,5): error MSB4062: The "GenerateFunctionsExtensionsMetadata" task could not be loaded from the assembly C:\Users\Phillip Carter\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.0-beta2\build\..\tools\net46\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll. Could not load file or assembly 'file:///C:\Users\Phillip Carter\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.0-beta2\tools\net46\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
1>Done building project "PaketFunctions.fsproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Each of the other projects seems to load in 15.6 Preview 5 just fine, and their project property pages don't have issues. The SAFE bookstore app, which uses Paket, also works fine and does not have the issue with property pages.

I think what you're seeing is the same root cause as #4085, which I cannot reproduce on the SAFE Bookstore nor the FAKE-netcore solution. Both of those use Paket, load correctly, have IntelliSense, build, and do not show duplicates.

@forki since this is using Paket and Functions, do you see similar issues with your functions apps if you open them in VS?

**Comment by xperiandri** [comment] 2018-02-15 14:01
Do you have both components installed? F# for desktop and F# for .NET Core.

**Comment by cartermp** [comment] 2018-02-15 16:06
Yes, this is with both Workloads (and more) installed. My suspicion is that the property pages issue is a red herring, and that #4085 tracks the root cause
