### ISSUE TITLE
Cannot build project templates created with dotnet new in F#, in .NET Core

### ISSUE THREAD

**Issue by luminescent** [Microsoft/visualfsharp#3567] opened 2017-09-11 11:07 UTC
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. `dotnet new xunit -lang F#` (I have also tried `dotnet new console -lang F#` with similar results) 

2. `dotnet build` 

#### Expected behavior

I expect the project to build and it used to until a couple of hours ago. 

#### Actual behavior

It now stopped building with the error below, suddenly. It used to work couple of hours ago and I haven't done any updates. 

```
c:\work\src\testNetCore>dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.0.0\FSharp\Microsoft.FSharp.Targets(224,9): error MSB4062: The "Fsc" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll. Could not load file or assembly 'C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll'. Format of the executable (.exe) or library (.dll) is invalid. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\work\src\testNetCore\testNetCore.fsproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.0.0\FSharp\Microsoft.FSharp.Targets(224,9): error MSB4062: The "Fsc" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll. Could not load file or assembly 'C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll'. Format of the executable (.exe) or library (.dll) is invalid. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\work\src\testNetCore\testNetCore.fsproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.52
```

#### Known workarounds

I rerun the installer for .NET Core 2.0 and choose Repair. This fixed it.

#### Related information 

* Operating system: Windows 10 Professional
* Branch: not sure? Installed from installer.
* .NET Runtime, CoreCLR or Mono Version: `dotnet --version` returns `2.0.0` . `fsc` has version `4.1`.
* Editing Tools (e.g. Visual Studio Version): Visual Studio Code latest version, but haven't actually used it on this new template
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions: n/a?
* Links to performance testing scripts n/a
* Indications of severity: I'd say critical. Out of the box templates should compile.

**Comment by cartermp** [comment] 2017-09-11 16:03
@KevinRansom any idea what could cause MSBuild from failing to find FSharp.Build.dll?

**Comment by KevinRansom** [comment] 2017-09-20 08:53
@luminescent sorry it took so long for me to see this.

The interesting part of the error is this:
Could not load file or assembly 'C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll'. 
Format of the executable (.exe) or library (.dll) is invalid.

I don't know how this can happen, If this is still reproducible could you please zip up the 'C:\Program Files\dotnet\sdk\2.0.0\FSharp\'  directory I would be interested in looking to see why it is considered invalid.

Thanks

Kevin

**Comment by cartermp** [comment] 2018-02-14 04:39
@luminescent I've still not seen this either on mac or Windows. Here's the latest on my machine: 
![image](https://user-images.githubusercontent.com/6309070/36188002-f9a1ff8a-10fd-11e8-98fc-391325f65d27.png)

I'll close this out due to this. Please do ping if you see it again so that we can re-open it.

**Closed by cartermp** 2018-02-14 04:39 UTC
Labels: Area-DotNetCore, needs repro

**Comment by luminescent** [comment] 2018-02-14 19:37
I wasn't able to reproduce it after repairing the installation either. Must
have been a one time fluke...

On 14 Feb 2018 04:39, "Phillip Carter" <notifications@github.com> wrote:

@luminescent <https://github.com/luminescent> I've still not seen this
either on mac or Windows. Here's the latest on my machine:
[image: image]
<https://user-images.githubusercontent.com/6309070/36188002-f9a1ff8a-10fd-11e8-98fc-391325f65d27.png>

I'll close this out due to this. Please do ping if you see it again so that
we can re-open it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/3567#issuecomment-365494292>,
or mute the thread
