### ISSUE TITLE
Some existing projects don't compile with VS2017 (FAKE/PCLs/...)

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#2340] opened 2017-01-28 19:03 UTC
Many projects that worked fine with Visual Studio 2015 can't resolve `FSharp.Core` when loaded in 2017 RC3
Examples are: 
[FSharp.Data](https://github.com/fsharp/FSharp.Data), [Gjallarhorn](https://github.com/ReedCopsey/Gjallarhorn)

#### Expected behavior

Project builds correctly, both from command prompt and in Visual Studio 2017

#### Actual behavior

`1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1912,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "FSharp.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.`

and

`The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\FSharp\Microsoft.Portable.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

#### Known workarounds

Manually edit .fsproj files adding HintPath elements

#### Related information 

Tested on machine with no other version installed but VS 2017 RC3 with preview (RC3) F#. This concerns both CLI and IDE, portable and full .NET targets.

I think the loss of backwards compatibility may be confusing to newcomers.

**Comment by forki** [comment] 2017-01-28 19:18
Yes this is a general issue with installed targets files. The concept is
broken and the fsproj files need to be adjusted for every release. In
theory it should all be possible to solve with MSBuild vnext or by using
the fsharp.compiler packages from nuget. In practice this is really hard.

Am 28.01.2017 20:03 schrieb "majocha" <notifications@github.com>:

**Comment by dsyme** [comment] 2017-01-29 21:57
This sounds like a significant regression. 

Previous VS releases always compiled project files that worked in various previous releases without needing to adjust project files.  To test this, the http://github.com/fsharp/fsharp repo has a whole bunch of projects here https://github.com/fsharp/fsharp/tree/master/tests/projects - all these should really continue to compile in all editions of Visual Studio without change.

I know there have been changes in location for installed target files etc - I didn't understand what was going on there.

That said, moving away from installed target files would be great, relying only on nuget pacakges.

**Comment by cartermp** [comment] 2017-01-30 16:55
Tagging @Pilchie and @brettfo - I'm not sure what the cause is here, maybe @brettfo knows more.

Moving to the new MSBuild as the default and being on the Roslyn Project system is on my immediate radar in terms of "what we need to do for tooling".  I'm not sure how much that helps, but the benefits it gives us are large enough that I'm inclined to say we should fix those regressions as we move over.  If there's a relatively quick way to NuGetize our dependencies in the short-term then I think that's worth doing.

**Comment by Pilchie** [comment] 2017-01-30 17:19
I suspect this is because FSharp.Core used to be in the GAC, so even if the path wasn't resolved by the targets, the ResolveAssemblyReferences task would find it in the GAC and use that.  Fixing this shouldn't require either new MSBuild or new project system.  The targets files that include it as a reference should do so via a well-known variable like `$(MsBuildExtensionsPath)`, - and if the relative path has *changed*, we should add some version conditions to find it in the right place per-version.

**Comment by Pilchie** [comment] 2017-01-30 17:19
@KevinRansom - do you know where in the targets files we add the reference to FSharp.Core?

**Comment by dsyme** [comment] 2017-01-30 18:21
@Pilchie MSBuild resolves an FSharp.Core reference that is in the project file.  The way this is expressed in the project file depends on .NET Framework v. Portable projects. For .NET Framework it is like this:
```
    <Reference Include="FSharp.Core, Version=$(TargetFSharpCoreVersion), Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
      <Private>True</Private>
    </Reference>
```

I believe MSBuild command line and VS2015 resolved this particular reference via AssemblyFoldersEx via the following registry keys:

![capture55](https://cloud.githubusercontent.com/assets/7204669/22435518/414c40d6-e718-11e6-8e32-f3c4e46b81ad.PNG)

Likewise it is worth looking at how the standard reference text gets resolved for each of Profile47, Profile7/78/259 project files.

I assume the current installer continues to lay down all necessary reference assemblies e.g.
```
C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.1.0\FSharp.Core.*
C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\FSharp.Core.*
C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.1.0\FSharp.Core.*
```

If it doesn't that would be a problem.

Anyway that's how stuff has worked so far.  Ideally everyone should move everything to use an FSharp.Core nuget package.  But that would involve changing every F# project file in the world, and correlating TargetFSharpCoreVersion with specific nuget package numbers

**Comment by dsyme** [comment] 2017-01-30 18:44
Here is a bug that describes the issue:  https://github.com/fsprojects/ProjectScaffold/issues/283

The workaround appears to require ``vcvarsall.bat`` to be called (anyone know why?? does this apply to C# projects too??), to which the reply was

> Depending on vcvarsall.bat being called would be a major regression that should be fixed though.

https://github.com/fsprojects/ProjectScaffold/issues/283#issuecomment-274948338

**Comment by Pilchie** [comment] 2017-01-30 18:53
Not sure about the .NET Framework case, but for .NET Portable, this line looks problematic:

`    <HintPath>$(MSBuildExtensionsPath32)\..\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>`

MSBuild is installed under the VS directory, but Reference Assemblies remains under program files, so this hint path won't resolve correctly.

Tagging @AndyGerlicher from MSBuild to see if he can help advise how these targets *should* be structured.

**Comment by dsyme** [comment] 2017-01-30 19:11
@Pilchie From a quick glance there's been changes in the reference text for VS2017, but no project upgrade path has been implemented

e.g. this is now being used:

```
      <HintPath>$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>

```

So the workaround is likely to be to universally change 
```
<HintPath>$(MSBuildExtensionsPath32)\..\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>

```
to
```
      <HintPath>$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\FSharp\.NETCore\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>
```

I don't know why this wasn't used all along.

This will presumably break many builds which include F# projects, so if confirmed it would be wise to communicate this widely.

Not sure about the targets files problems,. that should also be investigated

**Comment by cloudRoutine** [comment] 2017-02-11 23:29
I ran into some similar issues [a few months back and wrote a bit about it](https://github.com/Microsoft/visualfsharp/issues/1435#issue-171026442)

> This means that there is an expectation that targets files are installed machine-wide at...
> If they are not installed in these locations then failures will happen.

@dsyme those targets files just redirect to the sdk targets file so I don't understand the benefits of having this layer of indirection. 

Wouldn't it be easier to base the targets around the standalone SDK installation so that people who only use that don't run into the issue where they can't build their project because they don't use VS.

```xml
<Choose>
    <When Condition="$(TargetFSharpCoreVersion) &gt;= 4.3.0.0 AND $(TargetFSharpCoreVersion) &lt; 4.3.1.0 ">
        <PropertyGroup>
            <FSharpTargetsPath>$(MSBuildProgramFiles32)\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </When>
    <When Condition="$(TargetFSharpCoreVersion) &gt;= 4.3.1.0 AND $(TargetFSharpCoreVersion) &lt; 4.4.0.0 ">
        <PropertyGroup>
            <FSharpTargetsPath>$(MSBuildProgramFiles32)\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </When>
    <When Condition="$(TargetFSharpCoreVersion) &gt;= 4.4.0.0 AND $(TargetFSharpCoreVersion) &lt; 4.4.1.0 ">
        <PropertyGroup>
            <FSharpTargetsPath>$(MSBuildProgramFiles32)\Microsoft SDKs\F#\4.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </When>
    <Otherwise>
        <PropertyGroup>
            <FSharpTargetsPath>$(MSBuildProgramFiles32)\Microsoft SDKs\F#\4.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </Otherwise>
</Choose>
<Import Project="$(FSharpTargetsPath)" Condition="Exists('$(FSharpTargetsPath)')" />
```

**Comment by dsyme** [comment] 2017-04-29 13:32
My impression is that this is being dealt with via updates to FAKE and by using the right msbuild on a system.

**Closed by dsyme** 2017-04-29 13:32 UTC
Labels: Area-IDE Project System, Area-Setup, bug, regression, Urgency-Now

**Comment by dsyme** [comment] 2017-06-23 17:53
Just to mention I had a build problem with a project file using the raw "cmd" command prompt (on AppVeyor CI actually) which was fixed by adding this to the top of the project file (for some reason it was missing)

     <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />

**Comment by spazmodius** [comment] 2018-03-12 16:43
Was this closed with no fix?  When I run `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe`, my F# projects looks for `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\FSharp\Microsoft.FSharp.Targets`, which is not there.  

(It can be found at `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\FSharp\Microsoft.FSharp.Targets`)

Is this expected to not work?

**Comment by cartermp** [comment] 2018-03-12 16:55
@spazmodius In general, building with previous versions of msbuild is fraught with issues any time there is a release. Do you still see that same issue if you build with MSBuild 15.0? The original issue uses MSBuild 15 (the one released with VS 2017) rather than MSBuild 14.0 (the one released with VS 2015).

**Comment by KevinRansom** [comment] 2018-03-12 19:32
@spazmodius 
Hi mate, can you attach your project file, I will take a look and see if what you have is expected to work.

In general project files from earlier versions of Visual Studio are expected to work, assuming they were not manually edited in an incompatible manner.

Thanks

Kevin

**Comment by spazmodius** [comment] 2018-03-12 20:27
Sure, it is here https://gist.github.com/spazmodius/18c55c814d64c6d84f0739fe9774a340 .

As my gulp script always uses msbuild 14.0, but my environment is VS 2017, the mismatch defeats finding the targets file.  If I get gulp to use the msbuild under `...\Microsoft Visual Studio\2017\Enterprise\MSBuild` then it works.

There seems to have been a pattern, prior to 15.0, of putting targets in a `Program FIles (x86)\MSBuild\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp`.

**Comment by KevinRansom** [comment] 2018-03-12 20:45
Yes, so ... that kind of mix and match won't really work for us because ... we rely on a bunch of well know msbuild variables.
in this case:  $(MSBuildExtensionsPath32)
https://gist.github.com/spazmodius/18c55c814d64c6d84f0739fe9774a340#file-gistfile1-txt-L46

This will be set by msbuild 14 to point to the msbuild 14 extensions folder, however, you are using a dev 15 installed environment and I presume you want to use the dev 15 compiler. And so I assume you want to use a dev 15 FSharp Compiler.

That kind of mix and match is not supported.  We expect either a consistent VS 2015 install or a consistent vs2017 install.  Either should work fine, but using MSBuild from 1 and compiler and tools from the other is not supported.

I hope this explains it for you
Kevin

**Comment by spazmodius** [comment] 2018-03-12 21:12
Got it. Thanks for your help!

**Comment by ScottHutchinson** [comment] 2018-08-10 16:57
This is still not right. Did a fresh install of VS 2017 with F# language support. Tried to build an F# project that builds fine in VS 2015, but I got this: `warning MSB3245: Could not resolve this reference. Could not locate the assembly "FSharp.Core, Version=4.4.0.0`

So much for backward compatibility. I was able to fix it by installing this: https://www.microsoft.com/en-us/download/details.aspx?id=48179

Also, it seems that the IDE is broken too, because the warnings are not shown in the Errors List window, which says "0 Warnings".

**Comment by KevinRansom** [comment] 2018-08-10 17:05
Can you attach the project file?  I don't need any source I will take a look.

**Comment by cartermp** [comment] 2018-08-10 17:12
@ScottHutchinson Do you know if your project is taking a dependency on msbuild 14 or lower? This is a common cause for issues, but it is unrelated to the F# tools. The solution is usually to either:

(a) Not depend on an msbuild toolset directly
(b) Upgrade that dependency to msbuild 15

**Comment by ScottHutchinson** [comment] 2018-08-10 18:25
@KevinRansom Here is the .fsproj file. Thanks for looking into this.

https://gist.github.com/ScottHutchinson/cc89522bec13abadf62d53510362d2af

**Comment by KevinRansom** [comment] 2018-08-10 20:46
It's this code here:

````
    <Reference Include="FSharp.Core, Version=$(TargetFSharpCoreVersion), Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
      <Private>True</Private>
    </Reference>

````

When we moved the FSharp Compiler from a global location to a side by side location we realized that if developers manually modified their FSharp.Core location it was going to break, however, for non-modified projects we translate the global location to the side by side location, here:

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets#L410

To make this compiler correctly in VS2017. you should modify the FSharp.Core reference to:
It needs to look like this, as a benefit, this should also work in VS2015.
````
    <Reference Include="FSharp.Core"> 
      <Name>FSharp.Core</Name> 
      <AssemblyName>FSharp.Core.dll</AssemblyName> 
      <HintPath>$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\$(TargetFSharpCoreVersion)\FSharp.Core.dll</HintPath>
    </Reference> 
````

**Comment by ScottHutchinson** [comment] 2018-08-10 21:30
@KevinRansom That change did work in VS2015. I can't really test it conclusively in VS2017 right now, because I have only one instance available and I fixed that one already with the installer as mentioned above in https://github.com/Microsoft/visualfsharp/issues/2340#issuecomment-412143090

But we should be getting VS2017 on several more PCs in September, so we will find out then for sure if your fix worked.

**Comment by KevinRansom** [comment] 2018-08-10 23:38
Thanks mate, I'm pretty confident :-)
