### ISSUE TITLE
Failure to load type providers from Nuget package

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#4338] opened 2018-02-10 23:48 UTC
I have a strange situation where a type provider works perfectly when reference as local binary but fails with strange inconsistent errors when referenced as Nuget package. Up to the point where I can point to  exactly same binary located in nuget local cache but it fails as a nuget package
I hit this problem with https://www.nuget.org/packages/FSharp.Data.Npgsql. 
Seems @sergey-tihon  has this issue with Swagger type provider too.
https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/184#issuecomment-364625781

This basically renders type providers as completely un-usable due to unpredictability of the issue so it would nice to fix ASAP.
It is possibly related to the latest changes to https://github.com/fsprojects/FSharp.TypeProviders.SDK but I'm not sure because I expect that it would not work as local binary too. 
Thanks.

**Comment by sergey-tihon** [comment] 2018-02-11 06:39
IDE shows error `Incorrect instance type Parameter name: obj` after ~1min of working with provided types and methods. Occurs only when TP restored from NuGet.

Compilation is successful, compiled program also runs correctly and ~1st min of Intellisense look good.

#### Repro steps

1. Clone https://github.com/sergey-tihon/swagger-issue101
2. Open onle solution in IDE 
1. Wait for intellisense, type something in editor, checkout intellisense of provided types

#### Actual behavior

VS 2017
![vs_swagger_low](https://user-images.githubusercontent.com/1197905/35962377-2f69a608-0cc2-11e8-8d4e-1f00fdd991ad.gif)

Ionide
![sw_vs_code](https://user-images.githubusercontent.com/1197905/36058838-0e8fbe9c-0e3c-11e8-90b1-dcc3b98e7d04.gif)

#### Related information 

Environment 1

* Windows 10
* .NET Runtime 4.6.1 (old project files)
* Visual Studio 15.5.6
* Visual F# Tool 15.4.1.18020604

Environment 2

* macOS High Sierra 10.13.3
* Mono JIT compiler version 5.4.1.7 (2017-06/e66d9abbb27 Wed Oct 25 12:10:41 EDT 2017)
* Latest Ionide

**Comment by dsyme** [comment] 2018-02-12 11:15
Any step-by-step instructions for both problems would be immensely useful. Also sample projects and exact NuGet package numbers please.

For the second issue we really need a stack trace too

**Comment by sergey-tihon** [comment] 2018-02-12 16:00
> For the second issue we really need a stack trace too

@dsyme Any tip how to catch exception inside IDE?

> Also sample projects and exact NuGet package numbers, please.

My sample project https://github.com/sergey-tihon/swagger-issue101/ has all dependencies committed inside the git repo.

**Comment by sergey-tihon** [comment] 2018-02-12 16:18
I got more details for my case!
```
System.ArgumentException
  HResult=0x80070057
  Message=Incorrect instance type
Parameter name: obj
  Source=FSharp.Core
  StackTrace:
   at Microsoft.FSharp.Quotations.PatternsModule.checkObj(MemberInfo membInfo, FSharpExpr obj)
   at Microsoft.FSharp.Quotations.PatternsModule.mkInstanceFieldGet(FSharpExpr obj, FieldInfo finfo)
   at Microsoft.FSharp.Quotations.FSharpExpr.FieldGet(FSharpExpr obj, FieldInfo fieldInfo)
   at <StartupCode$SwaggerProvider-DesignTime>.$DefinitionCompiler.toStr@231-1.Invoke(Tuple`2 tupledArg) in X:\SwaggerProvider\src\SwaggerProvider.DesignTime\DefinitionCompiler.fs:line 232
   at <StartupCode$SwaggerProvider-DesignTime>.$DefinitionCompiler.toStr@227.Invoke(FSharpList`1 args) in X:\SwaggerProvider\src\SwaggerProvider.DesignTime\DefinitionCompiler.fs:line 231
   at ProviderImplementation.ProvidedTypes.ProvidedMethod.GetInvokeCode(FSharpList`1 args) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 993
   at <StartupCode$SwaggerProvider-DesignTime>.$ProvidedTypes.xT@8883-26.Invoke(FSharpList`1 arg00) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 8883
   at ProviderImplementation.ProvidedTypes.QuotationSimplifier.TranslateQuotationToCode(FSharpFunc`2 qexprf, String[] paramNames, FSharpExpr[] argExprs) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 8361
   at ProviderImplementation.ProvidedTypes.ProvidedTypesContext.convCodeToTgt[a](FSharpFunc`2 codeFun, Boolean isStatic, ProvidedParameter[] parameters, Boolean isGenerated, FSharpList`1 argsT) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 8761
   at <StartupCode$SwaggerProvider-DesignTime>.$ProvidedTypes.xT@8883-27.Invoke(FSharpList`1 argsT) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 8883
   at ProviderImplementation.ProvidedTypes.ProvidedMethod.GetInvokeCode(FSharpList`1 args) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 993
   at <StartupCode$SwaggerProvider-DesignTime>.$ProvidedTypes.Compile@14023-13.Invoke(ILTypeBuilder tb, FSharpOption`1 ptdT) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 14119
   at <StartupCode$SwaggerProvider-DesignTime>.$ProvidedTypes.typeMembers@13864.Invoke(ProvidedTypeDefinition ptd) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 13865
   at <StartupCode$SwaggerProvider-DesignTime>.$ProvidedTypes.nestedType@13870.Invoke(Type ntd) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 13871
   at <StartupCode$SwaggerProvider-DesignTime>.$ProvidedTypes.typeMembers@13864.Invoke(ProvidedTypeDefinition ptd) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 13866
   at ProviderImplementation.ProvidedTypes.AssemblyCompiler.iterateTypes[a](FSharpFunc`2 f, IEnumerable`1 providedTypeDefinitions) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 13877
   at <StartupCode$SwaggerProvider-DesignTime>.$ProvidedTypes.Compile@14023-12.Invoke(FSharpFunc`2 f, IEnumerable`1 providedTypeDefinitions) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 14023
   at ProviderImplementation.ProvidedTypes.AssemblyCompiler.Compile(Boolean isHostedExecution) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 14023
   at ProviderImplementation.ProvidedTypes.TypeProviderForNamespaces.Microsoft-FSharp-Core-CompilerServices-ITypeProvider-GetGeneratedAssemblyContents(Assembly assembly) in X:\SwaggerProvider\paket-files\fsprojects\FSharp.TypeProviders.SDK\src\ProvidedTypes.fs:line 14406
   at Microsoft.FSharp.Compiler.Tainted`1.Protect[a](FSharpFunc`2 f, range range)
```

<img width="795" alt="2018-02-12_1914" src="https://user-images.githubusercontent.com/1197905/36106824-6dad5d50-1029-11e8-95ef-82212103f71b.png">

**Comment by dmitry-a-morozov** [comment] 2018-02-12 16:38
https://github.com/demetrixbio/FSharp.Data.Npgsql/tree/visualfsharp-issue-4338

Steps:
1) from repo root 
- docker build -t pg_dvdrental .\tests\
- docker run -d -p 32768:5432 --name dvdrental pg_dvdrental
2) Navigate to tests/SampleApp/
  - Should build & run successfully. It uses https://www.nuget.org/packages/FSharp.Data.Npgsql/0.1.17-beta
  - Un-comment reference to `ResultType` https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/visualfsharp-issue-4338/tests/SampleApp/Program.fs#L9.  Compilation fails with 
```
FSharp.Data.Npgsql\tests\SampleApp\Program.fs(10,74): error FS0001: This expression was expected to have type    'FSharp.Data.Npgsql.ResultType (FSharp.Data.Npgsql.DesignTime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)'    but here has type    'FSharp.Data.Npgsql.ResultType (FSharp.Data.Npgsql, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)'
```
- Go project file and replace reference to nuget with reference to binary from same package. 
Comment out https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/visualfsharp-issue-4338/tests/SampleApp/SampleApp.fsproj#L13
And un-comment https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/visualfsharp-issue-4338/tests/SampleApp/SampleApp.fsproj#L18
The project compiles and run successfully.

**Comment by dmitry-a-morozov** [comment] 2018-02-12 19:31
@dsyme Because my problem is around type rewrite for ProvidedStaticParameter I tried to pull it from runtime component. It still fails and here what I found so far

![image](https://user-images.githubusercontent.com/3004037/36115462-fdbf8cca-0fe7-11e8-8ab4-98f0127065e7.png)

Since when `TypeProviderConfig.RuntimeAssembly` returns design-time assembly?

**Comment by dmitry-a-morozov** [comment] 2018-02-12 19:43
I guess this is why Swagger type provider fails too - it also has design-time/run-time separation. For combo style type providers it doesn't matter.

**Comment by dmitry-a-morozov** [comment] 2018-02-12 19:45
@dsyme I also can confirm that `TypeProviderConfig.RuntimeAssembly` has incorrect value only when a type provider loaded from nuget package. When loaded directly from binary it has right value.

**Comment by sergey-tihon** [comment] 2018-02-12 20:09
@dmitry-a-morozov Maybe we should explicitly specify in *.nuspec that NuGet should not reference DesignTime file to project after install https://docs.microsoft.com/en-us/nuget/reference/nuspec#specifying-explicit-assembly-references ?

**Comment by dmitry-a-morozov** [comment] 2018-02-12 20:16
I don't use *.nuspec anymore. It's just `dotnet pack`. 
Also, design time assembly is never explicitly referenced rather it's loaded by F# compiler from same folder as run-time based on `CompilerServices.TypeProviderAssembly` attribute value.

**Comment by dmitry-a-morozov** [comment] 2018-02-12 22:39
@sergey-tihon 
Temp fix
https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/1696cd4d8fc6dc04ba50e7f4d8b2e77059c22c46/src/DesignTime/TypeProviderAssembly.fs#L14
https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/1696cd4d8fc6dc04ba50e7f4d8b2e77059c22c46/src/DesignTime/TypeProviderAssembly.fs#L41

**Comment by dsyme** [comment] 2018-02-13 16:18
@dmitry-a-morozov I think @sergey-tihon may be on the right track.  After referencing the https://www.nuget.org/packages/FSharp.Data.Npgsql/0.1.17-beta package using Visual Studio 2017 I can confirm that references to both design-time and runtime assemblies have been added.  My understanding is that this is not what you want you only want the runtime assembly to be added as a reference

![image](https://user-images.githubusercontent.com/7204669/36160203-81a92f14-10d8-11e8-851c-3c2d57a3a368.png)

Looking at https://docs.microsoft.com/en-us/dotnet/core/tools/csproj I can't immediately see a way of excluding the design time DLL from being an implicit reference.  You may have to use an explicit nuspec file for your packaging, see https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuspecfile.  Let me know if this works and we can add the magic incantations to a TPSDK sample

**Comment by dsyme** [comment] 2018-02-13 16:20
You might also get mileage by removing this https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/master/src/DesignTime/TypeProviderAssembly.fs#L9.  This is saying that the DesignTime assembly is itself a Combo type provider.  I don't think that's what you want.

**Comment by baronfel** [comment] 2018-02-13 16:34
Can confirm that setting the explicit references list makes the IDE experience work again! https://github.com/fsprojects/SwaggerProvider/pull/104

**Comment by baronfel** [comment] 2018-02-13 16:51
We've got a beta going through the pipeline that we can use to do an end-to-end test. It should be about half an hour before I can report back on that.

**Comment by sergey-tihon** [comment] 2018-02-13 20:34
Confirm that it looks like the fix for SwaggerProvide (explicitly specify assemblies that should be referenced from NuGet package in nuspec/paket template)

**Comment by dsyme** [comment] 2018-02-13 22:15
Closing this as the issue appears solved (until next issue is found...) :)

**Closed by dsyme** 2018-02-13 22:15 UTC

**Comment by dmitry-a-morozov** [comment] 2018-02-14 03:42
@dsyme @sergey-tihon Thank you for help. 
@dsyme I can claim that we have solid-working PostgreSQL type provider with advanced features and basic docs. https://github.com/demetrixbio/FSharp.Data.Npgsql/blob/master/README.md
