### ISSUE TITLE
[From VSTS] Incremental Build error case seems to be getting hit

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3675] opened 2017-10-02 18:04 UTC
This line:

https://github.com/Microsoft/visualfsharp/blob/20573b7decc4989b625a769952c45a4c53fc510a/src/fsharp/vs/IncrementalBuild.fs#L1602

Appears to be getting hit:

* https://developercommunity.visualstudio.com/content/problem/118911/fsharp-syntax-highlighting-broken.html
* https://twitter.com/d3dal3/status/913832012800241664

I've personally never seen this before, but given that different people are seeing it, something is up.

**Comment by dsyme** [comment] 2017-10-02 18:39
Duplicate of https://github.com/Microsoft/visualfsharp/issues/3545

This is a bad bug - I believe it was because of the mismatch in options for a file in a project and has now been fixed, but I'm not sure

**Closed** 2017-10-02 19:08 UTC
Labels: Area-IDE Language Service, needs repro

**Comment by cartermp** [comment] 2017-10-02 19:09
#3545 doesn't result in a complete loss of colorization and editor features, does it?  I've seen #3545 before as well, but never with a completely hosed editor.

**Comment by dsyme** [comment] 2017-10-02 20:35
@cartermp I think it would.  But either way we need reliable repros and we need to fix these

**Comment by brianberns** [comment] 2018-02-27 08:01
Not sure why this is closed. I'm still getting it in VS 15.5.7:

> Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1007; Id 1008; Id 1009; Id 1010; Id 1011|], Id 1013, false, None)).

I don't think it's an incremental build issue, because it doesn't go away even if I do a full, clean rebuild.

**Comment by cartermp** [comment] 2018-02-27 16:16
@brianberns This bug is a duplicate of #3545
