### ISSUE TITLE
Changes in FSI assembly resolution between 4.0 and 4.1

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#3444] opened 2017-08-16 17:27 UTC
There have been behavioral changes in assembly resolution for fsi.exe/fsiAnyCpu.exe on .NET Framework between F# 4.0 and 4.1.  THis seems to apply when references such as ``PresentationCore.dll`` are resolved from "Reference Assemblies" and/or GAC.  

### Repro steps

Compare for example

    #r "PresentationCore"

or

    #r "PresentationCore.dll"

The reference ``#r "PresentationCore"`` 

* In F# 4.0 resolves as ``C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\PresentationCore.dll``.  

* In F# 4.1 ``fsi,exe`` and ``fsiAnyCpu,exe``, this resolves as ``C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\PresentationCore.dll``

The reference ``#r "PresentationCore.dll"``:

* In F# 4.0 resolves as ``C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\PresentationCore.dll``.  

* In F# 4.1 **fsi.exe**, resolves as ``C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\PresentationCore.dll``

* In F# 4.1 **fsiAnyCpu.exe** (64-bit) does not resolve

* In Visual F# 4.1 Tools editing does not resolve

#### Expected behavior

Same behaviour as F# 4.0?

It is possible this is best considered by-design, and fully version-qualified references are better for these kind of references anyway. See workaround below

#### Actual behavior

See above

#### Known workarounds

One workaround is to use a version-qualified reference

```
#r "PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
#r "PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
#r "WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
```

**Comment by ReedCopsey** [comment] 2017-08-16 18:01
I would strongly recommend trying to get back the 4.0 behavior. Users of PresentationCore and the like expect to get the 4.0 assembly version, as that's what happens in C#. I'd expect that to be true of most (all?) references - people will be expecting the v4.5.1 (or v.current) versions, not the v3 framework versions.

**Comment by KevinRansom** [comment] 2017-08-16 18:08
@dsyme yes we should try to make sure that existing scripts continue to run correctly.  I suspect although with no supporting evidence that this may have happened as a consequence of moving to the side by side msbuild.

**Comment by dsyme** [comment] 2017-08-16 18:35
@ReedCopsey To gauge the severity of this - do you know of other examples of scripting with WPF?

**Comment by dsyme** [comment] 2017-08-16 18:51
Some plausibly relevant changes that came up in a repo search for "fsi assembly resolution". None of them looked like they would cause this on first look, but we should check 

https://github.com/Microsoft/visualfsharp/pull/2887
https://github.com/Microsoft/visualfsharp/pull/2612
https://github.com/Microsoft/visualfsharp/pull/849

**Comment by ReedCopsey** [comment] 2017-08-16 19:04
@dsyme most of the people I know doing WPF with F# heavily are still on VS 2015. I have had quite a few people with issues related to WPF and 2017 - and I wonder if this is part of the cause. (Going to need to go back and try to figure it out.)

In general, scripting with WPF is problematic at best, though, anyways - given the weird initialization sematics and lifetime of the "one and only Application" instance. However, I do think that this is a poor choice of resolution _in general_ (separate from this specific instance/WPF), as it's not how the rest of the ecosystem typically works. The fact that resolution is going to v3 assemblies just seems wrong.

**Comment by dsyme** [comment] 2017-08-16 20:22
> However, I do think that this is a poor choice of resolution in general (separate from this specific instance/WPF), as it's not how the rest of the ecosystem typically works. The fact that resolution is going to v3 assemblies just seems wrong.

Yes, I'm wondering if this is affecting ``#r`` resolution of other assemblies that ship in .NET Framework

**Comment by KevinRansom** [comment] 2017-08-16 20:23
@dsyme, I would think it must ... since we don't really special case wpf.

**Comment by ReedCopsey** [comment] 2017-08-16 20:40
I think it has - which is more my concern. I've fielded quite a few questions from newcomers recently who are picking up weird assembly references and hitting issues... (None of which have been WPF specific.) In hindsight, I suspect this is the underlying problem.

**Comment by dsyme** [comment] 2017-08-16 20:48
@KevinRansom WPF is special because its implementation assemblies are not in ``C:\Windows\Microsoft.NET\Framework\v4.0.30319\`` but rather in ``C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF``.  I think this means we don't resolve to the implementation assembly first, but go to the reference assembly.  I don't know why MSBuild doesn't choose the right reference assembly though - it knows the .NET Framework version.

**Comment by dsyme** [comment] 2017-08-16 20:53
BTW if someone has F# 4.1 from Visual Studio 2017 RTM or 15.1 or 15.2 around then it would be good to check those.  just type ``#r "PresentationCore"`` into fsi.exe

**Comment by matthid** [comment] 2017-08-16 20:58
15.2:

```
Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "PresentationCore";;

--> Referenced 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\PresentationCore.dll'
```

**Comment by dsyme** [comment] 2017-08-21 21:40
F# 4.0, using ``fsi.exe --resolutions``

```
TargetFrameworkDirectories:
    C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\
InstalledAssemblyTables:
IgnoreInstalledAssemblyTable:
    False
SearchPaths:
    C:\GitHub\dsyme\visualfsharp
    C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\
    {TargetFrameworkDirectory}
    {Registry:Software\Microsoft\.NetFramework,v4.5.1,AssemblyFoldersEx}
    {AssemblyFolders}
    {GAC}
```

F# 4.1, using ``fsi.exe --resolutions``
```
TargetFrameworkDirectories:
    C:\Windows\Microsoft.NET\Framework\v4.0.30319\
InstalledAssemblyTables:
IgnoreInstalledAssemblyTable:
    False
SearchPaths:
    C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
    C:\GitHub\dsyme\visualfsharp
    {TargetFrameworkDirectory}
    {Registry:Software\Microsoft\.NetFramework,v4.6.1,AssemblyFoldersEx}
    {AssemblyFolders}
    {GAC}
    C:\Windows\Microsoft.NET\Framework\v4.0.30319
```

**Comment by dsyme** [comment] 2017-08-21 22:10
The key thing that has changed is ``TargetFrameworkDirectories`` - it is no longer the "reference assemblies" directory.  This is because in F# 4.0 CompileOps.fs was computing an empty list for targetFrameworkDirectories passed to MSBuild reference resolution, and then this code in ``ReferenceResolver.fs`` kicked in:

```

  | let targetFrameworkDirectories   =
-- | --
  | if   targetFrameworkDirectories=[] then   DeriveTargetFrameworkDirectories(targetFrameworkVersion, logMessage)
  | else   targetFrameworkDirectories \|>   Array.ofList

```
In F# 4.1 we did some "cleanup" in integrating the F# compiler service code to now pass a non-empty value for target frameworks, using the implementation assemblies as the target framework.  

However this is incorrect because it missies the ``WPF`` folder from the implementation assemblies.

This is a manifestation of the long-running problem we've had with FSI.EXE where we weren't distinguishing between reference assemblies (for compilation) and implementation assemblies (for runtime).

**Comment by dsyme** [comment] 2017-08-21 22:14
@KevinRansom There are various fixes available

1. Always look in the reference assemblies for the target framework first, even for FSI.EXE.  (The implementation assemblies _should_ still be found at runtime since the framework knows how to load those - however there is a small risk that we will try to do a reflection-load on a reference assembly and introduce a runtime failure), OR

2. Add the implementation assembly ``C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF`` to the target framework directories, if it exists.  That is simple enough but is a hack

3. Do the work to very carefully distinguish between reference and implementation assemblies, and use that here.

It's plausible we may need to make this a hotfix somehow. so I favour (2) - otherwise I favour (1) and then eventually (3)

**Comment by dsyme** [comment] 2017-08-21 22:15
@KevinRansom Please advise

**Comment by KevinRansom** [comment] 2017-08-24 17:54
Option 2 is fine in the desktop FSI.

@Pilchie, @brettfo, @cartermp  We should take this for 2017.4 preview 3.

**Comment by cartermp** [comment] 2017-08-24 18:07
Yeah, I think option 2 is good enough.  👍 on getting this into Preview 3

**Closed** 2017-08-26 12:05 UTC
Labels: 2 - Ready, Area-FSI, bug, regression, Tenet-Compatibility, Urgency-Now
