### ISSUE TITLE
When `match x with [] -> ...` compiles, but `if x = [] then...` does not

### ISSUE THREAD

**Issue by kkm000** [Microsoft/visualfsharp#5612] opened 2018-09-09 03:56 UTC
For `x : T list` where `T` is `[<NoEquality>]`, `match x with []...` compiles and works nominally, but `if x = []` results in a compile error. This is indeed a minor issue if an issue at all, and could be by design, but I am still reporting it because I think it could have been handled with a less surprise.

#### Repro steps

```F#
> type [<NoEquality;NoComparison>] T = T;;
type T = | T

> let f () = [ T ];;
val f : unit -> T list

> f() = [];;

  f() = [];;
  ^^^

stdin(21,1): error FS0001: The type 'T' does not support the 'equality' constraint because it has the 'NoEquality' attribute

> match f() with [] -> true | _ -> false;;
val it : bool = false

> match f() with [ _ ] -> true | _ -> false;;
val it : bool = true

> f().IsEmpty;;
val it : bool = false

>
```

#### Expected behavior

A comparison to the empty list constant `[]` be valid regardless of list element type constraints.

#### Actual behavior

As shown above. Baffling at first, but understandable. It logically follows from strictly following the constraint rules. But at the same time, it's surprising from the language user experience viewpoint.

#### Known workarounds

`match x with []` works, as, naturally, does `List.isEmpty()`.

#### Related information 

Windows 10, VS developer environment prompt.
```
>fsi

Microsoft (R) F# Interactive version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.
```
Same in a Framework project in VS.

**Comment by TIHan** [comment] 2018-09-10 23:13
I see how this might be surprising, but this is correct behavior. When you are pattern matching, you are not checking to see if a value is equal to another value.

For example:
```fsharp
type [<NoEquality;NoComparison>] T = T of int

let f () = [ T(2) ]

let x = match f () with [ x ] when x = T(2) -> true | _ -> false // fails to compile
let y = match f () with [ T(2) ] -> true | _ -> false // compiles fine
let z = match f () with [ T(n) ] when n = 2 -> true | _ -> false // compiles fine
```
The one that fails, you are checking if the list has one value and then check equality on that value against another value that is `T(2)`.
The ones that pass, you are checking to see if the list has one value that is type `T` with a literal `2`. (You can almost say that this is equality, but you are manually checking individual pieces of the structure)

I hope that makes sense; but again I understand this might be a bit confusing at first. Perhaps we should make these instructions in our docs.

**Comment by TIHan** [comment] 2018-09-10 23:36
Closing this as it is by design.

**Closed by TIHan** 2018-09-10 23:36 UTC
Labels: Resolution-By Design

**Comment by kkm000** [comment] 2018-09-11 16:32
Thanks for the elaborate clarification @TIHan. I of course understand why the current behavior is the way it is, and that e. g. `[T] = [T]` in my example could not ever compile, as it would involve comparing *in fact* a `T` and a `T`, which its definition has explicitly erased. If you read `x=[]` as "compare x with the list `[]`, element by element" (as presumably the compiler interprets it), then the behavior is absolutely correct. It's just not how, IMO, a human programmer thinks about this expression; for me, I read it just as "test if the list `x` is empty". I just thought if the *syntactic* comparison with the literal constant `[]` is (or may possibly be) a special case, and the type constraint could be relaxed for that particular special case. Just like, for example, C++ allows syntactically comparing pointers with the literal `0` (whether for better or worse is debatable). So yes, my report was half an expression of a surprise, half a suggestion, a pretty minor, naturally, but possibly useful from the UX perspective.
