### ISSUE TITLE
Metadata not shown for F# dlls for .NET Core

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#5657] opened 2018-09-17 17:08 UTC
The metadata for an F# dll, made for .NET Core, is empty in the Details tab of the Properties dialog for the dll.

Repro:

1. With VS 15.8.4 (latest at this date), create a new console application solution from File -&gt; New -&gt; Project... -&gt; Installed -&gt; Other languages -&gt; Visual F# -&gt; .NET Core. Choose &quot;Console App (.NET Core)&quot;. Pick a name and click OK.

Visual F# Tools, or some other optional F# tools that can be chosen during VS installation, might be needed for the template to show up.

2. Right click on the project file in Solution Explorer and choose Properties.

3. Target Framework should be &quot;.NET Core 2.1&quot;. I believe the result is the same for &quot;.NET Core 2.0&quot;.

4. Go to Package and set &quot;Package version&quot;, &quot;Assembly version&quot; and &quot;Assembly file version&quot; to &quot;1.2.3.4&quot;. Save.

5. Right click on the project in Solution Explorer and choose &quot;Edit project.fsproj&quot;. 

6. Build the solution. Open the folder with the built dll.

7. Right click on the dll and choose Properties and then the Details tab.

Expected result:

5. Check that the version numbers are correct.

7. The list of metadata should be populated. &quot;File version&quot; should be &quot;1.2.3.4&quot;, &quot;Product version&quot; should be &quot;1.2.3&quot;, &quot;Product name&quot; should be the name of the project, &quot;File description&quot; should be the name of the project and the &quot;Language&quot; should be set (e.g. to &quot;Language Neutral&quot;).

The result that I get when creating a C# Console App the same way is shown in an attached screenshot. Here we see the metadata, as expected.

Actual result:

7. None of the mentioned variables have data in them. They are blank instead. Please see the attached image.

Some version info:

Visual Studio 15.8.4
Microsoft Visual F# Tools 10.2 for F# 4.5
OS: Windows 10

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/336722/metadata-not-shown-for-f-dlls-for-net-core.html
VSTS ticketId: 685285_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment] 2018-09-17 17:08
@KevinRansom any ideas?

**Comment by mika-s** [comment] 2018-09-17 22:42
I am the original poster on Developer Community.

I tried making a .NET Framework project to check what it shows there. I made a .NET Framework console app and a .NET Framework library that the console app references. The metadata is shown correctly in that case. This is for .NET framework 4.7.2.

I then made a .NET Standard class library in the same solution and built it. The metadata is not shown for this dll.

So the issue is for .NET Core and .NET Standard dlls.

**Comment by KevinRansom** [comment] 2018-09-18 03:02
@mika-s,

It looks to me as if the bug is in the dotnet sdk here:  https://github.com/dotnet/sdk/blob/ab2176b3447e3e7820b5a340408110b6d498f907/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FSharp.targets#L27

When building from the command line:
dotnet build
generates an assembly with the necessary attributes.

msbuild
generates an assembly without the necessary attributes.

I will submit a PR.   Thanks for the report

Kevin

**Comment by cartermp** [comment] 2018-09-19 18:10
The part of this that was broken on the F# side has been fixed by #5663 

There is still a PR out on the .NET SDK that completes this here: https://github.com/dotnet/sdk/pull/2538

I'll close this out as resolved. We are planning on making this available with the VS 15.9 release.

**Closed by cartermp** 2018-09-19 18:10 UTC
Labels: Area-DotNetCore, Area-External
