### ISSUE TITLE
Implement go to definition for F#

### ISSUE THREAD

**Issue by hez2010** [Microsoft/visualfsharp#5523] opened 2018-08-16 17:12 UTC
Please provide a succinct description of the issue.

#### Repro steps

Currently "Go to definition" in F# only works within user-defined symbols, it's hard for users to quickly lookup library functions' usage.
I'm wondering now that the Intellisense in Visual Studio can generate F# lib functions' usage for user, why can't user use "Go to definition" or "Peek definition" to see usage in F# syntax from metadata just like what C# does.

#### Expected behavior

display usage in F# syntax from metadata just like what C# does.

#### Actual behavior

can not find the definition.

#### Known workarounds

vs

#### Related information 

Provide any related information 

* Operating system Windows 10 17134.228
* Branch all branches
* .NET Runtime, CoreCLR or Mono Version .NET Core 2.1.400
* Editing Tools (e.g. Visual Studio Version) vs 15.8
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions n/a
* Links to performance testing scripts n/a
* Indications of severity normal

**Comment by cartermp** [comment] 2018-08-16 17:16
Closing as duplicate of #1939 

The main issue isn't in reading metadata, but writing a palatable representation to a temporary window. There is a closed trial PR that gets this mostly there, but it had too many quirks to accept at the time. I'm interested in trying to take it on for VS 2019, though.

**Closed by cartermp** 2018-08-16 17:16 UTC
