### ISSUE TITLE
Installing F# SDK Tools to VS Experimental Instance 

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#975] opened 2016-02-20 21:43 UTC
https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md#4-optional-install-the-visual-f-ide-tools-and-clobber-the-f-sdk-on-the-machine

Instead of clobbering the machine wide installation of F# is it possible to install the VSIX and update the vsintegration in an experimental instance instead to remove the need to repair VS to go back to the release version of the SDK?

**Comment by cloudRoutine** [comment] 2016-02-21 21:49
Or at the very least anything to avoid 
> Repairing Visual Studio 2015 is currently the only way to revert this step

as this can take several hours at worst

**Comment by dsyme** [comment] 2017-06-22 16:48
This is a duplicate of https://github.com/Microsoft/visualfsharp/issues/232

**Closed by dsyme** 2017-06-22 16:48 UTC
Labels: infrastructure
