### ISSUE TITLE
Valid code doesn't compile in Release mode

### ISSUE THREAD

**Issue by OkayX6** [Microsoft/visualfsharp#1264] opened 2016-06-15 16:05 UTC
I have a perfectly valid code that doesn't compile in Release mode, when defining value ``let subStr`` in the code below.

#### Repro steps

- Create empty console application
- Add reference to FSharp.Data 2.3.0
- Copy-paste the following code into Program.fs:

```fsharp
open FSharp.Data

type StatsResponse = JsonProvider<"""[
  {
    "yesCount": 983,
    "moyCount": 458,
    "noCount": 280,
    "alertCount": 3,
    "idSection": 94,
    "sectionName": "Section A"
  }]""">

type Stats(sectionStats: StatsResponse.Root[]) = 
    let sectionIdToStatsMap =
        sectionStats
        |> Seq.map (fun stats -> stats.IdSection, stats)
        |> dict

    member val SectionStats = sectionIdToStatsMap.Values

let generateReportFromStats (clientStats: #seq<string * Stats>) =
    clientStats
    |> Seq.iter (fun (clientName, stats) ->
        // BUG: it works when swapping the two following lines
        let orderedStats = stats.SectionStats
        let subStr = clientName.Substring(23)

        for s in orderedStats do
            printfn "%s" subStr
    )

[<EntryPoint>]
let main argv = 
    printfn "%A" argv
    0 // return an integer exit code
```

- Try to compile...

#### Expected behavior

Code should compile.

#### Actual behavior

Code doesn't compile with error: ``Undefined value 'subStr : string'
``

#### Known workarounds

Swap the two lines that start by: ``let subStr`` and ``let orderedStats``.

#### Related information 

* Windows 10 Pro
* F# 4.0
* .NET 4.6
* Visual Studio Enterprise 2015

**Comment by smoothdeveloper** [comment] 2016-06-15 17:01
@OkayX6 could you check if #742 is the issue by applying the work around?

**Comment by forki** [comment] 2016-06-16 07:56
I reproduced with the compiler from VS2015, but somehow I can't reproduce with master.

But I get.

![image](https://cloud.githubusercontent.com/assets/57396/16109346/9a7e1036-33a8-11e6-8bee-5ba701723ffb.png)

**Comment by OkayX6** [comment] 2016-06-16 14:31
@smoothdeveloper Yes, the workaround is working, so it's unrelated to TypeProviders :).

**Comment by dsyme** [comment] 2016-06-16 15:37
Since this is a duplicate of a bug that has been fixed I will close this

**Closed by dsyme** 2016-06-16 15:37 UTC
