### ISSUE TITLE
No IntelliSense when instantiating type with parameters in its constructor

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1766] opened 2016-11-17 18:44 UTC
On a machine with dev15 and F# tools, enter the following as a program:

```fsharp
type Foo(item1: int, item2: int, item3: int) =
    member this.TheSum = item1 + item2 + item3

[<EntryPoint>]
let main argv = 
    let foo = Foo(
    0 // return an integer exit code
```

Note that there is no IntelliSense:

![no-intellise-constructor](https://cloud.githubusercontent.com/assets/6309070/20402724/bea05798-acb2-11e6-9afe-cb6b412c15d2.PNG)

**Comment by dsyme** [comment] 2016-11-23 21:55
This is a duplicate of #1767

**Closed by dsyme** 2016-11-23 21:55 UTC
Labels: Area-IDE Language Service, bug, regression, Urgency-Now
