### ISSUE TITLE
Using Paste to add files to an F# project causes the order of files in the project and on the UI to get out of sync

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#104] opened 2015-01-26 19:16 UTC
Repro:
1.Create a new F# Console Application 
2.Create 3 F# source files (.fs) on disk 
3.Select all three files using windows explorer and paste them on to the F# project in Solution Explorer, note the files are appended to the project in the display. 
4.select program.fs 
5.use alt+down arrow to move it to the bottom of the source file list 
Image 
6.build project and note the build error similar to:

C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe TypeThree.fs TypeTwo.fs Program.fs TypeOne.fs

c:\temp\ConsoleApplication1\ConsoleApplication1\Program.fs(4,1): error FS0222: Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.
On close inspection of the command line you will see that TypeOne.fs appears after program.fs even though in the ui, TypeOne,fs is at the top and program.fs is at the bottom

![qh1w8cd](https://cloud.githubusercontent.com/assets/5175830/5906460/9dc445ee-a54c-11e4-9388-d8b31da792bf.png)

comments

>ovatsus wrote Jun 28, 2014 at 11:35 AM [x] 
>I get this all the time. I copy paste a file to create a new one, and half the times things won't compile until I unload and load the project again and fix the ordering.

**Comment by forki** [comment] 2015-01-26 19:17
I have similar issues with right click + "add existing file".

**Comment by rojepp** [comment] 2015-02-23 23:20
I seem to be completely unable to get EnableOpenSource.vsix running on my machine today, so just some notes here. I'm fairly sure this is caused by [handling just one file](https://github.com/Microsoft/visualfsharp/blob/fsharp4/vsintegration/src/vs/FsPkgs/FSharp.Project/FS/Project.fs#L987). Indeed, I can not repro when there is one file instead of three. 

A simple change like below might work (files may need to be reversed)
```fsharp
                addFilesNotification <- Some(fun files -> 
                    for absoluteFileName in files do
                        let relativeFileName = PackageUtilities.MakeRelativeIfRooted(absoluteFileName, fshProjNode.BaseURI)
                        move relativeFileName)
```

**Comment by enricosada** [comment] 2015-04-22 07:37
i'll try to fix this bug, assign it to me (or to you @latkin as usual :smile: )

**Comment by enricosada** [comment] 2015-04-22 16:26
fix #104 

smaller repro:

- create a project
- copy 3 files ( File1.fs, File2.fs, File3.fs ) 
- select project node
- paste
- now on video is

![image](https://cloud.githubusercontent.com/assets/147243/7279518/d97acc48-e91c-11e4-84d4-e0c2452cb4c7.png)

- click save on project node
- the msbuild is
```xml
    <Compile Include="File2.fs" />
    <Compile Include="File3.fs" />
    <Compile Include="Program.fs" />
    <None Include="App.config" />
    <Compile Include="File1.fs" />
```

**Closed** 2015-04-27 20:57 UTC
Labels: bug, fixed

**Comment by xenoputtss** [comment] 2016-01-21 19:37
I am currently getting this issue.  I am using VS2015.

To Reproduce my issue i am able to do this
start with a a project with 3 files.  Select one of them in solution explorer and copy/paste (should create a "copy of selected file" file)  rearrange files how you think the should be.  Build.

**Comment by tjaskula** [comment] 2016-06-06 22:19
Hi, I have the same problem in VS2015.

**Comment by mariomeyrelles** [comment] 2017-03-23 22:49
I also had this problem using VS2017 today. I copied a file instead of adding the file...
