### ISSUE TITLE
Unused Value should not be shown on OR pattern matches

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#2935] opened 2017-04-28 05:35 UTC
![](http://i.imgur.com/1yNlNW0.png)

``` fsharp
    let removeComment (text:string) =
        let stripComment pos =
            let ln = text.Substring(0,pos).Trim() in printfn "%s" ln; ln
        match text.IndexOf "//", text.IndexOf "#" with
        | -1 , -1 -> text
        | -1,  p | p , -1 -> stripComment p
        | p1, p2 -> stripComment (min p1 p2) 
```

Unused values can be replaced with `_`, but both `p` bindings are necessary, if you remove one

![](http://i.imgur.com/ceOjvfO.png)

**Comment by vasily-kirichenko** [comment] 2017-04-28 07:12
![image](https://cloud.githubusercontent.com/assets/873919/25518105/1cfdceca-2bfb-11e7-80ad-3e2a9f89254c.png)

**Comment by vasily-kirichenko** [comment] 2017-04-28 17:02
Sorry, the sample above is not compilable. I'll debug a proper sample.

**Comment by vasily-kirichenko** [comment] 2017-04-28 17:15
I cannot reproduce it on current master:

![1](https://cloud.githubusercontent.com/assets/873919/25539282/2b278d84-2c4f-11e7-8cae-f44b57339cce.gif)

**Comment by cartermp** [comment] 2017-04-28 17:17
@cloudRoutine Is this fixed on master in your code?

**Comment by cloudRoutine** [comment] 2017-04-28 17:26
It's not happening for me anymore, so maybe it's just another one of the phantom errors that seem to start up when VS has been running too long. Errors stay in the buffer despite builds completing successfully, opens are reported as unused when they're being used, simplify name appears on fully qualified types and modules. 

I haven't been reporting them because I haven't been able to produce any repros, but these issues definitely keep happening 😑

**Comment by cartermp** [comment] 2017-04-28 17:27
Okay, closing for now.

**Closed by cartermp** 2017-04-28 17:27 UTC
Labels: Area-IDE Language Service, bug, Urgency-Soon
