### ISSUE TITLE
Operators starting with '|' ignore indentation, except for (|>) 

### ISSUE THREAD

**Issue by aqtq314** [Microsoft/visualfsharp#403] opened 2015-05-01 17:19 UTC
Define
```F#
let inline ( |>! ) a f = f a; a
```
```text
val inline ( |>! ) : a:'a -> f:('a -> unit) -> 'a
```
Then
```F#
match Some () with
| Some () -> true
| None -> false
|>! printfn "#### %b"
```
```
#### true
val it : bool = true
```
```F#
match Some () with
| Some () ->
    true
| None ->
    false
|>! printfn "#### %b"
```
```
val it : bool = true
```
Note that the second case doesn’t print “#### true”

However, the same problem doesn't arise with the ( |> ) operator
```F#
match Some () with
| Some () ->
    true
| None ->
    false
|> fun b -> printfn "#### %b" b; b
```
```
#### true
val it : bool = true
```

**Comment by latkin** [comment] 2015-05-01 18:08
Duplicate of #120, this is by-design

**Closed by latkin** 2015-05-01 18:08 UTC
