### ISSUE TITLE
Add type annotations as code lens

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2368] opened 2017-02-03 23:54 UTC
This is a feature request.

The type annotations displayed above value definitions in VS Code is really useful:
![image](https://cloud.githubusercontent.com/assets/64654/22612912/cbba8178-ea6b-11e6-8a38-c6ab2a2b4977.png)

It would be great if we could utilise the 'code lens' feature of Visual Studio, as shown below:
![image](https://cloud.githubusercontent.com/assets/64654/22612943/f7b48e72-ea6b-11e6-9c7e-f51ff004f3d7.png)

I'm not sure how difficult this would be to add, but I'm under the impression that the code lens code is available on Roslyn:
https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Features/CSharp/Portable/CodeLens/CSharpCodeLensDisplayInfoService.cs

**Comment by vasily-kirichenko** [comment] 2017-02-04 06:43
I looked at it earlier, the problem is that the API is ISyntaxNode based, which we don't support.

**Comment by vasily-kirichenko** [comment] 2017-02-04 06:45
(BTW, I personally don't like the ionide feature - too much noise)

**Comment by forki** [comment] 2017-02-04 08:34
The signature feature is amazing. I really love it.

**Comment by vasily-kirichenko** [comment] 2017-02-04 08:42
@forki go ahead :)

**Comment by forki** [comment] 2017-02-04 08:47
No I don't love it that much ;-)

**Comment by saul** [comment] 2017-02-04 09:01
Obviously if it was to be implemented we'd need to give the option to disable it in the settings.

**Comment by cartermp** [comment] 2017-02-04 18:11
I'm not sure how best to approach this - from what I understand, the CodeLens APIs themselves are closed source, so I believe that there is first a dependency on making them open.  I can try to reach out to the people who own that area to see how feasible it would be to open them up so that the F# community can start implementing things like this feature request.

In terms of specifically making CodeLens show type signatures, I agree that it's a cool thing and also agree that it ought to be toggled.  I'm not too sure about making it on by default, though.  It's a somewhat divisive feature, and a lot of care would have to go in to making sure that it isn't too "jumpy".  I know @Krzysztof-Cieslak had to do some work here and may be able to offer some advice on that.

**Comment by vasily-kirichenko** [comment] 2017-02-04 18:52
Type signatures in Ionide as "jumpy" as before. It makes the feature even less enjoyable.

**Comment by cartermp** [comment] 2017-02-04 19:18
Right, and I would say that if it were implemented, it should be _off_ by default until a non-jumpy implementation could get implemented.

**Comment by cartermp** [comment] 2017-02-04 19:18
All of this would be preceded by proper support for configurability, though.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-04 19:58
I've fixed some performance issue we had in FSAC with finding locations of CodeLenses  but it doesn't remove "jumpy effect" completely (and it wouldn't be problem here since smarter people than me would implement it anyway :) )

I believe the core problem with "jumpy effect" right now is the fact that:
1. FCS'  `parseResults.GetNavigationItems().Declarations` seems to return empty list if the file is in not-parseable state (what makes sense)
2. I don't have control over how often VSCode ask for CodeLenses location [what may or may not be issue in VS, depending on how API looks like]

I'm pretty sure "jumpy effect" can be eliminated by providing stale results (either with empty CodeLens [it would at least keep position, so editor won't remove those additional lines] or with also stale signatures)

**Comment by realvictorprm** [comment] 2017-04-23 18:25
I would like to give it a try. I talked with @cloudRoutine about some implementation details which need to be tested. If something works out I'll report it here.

**Comment by vasily-kirichenko** [comment] 2017-04-23 19:00
@realvictorprm I tried to find a way to add an adornment that can be inserted between lines and failed. Maybe you will be more lucky.

**Comment by realvictorprm** [comment] 2017-04-24 18:40
@vasily-kirichenko I managed to achieve this.
![image](https://cloud.githubusercontent.com/assets/25414896/25353009/2960c818-292e-11e7-90c0-53f556c64daf.png)

The lines are being made bigger and a suitable adornment is added 😃 !

**Comment by cloudRoutine** [comment] 2017-04-24 18:42
cc @JoshVarty

**Comment by realvictorprm** [comment] 2017-04-24 18:45
Btw, where should I start adding the stuff?`
Any suggestions?

**Comment by vasily-kirichenko** [comment] 2017-04-24 19:03
@realvictorprm I think `QuickInfo` folder in `FSharp.Editor` project is OK for now. However, maybe it's better to add a new `CodeLense` folder. Yeah, it may be better. As you wish.

**Comment by vasily-kirichenko** [comment] 2017-04-24 19:04
And yes, it's absolutely awesome :) Make a PR as soon as possible so we all could review and help with it.

**Comment by cartermp** [comment] 2017-04-24 19:04
A new CodeLens folder would probably be best.  If you have the latest nightly, it should be easy to add folders.  This looks really cool!

**Comment by vasily-kirichenko** [comment] 2017-04-24 19:06
BTW, I think we will be able to make the signatures colored (unlike Code ;)

**Comment by realvictorprm** [comment] 2017-04-24 19:09
Everything is possible. It's a simple TextBox 😄 @vasily-kirichenko

**Comment by cartermp** [comment] 2017-04-24 19:10
I, for one, would love rainbow colors in the signatures.

**Comment by cloudRoutine** [comment] 2017-04-24 19:11
@vasily-kirichenko we definitely can, this is what I was telling you we could do the other day. Instead of using a textbox we could use a stack panel and have generalized mechanism for additional contextual information that can expand above or below any particular line. It could be for errors, inline evaluation, VCS metadata, etc.

**Comment by realvictorprm** [comment] 2017-04-24 20:49
You can assign me to the issue (whoever is allowed to)

**Comment by cartermp** [comment] 2017-04-24 21:14
@realvictorprm Interestingly enough, I cannot assign you here (though I can assign @saul, so the limitation does not appear to be organization-specific).

**Comment by realvictorprm** [comment] 2017-04-24 21:16
What a bummer 😕 @cartermp 
Any Idea why?

**Comment by cartermp** [comment] 2017-04-24 22:02
Yup, looks like you can be assigned to the PR, just not the issue.  I think it's a quirk with GitHub:
![assign-people](https://cloud.githubusercontent.com/assets/6309070/25360691/089875ce-28ff-11e7-9a23-c8386f60a3eb.gif)

**Comment by realvictorprm** [comment] 2017-04-25 19:58
Look here fellows:
https://github.com/realvictorprm/VisualFSharpCodeLens/

I made a small repo for the current working state. I wasn't able yet to integrate it tough.

**Comment by vasily-kirichenko** [comment] 2017-04-25 20:28
wow, wow, wow. Don't use checkFileResults.PartialAssemblySignature.Entities, use checkFileResults.GetAllUsesOfAllSymbolsInFile instead.

**Comment by realvictorprm** [comment] 2017-04-25 20:30
Haha thanks finally someone who tells me what could be improved.
@vasily-kirichenko I wasn't fine with that too :wink: but with what you suggest I couldn't come up yet with a solution. I'll try it now again 😄

**Comment by vasily-kirichenko** [comment] 2017-04-25 20:36
:) GetProjectOptionsFromScript is a heavy operation, cache FSharpOptions for now (VFT does cache already, so it won't be a problem as merge it into the main repo)

**Comment by realvictorprm** [comment] 2017-04-25 20:37
hmm, no I don't see a way using GetAllUsesOfAllSymbolsInFile @vasily-kirichenko 
I tried it today for a couple of hours too but I didn't got the correct type name results.

okay I'll cache that now. maybe performance will go up with this 😄

**Comment by vasily-kirichenko** [comment] 2017-04-25 20:40
I'll try to fix the FCS part tomorrow and make a PR here.

**Comment by realvictorprm** [comment] 2017-04-25 20:41
how you mean? Don't worry I can take care of the stuff :wink:

**Comment by vasily-kirichenko** [comment] 2017-04-25 20:43
ok :)

**Comment by vasily-kirichenko** [comment] 2017-04-25 20:54
How Ionide does it: it asks for a tooltip for each symbol, then takes the first line from it and shows. We want to get structured text instead (as it does Quick Info) and format it.

**Comment by realvictorprm** [comment] 2017-04-25 20:55
Yeah I already thought about such approach too because the Quickinfo show the signature too.

**Comment by vasily-kirichenko** [comment] 2017-04-26 05:37
@realvictorprm I think we can (and should) port the logic used to format and colorize types used in fsi, see over here https://github.com/Microsoft/visualfsharp/blob/5b3688a91d13f5050cd89be594d939b816005426/src/fsharp/fsi/fsi.fs#L152

**Comment by realvictorprm** [comment] 2017-04-26 08:31
Just for showing other people the progress here too:
![Showcase](https://raw.githubusercontent.com/realvictorprm/VisualFSharpCodeLens/master/misc/CodeLensShowcase1.gif)

Okay, I'll look into it @vasily-kirichenko There's still some small bugs left in the code lens, e.g. members of types where the signature should be `int` but is `unit -> int` (which logically is correctly but we don't apply unit. I guess it's done internal)

**Comment by vasily-kirichenko** [comment] 2017-04-26 08:40
@realvictorprm Pull my PR please.

**Comment by realvictorprm** [comment] 2017-09-19 07:07
I consider to change my current PR to add only "sideways" Code-Lens similar to those recently added to Ionide. I think those could work without big problems.

**Comment by cartermp** [comment] 2018-06-29 21:48
This is now implemented, though experimental. Closing for posterity.

**Closed by cartermp** 2018-06-29 21:48 UTC
Labels: Area-IDE Language Service, Feature Request

**Comment by cartermp** [comment] 2018-08-09 15:46
@erlis If you use VS 15.8 Preview, you can turn it on via Settings > Text Editor > F#.

**Comment by toburger** [comment] 2018-08-23 06:51
Is there a way to disable the F# Language Service logging for this feature? I normally have the output window open (and the option "Show Output window when build starts" set) and it distracts quite a bit when working in the text editor and the logging kicks in.

Apart from that I like this feature! First it was a bit awkward to have the code lens on the right of the definition and changed it to be on top, but the editor window was jumping around while editing the source code and I changed it back to be on the right.

**Comment by cartermp** [comment] 2018-08-23 15:17
@toburger This is done in #5145 and tracked by #5188
