### ISSUE TITLE
Adding a breakpoint then debugging can cause it to become "unclickable"

### ISSUE THREAD

**Issue by EBrown8534** [Microsoft/visualfsharp#3828] opened 2017-10-26 13:06 UTC
I've recently noticed that breakpoints become "unclickable" in certain situations, and it looks like it's related to them binding to a larger scope (described in #3441). In some cases, if the breakpoint binds to a larger scope (basically, binds to a different line than set), then you debug, the breakpoint can *not* be removed after debugging by clicking on it, you either have to "Delete All Breakpoints", "Toggle Breakpoint" *within* it, or debug, hit the breakpoint, then delete it once hit.

#### Repro steps

Given the following code snippet:

    module BreakpointTest
    let swapMany els arr =
        seq {
            for i in 0..(Array.length arr - 1) ->
                match els |> List.tryFind (fun el ->
                    match el with
                    | (el1, el2) when el1 = i || el2 = i -> true
                    | _ -> false) with
                | Some (el1, el2) when el1 = i -> arr.[el2]
                | Some (el1, el2) when el2 = i -> arr.[el1]
                | _ -> arr.[i]
        }

If we try to set a breakpoint on line 5 (`match els |> List.tryFind`) it is set to line 4, and "begins" at the arrow:

![f issue 1 - image 1](https://user-images.githubusercontent.com/2687214/32054328-0f9473aa-ba2c-11e7-89d6-ff157365f37e.png)

We then begin debugging, the breakpoint does *not* appear to need to be hit. When debugging ends, we can no longer delete the breakpoint by selecting the red circle at the left, doing so adds a new breakpoint on all of line 4:

![f issue 1 - image 2](https://user-images.githubusercontent.com/2687214/32054372-2f79f4f6-ba2c-11e7-8d61-08976c1225a1.png)

When we delete this breakpoint, it only removes the new breakpoint.

#### Expected behavior

We should be able to delete the previous breakpoint without having to debug again, use the "Toggle Breakpoint" or "Delete All Breakpoints".

#### Actual behavior

The breakpoint enters a 'state' where it cannot be removed unless we begin debugging again, and delete it when it's hit, use the "Toggle Breakpoint" when *inside* the breakpoint, or "Delete All Breakpoints."

#### Known workarounds

Begin debugging again, then when the breakpoint is hit delete it;

OR

Use the "Delete All Breakpoints" command to remove it;

OR

Select "Toggle Breakpoint" when the cursor is within the breakpoint area;

#### Related information 

* Windows 10 Pro x64
* .NET Framework 4.5.2 / F# 4.4.1.0
* Visual Studio 2017 Update 4 (Version 15.4.0)
* Severity: minor/convenience

**Comment by cartermp** [comment] 2017-11-17 22:34
@EBrown8534 I cannot reproduce the breakpoint failing to be removed - can you try this on VS 2017 15.5 Preview 4?

**Comment by EBrown8534** [comment] 2017-11-29 19:06
@cartermp I can only reproduce on one PC, and I cannot upgrade for compatibility reasons, so I think it's probably safe to put this on hold for now. I'll comment (and ping) if I can reproduce with a newer version. Thanks! :)

**Comment by cartermp** [comment] 2018-02-14 04:36
@EBrown8534 I'll close this for now - please ping if you see it again and we can re-open

**Closed by cartermp** 2018-02-14 04:36 UTC
Labels: needs repro
