### ISSUE TITLE
FSI on Mac: "Cannot resolve method because the declaring type of the method [...] handle is generic.

### ISSUE THREAD

**Issue by aspnetde** [Microsoft/visualfsharp#3398] opened 2017-07-27 19:54 UTC
I am running into a crash with FSI on Mac, I can't work around. The same code that produces the crash works when compiled with Visual Studio (for Mac) as regular *.fs module. On Windows it also works with FSI.

#### Repro steps

Execute the following code with fsharpi on Mac:

```fsharp
open System

type DemoState = { Title : string }
type AppState = { Demo : DemoState }

type Store<'TState>() = 
    member this.Subscribe<'TSelection> (selector:Func<'TState, 'TSelection>) (callback:Action<'TSelection, 'TState>) =
        let c:obj * 'TState -> unit = fun (selection, state) -> callback.Invoke((selection :?> 'TSelection), state)
        let s:'TState -> obj = fun state -> (selector.Invoke state) :> obj
        
        let subscription = new Subscription<'TState>(this, c, s)
        
        subscription

and Subscription<'TState>(store:Store<'TState>, callback:obj * 'TState -> unit, selector:'TState -> obj) =
    let store = store
    member this.Callback = callback
    member this.Selector = selector

// Create the store instance
let store = Store()

// Add a subscription
let logSubscription (title:string) (state:AppState) =
    printfn "Title: %s" title
    printfn "State: %O" state

let selector = Func<AppState, string> (fun state -> state.Demo.Title)
let callback = Action<string, AppState> logSubscription

// And boom
store.Subscribe selector callback
```
#### Expected behavior

Not to fail.

#### Actual behavior

Failing with

```
System.ArgumentException: Cannot resolve method Subscription`1 Subscribe[TSelection](System.Func`2[TState,TSelection], System.Action`2[TSelection,TState]) because the declaring type of the method handle FSI_0002+Store`1[TState] is generic. Explicitly provide the declaring type to GetMethodFromHandle.
  at System.Reflection.MethodBase.GetMethodFromHandle (System.RuntimeMethodHandle handle) [0x00072] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Reflection.Emit.GenericTypeParameterBuilder.InternalResolve () [0x00019] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Reflection.Emit.TypeBuilderInstantiation.InternalResolve () [0x0001e] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Reflection.Emit.ConstructorOnTypeBuilderInst.RuntimeResolve () [0x00000] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at System.Reflection.Emit.ModuleBuilder.RuntimeResolve (System.Object obj) [0x00080] in <ffb99659fc1c47faa4d5f883014d08aa>:0
  at <StartupCode$FSI_0002>.$FSI_0002.main@ () [0x00044] in <0e5e3226a7764792a4247fc606b6c0f1>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <ffb99659fc1c47faa4d5f883014d08aa>:0
```
#### Known workarounds

I tracked it down to line 8 and 9. When called with

```fsharp
let c:obj * 'TState -> unit = fun (selection, state) -> ()
let s:'TState -> obj = fun state -> Object()
```
instead of
```fsharp
let c:obj * 'TState -> unit = fun (selection, state) -> callback.Invoke((selection :?> 'TSelection), state)
let s:'TState -> obj = fun state -> (selector.Invoke state) :> obj
```
it works.

#### Related information 

* macOS Sierra 10.12.5
* Mono 5.0.1.1 (2017-02/5077205) (64-bit)
* F# Interactive for F# 4.1
* When compiling in VS, working with `FSharp.Core` 4.2.1 and `System.ValueTuple` 4.3.1
* Tools: Visual Studio for Mac (7.0.1 (build 24)), Visual Studio Code (Version 1.14.2)

**Comment by 7sharp9** [comment] 2017-07-28 10:16
I can confirm its broken on OS X 10.12.6 and mono 5.4.0.123 too.

**Comment by forki** [comment] 2017-07-28 10:27
just for sake of completeness: tried it on master with windows fsi:

![image](https://user-images.githubusercontent.com/57396/28713626-1cde7282-7390-11e7-8c21-42a5e60891b1.png)

seems to work

**Comment by aspnetde** [comment] 2017-07-28 10:29
Just for the sake of not getting confused: It does. Just failing with FSI on Mac.

FSI on Win: OK
VS on Win: OK
VS for Mac: OK
FSI on Mac: NOT OK

**Comment by forki** [comment] 2017-07-28 10:31
@aspnetde yes. but @nosami thought it might be related to fact that mono often has new F# compiler.

anyway @nosami here is it with logRefEmitCalls enabled:

![image](https://user-images.githubusercontent.com/57396/28713716-966ce624-7390-11e7-8028-03c6e898d00c.png)

**Comment by nosami** [comment] 2017-07-28 10:33
@forki Thanks. This must be a bug with Mono's Reflection.Emit. I'll get it looked at.

**Comment by nosami** [comment] 2017-07-28 10:37
A little strange if it works on VS for Mac but not fsharpi though. VS for Mac uses FCS to compile whereas fsharpi is using fsharp/fsharp. Might just need fsharp/fsharp to be bumped in mono. Will check.

**Comment by forki** [comment] 2017-07-28 10:38
updated my comment with the full trace

**Comment by nosami** [comment] 2017-07-28 11:13
@aspnetde When you say it works on VS for Mac, you mean as a compiled exe, not via F# Interactive inside VS for Mac?

**Comment by nosami** [comment] 2017-07-28 11:21
I bumped F# to 4.1.24 in Mono 5.4.0.136 and the issue is still there.

**Comment by aspnetde** [comment] 2017-07-28 11:46
@nosami 

> When you say it works on VS for Mac, you mean as a compiled exe, not via F# Interactive inside VS for Mac?

Right. Doesn't matter if I run it against F# Interactive from command line, VS for Mac, or Visual Studio Code.

**Comment by nosami** [comment] 2017-07-28 12:33
Tested with mono 4.8.0.334 and it's working :(

**Comment by forki** [comment] 2017-07-28 12:36
mono is mono again.
I wished it would be duo.

**Comment by 7sharp9** [comment] 2017-07-28 12:37
fsharpi has never ever been stable on mono, that why I never use it.

**Comment by nosami** [comment] 2017-07-28 12:39
Each one of these Reflection.Emit bugs are getting regression tests added where there were none before. Unfortunately, fsharpi is the biggest source of Reflection.Emit bugs. The bugs are rarely seen by C# devs.

**Comment by nosami** [comment] 2017-07-28 12:40
Filed - https://bugzilla.xamarin.com/show_bug.cgi?id=58454

**Comment by aspnetde** [comment] 2017-07-28 12:40
As I am a C# dev by day, I have seen a lot of different bugs with 5.x. Have a whole Xamarin build system still downgraded to 4.8. Not the best release the world has seen ...

**Comment by forki** [comment] 2017-07-28 12:47
@nosami I would argue F# is not the source of the bugs. ;-)

**Comment by nosami** [comment] 2017-07-28 12:48
I didn't say that it was :) Just wanted to eliminate it before proceeding :)

**Comment by forki** [comment] 2017-07-28 12:49
> Unfortunately, fsharpi is the biggest source of Reflection.Emit bugs.

**Comment by nosami** [comment] 2017-07-28 12:51
Ah, I meant to say that fsharpi is probably the biggest consumer of the Reflection.Emit APIs

**Comment by cartermp** [comment] 2017-07-28 15:20
Closing in favor of the Mono bug.

**Closed by cartermp** 2017-07-28 15:20 UTC
