### ISSUE TITLE
IntelliSense doesn't pop up when calling constructor in dev15

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1708] opened 2016-11-04 17:46 UTC
1. Install dev15 rel or prerel with .NET Desktop, and create a new F# project.
2. **Type** the following into an F# script file:

```fsharp
let validateHello (s: string): Result<string, string> =
    if s.Contains("hello") then Ok(
```

Expected: IntelliSense which gives the name and type of the input, since it's specified to be a `string`.
Actual: No IntelliSense at all.

**Comment by OmarTawfik** [comment] 2016-11-04 19:02
@cartermp this is a duplicate of #1598

**Closed by OmarTawfik** 2016-11-04 19:02 UTC
Labels: Area-IDE Language Service
