### ISSUE TITLE
Right-click opens FSI window

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1972] opened 2016-12-09 05:01 UTC
1. Build a release build of the VS tools in latest master.
2. Install the release VSIX.
3. Right-click in a file.

![fsi-launch](https://cloud.githubusercontent.com/assets/6309070/21038310/6442d70c-bd89-11e6-8d6a-841302fa7cbe.gif)

**Comment by rojepp** [comment] 2016-12-09 16:18
Duplicate of #1313, so it happens in VS2015 too.

**Comment by cartermp** [comment] 2016-12-09 16:27
This was actually fixed between vs2015 Update 3 and dev15 Preview 4.  However this doesn't quite behave the same way as the Update 3 bug.

**Comment by cartermp** [comment] 2016-12-09 16:28
Also important to note that dev15 Preview 4 was using the old language service.

**Closed** 2016-12-13 22:00 UTC
Labels: Area-FSI, bug
