### ISSUE TITLE
Go to Definition is showing metadata instead actual F# code in a C# project that has a reference to a F# project.

### ISSUE THREAD

**Issue by TonyHenrique** [Microsoft/visualfsharp#4992] opened 2018-05-24 13:23 UTC
I have a C# and a Project Reference to an F# class library in @VisualStudio; On the C# code when I select a F# Type and press F12 it goes to the metadata view C# version of the F# Type instead of going to the Definition in the .fs file. When debugging, It goes to the .fs file correctly.

* Visual Studio 2017 Version 15.8.0 Preview 1.1

![1](https://user-images.githubusercontent.com/6307623/40488177-82639892-5f3c-11e8-8c7c-82c9ec98fa26.png)
![2](https://user-images.githubusercontent.com/6307623/40488185-86034646-5f3c-11e8-8cd3-06fb374446ea.png)
![3](https://user-images.githubusercontent.com/6307623/40488191-891f6f4e-5f3c-11e8-8b64-5e637dc266cd.png)

**Comment by cartermp** [comment] 2018-08-13 01:08
Closing as duplicate of #3497

**Closed by cartermp** 2018-08-13 01:08 UTC
