### ISSUE TITLE
Can't create WSDL TypeProvider in VS2015 Update 1

### ISSUE THREAD

**Issue by pottereric** [Microsoft/visualfsharp#753] opened 2015-12-02 13:43 UTC
I had a clean install of Windows 10 about a month ago on Windows 10. Yesterday I installed Update 1. 

Before the update, I had been unable to create WSDL type providers. I assumed this was becaue of issue 637. I tried to create one now that I had update 1 installed. 

When I tried to add a reference to Microsoft.FSharp.Data.TypeProviders from the extensions tab in the add references dialog, it could not be found.

I added Microsoft.FSharp.Data.TypeProviders from Nuget. But when I declare my type provider, I get the error that says "The type provider 'Microsoft.FSharp.Data.TypeProviders.DesignTime.DataProviders' reported an error: The .NET SDK 4.0 or 4.5 tools could not be foun".

**Comment by enricosada** [comment] 2015-12-02 16:21
duplicate of #749

**Comment by KevinRansom** [comment] 2015-12-03 03:00
This is not repro for me.   It shows up on all of my existing installs, and on two separate clean machine VS2015 only installs today.

On a clean VM, with VS2015 installed with update 1 applied.

I wonder how your machine got into the state where it wasn't installed?

![tp](https://cloud.githubusercontent.com/assets/5175830/11550621/57e97eda-9926-11e5-8739-57118584ff62.jpg)

**Comment by dsyme** [comment] 2015-12-03 10:06
@pottereric Could you look at the analysis of possible causes in https://github.com/Microsoft/visualfsharp/issues/749 and see what the state of your system is?

**Comment by dsyme** [comment] 2015-12-03 10:06
Closing as duplicate of #749

**Closed by dsyme** 2015-12-03 10:06 UTC
Labels: duplicate, not repro

**Comment by pottereric** [comment] 2015-12-03 14:07
I had a clean install of Windows 10 and Visual Studio 2015 shortly after VS2015 came out. I've been using it for my daily work ever since. Unfortunately, this makes it hard to know what changes I've made to the state of the machine. I was experianceing Issue #637 on this machine. I installed Update 1 on top of my VS2015 install. Now when I try to add a revernce to the TypeProviders dll, it doesn't appear. 

![typeprovidersissue](https://cloud.githubusercontent.com/assets/1797047/11562434/ee4247a2-999b-11e5-9c19-10a6cd2ea0d1.png)
 
Under HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319\AssemblyFoldersEx\F# 4.0 Type Providers, the value is "C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers\"

But the folder doesn't exist. This is what I have in C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0.

![notypeprovidersfolder](https://cloud.githubusercontent.com/assets/1797047/11562626/1bd2d0c8-999d-11e5-809f-b11ae0cf8d38.png)

**Comment by dsyme** [comment] 2015-12-03 15:00
@pottereric Could you add that info to #749 please? thanks

**Comment by pottereric** [comment] 2015-12-03 15:43
I moved it there.
