### ISSUE TITLE
VS 2019 Preview 3.0 F# Re-Format indentation on paste option removes all indentation.

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#6281] opened 2019-02-26 04:28 UTC
**Formatting edited by @cartermp**

Open or create an F# project, a console application will do. Ensure the Re-format indentation on paste option is enables in the F# settings of the text editor.

Cut or copy 2 or more lines of indented code, say from inside a function.  Then paste anywhere, including back over the still selected region that was copied.  All indentation is removed.

Turning off the F# Re-format indentation on paste option leave the indentation intact but of course doesn't then indent it correctly for the new location where it is pasted either.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/465378/vs-2019-preview-30-f-re-format-indentation-on-past.html
VSTS ticketId: 797946_
_These are the original issue comments:_

Visual Studio Feedback System on 2/21/2019, 11:53 PM (3 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

--

David on 2/22/2019, 04:24 AM (3 days ago): <p>Further clarification on how to reproduce this:<br><br>Drag select the lines from the left of the text editor (on the line numbers if enabled).  Ctrl+C to copy the current line without a selection or selecting a portion of text starting part way across a line doesn't exhibit this behaviour, it must be whole lines that are selected.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment] 2019-02-26 04:28
cc @saul any ideas here?

**Comment by realparadyne** [comment] 2019-02-28 14:34
I think you can close this.  The issue I was having was because I didn't know about this:

https://github.com/Microsoft/visualfsharp/pull/4702

The caret position is now critical to determining what indentation you end up with.  If you just cut some lines and paste directly back again the caret is left aligned for the paste.  Now I know what it is doing it looks like it is a good feature and not a bug!

**Closed** 2019-04-06 16:58 UTC
Labels: Resolution-Not Applicable
