### ISSUE TITLE
Type inference error with funny type variable names.

### ISSUE THREAD

**Issue by gmpl** [Microsoft/visualfsharp#731] opened 2015-11-18 18:31 UTC
I want to report this funny error:

     type Type =
        static member M1 v (h:'E1->_) = let f (t:^t) = (^t : (static member M2: _ -> _) v) in f Unchecked.defaultof<Type> h
        static member M2 (m:Choice<'T,'E1>) = fun (h:'E1 -> Choice<'T,'E2>) -> match m with Choice1Of2 v -> Choice1Of2 v | Choice2Of2 e -> h e

This gives:

    ~vs4DD6.fsx(3,48): error FS0001: Type mismatch. Expecting a
    'E1 -> 'a    
    but given a
    'E11 -> Choice<'T,'E2>    
    The type ''E1' does not match the type ''E10'

Which is funny because there is no mention of <code>'E10</code> nor <code>'E11</code> in the code. Where it came from?
I know there are million ways of workaround this, for instance inverting the order of the static members solves the issue but I thought it might be worth to investigate.

**Comment by radekm** [comment] 2015-11-18 19:10
> Where it came from?

Maybe compiler does some standardization apart before unification/constraint solving?

**Comment by dsyme** [comment] 2015-12-02 12:38
This is a ramification of various simplifications we make when presenting type information. See ``minimalStringOfTwoTypes`` here for example: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/NicePrint.fs#L1891.

It is corner-case enough that I will close this as by design. However I do believe it's (obviously) possible to improve the situation, and an experimental PR to do that would always be welcome.

**Closed by dsyme** 2015-12-02 12:38 UTC
