### ISSUE TITLE
"Unexpected no result" error when executing Async computation

### ISSUE THREAD

**Issue by stishkin** [Microsoft/visualfsharp#2720] opened 2017-03-28 21:22 UTC
Unfortunately I do not have much info on this issue. 
Just the following stack trace. This is intermittent issue, and I have no repro for this.

F# 4.1 compiler running on Mono mono-complete-4.6.2.7-0.xamarin.1.x86_64
OS: Redhat 7.2

> System.Exception: Unexpected no result
  at Microsoft.FSharp.Control.AsyncImpl+ResultCell`1[T].GrabResult () [0x0000b] in <58b0ca73904cf4daa745038373cab058>:0 
  at <StartupCode$FSharp-Core>.$Control+AsyncWaitAsyncWithTimeout@1822-3[T].Invoke (System.Boolean _arg2) [0x00004] in <58b0ca73904cf4daa745038373cab058>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+args@825-1[a,b].Invoke (a a) [0x00016] in <58b0ca73904cf4daa745038373cab058>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a] (Microsoft.FSharp.Control.AsyncBuilderImpl+AsyncImplResult`1[T] res) [0x0002d] in <58b0ca73904cf4daa745038373cab058>:0 
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a] (System.Threading.CancellationToken token, Microsoft.FSharp.Control.FSharpAsync`1[T] computation) [0x00029] in <58b0ca73904cf4daa745038373cab058>:0 
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a] (System.Threading.CancellationToken token, Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout) [0x00014] in <58b0ca73904cf4daa745038373cab058>:0 
  at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T] (Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout, Microsoft.FSharp.Core.FSharpOption`1[T] cancellationToken) [0x00071] in <58b0ca73904cf4daa745038373cab058>:0

**Comment by dsyme** [comment] 2017-03-29 18:27
@stishkin We will need a reliable repro for this I think

**Comment by blumu** [comment] 2017-04-04 19:19
It may be tricky for us to get a consistent repro. Would a crash dump be helpful maybe? @dsyme

**Comment by blumu** [comment] 2017-04-08 03:59
Repro details coming soon! :-)

**Comment by blumu** [comment] 2017-04-10 21:43
We were able to extract a repro. Kudos to @marina-p for coming up with it! So far we've only been able to repro on a specific version of Mono with both F#4.0 and F#4.1 (`Mono Stable 4.6.2.7/08fd525 Mon Nov 14 10:53:45 UTC 2016`) on a single core VM. It does not repro on mono running on Windows.

We found a workaround (which simplified our code at the same time), so we are not blocked by it. 
Perhaps it's just a Mono bug after all, it would be good to confirm. @dsyme 

Here is the smallest repro we could get:
```fsharp
/// Repro on RedHat Linux with Mono Stable 4.6.2.7/08fd525 Mon Nov 14 10:53:45 UTC 2016
/// with binary built with F#4.1 (Windows)
//  Steps: repeat following steps until it crashes
//   In one bash session run
//          pkill -9 -f mono ; mono bug3292.exe
//   In a second bash session run:
//          while true; echo sigstp; do pkill -f -TSTP mono && sleep 10 && pkill -CONT -f mono ; sleep 2; done
let rec waitForProcessExitAsync (instance: System.Diagnostics.Process) =
    async {
        if not instance.HasExited then
            try
                let! wait = Async.StartChild(Async.AwaitEvent(instance.Exited), 500)
                let! _ = wait
                return()
            with
            | :? System.TimeoutException ->
                return! waitForProcessExitAsync instance
    }

for i in Seq.initInfinite id do
    async {
        printfn "starting iteration %d - Launching child process" i
        use instance =
            let command, arg =
                match System.Environment.OSVersion.Platform with
                | System.PlatformID.Unix -> "sleep", "1"
                | _ -> "timeout",  "/t 1 /NOBREAK"
            new System.Diagnostics.Process(StartInfo =System.Diagnostics.ProcessStartInfo(command, arg))
        let r = instance.Start()
        do! waitForProcessExitAsync instance
    } |> Async.RunSynchronously
```
It can take a few minutes for it to crash, so be patient :-) On my machine it usually crashes after about 10-30 iterations.

Finally, I was not able to repro when making the following changes. (Either because the change is related to the root cause of the bug or because I was not patient enough to get to the crash.):
-  Replacing the recursive async in `waitForProcessExitAsync` by just a while loop (may be related to the fact that Mono [does not support tail calls](https://bugzilla.novell.com/show_bug.cgi?id=476785)
- Replacing `waitForProcessExitAsync` with just:
```fsharp
let rec waitForProcessExitAsync (instance:System.Diagnostics.Process) =
    async {
        if not instance.HasExited then
            do! Async.Sleep(500)
            return! waitForProcessExitAsync instance
    }
```    
(which is simpler but not quite the same as the initial version, where the polling stops as soon as the .Net event is signaled.)
- Removing the for loop and have a single call to `Process.Start`
- Instead of starting a child process with `System.Diagnostics.Process.Start`, creating a custom .Net Event and signal it after a timeout period.
- Using a different version of Mono

**Comment by dsyme** [comment] 2017-06-22 16:37
@blumu Thanks for looking into this in such detail. I'm not sure what to do here - Historically Mono has had bugs that affect async, but there are no known remaining bugs in this area Mono 5.x.  

I think I will close this since it only affects a particular verion of Mono.  If it is still having problems with Mono 5.x then please add a bug in the Mono bug tracking system and reopen this bug here?

thanks again!

**Closed by dsyme** 2017-06-22 16:37 UTC
Labels: Need More Info

**Comment by blumu** [comment] 2017-06-23 20:47
OK. (We have not seen this issue again since we've upgraded to a more recent version of Mono.)
