### ISSUE TITLE
Intellisense tooltips fail to display anything after a while

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#5230] opened 2018-06-22 20:57 UTC
If you keep iterating through Intellisense options, at some point the tooltips become empty.
Example:
![image](https://user-images.githubusercontent.com/1631157/41798724-c425fe7a-763c-11e8-9794-7e8dbe45d850.png)
Keep scrolling with the up/down keys or the mouse, waiting for the tooltip each time.
Eventually...
![image](https://user-images.githubusercontent.com/1631157/41798787-fa32f3c4-763c-11e8-83ab-2f3d8838afcf.png)
The tooltip appears empty.

This seems random but easy to reproduce. Only takes me ~10 tries to reproduce usually.

Visual Studio 2017 Enteprise
15.7.4
F# Tools 10.1 for F# 4.1 15.7.0.0

**Comment by cartermp** [comment] 2018-06-22 21:03
Thanks for the report. Closing as a duplicate of #4714. This is fixed and available in nightlies today, and will be available when 15.8 ships.

**Closed by cartermp** 2018-06-22 21:03 UTC
