### ISSUE TITLE
Immediate VS2017 15.8.2 crash when going to Options > F# > Advanced, with "A TwoWay or OneWayToSource binding cannot work on the read-only property IsOutliningEnabled of type ... AdvancedOptions"

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5144] opened 2018-06-08 11:54 UTC
Going to Tools > Options > Editor > F# > Advanced crashes Visual Studio immediately.

![image](https://user-images.githubusercontent.com/16015770/41155883-f7d2f8e0-6b1f-11e8-8c1b-a26a9b9d91ef.png)

Debugging it shows the following exception:

> System.InvalidOperationException: 'A TwoWay or OneWayToSource binding cannot work on the read-only property 'IsOutliningEnabled' of type 'Microsoft.VisualStudio.FSharp.Editor.AdvancedOptions'.'

![image](https://user-images.githubusercontent.com/16015770/41155919-116a2e18-6b20-11e8-88d2-6bc9321c56d1.png)

### Repro steps

After updating my Preview instance from 15.7.x to 15.8.2 Preview, going over the options, it just immediately crashed. I restarted with most extensions disabled, but the same happened.

* Regardless of whether there's a solution open or not
* Go to Tools > Options
* Open Editor > F#
* Click "Advanced"
* BOOM!

### Expected behavior

Visual Studio should not crash when going through the Options dialog.

### Actual behavior

A crash as described above. After I loaded symbols and started VS with debugger attached, the exception changed (strange):

![image](https://user-images.githubusercontent.com/16015770/41156403-06ee5ec6-6b22-11e8-8033-4ba2081ac00c.png)

Even when I set the debugger to break on InvalidOperationException, it doesn't do so, it just comes up with the message above. The stack isn't very useful either:

![image](https://user-images.githubusercontent.com/16015770/41156491-624eecae-6b22-11e8-9cc8-70542cb3f226.png)

When I attach post-mortem, I see the error as mentioned above, but the stack shows up empty. It's odd that there's such difference.

In fact, I have no idea how to get more information, but hopefully someone here knows better :).

### Known workarounds

None, VS2017 completely crashes, no way to get to these settings in the Options dialog.

### Related information 

* Windows 7, all updates
* Visual Studio 2017 15.8.2 Preview

**Comment by majocha** [comment] 2018-06-08 12:43
Bad merge ate the CLIMutable attribute. It is fixed in nightlies, I think. Somehow the fix didn't make it to 15.8? #4941

**Comment by abelbraaksma** [comment] 2018-06-08 12:57
I searched on the error, didn't see it was already reported. Tx!

**Comment by cartermp** [comment] 2018-06-08 15:08
Closing as dupe of #4941

**Closed by cartermp** 2018-06-08 15:08 UTC
