### ISSUE TITLE
Visual F# Tools (nightly build) innoperative for source files.

### ISSUE THREAD

**Issue by ricardozimmer** [Microsoft/visualfsharp#5652] opened 2018-09-15 17:34 UTC
Please provide a succinct description of the issue.
****
VS Community latest update 2017 V 15.8.4  when using nightly build F# Tools. Looks similar to #5465 previously reported for 2017 V 15.7.6, but now, only for source files (.fs).  The editor doesn't get any color, and right side of the keyboard inoperative such as numpads, enter, backspace. I can type letters like aaaaaaa but no way to delete them. As far I can see, it works fine in scripts (.fsx). 
Uninstalling, works fine. 
* Operating system Windows 10
* Editing Tools (e.g. Visual Studio Version) 2017 Community 15.8.4

**Comment by TIHan** [comment] 2018-09-17 17:58
What's odd is that scripts work. Which nightly builds are you using?

**Comment by cartermp** [comment] 2018-09-17 18:15
I cannot reproduce the lack of any language service light-up, but on **15.8.20180917.1** installed into my 15.8.3 installation, only syntactic classification is kicked off in non-SDK-style projects in the VisualFSharp solution. SDK-style ones are fine.

So there's definitely an issue, at least with old-style project formats.

**Comment by ricardozimmer** [comment] 2018-09-18 18:13
The current version that works fine is 15.8.20180810.4
Problem kicks in with New Version 15.8.20180918.1.
I'm attaching 2 snapshots, one on a fsx file, and the second on a fs file on the next tab,  with New Version installed. 
 What else can I do to help?

![image](https://user-images.githubusercontent.com/16667821/45707281-d2052680-bb54-11e8-9111-c46d3b5a5103.png) (script file)

![image](https://user-images.githubusercontent.com/16667821/45707387-1690c200-bb55-11e8-84e2-c35e1f9462fb.png) (source file)

**Comment by cartermp** [comment] 2018-09-21 23:12
@ricardozimmer Thanks, this is enough information to proceed with a fix.

**Comment by ricardozimmer** [comment] 2018-09-28 05:42
@cartermp Got Version 15.8.20180926.2, and is working fine as far I can tell. Thanks.

**Comment by cartermp** [comment] 2018-09-28 07:46
Thanks @ricardozimmer, glad it's all fine for you! Closing this since #5687 is merged.

**Closed by cartermp** 2018-09-28 07:46 UTC
Labels: Area-IDE Language Service, Urgency-Soon
