### ISSUE TITLE
Fields annotated with LiteralAttribute no longer compile to literal fields in IL

### ISSUE THREAD

**Issue by krontogiannis** [Microsoft/visualfsharp#4688] opened 2018-04-05 10:05 UTC
After upgrading to VS2017 15.6.4 (issue persists in 15.6.5 and VS 2017 preview) fields annotated with the literal attribute no longer compile to IL literal fields. This leads to breaking builds.

#### Repro steps

1. Step A : Create a new project with just a Literal declaration:
```
module Foo

let [<Literal>] bar = "BAR"
```

2. Step B: Compile with Visual Studio 2017 15.6.4/15.6.5 and examine the IL:
```
.class public auto ansi abstract sealed Foo
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 07 00 00 00 00 00
	)
	// Fields
	.field public static string bar = "BAR"
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.LiteralAttribute::.ctor() = (
		01 00 00 00
	)
	.custom instance void [mscorlib]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggerBrowsableState) = (
		01 00 00 00 00 00 00 00
	)

} // end of class Foo
```

3. Compile with Visual Studio 2015
```
.class public auto ansi abstract sealed Foo
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 07 00 00 00 00 00
	)
	// Fields
	.field public static literal string bar = "BAR"
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.LiteralAttribute::.ctor() = (
		01 00 00 00
	)
	.custom instance void [mscorlib]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggerBrowsableState) = (
		01 00 00 00 00 00 00 00
	)

	// Methods
	.method private specialname rtspecialname static 
		void .cctor () cil managed 
	{
		// Method begins at RVA 0x2050
		// Code size 13 (0xd)
		.maxstack 8

		IL_0000: ldc.i4.0
		IL_0001: stsfld int32 '<StartupCode$Library1>.$Foo'::init@
		IL_0006: ldsfld int32 '<StartupCode$Library1>.$Foo'::init@
		IL_000b: pop
		IL_000c: ret
	} // end of method Foo::.cctor

} // end of class Foo
```

4. Optional: Reference the field from an attribute, in a new C# and F# project (while using the latest VS 2017)
This compiles fine.
```
module Lib2

open System.Reflection

[<assembly: AssemblyTitle(Foo.bar)>]
do ()

```

C# build breaks because `CS0182 | An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type`

```
[assembly: AssemblyTitle(Foo.bar)]
```

#### Expected behavior

Field should be annotated as a IL literal and be consumed properly by C# projects.

#### Actual behavior

Field does not compile as an IL literal.

#### Known workarounds

In general no, but in some cases you can work around this by refactoring your code (e.g. if you own both projects and makes sense to move the C# declarations in the F# project).

#### Related information 

Provide any related information 

* Operating system : Windows 10 Pro
* .NET Framework 4.7.02556
* Editing Tools : VS Enterprise 2017 15.6.5 / Microsoft Visual F# Tools 10.1 for F# 4.1

**Comment by abelbraaksma** [comment] 2018-04-05 21:12
I believe this is the same as #4617, and was resolved through #4519. This can happen if you run the preview edition on the same machine as the production release of VS 2017, because parts are still shared between editions (see discussion my issue #4617, as @KevinRansom mentions there, this will be fixed soon, probably in 15.8). 

The issue with the `LiteralAttribute` not being compiled properly is fixed for Update 3. Once that comes out, you can install the Preview Update and your VS Ent edition should also be fixed.

Meanwhile the workaround is either to switch back, to not use the `LiteralAttribute` if you can avoid it, or compile with a commandline version that wasn't updated. Or just wait a few days, I believe it comes out any day now.

**Comment by KevinRansom** [comment] 2018-04-05 21:17
@abelbraaksma @krontogiannis fixed in the latest 15.7 preview 3, will definitely be fixed in 15.7 rtm.
Because we don't yet do sideby side compilers, just installing the latest 15.7 preview will fix it for your whole machine.  in 15.8 we plan to have fully side by side compilers too, at last. 


Kevin

**Comment by abelbraaksma** [comment] 2018-04-05 21:28
@KevinRansom, 15.6.5 just came out, if you have this bug from installing a Preview, would updating to a new RTM (in this case from 15.6.4 to 15.6.5) also resolve the issue?

 In other words, will the installer install _newer_ libraries (which would fix this), or only overwrite existing files if the version is higher (which I think would not fix this and will have us wait until Preview 3).

**Comment by KevinRansom** [comment] 2018-04-05 21:58
@abelbraaksma 
I'm not sure ... though probably not. Component upgrade is based on version number, and 15.7 is higher than 15.6.5.

We so need a side by side compiler.

**Comment by cartermp** [comment] 2018-04-08 08:46
Closing as dupe of #4519 - the workaround until Preview 3 of 15.7 is to not be using a Preview build of VS.

**Closed by cartermp** 2018-04-08 08:46 UTC
