### ISSUE TITLE
Various navigation bar bugs

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2132] opened 2016-12-30 12:35 UTC
I've found a few issues with the navigation bar implementation on master:

1. Properties with a getter and setter are shown twice (once for the setter, once for the getter)
2. Private values are shown as methods as opposed to private fields
3. Methods do not show the parameters list as they do in C#

### Demonstration of issue 1
![sketch 24](https://cloud.githubusercontent.com/assets/64654/21565135/15f78732-ce8c-11e6-836d-9ff634f950bc.png)

### Demonstration of issue 2
![sketch 25](https://cloud.githubusercontent.com/assets/64654/21565141/1a7b7b24-ce8c-11e6-8ca9-ee0f84c4b8b1.png)

### Issue 3: example of parameter list as in C#
![sketch](https://cloud.githubusercontent.com/assets/64654/21565156/662ec35a-ce8c-11e6-8ce5-3d6ecfaaab26.png)

/cc @vasily-kirichenko

**Comment by cartermp** [comment] 2016-12-30 17:28
Confirmed all three.  I think that the first two are bugs.  The latter is more of a feature request IMO.

**Comment by cartermp** [comment] 2016-12-30 17:49
I noticed another interesting issue.  Given the following code:

```fs
type MyClass() =
    let mutable value = "hello"

    let tupleize x y = (x, y)

    member this.TurnIntoTuple(x: string, y: int) = tupleize x y

    member private this.Whatever() = ()

    member this.MyProperty
        with get() = value
        and set(s) = value <- s
```

`value` is being treated as a method, and `tupleize ` is being treated as a constant.  That classification is being assigned in ServiceNavigation: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/ServiceNavigation.fs#L82

**Comment by saul** [comment] 2016-12-30 18:44
Out of interest - do we not have any tests for NavigationImpl? If not it seems like a simple thing to write tests for.

**Comment by vasily-kirichenko** [comment] 2016-12-30 19:15
We have a single test in VFPT https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/tests/FSharp.Editing.Tests/NavigableItemsCollectorTests.fs#L46, I think it'd be great to port it to this repo and add some more tests.

**Comment by cartermp** [comment] 2016-12-30 19:19
Agreed, this could be quite helpful.

**Comment by vasily-kirichenko** [comment] 2016-12-30 19:37
Ah, sorry, wrong test in my message. We reuse the implementation that's available in FCS (was written by @7sharp9 if I'm correct) and is used in XS. So, no tests I think.

About three duplicates for properties, it's expected because AST contains one node for property itself, one for getter and one for setter. I think this piece of code may be helpful in fixing the bug: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/ServiceParseTreeWalk.fs#L418-L454

About method signatures, it's not a simple thing to implement. We could try to use quick info (toolpips) for this, as we did in VFPT for Quick Info Panel, but what we did there was just getting the first line from the tooltip + some simple filtering. 

About the glyphs, it should be fixed.

**Comment by cartermp** [comment] 2016-12-30 21:52
@vasily-kirichenko Hmmm, interesting.  I wonder if there's a way to special-case the fact that the AST has a node for both the getter and setter just for the navigation service?

**Comment by saul** [comment] 2016-12-31 10:50
Maybe take a look at refactoring Tests.LanguageService.NavigationBar.fs? They look relevant and have been disabled since Roslyn move.

**Comment by vasily-kirichenko** [comment] 2016-12-31 13:34
@saul The old navbar calls the same ast traversing code https://github.com/Microsoft/visualfsharp/blob/efde2a8758b3f35e6637cd1d63d7aa370129d2af/src/fsharp/vs/ServiceNavigation.fs#L403

**Comment by cartermp** [comment] 2017-01-01 17:49
Modified to `urgency-later`, since the actionable item here, in terms of what can feasibly be done between now and release, is the Glyph change.

**Comment by cartermp** [comment] 2017-01-06 19:33
Method signatures is a bigger feature that'll have to come in a VS 2017 update.

**Comment by saul** [comment] 2017-01-06 19:34
@cartermp I suggest closing the issue and we can have a discussion about the feature request in future. The bugs in this issue have been resolved

**Comment by cartermp** [comment] 2017-01-06 19:44
Sounds good.

**Closed by cartermp** 2017-01-06 19:44 UTC
Labels: Area-IDE Language Service, bug, Urgency-Later
