### ISSUE TITLE
Make intellisense/navigation work across languages 

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1661] opened 2016-10-26 08:07 UTC
One of the most important features to get F# adopted is to make F#/C# integration work properly - just as if you would only use C#.
With the latest roslyn changes in this repo, I'd like to know where we are standing with this and what the plan for this is.

**Comment by dsyme** [comment] 2017-05-09 19:55
Duplicate of  https://github.com/Microsoft/visualfsharp/issues/1939

**Closed by dsyme** 2017-05-09 19:55 UTC
Labels: discussion
