### ISSUE TITLE
Unneccessary boxing when type is constrained to be a reference type

### ISSUE THREAD

**Issue by Liminiens** [Microsoft/visualfsharp#6042] opened 2018-12-20 10:30 UTC
#### Repro steps
Define the active pattern below.

```
let (|DefaultArg|) def obj = 
      match obj with
      | null -> def
      | _ -> obj
```

`obj` is constrained to be a reference type

#### Expected behavior

`obj` is compared to null directly

```
IL_0000: ldarg.1      // obj
IL_0001: brfalse.s    IL_0005

IL_0003: br.s         IL_0007

IL_0005: ldarg.0      // def
IL_0006: ret

IL_0007: ldarg.1      // obj
IL_0008: ret
```

#### Actual behavior

```
IL_0000: ldarg.1      // obj
IL_0001: box          !!0/*a*/ -- unneccessary boxing
IL_0006: brfalse.s    IL_000a

IL_0008: br.s         IL_000c

IL_000a: ldarg.0      // def
IL_000b: ret

IL_000c: ldarg.1      // obj
IL_000d: ret
```

#### Provide any related information 

* .NET Core 2.2.200

**Comment by gsomix** [comment] 2018-12-20 16:23
@Liminiens 

https://stackoverflow.com/questions/4475576/why-the-compiler-emits-box-instructions-to-compare-instances-of-a-reference-type

**Comment by cartermp** [comment] 2018-12-20 17:53
Closing as by design. Thanks for the link @gsomix

**Closed by cartermp** 2018-12-20 17:53 UTC
Labels: Resolution-By Design
