### ISSUE TITLE
FSC : error FS0193: Could not find file 'D:\project\[GUID].dll' after update to 15.7.1 

### ISSUE THREAD

**Issue by fbehrens** [Microsoft/visualfsharp#4872] opened 2018-05-10 09:35 UTC
update to version 15.7.1 (community)  broke my build with: 
```
FSC : error FS0193: Could not find file 'D:\scripts2dev\libwba\src\bayer\d060edca-6e61-4c41-beb4-6ab552a37386.dll' 
```
The `Guid` part is always another one on every run.

With `15.6.7` it is building.

Here is the [diagnostic output and fsproj](https://gist.github.com/fbehrens/9b668b62ca6777a5a0a2a35367fe6d33)

Any suggestions ?

**Comment by abk-x** [comment] 2018-05-10 09:41
Hi, this isn't a fix, but perhaps you can work around this issue by using the new fsproj format (the format you pasted looks like the old format)?

**Comment by fbehrens** [comment] 2018-05-10 09:54
Thanks, will try do that. 

As I only see manual conversion guides, I will try to create a new Project,  or is there a tool ?

**Comment by abk-x** [comment] 2018-05-10 09:54
You can use this I think, https://github.com/hvanbakel/CsprojToVs2017/, just rename your fsproj to csproj as the author hardcoded it for csproj.

**Comment by cartermp** [comment] 2018-05-10 14:54
Closing as duplicate of https://github.com/Microsoft/visualfsharp/issues/4795

There is no workaround, but a servicing fix with the fix for this particular issue will be underway.

**Closed by cartermp** 2018-05-10 14:54 UTC

**Comment by fbehrens** [comment] 2018-05-10 22:10
I have updated to `fsproj` to `vs17`-format und updated the [diagnostic output and fsproj](https://gist.github.com/fbehrens/9b668b62ca6777a5a0a2a35367fe6d33)

Still the same errors.
