### ISSUE TITLE
Can't Ctrl+RightArrow (Edit.MoveControlRight) past __. in Visual Studio 15.9.0

### ISSUE THREAD

**Issue by marklam** [Microsoft/visualfsharp#5908] opened 2018-11-15 15:11 UTC
Pressing Ctrl+RightArrow (bound to `Edit.MoveControlRight`) steps past words - until it reaches `__.` where it gets stuck

#### Repro steps

Create a new F# source file in Visual Studio
Paste the following
```F#
type X() =
    member __.ToString() = "No!"
```
Put the cursor at the top of the file and keep pressing [Ctrl] + → until you get to the `__.`
Press [Ctrl] + → lots more

#### Expected behavior

The cursor moves past `__.` to `ToString` and on to the end of the file

#### Actual behavior

The cursor gets stuck in front of the `__.`

#### Known workarounds

Use unmodified →

#### Related information 

* Windows 10
* VisualStudio.15.Release/15.9.0+28307.53
* Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
* very low severity, medium annoyance

**Comment by abelbraaksma** [comment] 2018-11-15 16:46
I can confirm that this is indeed a problem, I just updated to 15.9.0 and see the same issue. It only happens when going Ctrl+Right, not when going Ctrl + Left. Also, once the cursor is between the two underscores, it works normally.

**Comment by cartermp** [comment] 2018-11-15 16:52
Labeling this external for now, since we didn't make any changes in related areas for 15.9. @gundermanc any ideas? Repro code:

F# project of any variant

```fsharp
type C() =
    member __.Foo() = ()
```

I can reproduce this, but only in the F# editor. C# is fine. We haven

**Comment by marklam** [comment] 2018-11-15 17:04
It doesn't have to be `__.` 

This also does it at `__=`
```f#
let __= "" in __.Length
```

**Comment by gundermanc** [comment] 2018-11-16 18:18
@JPWilli @olegtk, is this related to multi-caret support?

**Comment by olegtk** [comment] 2018-11-16 19:13
I believe it's a known issue, Ctrl+RightArrow now uses text navigator extensibility point. @grabalon has more context

**Comment by grabalon** [comment] 2018-11-16 20:13
We're now using word definitions as provided by the language service. In the F# case it looks like we're bailing with the code here:
http://index/?query=AbstractVsTextViewFilter&rightProject=Microsoft.VisualStudio.LanguageServices&file=Implementation%5CAbstractVsTextViewFilter%602.cs&line=124

**Comment by cartermp** [comment] 2018-11-19 18:45
@grabalon Could you point us to the interface we need to implement if that's the case? I don't recall a change like this being asked of us, so we likely don't implement something.

**Comment by grabalon** [comment] 2018-11-19 20:15
The link above points to a call to IVsTextViewFilter.GetWordExtent(int iLine, int iIndex, uint dwFlags, TextSpan[] pSpan)

I'd suggest you start looking there.

**Comment by marklam** [comment] 2019-02-25 10:57
This looks ok on 16.0.0 preview 3

**Comment by cartermp** [comment] 2019-02-25 16:19
Thanks @marklam I'll close this out, but definitely report back if you notice it again

**Closed by cartermp** 2019-02-25 16:19 UTC
Labels: Area-External
