### ISSUE TITLE
Visual Studio Preview starts after a while to block in short intervals the UI when I write code in F# (doesn't try with C#)

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#6147] opened 2019-01-25 18:51 UTC
VSF_TYPE_MARKDOWNVisual Studio Preview starts after a while to block in short intervals the UI when I write code in F# (doesn't try with C#).
Sometime a Window with appears with the Text &quot;Please wait for an editor command to finish&quot;. Sometimes VS blocks without the Window. The Block are mostly between 1 and 5 sendonds and disappears, when I restart VS. But after a while the blocking starts again in relative short intervals.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/435700/visual-studio-preview-starts-after-a-while-to-bloc.html
VSTS ticketId: 777174_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment] 2019-01-25 18:52
Based on logs this is a xamarin project, but there were no diagnostics that could indicate a particular problem.

It could also just be the typical NGEN-still-doing-stuff on a relatively fresh installation, which does tend to slow a few things down from time to time. I'll close as no repro unless something specific comes up.

**Comment by DieselMeister** [comment] 2019-01-25 20:09
What do you need to do to get better information for you? The issue is present and very annoying. VS 2017 does work normal. I must use both in parallel, because VS 2019 is not able to debug and build f# Android archives. (but that's another issues). So I had VS 2017 to Debug, while the use of the Editor in VS 2019 is improved. But the upcoming stucking after a while using the editor is annoying.

So how can I give you better information for help.

**Comment by cartermp** [comment] 2019-01-25 22:03
Do you see it in non-Xamarin projects? We cannot reproduce this in our own repository, nor in other projects that use the older project file format.

**Comment by TIHan** [comment] 2019-01-29 22:16
@DieselMeister That issue sounds very annoying. It is hard for us to reproduce at the moment. Does this happen in new ConsoleApp projects? Only in Android projects? Or just your specific project?

**Comment by DieselMeister** [comment] 2019-01-30 07:41
Hi. I start to write on a F# Fable Application. I will report to you soon, if the issue is present.

**Comment by cartermp** [comment] 2019-01-30 07:52
@DieselMeister If it's possible to share the source, we can definitely investigate the problem.

**Comment by DieselMeister** [comment] 2019-02-17 13:00
I did not recognize the stucking any more with the latest (3.0) version on visual studio 2019 preview. The development run smoothly :)


So the ticket can be closed.

Thank a lot!

**Comment by cartermp** [comment] 2019-02-18 17:00
@DieselMeister Thanks, I'll close the issue. I don't think this one was actually us though 🙂. I believe the Xamarin tools may have had an issue that led to the frustrating UI delays, and it seems that has been resolved. Do ping back here if you notice again!

**Closed by cartermp** 2019-02-18 17:00 UTC
Labels: needs repro
