### ISSUE TITLE
Inherited interface with covariant parameter isn't compatible

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#5277] opened 2018-06-30 22:04 UTC
A simple repro by @vasily-kirichenko:
```csharp
public interface IMyInterface {}
public interface IMyBuilder<out T> where T : IMyInterface { }
```

```fsharp
type InterfaceImpl() = interface IMyInterface    
let x: IMyBuilder<IMyInterface> = Unchecked.defaultof<IMyBuilder<InterfaceImpl>> :> _
```

<img width="635" alt="screen shot 2018-07-01 at 16 01 05" src="https://user-images.githubusercontent.com/3923587/42134608-01cfc76c-7d48-11e8-9d39-645136008054.png">

The repro with types hierarchy it was initially reproduced on: [InheritedInterfaceIncompatible.zip](https://transfer.sh/Z2urz/InheritedInterfaceIncompatible.zip)

<img width="905" alt="screen shot 2018-07-01 at 00 37 54" src="https://user-images.githubusercontent.com/3923587/42129291-b94e3894-7cc9-11e8-96a2-059df89dde46.png">

**Comment by auduchinok** [comment] 2018-07-01 12:57
A simple repro by @vasily-kirichenko 
```csharp
public interface IMyInterface {}
public interface IMyBuilder<out T> where T : IMyInterface { }
```

```fsharp
type InterfaceImpl() = interface IMyInterface    
let x: IMyBuilder<IMyInterface> = Unchecked.defaultof<IMyBuilder<InterfaceImpl>> :> _
```

**Comment by vasily-kirichenko** [comment] 2018-07-01 13:07
I can reproduce it in VS 2015 as well.

**Comment by vasily-kirichenko** [comment] 2018-07-01 13:11
It's also reproduced if all the types are defined in F#, but it's understandable because F# does not support covariance:

![image](https://user-images.githubusercontent.com/873919/42134684-72f0a0b4-7d49-11e8-821c-cd284c833ae0.png)

**Comment by zpodlovics** [comment] 2018-07-01 23:13
"For generic type parameters, the out keyword specifies that the type parameter is covariant. You can use the out keyword in generic interfaces and delegates."

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-generic-modifier

**Comment by cartermp** [comment] 2018-08-30 15:40
Closing this in favor of the language suggestion for covariance/contravariance: https://github.com/fsharp/fslang-suggestions/issues/162

**Closed by cartermp** 2018-08-30 15:40 UTC
Labels: Area-Compiler
