### ISSUE TITLE
Latest nightly doesn't install

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#3152] opened 2017-05-29 22:02 UTC
![image](https://cloud.githubusercontent.com/assets/4236651/26562914/32df9d84-44cb-11e7-8a07-447a4b09bc5e.png)

**Comment by cartermp** [comment] 2017-05-29 22:04
FYI I saw this as well when I had the previous nightly installed.  Not sure what the exact repro steps are.  cc @brettfo

**Comment by 0x53A** [comment] 2017-05-29 22:11
I uninstalled F# and reinstalled it. Afterwards VS2017 crashed when opening a solution (Paket).

![image](https://cloud.githubusercontent.com/assets/4236651/26563032/6d866f3e-44cc-11e7-8f0a-6e9484ff8c4c.png)

I clicked on Debug and selected VS2015:
![image](https://cloud.githubusercontent.com/assets/4236651/26563035/7a545be0-44cc-11e7-83cc-7bb70ccd32e5.png)

![image](https://cloud.githubusercontent.com/assets/4236651/26563022/41a8b98a-44cc-11e7-813d-b29bb3853870.png)

**Comment by 0x53A** [comment] 2017-05-29 22:13
using the almighty dnSpy:

![image](https://cloud.githubusercontent.com/assets/4236651/26563050/b08f2f46-44cc-11e7-8a7d-e09a8dce3733.png)

![image](https://cloud.githubusercontent.com/assets/4236651/26563060/cb9538da-44cc-11e7-93c2-eb2b88a3a19b.png)

**Comment by cartermp** [comment] 2017-05-29 22:16
@brettfo Could this be related to the Roslyn refs update?  Seems like an issue with the language service.

@0x53A Even though Update 3 Preview 1 is broken-ish for F# right now (no completion), could you try the latest nightly with that Preview?  Trying to see if it's breaking because the nightlies have an underlying assumption about what's in box.

**Comment by 0x53A** [comment] 2017-05-29 22:38
@cartermp 

Well, VS 2017.3pre with nightly does not crash.

But the thing with Vs 2017.2 is, I installed the original version from the setup, NOT the nightly, and it crashes, so it seems the uninstall wasn't removing everything.

**Comment by cartermp** [comment] 2017-05-29 22:44
@0x53A Yes, it's a known issue.  @brettfo Is currently working on the fix (along with other fixes) and it should be in for Preview 2.

**Comment by 0x53A** [comment] 2017-05-29 22:53
I haven't been able to restore the non-preview instance to working.

Neither deinstalling it from the gui nor ``VSIXInstaller.exe /u:VisualFSharp`` helped, it still crashes on opening the paket solution.

I haven't yet tried a repair, because it is 00:50 here and I need to sleep. =)

Since this is "just" on my private computer, not on my work computer, I will just ignore it for now ...

Ping me if you need any logs or whatever.

**Comment by 0x53A** [comment] 2017-05-29 22:54
Ok I don't know what you did, but manually downloading https://dotnet.myget.org/feed/fsharp/package/vsix/VisualFSharp/15.4.1.17052902 and installing that seems to have fixed the issue, my VS 2015.2 (non preview instance) now works again.

**Comment by cartermp** [comment] 2017-05-29 22:55
Okay.  Thanks for investigating @0x53A.  We'll try and get the word out; even though the assumption with nightlies is that you can be broken from time to time, this one basically does lock people out of a good tools install.

**Comment by cartermp** [comment] 2017-05-29 23:02
https://twitter.com/_cartermp/status/869328082733219841

**Comment by realvictorprm** [comment] 2017-06-03 07:08
Is this still valid?

**Comment by cartermp** [comment] 2017-06-03 07:11
It looks like this may not be valid anymore.  I think were were some bad references in a series of nightlies that were reverted.  If nobody else can repro, this can be closed.

**Comment by realvictorprm** [comment] 2017-06-03 07:12
Good. I didn't hear of any problems the last days.

**Comment by cartermp** [comment] 2017-06-03 17:33
Closing this, as I can confirm that the latest nightlies install now.

**Closed by cartermp** 2017-06-03 17:33 UTC
Labels: Area-Setup, needs repro
