### ISSUE TITLE
CSC Async/Await State Machines Halt in FSI 4.1

### ISSUE THREAD

**Issue by chrnola** [Microsoft/visualfsharp#4354] opened 2018-02-14 15:32 UTC
#### Repro steps

1. Compile a C# library that exposes a function with async/await syntax sugar:
```
namespace ReproLib
{
    using System;
    using System.Threading.Tasks;

    public class Bug
    {
        public async Task<string> SleepsForABit()
        {
            await Task.Delay(TimeSpan.FromSeconds(5));
            return "Done waiting";
        }
    }
}
```

2. Load that compiled .dll in FSI and try to await the exposed task:

```
#r "ReproLib"

printfn "Sleeping, should wake in 5 seconds"

ReproLib.Bug().SleepsForABit()
|> Async.AwaitTask
|> Async.RunSynchronously
|> printfn "%s"

```

The attached solution should aid in reproducing the issue: [FsiBug.zip](https://github.com/Microsoft/visualfsharp/files/1724539/FsiBug.zip). Build and run the `ReproConsoleApp` and observe that it returns ("Done waiting"). Then run the included `Bug.fsx` through FSI and observe that it does *not* return.

#### Expected behavior

The script should sleep for 5 seconds and then print "Done waiting".

#### Actual behavior

Script prints "Sleeping, should wake in 5 seconds" but never does when run from FSI 4.1. However the script works as intended when run in FSI 14.0.23413.0.

#### Known workarounds

Compile with `FSC`.

Use an explicit ``async { ... }``:

    async { return! ReproLib.Bug().SleepsForABit() |> Async.AwaitTask } 
    |> Async.RunSynchronously

#### Related information 

* Operating system: Windows 10 Build 1709
* Branch: Nightly VSIX package 15.4.1.18021203
* Runtime: Full .NET Framework 4.7
* Editing Tools (e.g. Visual Studio Version): VS 2017 Enterprise

**Comment by 0x53A** [comment] 2018-02-14 16:30
The difference is the SynchronizationContext, and the deadlock can be reproduced in a C# WPF app.

ConsoleApp: no SynchronizationContext

FSI:

```

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> System.Threading.SynchronizationContext.Current
;;
val it : System.Threading.SynchronizationContext =
  System.Windows.Forms.WindowsFormsSynchronizationContext

> 
```

__So why does it deadlock?__

After the ``await``, it tries to go back to the previous context, if there was one. In FSI, it tries to go back to the Main-Thread.

BUT: The Main Thread is currently waiting for the Task to finish (``Async.RunSynchronously``).

So the Task waits for the main thread, the main thread waits for the Task.


__How can you fix it?__

```C#
await Task.Delay(TimeSpan.FromSeconds(5)).ConfigureAwait(false);
```

With ``ConfigureAwait(false)`` you say that you do __not__ need to go back to the previous context, instead it will execute in the ThreadPool. So no deadlock.

**Comment by chrnola** [comment] 2018-02-14 17:22
@0x53A Hey, thanks for the response!

However, I just tried adding `.ConfigureAwait(false)` and I'm still able to reproduce the deadlock in FSI. Also the fact that different versions of FSI yield different results leads me to believe that there's something else wrong here.

**Comment by dsyme** [comment] 2018-02-14 17:23
F# async does actually run the async on a new thread if RunSynchronously is blocking the UI thread. This can be done because F# async uses the "generator" model of async and so we get to know the execution context before we start the async.   However this doesn't apply to the async returned by AwaitTask - you have to use an async computation as follows:

```fsharp
#r "a.dll"

printfn "Sleeping, should wake in 5 seconds"

async { return! ReproLib.Bug().SleepsForABit() |> Async.AwaitTask } 
|> Async.RunSynchronously
```

There's also the question of what exactly changed between F# 4.0 and 4.1....  I think it's that Async.AwaitTask doesn't use ConfigureAwait(false) for all task starts

**Comment by chrnola** [comment] 2018-02-14 18:25
Thanks @dsyme, adding the explicit async computation worked as described. 👍

**Comment by dsyme** [comment] 2018-02-21 14:46
OK, closing as by design

**Closed by dsyme** 2018-02-21 14:46 UTC
