### ISSUE TITLE
Erroneous warning FS1189 on syntax of explicit type parameters

### ISSUE THREAD

**Issue by drvink** [Microsoft/visualfsharp#396] opened 2015-04-30 19:40 UTC
The default implementations of `( *> )` and `( <* )` in CApplicative in the second file get blue squigglies: "Type parameters must be placed directly adjacent to the type name, e.g. "type C<'T>", not type "C   <'T>""

Functor.fs
```fsharp
#light "off"
module Functor

open System

let inline ``const`` x _ = x

type CFunctor = class
  static member inline fmap (f : ^a -> ^b, a : ^a list) = List.map f a
  static member inline fmap (f : ^a -> ^b, a : ^a option) =
    match a with
    | None -> None
    | Some x -> Some (f x)

  // default implementation of replace (aka <$)
  static member inline replace< ^a, ^b, ^c, ^d, ^e when
      ^a :> CFunctor and
      (^a or ^d) : (static member fmap : (^b -> ^c) * ^d -> ^e) >
      (a, f) =
    ((^a or ^d) :
      (static member fmap : (^b -> ^c) * ^d -> ^e) (``const`` a, f))

  // call overridden replace if present
  static member inline replace (a : ^a, f : ^b) =
    (^b : (static member replace : ^a * ^b -> ^c) (a, f))
end

module Impl = begin
  let inline replace_instance< ^a, ^b, ^c, ^d when
      (^a or ^c) : (static member replace : ^b * ^c -> ^d)>
      (a, f) =
    ((^a or ^c) : (static member replace : ^b * ^c -> ^d) (a, f))

  let inline fmap_instance< ^a, ^b, ^c, ^d, ^e when
      (^a or ^d) : (static member fmap : (^b -> ^c) * ^d -> ^e)>
      (f, a) =
    ((^a or ^d) : (static member fmap : (^b -> ^c) * ^d -> ^e) (f, a))
end
open Impl

let inline fmap f a = fmap_instance<CFunctor, _, _, _, _> (f, a)
/// aka <$
let inline replace a f = replace_instance<CFunctor, _, _, _> (a, f)

(*
type test(arg : string) = class
  member __.data = arg
  static member inline fmap (f : char -> char, a : test) = String.map f a.data
  static member inline replace (a : char, f : test) =
    test.fmap (``const`` a, f)
end

let _ =
  printfn "%A" <| fmap id [1;2;3];
  printfn "%A" <| replace 5 [1;2;3];
  printfn "%A" <| fmap ((+) 1) (Some 2);
  printfn "%A" <| replace 'q' (test("HI"))
 *)
```

Applicative.fs
```fsharp
#light "off"
module Applicative

open System

open Functor

type CApplicative = class
  // default implementation of *>
  static member inline ( *>)< ^a, ^b, ^c, ^d, ^e, ^f, ^g when
      ^a :> CApplicative
      and ^b :> CFunctor
      and (^a or ^c or ^d) : (static member (<*>) : (^f -> ^g) * ^d -> ^e)
      and (^b or ^c) : (static member replace : (^a -> ^a) * ^c -> (^f -> ^g))>
      (a : ^c, b : ^d) =
    ((^a or ^c or ^d) : (static member (<*>) : (^f -> ^g) * ^d -> ^e)
       ((^b or ^c) :
          (static member replace : (^a -> ^a) * ^c -> (^f -> ^g)) (id, a)), b)

  // call overridden *> if present
  static member inline ( *>) (a : ^a, b : ^b) =
    ((^a or ^b) : (static member ( *>) : ^a * ^b -> ^c) (a, b))

  // default <*
  static member inline (<*)< ^a, ^b, ^c, ^d, ^e, ^f, ^g, ^h when
      ^a :> CApplicative
      and ^b :> CFunctor
      and ^b : (static member fmap
                    : (^c -> (^a -> ^c)) * (^a -> ^c) -> (^g -> ^h))
      and (^a or ^d) : (static member (<*>)
                            : (^g -> ^h) * ^d -> (^f -> ^a -> ^e))>
      (a : (^a -> ^c), b : ^d) =
    ((^a or ^d) : (static member (<*>) : (^g -> ^h) * ^d -> (^f -> ^a -> ^e))
      ((^b : (static member fmap
                  : (^c -> (^a -> ^c)) * (^a -> ^c) -> (^g -> ^h))
                (``const``, a)), b))

  // call overridden <*
  static member inline (<*) (a : ^a, b : ^b) =
    ((^a or ^b) : (static member (<*) : ^a * ^b -> ^c) (a, b))
end

module Impl = begin
  let inline apply_instance< ^a, ^b, ^c, ^d, ^e when
      (^a or ^c or ^d) : (static member (<*>) : (^b -> ^c) * ^d -> ^e)>
      (a, b) =
    ((^a or ^c or ^d) : (static member (<*>) : (^b -> ^c) * ^d -> ^e) (a, b))

  let inline seqd1_instance< ^a, ^b, ^c when
      (^a or ^b or ^c) : (static member ( *>) : ^b * ^c -> ^c)> (a, b) =
    ((^a or ^b or ^c) : (static member ( *>) : ^b * ^c -> ^c) (a, b))

  let inline seqd2_instance< ^a, ^b, ^c when
      (^a or ^b or ^c) : (static member (<*) : ^b * ^c -> ^c)>
      (a, b) =
    ((^a or ^b or ^c) : (static member (<*) : ^b * ^c -> ^c) (a, b))

  let inline pure_instance< ^a, ^b, ^c when
      (^a or ^b) : (static member ``pure`` : ^b -> ^c)> a =
    ((^a or ^b) : (static member ``pure`` : ^b -> ^c) a)
end
open Impl

let inline (<*>) f a = apply_instance<CApplicative, _, _, _, _> (f, a)
let inline ( *>) a b = seqd1_instance<CApplicative, _, _> (a, b)
let inline (<*) a b = seqd2_instance<CApplicative, _, _> (a, b)
let inline ``pure`` a = pure_instance<CApplicative, _, _> a
let inline liftA f a = ``pure`` f <*> a
let inline liftA2 f a b = fmap f a <*> b
let inline liftA3 f a b c = fmap f a <*> b <*> c
```

**Comment by dsyme** [comment] 2015-05-01 17:33
Hi @drvink , could you minimize the repro for this?  (We should actually add a request "please work to minimize the repros" to [CONTRIBUTING.md](https://github.com/Microsoft/visualfsharp/blob/fsharp4/CONTRIBUTING.md) )

**Comment by dsyme** [comment] 2015-05-01 17:36
OK, well, I took a look anyway.  Can you try using this?

    static member inline ``*>``< ^a, ...

It seems to work ok.  If it works for you, we'll likely close this as by design and document it in the language spec.

**Comment by drvink** [comment] 2015-05-01 17:46
That seems to fix it.

**Closed** 2015-05-01 18:16 UTC
Labels: question
