### ISSUE TITLE
Wrong structure guideline for top level module

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3870] opened 2017-11-02 18:37 UTC
15.5. preview 2

![image](https://user-images.githubusercontent.com/873919/32343865-088cafc4-c016-11e7-9cf4-7b8aef84d0e5.png)

**Comment by cartermp** [comment] 2018-02-14 18:38
This appears to be a dupe of #4266 which has been fixed by the VS editor team

**Closed by cartermp** 2018-02-14 18:38 UTC
Labels: Area-IDE Language Service, Urgency-Soon, bug
