### ISSUE TITLE
VS2015: consuming Result type compiles, but fails at runtime

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#2566] opened 2017-03-09 12:36 UTC
The same code compiled with VS 2017 works.
![image](https://cloud.githubusercontent.com/assets/4236651/23750424/36be1fb8-04cd-11e7-8a98-e13dd256a851.png)

See how it tries to load FSharpResult from my own Assembly, not from FSharp.Core.

I don't think there is anything that can be done, just wanted to let you know because I couldn't find any information about this.

**Comment by vasily-kirichenko** [comment] 2017-03-09 15:13
I think it's because you are the very first person who uses Result at all :)

**Comment by KevinRansom** [comment] 2017-03-09 15:20
@0x53A 

FSharpResult is an FSharp 4.1 feature and requires the 4.1 version of the FSharp.Core.dll.  On VS 2015 the build will try to use the 4.0 compiler and FSharp.Core.  Which will result in the compiler not being able to find the type.

I hope this helps?

Kevin

**Comment by dsyme** [comment] 2017-03-09 17:36
Further, if you explicitly reference FSharp.Core 4.4.1.0 with F# 4.0 then it contains struct union types - which F# 4.0 will not understand.  

F# 4.0 won't give you a particularly good error message - indeed now I think about it you will probably just generate invalid code.  We didn't future proof F# 4.0 in this regard.

**Comment by 0x53A** [comment] 2017-03-09 18:07
Thats exactly what I did - I added FSharp.Core 4.4.1.0 via Nuget to VS2015 and compiled code consuming the struct union. It compiles but fails at runtime.

> F# 4.0 won't give you a particularly good error message - indeed now I think about it you will probably just generate invalid code. We didn't future proof F# 4.0 in this regard.

__I know why it happens, and I know there is nothing you can change, I just wanted to document it =)__


The big issue is, that currently our solution can be opened and successfully compiled with both VS 2015 and VS 2017, but VS 2015 will create invalid code. Even worse, if you first open VS2015, and compile the project, then open the solution with VS2017 and press debug, it won't rebuild (because the timestamps match) and launch with the invalid code.

In my case, this is not that big of an issue, we have a small team, and I can just tell everyone to move to VS2017. What would be even better would be if there was a way to prohibit compilation with VS 2015.

**Comment by dsyme** [comment] 2017-03-09 18:57
> IF I do not use any new features of F#4.1, is it safe to reference FSharp.Core 4.4.1.0 from fsc 4.0? I do not really need to use the Result type, it was just handy.

Yes, AFAIK

**Comment by KevinRansom** [comment] 2017-03-09 20:47
@0x53A ,  In order to reduce the problems identifying new and old features, you can use the multi-targeting feature to compile against FSharp.Core.dll v4.0.  This won't protect you against new language features like struct tuples, records and unions, because that is a really hard problem to solve.

<img width="893" alt="screen shot 2017-03-09 at 2 39 34 pm" src="https://cloud.githubusercontent.com/assets/5175830/23770026/07674758-04d7-11e7-84bc-087228b511b3.png">

Let me know if you have any other issues.

**Comment by 0x53A** [comment] 2017-03-09 20:59
@KevinRansom  I am hitting https://github.com/Microsoft/visualfsharp/issues/2399 , so if I want to compile with VS2017, i need to reference Core 4.4.1.0.

**Comment by KevinRansom** [comment] 2017-03-09 21:14
Bugger about #2399 .  Switching to VS2017 is a great choice.  I have to say I love what everyone has done.

**Comment by smoothdeveloper** [comment] 2017-03-09 23:00
@KevinRansom the problem with multi-targetting is that it is tied to which `FSharp.Core` version you'll end up with, which leads to many headaches due to binding redirect issues.

The main reason most F# users relies on FSharp.Core from nuget.org and use paket is that they want the binding redirects issue to be taken care automatically.

**Comment by dsyme** [comment] 2017-03-14 13:21
Closing as by design (somewhat unfortunately, but the past is hard to change)

**Closed by dsyme** 2017-03-14 13:21 UTC
