### ISSUE TITLE
[VS 15.6 RTW] alt-up/down arrows do not reposition file for legacy projects

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4405] opened 2018-02-28 00:15 UTC
VS 15.6 preview6

1. Create a .NET Framework-based F# project
2. Alt+up/Alt+Down on a file (`Program.fs`)

**Expected:** files move up/down
**Actual:** They don't

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/204016/vs-156-preview6-alt-updown-arrows-do-not-repositio.html
VSTS ticketId: 572477_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment] 2018-02-28 00:18
It's unclear if this is something we can adjust here, in dotnet-project-system, or in the VS editor itself. Either way, the root of the issue is that we assigned hotkeys to .NET Core SDK-based projects for Alt+Up/Alt+Down. This apparently removed the cability from legacy projects because you can only have one key binding per editor context.

**Comment by TIHan** [comment] 2018-02-28 00:40
We have a possible solution to this.

We need to create an interface that we export an implementation to execute the legacy VisualFSharp commands for MoveUp/Down. This interface will live in VisualFSharp.

Using COM definitions, we can have the same interface in dotnet/project-system and get an instance through MEF. With this instance, we can execute the legacy MoveUp/Down once we see a hierarchy that is not CPS based.

**Comment by cartermp** [comment] 2018-02-28 16:58
Labeling and adding to the 15.6 milestone. This won't block the release since we're so soon to shipping, but we're going to target a servicing fix.

**Comment by cartermp** [comment] 2018-03-09 02:30
This has been fixed in https://github.com/dotnet/project-system/pull/3331 and merged into a validation build. Servicing fix should be out fairly soon.

**Closed by cartermp** 2018-03-09 02:30 UTC
Labels: Area-IDE Project System, Urgency-Now
