### ISSUE TITLE
Assert This Must be called from the GUI Thread

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#5079] opened 2018-06-03 01:58 UTC
Debugging a debug build of F# in VS with an F# project loading.

![image](https://user-images.githubusercontent.com/5175830/40882428-766b8e80-6696-11e8-82bc-00ec1e118ff2.png)

Callstack:
````
>	FSharp.ProjectSystem.Base.dll!Microsoft.VisualStudio.FSharp.ProjectSystem.UIThread.MustBeCalledFromUIThread() Line 53	C#
 	FSharp.ProjectSystem.Base.dll!Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectNode.SetupProjectGlobalPropertiesThatAllProjectSystemsMustSet() Line 3104	C#
 	FSharp.ProjectSystem.Base.dll!Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectNode.SetBuildProject(Microsoft.Build.Evaluation.Project newBuildProject) Line 3044	C#
 	FSharp.ProjectSystem.FSharp.dll!Microsoft.VisualStudio.FSharp.ProjectSystem.FSharpProjectNode.SetBuildProject(Microsoft.Build.Evaluation.Project newProj) Line 1391	F#
 	FSharp.ProjectSystem.Base.dll!Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectNode.BuildProject.set(Microsoft.Build.Evaluation.Project value) Line 1167	C#
 	FSharp.ProjectSystem.Base.dll!Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectFactory.PreCreateForOuter(System.IntPtr outerProjectIUnknown) Line 143	C#
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectFactoryBase.Microsoft.VisualStudio.Shell.Flavor.IVsAggregatableProjectFactoryCorrected.PreCreateForOuter(System.IntPtr outerProjectIUnknown, out System.IntPtr projectIUnknown)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	FSharp.ProjectSystem.Base.dll!Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectFactory.CreateProject(string fileName, string location, string name, uint flags, ref System.Guid projectGuid, out System.IntPtr project, out int canceled) Line 120	C#
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectFactoryBase.Microsoft.VisualStudio.Shell.Interop.IVsProjectFactory.CreateProject(string fileName, string location, string name, uint flags, ref System.Guid projectGuid, out System.IntPtr project, out int canceled)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.Packages.MRU.ExtensionMethods.TryOpenProject(Microsoft.VisualStudio.Shell.Interop.IVsSolution solution, string projectPath, System.Guid projectGuid)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.CodeContainerAccessManager.OpenLocalCodeContainerAsync(Microsoft.VisualStudio.Shell.CodeContainerManagement.CodeContainer codeContainer)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.VisualStudio.PlatformUI.MruItemOpenResult>.Start<Microsoft.VisualStudio.PlatformUI.CodeContainerAccessManager.<OpenLocalCodeContainerAsync>d__9>(ref Microsoft.VisualStudio.PlatformUI.CodeContainerAccessManager.<OpenLocalCodeContainerAsync>d__9 stateMachine)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.CodeContainerAccessManager.OpenLocalCodeContainerAsync(Microsoft.VisualStudio.Shell.CodeContainerManagement.CodeContainer codeContainer)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.CodeContainerAccessManager.OpenAsync(Microsoft.VisualStudio.Shell.CodeContainerManagement.CodeContainer codeContainer)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.VisualStudio.PlatformUI.MruItemOpenResult>.Start<Microsoft.VisualStudio.PlatformUI.CodeContainerAccessManager.<OpenAsync>d__6>(ref Microsoft.VisualStudio.PlatformUI.CodeContainerAccessManager.<OpenAsync>d__6 stateMachine)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.CodeContainerAccessManager.OpenAsync(Microsoft.VisualStudio.Shell.CodeContainerManagement.CodeContainer codeContainer)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.CodeContainerListViewModel.OnOpen.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.VisualStudio.PlatformUI.CodeContainerListViewModel.(ref Microsoft.VisualStudio.PlatformUI.CodeContainerListViewModel.<>c__DisplayClass22_0.<<OnOpen>b__0>d stateMachine)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.CodeContainerListViewModel.OnOpen.AnonymousMethod__0()	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob<Microsoft.VisualStudio.Threading.EmptyStruct>(System.Func<System.Threading.Tasks.Task> asyncMethod, Microsoft.VisualStudio.Threading.JoinableTask job)	Unknown
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync(System.Func<System.Threading.Tasks.Task> asyncMethod, bool synchronouslyBlocking, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions, System.Delegate entrypointOverride)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.CodeContainerListViewModel.OnOpen(Microsoft.VisualStudio.PlatformUI.CodeContainerViewModelBase codeContainerViewModel)	Unknown
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.CodeContainerViewModelBase..ctor.AnonymousMethod__0(object o)	Unknown
 	Microsoft.VisualStudio.Utilities.dll!Microsoft.VisualStudio.PlatformUI.DelegateCommand.Execute(object parameter)	Unknown
 	PresentationFramework.dll!MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource commandSource, bool userInitiated)	Unknown
 	PresentationFramework.dll!System.Windows.Controls.Primitives.ButtonBase.OnClick()	Unknown
 	PresentationFramework.dll!System.Windows.Controls.Button.OnClick()	Unknown
 	PresentationFramework.dll!System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs e)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnMouseLeftButtonUpThunk(object sender, System.Windows.Input.MouseButtonEventArgs e)	Unknown
 	PresentationCore.dll!System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate genericHandler, object genericTarget)	Unknown
 	PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)	Unknown
 	PresentationCore.dll!System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, System.Windows.RoutedEventArgs routedEventArgs)	Unknown
 	PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args, System.Windows.RoutedEvent newEvent)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.OnMouseUpThunk(object sender, System.Windows.Input.MouseButtonEventArgs e)	Unknown
 	PresentationCore.dll!System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate genericHandler, object genericTarget)	Unknown
 	PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)	Unknown
 	PresentationCore.dll!System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, System.Windows.RoutedEventArgs routedEventArgs)	Unknown
 	PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs args)	Unknown
 	PresentationCore.dll!System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs args, bool trusted)	Unknown
 	PresentationCore.dll!System.Windows.Input.InputManager.ProcessStagingArea()	Unknown
 	PresentationCore.dll!System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs input)	Unknown
 	PresentationCore.dll!System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport inputReport)	Unknown
 	PresentationCore.dll!System.Windows.Interop.HwndMouseInputProvider.ReportInput(System.IntPtr hwnd, System.Windows.Input.InputMode mode, int timestamp, System.Windows.Input.RawMouseActions actions, int x, int y, int wheel)	Unknown
 	PresentationCore.dll!System.Windows.Interop.HwndMouseInputProvider.FilterMessage(System.IntPtr hwnd, MS.Internal.Interop.WindowMessage msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	PresentationCore.dll!System.Windows.Interop.HwndSource.InputFilterMessage(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown

````

**Comment by cartermp** [comment] 2018-08-12 19:29
Dupe of #5296

**Closed by cartermp** 2018-08-12 19:29 UTC
