### ISSUE TITLE
If a statement raises multiple errors, the last is shown in the tooltip, but should be the first

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1978] opened 2016-12-09 16:16 UTC
Suppose a single statement raises multiple errors, then hovering over it will show the last error. This is often useless, since the last error is often caused by the previous one. Instead, the first error should be shown.

Here's the quiz: can you spot the error (don't read beyond this section and think for a moment how to fix the error based on the message)?

![Error tooltip](http://i.imgur.com/o5IXRti.png)

## Repro steps

Reproduction works with any statement that spawns more than one error on the same spot. Here's one such example (which actually caused me to raise an SO question that turned out to be entirely beside the point).

```
namespace Help
    open System

    type SomeAttribute() =
        inherit Attribute()

        new(t: Type) = SomeAttribute()

    type D = X

    module T =
        // hovering the next line shows the second error, not the first, 
        // which is the actual error that needs resolution
        [<Some(typeof<Help.D>)>]
        let TestAttribute x = x
```

## Expected behavior

First error should be shown, or all errors (related to the cursor position) should be shown.

## Actual behavior

The last error is shown that related to the cursor position.

## Known workarounds

Once you have found out that this is actually an issue, you need to teach yourself to always compile the solution prior to trying to resolving an error, esp. if the trivial response to a popup-error does not solve it. Once compiled you see the hidden earlier errors.

This can lead to a lot of wasting time during development. The tooltips are very helpful and speed up development _if accurate_, otherwise they have the adverse effect.

## Related information 

Tested with VS2015, Update 3, F# 4.0, but seen in previous versions of both VS and F# as well.

**Comment by vasily-kirichenko** [comment] 2016-12-09 17:05
Current master:

![image](https://cloud.githubusercontent.com/assets/873919/21057451/cfd46b36-be4a-11e6-8ead-7a9db102ed8f.png)

**Comment by abelbraaksma** [comment] 2016-12-09 17:09
@vasily-kirichenko , that looks promising. So in VS2017 (or just any VS with F# 4.1) will show both or all errors? That'd be great! My only (minor) gripe with it is that they are in reverse order, but having them both is a big win already.

**Comment by cartermp** [comment] 2016-12-09 17:44
I agree that reversing the _current_ ordering of the errors would be useful.  Perhaps some work could go into formatting them a bit more, too.

**Comment by vasily-kirichenko** [comment] 2016-12-09 17:50
We use `HashSet` here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/DocumentDiagnosticAnalyzer.fs#L76 which do not preserve ordering, it's likely the cause of the issue.

**Comment by vasily-kirichenko** [comment] 2016-12-09 18:08
I've removed the hashset and we return the errors in one order:

![image](https://cloud.githubusercontent.com/assets/873919/21059430/6800a926-be53-11e6-801a-40f82b80b390.png)

but they appear in the tooltip reversed:

![image](https://cloud.githubusercontent.com/assets/873919/21059452/9552ba0e-be53-11e6-8c61-af901df600e5.png)

**Comment by abelbraaksma** [comment] 2016-12-10 15:09
> but they appear in the tooltip reversed:

Maybe the tooltip renderer takes the list bottom-up, as if it is a queue (last-in-first-out)? Here's another repro that causes multiple errors on the same spot (in order, FS1114, FS1116, FS1118), where the middle one is actually a warning.

You can use it for testing if the order-issue is explicit for only one case or whether they are all in reverse order. Furthermore, with the warning in the middle, you can check if warnings go last (should they?), or don't popup at all if there are already errors too?

This example is also different in that you need to compile before you see the errors and the tooltips. Finally it is different in that it shows the first raised error in VS2015 as the actual error.

```
module Test =
    type SomeType =
        | Int of int64
        | Float of float

        static member MyEquals (x, other: SomeType) =
            float x = float other // FS1114

        static member inline op_Explicit(n: SomeType): float =  // FS1113, FS1116, FS1118. tooltip FS1113
            match n with
            | Int i -> float i
            | Float f -> f

        static member inline op_Explicit(n: SomeType): int64 =
            match n with
            | Int i ->  i
            | Float f -> int64 f

```

(taken from my earlier [bug report on inline member resolution here](https://github.com/Microsoft/visualfsharp/issues/1565))

**Comment by dsyme** [comment] 2017-05-09 23:10
This is fixed in master (AFAICS)

**Closed by dsyme** 2017-05-09 23:10 UTC
Labels: Area-IDE Language Service, Feature Request
