### ISSUE TITLE
Alt+Enter for "Execute in F# Interactive" doesn't work without a loaded solution

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3092] opened 2017-05-19 23:27 UTC
It appears that there is a regression in the VS Editor. A bug has been filed there, with this as a tracking bug for community members who cannot access our internal bug tracker for VS.

 **Old issue:**

Dupe from here: https://developercommunity.visualstudio.com/content/problem/58735/altenter-for-execute-in-f-interactive-doesnt-work.html

### Repro steps

1. Open Visual Studio.
2. Do not load a solution.
3. Load (or create) an FSX file.
4. Type in some code, select it, press Alt+Enter.

**Actual result:** nothing happens (status bar says "No quick actions available here").

**Expected result:** F# interactive window should open and the code sent there for execution.

### Additional info

The Alt+Enter shortcut is specified in Options -> Environment -> Keyboard with "Use in" = "Global" (see attached screenshot), and it does work as expected as long as a solution is loaded.

**Comment by JoshVarty** [comment] 2017-05-19 23:33
I'll look into this and try to see what's going on.

**Comment by cartermp** [comment] 2017-05-19 23:45
Thanks @JoshVarty!

**Comment by JoshVarty** [comment] 2017-05-20 01:02
I've confirmed that the FSharpEditorFactory is not being used to open these files, which explains why we're not getting Alt+Enter keybindings:

![image](https://cloud.githubusercontent.com/assets/1249087/26271614/1fc8bc64-3cbd-11e7-9f73-1fc3eaa9475f.png)

I don't think I'm going to be able to track down exactly why this is the case, but I'll take a look at this first thing Monday morning.

**Comment by KevinRansom** [comment] 2017-05-20 04:57
@JoshVarty 
Thanks mate

**Comment by JoshVarty** [comment] 2017-05-24 17:53
So I've looked into this a bit more and made the following observations:

### We have registered multiple editor factory GUIDs. 

`4EB7CCB7-4336-4FFD-B12B-396E9FD079A9` is declared [here](https://github.com/Microsoft/visualfsharp/blob/ba63403cb5898596c5e875a14ce22b33ef618c01/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L252). 
We're using this GUID [here](https://github.com/Microsoft/visualfsharp/blob/6f5b2c4d78ab386a1b03a65457bdc7f8561635d0/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L274-L279) which registers interest for various file extensions (`.fs`, `.fsi` etc.). However *there is no corresponding editor factory for this GUID*. It looks like perhaps we used to have an editor factory that was removed at some point.

`8a5aa6cf-46e3-4520-a70a-7393d15233e9` is declared [here](https://github.com/Microsoft/visualfsharp/blob/ba63403cb5898596c5e875a14ce22b33ef618c01/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L253). 
It's used to register our Alt+Enter keybindings [here](https://github.com/Microsoft/visualfsharp/blob/389f04f326a55d58111f2ca1b627b8736c3f0561/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L225-L226) and to register our editor factory [here](https://github.com/Microsoft/visualfsharp/blob/5f151a291ebb8aeeff0eb9c8388fa6efcd836e17/vsintegration/src/FSharp.ProjectSystem.Base/Project/FSharpEditorFactory.cs#L19-L24).

### Proposed Solution

1. Remove `8a5aa6cf-46e3-4520-a70a-7393d15233e9` and use `4EB7CCB7-4336-4FFD-B12B-396E9FD079A9` everywhere. `4EB7CCB7-4336-4FFD-B12B-396E9FD079A9` was in the codebase first, so it feels natural to prefer it.
2. Remove [this code](https://github.com/Microsoft/visualfsharp/blob/6f5b2c4d78ab386a1b03a65457bdc7f8561635d0/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L274-L279). We're doing the same thing in our editor factory.
3. Register interest in the file extensions explicitly in our `.pkgdef` similar to what Roslyn is doing [here](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/CSharp/Impl/CSharpPackageRegistration.pkgdef#L32-L33).
4. Register editor factory explicitly in our `.pkgdef` similar to what Roslyn is doing [here](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/CSharp/Impl/CSharpPackageRegistration.pkgdef#L24-L30). 

### Problems 
Unfortunately, when I make these changes locally I only get the correct behavior **after** I have loaded at least one solution with an F# project. 

I'm buried with other bugs for 15.3 so I won't be able to look into this issue until next week at the earliest.

**Comment by dsyme** [comment] 2017-05-25 15:51
@JoshVarty I followed your recipe and pushed a version of it here: https://github.com/Microsoft/visualfsharp/pull/3115. Is that what you meant? However I haven't tried it out, and don't know what the different entries are doing exactly

**Comment by JoshVarty** [comment] 2017-05-25 17:41
It seems close, but I pulled it down and it seems to have the same issue: If you open a `.fs` file without a solution you can't use Alt+Enter because the wrong editor factory is chosen. 

FWIW, you can see how VS is about to open the file by using `Open With...` and seeing which it has decided is the "Default" editor factory:
![image](http://i.imgur.com/TzBtfhi.gif)

**Comment by dsyme** [comment] 2017-06-06 20:06
@JoshVarty This stuff is beyond my skills :) I just copied what you had. 

Any idea on what to do next?

**Comment by dsyme** [comment] 2017-06-20 15:55
@cartermp Could you check the repro please when you get the chance? Going back to the original repro, I don't repro this with Nightly installed (I haven't tried without it installed).  F# Interactive Alt-Enter works OK for me

Perhaps I fiddled with my key bindings though,

**Comment by dsyme** [comment] 2017-06-20 15:56
(I reset my key bindings to "Default" and still couldn't repro
1. Start VS
2. Open an existing .fsx script
3. Highlight some text and hit Alt-Enter

**Comment by cartermp** [comment] 2017-06-23 22:02
I can reproduce this with Alt+Enter, but not with right-click+Execute in Interactive.

1. Start VS
2. Create new F# Script file (Script1.fsx)
3. Write some quick, basic code
4. Select all and Alt+Enter

**Comment by dsyme** [comment] 2017-06-26 15:45
@cartermp Still no repro for me.  What VS setup profile do you have installed?  And any other tools?

**Comment by cartermp** [comment] 2017-06-26 15:51
Default profile when installed - I don't have anything custom.

> And any other tools?

In this case, I also have Xamarin tools installed.  Perhaps that affected it?  This is on the latest servicing release of 15.2 (though I observed it prior to those servicing releases as well).

**Comment by dsyme** [comment] 2017-09-01 22:34
@cartermp I still can't repro this - I have 15.3.1 and the Xamarin tools

**Comment by cartermp** [comment] 2017-09-08 01:02
I can no longer repro this with 15.3.3 + Nightlies.  Yay!

**Comment by dsyme** [comment] 2017-09-08 09:38
Thanks for checking! :) 🍾

**Comment by toburger** [comment] 2017-12-18 11:04
With VS 15.5 Alt+Enter stopped working again when creating a blank F# script file (for both Stable and Nightlies). I don't know if it the regression is even older...
After saving the file, closing it and reopening it Alt+Enter works as expected.

**Comment by cartermp** [comment] 2017-12-18 17:26
I can reproduce this again in 15.6.1 + self-built VSIX.

**Comment by cartermp** [comment] 2017-12-18 17:27
I haven't the faintest idea how the editor picks the correct key binding, but I suspect this is related to the unused analyzer being triggered in code, thus triggering the lightbulb rather than sending to F# Interactive.

**Comment by KevinRansom** [comment] 2017-12-18 17:48
I see this too ..
If I have fsi window visible, it works fine.  If I have created an F# project it works fine.  But if I close fsi, shutdown and restart vs, then alt+ Enter doesn't work and gives a message "No quick Actions available here"  in the status bar.

Wierdly opening the fsi window, doesn't work ... but starting vs with the fsi window visible does work.

**Comment by Rickasaurus** [comment] 2017-12-19 22:44
Seems like this is still happening in 15.5.1, I have a fresh install and no Alt-Enter support (only tried fsx files so far).

**Comment by cartermp** [comment] 2018-01-29 23:03
See here: https://twitter.com/_cartermp/status/958112771387764736

This now does not work even if the FSI window is loaded.

Repro steps:

1. Open VS
2. Create new F# script file
3. Type some code like `let foo () = ()`
4. Alt+Enter and note that it triggers a code fix
5. Open F# Interactive window
6. Alt+Enter again and note that it still triggers the code fix

@olegtk, anyone on your end who could help us look into this? We haven't modified anything on our end for scripting or registering our editor in quite a long time. This was fixed a while back, but then regressed again despite no change on our end.

**Comment by olegtk** [comment] 2018-01-30 04:44
Oh no, did we break it again? :( Please route the bug to the editor. We need to add an integration test for this feature too to avoid breaking it.

**Comment by cartermp** [comment] 2018-01-30 05:15
@olegtk Done! https://devdiv.visualstudio.com/DevDiv/_workitems/edit/559474

(Not sure if the area path is 100% correct)

**Comment by TIHan** [comment] 2018-03-30 19:25
This has been resolved.

**Closed by TIHan** 2018-03-30 19:25 UTC
Labels: Area-External, Area-IDE FSI, Urgency-Soon, regression
