### ISSUE TITLE
Opening an .fsx file - also from C# projects or outside a project - should trigger an install of the Visual F# Tools

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#702] opened 2015-10-27 10:01 UTC
FAKE is an important build tool in the .NET ecosystem. Our company and many of our customers are using it to automate the build and deployment process. We always used VisualStudio to edit FAKE scripts and until VS2015 this worked with every Visual Studio installation out of the box.

Now in Visual Studio 2015 Visual F# is no longer part of a default installation (see https://github.com/Microsoft/visualfsharp/issues/544). In general it's a good idea to make VS install features on demand, but unfortunately it breaks our workflow here. While opening a F# project (`*.fsproj` files) triggers the installer, opeing `*.fsx` files does not. So if you have a VB or C#-only solution the installer will not be triggered - even if you have a FAKE build script (which is usally called `build.fsx`).

The solution for us would be to trigger the F# installer when VS 2015 detects a `*.fsx` in the solution. 
EDIT: I think triggering the installer when a `*.fsx` is opened would be enough.

Unfortunately I don't know of any other situation in VS where a similar situation is happening, but I assume if VS would unbundle C# and VB compilers then we would know very soon.

**Comment by Thorium** [comment] 2015-10-27 10:07
+1

**Comment by forki** [comment] 2015-10-27 10:32
> EDIT: I think triggering the installer when a *.fsx is opened would be enough.

It would probably also help @Thorium who does not have build.fsx added to sln.

**Comment by PsAccelerator** [comment] 2015-10-27 12:23
We have a solution with C# projects and use F# for scripting. After the team installed VS2015 the team got lost because they did not install F#. So please make this work.

**Comment by Mharlin** [comment] 2015-10-27 12:55
+1

**Comment by monkieboy** [comment] 2015-10-27 13:23
+1

**Comment by Slesa** [comment] 2015-10-27 14:17
+1

**Comment by Krishna-Desiraju** [comment] 2015-10-27 14:28
+1

**Comment by brase** [comment] 2015-10-27 14:38
+1

**Comment by matthid** [comment] 2015-10-27 14:42
+1

**Comment by vbfox** [comment] 2015-10-27 15:42
+1

**Comment by robertpi** [comment] 2015-10-27 15:52
+1

**Comment by pmiossec** [comment] 2015-10-27 21:06
+1

**Comment by jeroldhaas** [comment] 2015-10-28 21:08
+1

**Comment by KevinRansom** [comment] 2015-10-29 17:55
No that's not what is required.  There is already a feature request to the team that own the OOB setup feed to add support for install detection for File Open, but it is not yet approved.

@Thorium  F# can be installed from the command line and that will include the VS 2015 extensions.  The installer can be found here:  http://www.microsoft.com/en-us/download/details.aspx?id=48179

So have your installer or deployment script download and execute this program and all should be well.

I realize the VS componentization effort, increased some of the friction for usage of the components but a 16 GB full install of VS introduces a lot more friction.

Thanks

Kevin

**Comment by Thorium** [comment] 2015-10-29 18:14
Thanks @KevinRansom, there is very little documentation about this:

- To install this I assume I need admin rights to the command prompt? Currently my deployment script runs as a normal command prompt.
- Will that Tools package also include F#?
- What is FSharp_BundleLP.exe?
- Can that exe be downloaded from some static url or can the path change? This form tries to do a post-request, not get-request, so it hints that don't do a direct request from the deployment script.
- How do I detect in the command line if this package is needed or already installed?

**Comment by forki** [comment] 2015-10-29 19:40
It's a bit sad to hear that this is a "feature request" instead of a bug. Anyways cool to hear that this will get addressed eventually   ;-) 

@KevinRansom yes we all agree that a "lazy install VS" is the way to go. But introducing this completely untested (at least untested from community) and after the RC phase feels a bit like kick in the monads for people who evangelize F# every day. But we already discussed this. So thanks for logging this in the VS Installer bug tracker.

![tumblr_inline_nwfybcxtvp1raprkq_500](https://cloud.githubusercontent.com/assets/57396/10829943/3a4ef0bc-7e7d-11e5-9a60-a78a5b58f2eb.gif)

**Comment by dsyme** [comment] 2017-06-22 13:09
Duplicate of https://github.com/Microsoft/visualfsharp/issues/1040

**Closed by dsyme** 2017-06-22 13:09 UTC
Labels: Area-Setup, Feature Request
