### ISSUE TITLE
Spurious error message on building FSharp solution

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#3149] opened 2017-05-29 13:38 UTC
At the present time, if you successfully get build to run locally, opening up `FSharp.sln` in VS still shows the following error messages: -

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error loading lock file 'C:\Users\Isaac\Source\Repos\visualfsharp\src\fsharp\Fsc\project.lock.json' : Error reading '' at line 18434 column 24 : Unsupported type: SharedFramework				
Error		Error loading lock file 'C:\Users\Isaac\Source\Repos\visualfsharp\src\fsharp\FSharp.Core.Unittests\project.lock.json' : Error reading '' at line 18775 column 24 : Unsupported type: SharedFramework				
Error		Error loading lock file 'C:\Users\Isaac\Source\Repos\visualfsharp\src\fsharp\fsi\project.lock.json' : Error reading '' at line 18416 column 24 : Unsupported type: SharedFramework				
Error		Unable to resolve 'FSharp.Core.netcore (>= 1.0.0-rc)' for '.NETCoreApp,Version=v1.0 (osx.10.11-x64)'.				
Error		Unable to resolve 'FSharp.Core.netcore (>= 1.0.0-rc)' for '.NETCoreApp,Version=v1.0 (ubuntu.14.04-x64)'.				
Error		Unable to resolve 'FSharp.Core.netcore (>= 1.0.0-rc)' for '.NETCoreApp,Version=v1.0 (win7-x64)'.				
Error		Unable to resolve 'FSharp.Core.netcore (>= 1.0.0-rc)' for '.NETCoreApp,Version=v1.0 (win7-x86)'.				
Error		Unable to resolve 'FSharp.Core.netcore (>= 1.0.0-rc)' for '.NETCoreApp,Version=v1.0'.				
```

However, the solution still continues to "build" - you can compile and run unit tests.

**Comment by vasily-kirichenko** [comment] 2017-05-29 13:53
Duplicate of https://github.com/Microsoft/visualfsharp/issues/2425

**Closed** 2017-05-29 16:22 UTC
