### ISSUE TITLE
FSharp.Core netstandard 1.6 lib has broken forwarding

### ISSUE THREAD

**Issue by marek-safar** [Microsoft/visualfsharp#3481] opened 2017-08-21 21:46 UTC
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Download the 4.2.3 version of FSharp.Core

2. Inspect lib\netstandard1.6\FSharp.Core.dll

#### Expected behavior

Exported types have correct declaration and forward to types which exist

#### Actual behavior

It contains forwarders like

```
.class extern public forwarder System.AggregateException
{
  .assembly extern System.Runtime
}
```

which is wrong because such type does not exist in `System.Runtime` assembly but `System.Threading.Tasks` assembly instead. I guess this is due to https://github.com/Microsoft/visualfsharp/blob/68747e0dd0c88643bb1be52e126cd38731b6719e/src/fsharp/fsc.fs#L754 which needs to be updated to work with netstandard facades not just .net mscorlib.

Provide a description of the actual behaviour observed. 

#### Known workarounds

None

**Comment by dsyme** [comment] 2017-08-21 21:54
@KevinRansom That code should not be being used for .NET Core.  In particular, the ``--compiling-fslib-40`` flag should not be passed in except when compiling FSharp.Core for .NET Framework 4.x (i.e. for platforms that must be compatible with .NET Framework 2.0 FSharp.Core).

The flag is incorrectly added here: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/FSharp.Core.fsproj#L24

**Comment by matthid** [comment] 2017-08-21 22:05
Can someone clarify the impact of this, please?

**Comment by marek-safar** [comment] 2017-08-21 22:14
netstandard 1.6 is not .NET Core specific, see https://github.com/dotnet/standard/blob/master/docs/versions.md for various version which supports netstandard 1.6 (including .net 4.6.1)

**Comment by dsyme** [comment] 2017-08-21 22:17
@marek-safar Thanks, I updated my comment to indicate this is relevant to .NET Standard, not just .NET Core

@matthid I'd imagine we can udpate the nuget package pretty quickly

**Comment by dsyme** [comment] 2017-08-21 22:20
@KevinRansom See https://github.com/Microsoft/visualfsharp/pull/3482 for removing the flag.  Packages will need to be updated after validation

**Comment by cartermp** [comment] 2017-08-21 22:20
Is this also valid for previous versions of FSharp.Core that packages a netstandard dll (4.2.x)?  The file in question is far older than the last push to the package, so this has probably been in there for some time.

Also is this going to be present in the package that we'll eventually push that has a netstandard2.0 dll?

**Comment by matthid** [comment] 2017-08-21 22:58
@dsyme I was asking for the impact because of FAKE5 (I did not experience any failures but I'm still on 4.1.17 ...).

It reads as if this basically renders the package unusable for netcore. Is that correct?

**Comment by dsyme** [comment] 2017-08-22 09:05
> It reads as if this basically renders the package unusable for netcore. 

I doubt that very much. The repro doesn't have a concrete user-facing scenarios affected (though I assume one exists), and we test extensively using this DLL.  But I'd imagine there are some situations where it causes a problem.

**Comment by matthid** [comment] 2017-08-22 10:03
@dsyme thanks for clarifying.

**Comment by KevinRansom** [comment] 2017-08-22 18:52
@marek-safar , @dsyme thanks for the report and the fix.  I don't think this would actually cause a problem, due to all of the forwarding, unification and facades that happens on the desktop CLR and coreclr.  However, the fix is a great improvement, and it is now technically correct.

**Comment by KevinRansom** [comment] 2017-08-22 18:53
Fixed with: https://github.com/Microsoft/visualfsharp/pull/3482

**Closed by KevinRansom** 2017-08-22 18:53 UTC

**Comment by dsyme** [comment] 2017-08-22 19:13
@marek-safar Did you just stumble across this when looking at the DLL, or did it cause a problem in practice?

@KevinRansom I could imagine it causing a problem for the compiler, if it tries to chase through the forwarder

**Comment by KevinRansom** [comment] 2017-08-22 19:44
These type forwarders are for Silverlight and FSharp.Core 2.0. compatability.  All other profiles would use the correct .net ref assembly version.

https://github.com/Microsoft/visualfsharp/blob/6ce962e97de24273d167b6c174344e3017a6e4c7/src/fsharp/FSharp.Core/control.fsi#L3

I believe a failing scenario would be:
So if you have an F# core 2.o library for example, that raises an AggregateException and it is referenced from a netstandard 1.6 F# core then the loader will I think fail with a type load exception for the aggregate exception throw or perhaps when jitting the catch.

I doubt if anyone is actually relying on this.

I expect we can lose both of these switches and all of this code, now that we longer actively support build or test  FSharp.Core 2.0.

Kevin

**Comment by marek-safar** [comment] 2017-08-22 21:47
@dsyme it was reported by one of our customer because one of our tool is crashing on invalid exported type (typeref points something what does not exist)

**Comment by KevinRansom** [comment] 2017-08-22 21:51
Tools have a habit of showing these types of thing.  Well it's fixed now.  Thanks for the report.

**Comment by dsyme** [comment] 2017-08-22 23:06
@marek-safar Likewise - thanks

**Comment by 7sharp9** [comment] 2017-08-30 15:10
This affects referencing any F# net standard libraries from a Xamarin iOS project.   It makes building an iOS project with any linking impossible on a real device and is quite a blocker.  

Is there a nugget with this available yet?

**Comment by 7sharp9** [comment] 2017-08-30 15:11
Repo here: https://github.com/7sharp9/linker_test

**Comment by dsyme** [comment] 2017-08-30 15:13
@7sharp9 What error do you get?

**Comment by 7sharp9** [comment] 2017-08-30 15:13
error MT2001: Could not link assemblies. Reason: Object reference not set to an instance of an object

**Comment by 7sharp9** [comment] 2017-08-30 15:15
I found this by reading from: https://bugzilla.xamarin.com/show_bug.cgi?id=58063#c10
I logged this myself today: https://bugzilla.xamarin.com/show_bug.cgi?id=59109

**Comment by dsyme** [comment] 2017-08-30 15:22
I can't access ``https://bugzilla.xamarin.com/show_bug.cgi?id=58063#c10`` (well, I probably can if I dig out my old bugzilla account)

Could you compile or install master and check that using the latest .NET Standard 1.6 FSHarp.Core resolves your issue?  Or I could send it to you in a zip, or grab it from CI

**Comment by dsyme** [comment] 2017-08-30 15:24
@7sharp9 A recent CI link is here: https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part2_windows_nt/593/artifact/release/net40/bin/

**Comment by dsyme** [comment] 2017-08-30 15:25
@7sharp9 I can well believe this is a cause of problems for the Mono linker - I'm just looking for early validation that the problem is fixed if we republish nugets

**Comment by 7sharp9** [comment] 2017-08-31 09:56
Im trying to reference FSharp.Core directly to confirm, the problem is the sdk seems to want to always use the nuget reference, except there isn't actually one present in my project file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FSharp.Core">
      <HintPath>..\..\..\Downloads\FSharp.Core.4.2.3\lib\netstandard1.6\FSharp.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

**Comment by 7sharp9** [comment] 2017-08-31 09:57
![screen shot 2017-08-31 at 10 50 21](https://user-images.githubusercontent.com/588746/29917840-1acf0784-8e3b-11e7-887a-014a1314adc2.png)

**Comment by 7sharp9** [comment] 2017-08-31 10:14
[59109 – Linker fails to link assemblies- Reason- Object reference not set to an instance of an object (MT2001) (linker copy.pdf](https://github.com/Microsoft/visualfsharp/files/1266694/59109.Linker.fails.to.link.assemblies-.Reason-.Object.reference.not.set.to.an.instance.of.an.object.MT2001.linker.copy.pdf)

**Comment by 7sharp9** [comment] 2017-08-31 10:15
@dsyme I uploaded my bugzilla issue, it was updated recently with issues found in the FSharp pdb output

**Comment by 7sharp9** [comment] 2017-08-31 10:29
It looks like two different issues with FSharp.Core, this one and the one in my bugzilla above.  Do you want me to log:
>the F# compiler is generating a scope with 1 constant, while there's zero constant in the constant table.
I can't be much help with the repo as Jb Evian was looking at it, I do have a link to the cecil patch though: https://github.com/jbevain/cecil/commit/22b36c3dc5dcc0ddba38164904a1b3daf02151e2

**Comment by dsyme** [comment] 2017-08-31 10:33
> the sdk must be implicitly adding an Fsharp.Core, I can't seen to find where this is happening though.

There's some way to disable this - either the targets or the F# .NET SDK tooling RFC  should reveal it - or @KevinRansom  can advise

> the F# compiler is generating a scope with 1 constant, while there's zero constant in the constant table.

I'm not sure - we'd need a repro - and JB can maybe advise if this should also be fixed in the F# compiler

**Comment by 7sharp9** [comment] 2017-08-31 10:59
```
<DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
```
That disable the implicit FSharp.Core

So with the FSharp.Core from CI and hitting the second cecil issue anyway with the invalid pdf file.

**Comment by 7sharp9** [comment] 2017-08-31 11:01
@jbevain RE: jbevain/cecil@22b36c3 is this something that the F# compiler needs to address?

**Comment by dsyme** [comment] 2017-08-31 16:16
@KevinRansom It looks like Xamarin will need a new FSharp.Core nuget package to fix this (fairly important) iOS bug

**Comment by jbevain** [comment] 2017-08-31 16:58
@7sharp9 @dsyme hello folks,

Even if we fixed the tooling, ideally yes, this should be fixed in the F# compiler.

The bug that Dave created has a simple F# repro project:

https://bugzilla.xamarin.com/show_bug.cgi?id=59109

For the method `mylib.Say.hello`, I see one LocalScope record (the only LocalScope record in the table):

```
Method RID: 1 (mylib.Say.hello)
Import RID: 0
VariableList: 1 (Computed range: Index 1, Length: 0)
ConstantList: 0 (Computed range: Index 0, Length 1)
ScopeStart: 0
ScopeLength: 28
```

The ConstantList should start at 1.

**Comment by jbevain** [comment] 2017-08-31 17:21
The spec is okay with zero index for *List, so I'd say just ignore that :)

**Comment by KevinRansom** [comment] 2017-09-01 01:06
@jbevain 

What is the ask here?

1. Publish an updated FSharp.Core ?
2. Do we need a fix for the pdb?

Thanks

Kevin

**Comment by jbevain** [comment] 2017-09-01 16:17
@KevinRansom no has I said I don't think F# has anything to do. The pattern used in the metadata is unusual (first time I've seen it in 13years), but valid :)

**Comment by KevinRansom** [comment] 2017-09-01 18:59
@jbevain That's good, because I thought I had followed the spec very closely (like ... exactly) on the portable pdb stuff.

**Comment by dsyme** [comment] 2017-09-01 22:39
@KevinRansom I think we still need a new FSharp.Core published.  @7sharp9 reported above that the Xamarin iOS linker is hitting a NulLReferenceException when it follows the dud type forwarders (the original topic of this bug). I don't think the linker has been patched for that.

The other problem with Portable PDB has been solved by @jbevain

**Comment by KevinRansom** [comment] 2017-09-01 22:41
Yes, I agree.

**Comment by KevinRansom** [comment] 2017-09-01 23:14
Okay,
I just cherry-picked the fix into vs2017-rtm
the build lab is down until Tuesday, I think they are making use of labor day to upgrade a ton of stuff.
So I will push an update to nuget when we get builds back.

**Comment by dsyme** [comment] 2017-09-01 23:15
👍 

@7sharp9 If you can do any further early end-to-end validation that these fixes are together adequate for Xamarin iOS that would be great!

**Comment by 7sharp9** [comment] 2017-09-04 12:08
I have a manual cecil patch on my machine so I can get by until theres an official Xamarin.iOS patch that includes the cecil fix.  

The NRE from bad forwarders was fixed in Xamarn.iOS 10.14.24 which I think is in the alpha channel now, thats what Im using anyway and I don't see anything untoward in the build output.
