### ISSUE TITLE
Coreclr does not support itanium --- fsc for coreclr says it does.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#2607] opened 2017-03-14 01:13 UTC
````
c:\kevinransom\visualfsharp\tests\testbin\release\coreclr\FSC>dotnet fsc.exe /?
Microsoft (R) F# Compiler version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.


                - OUTPUT FILES -
--platform:<string>                      Limit which platforms this code can run on: x86, Itanium, x64, anycpu32bitpreferred, or anycpu. The default is anycpu.
````

**Comment by dsyme** [comment] 2017-06-29 03:50
@KevinRansom I will close this as by design.  It is correct that the compiler flag accepts Itanium for the case where we are cross-targeting to .NET Framework.

**Closed by dsyme** 2017-06-29 03:50 UTC
Labels: Area-Compiler, bug, Urgency-Soon
