### ISSUE TITLE
printf family functions don't format System.Decimal precision correctly

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#945] opened 2016-02-08 07:16 UTC
``` fsharp
printfn "%.3f %.3f %.3M" 1.2345678 1.2345678f 1.2345678M
```

Expected: `1.235 1.235 1.235`
Actual: `1.235 1.235 1.2345678`

**Comment by manofstick** [comment] 2016-02-08 22:35
...but, possibly surprisingly, "f" also type-checks for Decimal, so 

    printfn "%.3f %.3f %.3f" 1.2345678 1.2345678f 1.2345678M

works "as expected" (kinda)

**Comment by dsyme** [comment] 2016-02-09 01:02
Looks fixable than

**Comment by CaptainPaellion** [comment] 2016-03-02 01:47
> // %M ignores precision
On the culprit line, It appears that this is intended behavior.

**Comment by vladima** [comment] 2016-03-02 17:50
AFAIR this was the behavior in original printf implementation and I've preserved it during rewrite.

**Comment by dsyme** [comment] 2016-11-14 18:25
I'm closing this as by design - it's always been this way and the behavior should just be documented.

**Closed by dsyme** 2016-11-14 18:25 UTC
Labels: Area-Library, bug, Urgency-Soon
