### ISSUE TITLE
Impossible to access extension methods on types with same name as union case, yet intellisense gets it right

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4700] opened 2018-04-08 01:35 UTC
If you have a type with extension methods and you have a discriminated union with the same case name, the compiler cannot resolve it, not even if you use a fully qualified name.

I may be unaware of some special syntax to help the compiler resolve this. But since cases cannot have extensions, it stands to reason that the compiler manages to resolve this.

### Repro steps

Take the following code:

```f#
namespace CaseSpace

type Case = Case1 | Case2 with
    static member WhatCase = 
        function 
        | Case1 -> "case 1" 
        | Case2 -> "case 2"

type Other = Case | SomeCase
type YetOther = Case | SomeCase
```

In another file use the following:

```f#
namespace NewNamespace

module Cases =
    open CaseSpace

    let foo x =
        match x with
        | Case.Case1 -> CaseSpace.Case.WhatCase x  // 'WhatCase' is not found, though Case.Case1 is
        | Case.Case2 -> CaseSpace.Case.WhatCase x
```

### Expected behavior

The code should compile without error.

### Actual behavior

The code doesn't compile and says that it cannot find the `WhatCase`:

> error FS0039: The field, constructor or member 'WhatCase' is not defined.

Note that there's an almost poetic discrepancy in the tooltip: the error is shown, as is the signature of the function. Whatever runs the tooltips seems smart enough to find the signature. See:

![image](https://user-images.githubusercontent.com/16015770/38461969-33c3bf50-3ade-11e8-8bc1-3ad00efc8694.png)

Note also that F12-go-to-definition works, as does clicking on the links in the tooltip.

### Known workarounds

In this particular simplified scenario, removing the namespace solves it. But if you have name collisions, that doesn't work and you will need the FQN.

The workaround to name collisions *should* be to use fully qualified names, but that doesn't work here.

In some cases it is possible to change the order of importing the namespaces (that is, remove some and use FQN's). But the real problem here is that fully-qualifying the names *does not help*. 

I hope I am missing something and that there is an actual workaround. Because seeing it in the dropdown, knowing it is there and then not being able to use it is extremely confusing and in situations where projects are very large, the culprit is hard to find or even impossible to take away.

I have a use-case where I have no possibility of accessing existing extension methods on the types because of this.

### Related information 

This may be tricky to fix, but since the algorithm works properly for name resolution in the compiler used by the tooltips and intellisense, I know it is possible. Perhaps that part of the algorithm can be copied to the compiler?

![image](https://user-images.githubusercontent.com/16015770/38461960-eccd5b38-3add-11e8-837c-651975e0e0e9.png)

Seen on VS2015 through to VS2017 latest editions until today.

**Comment by dsyme** [comment] 2018-04-12 13:52
@abelbraaksma This is by design and should be tracked by a language suggestion please

if you want to make a namespace that has both a union case and a type called `Case` you should use `RequireQualifiedAccess`, e.g.
```
module  CaseSpace

[<RequireQualifiedAccess>]
type Case = Case1 | Case2 with
    static member WhatCase = 
        function 
        | Case1 -> "case 1" 
        | Case2 -> "case 2"

[<RequireQualifiedAccess>]
type Other = Case | SomeCase

[<RequireQualifiedAccess>]
type YetOther = Case | SomeCase
```

The F# compiler could reasonably give you a warning in this case - please also add that to the language suggestion.  Another case where a warning could be given is this:
```
module  CaseSpace

type Case = Case1 | Case2 with
    static member WhatCase = 
        function 
        | Case1 -> "case 1" 
        | Case2 -> "case 2"

let Case = 1
```
Again, the `let Case` value definition takes precedence in name resolution.

**Comment by dsyme** [comment] 2018-04-12 13:52
@abelbraaksma Closing as by design - please add a link to the language suggestion, thanks

**Closed by dsyme** 2018-04-12 13:52 UTC

**Comment by abelbraaksma** [comment] 2018-04-12 16:44
@dsyme, I am sympathetic to this being _by design_, but then there's still a bug: the intellisense parser/compiler comes up with a different resolution and shows in the tooltip the signature from the DU name.

Furthermore, even without `RequireQualifiedAccess` (the name implies that it _requires_ qualified access, but I think in fact it means that it _allows_ qualified access?), shouldn't there be a way to resolve such names? 

It may not always be possible to change the original definitions (which happens to be the case here), and then these types and/or cases are lost forever?

**Comment by matthid** [comment] 2018-04-12 17:18
> the name implies that it requires qualified access, but I think in fact it means that it allows qualified access?

No the name is correct. Qualified access is always allowed, but you have just hidden the name so you cannot access it. Also the Color in your screenshot looks like a DU-Case not like a DU-Type ... Not sure what intellisense is doing there.

There are similar cases (like https://github.com/Microsoft/visualfsharp/issues/4426) and "by design" basically means according to spec. This most likely the case here as well (I know it is hard to read ;) ). I'm pretty sure the spec says something about bringing the "DU"-Cases into scope. This basically means that you cannot access other things above with the same name.

Maybe one more workaround could be to use SRTP to access the static method (obviously it is better to refactor the code or use the `RequireQualifiedAccess` attribute).

@dsyme What is the reasoning that `| Case.Case1` is working in the match? Is there a different name resolution strategy within matching?
This looks like there a bit of inconsistency here? I guess this is because within the pattern it is not searching for everything but only for things which are valid, so it doesn't consider `Case` in `| Case.{}` to be the DU-Case from `YetOther` because you cannot access members at this point.

**Comment by abelbraaksma** [comment] 2018-04-12 20:15
> What is the reasoning that | Case.Case1 is working in the match? Is there a different name resolution strategy within matching?

@matthid, Thanks for pointing this out again, but now that you mention it, it is not DU case that was inaccessible, but the DU static member extension. Though I can't think of a technical reason why it cannot be resolved, considering that the DU case member is resolved properly. So, the compiler "knows" to find the type declaration.

Sidebar: with _there's no technical reason_ I mean: given a namepart X and a member M, there's a set of matching module and type declarations Y for each X. Find the highest precedence type or module in that set that has the signature M. The type is now the type of the module or type declaration the (static) member belongs to.

Currently, from the explanation of @dsyme, the highest type or module declaration is used and (with the exception for DU case names) will remain the only resolvable type. That the member belongs to an accessible, but shadowed other type is currently not taken into account (and perhaps for good reason).

>  Qualified access is always allowed, but you have just hidden the name so you cannot access it. 

Not sure I understand you here. It is allowed, but it is not possible? And by using `RequireQualifiedAccess` I somehow magically change the scoping rules for FQN's?

> Maybe one more workaround could be to use SRTP

You mean statically resolved type parameters? Haven't tried it, but if it cannot resolve it statically now, how can the compiler resolve it statically with SRTP? I'll give it a try to see what happens.

**Comment by matthid** [comment] 2018-04-13 04:16
> DU case that was inaccessible

no afaics basically the DU-Type “Case” is inaccessible as it is hidden by DU case “Case” of “YetOther”. Therefore you have a hard time accessing static members.

> Not sure I understand you here. It is allowed, but it is not possible? And by using RequireQualifiedAccess

Basically it doesn’t bring unqualified case names into scope, therefore your case type names are not hidden by them.
Yes it is not possible because “CaseSpace.Case” means the case of “YetOther” and hides the type you want to access.

With srtp you don’t have to spell out the typename yourself (which you cannot) therefore I feel like it would work.

**Comment by dsyme** [comment] 2018-04-13 18:40
> @dsyme, there's still a bug: the intellisense parser/compiler comes up with a different resolution and shows in the tooltip the signature from the DU name.

OK, perhaps file a different issue about that, or rename this issue

> ... and then these types and/or cases are lost forever (accept for, perhaps, reflection)?

Yes, in this case it is possible to define names that are so overloaded that they are inaccessible. It stems from the way union cases are dealt with. Using RequireQualifiedAccess is the solution to this.
