### ISSUE TITLE
AutoComplete - Keywords appearing in completion list during '.' completion

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#2723] opened 2017-03-28 22:12 UTC
![](http://i.imgur.com/sIJepDp.png)

![](http://i.imgur.com/7eU4vGs.png)

They should not be appearing in this completion context

cc @vasily-kirichenko

**Comment by vasily-kirichenko** [comment] 2017-04-22 15:36
It was fixed some time ago. I cannot reproduce it on master. @cartermp close this please.

**Closed** 2017-04-22 16:34 UTC
Labels: Area-IDE Language Service, Urgency-Soon
