### ISSUE TITLE
F# signatures provide no mechanism to distinguish between methods taking no arguments and those taking a single argument of type unit

### ISSUE THREAD

**Issue by kbattocchi** [Microsoft/visualfsharp#673] opened 2015-10-08 14:04 UTC
For most tuple types, signatures allow differentiation between methods which take multiple flat arguments and methods that take a single argument of tuple type:

``` fsharp
type I =
  abstract NoTuple : int * int -> unit // method with two arguments
  abstract Tuple : (int * int) -> unit // method with one argument of tuple type
```

However, no such possibility for disambiguation exists for the 0-tuple type (`unit`), although the compiler _does_ make a distinction at the point of definition:

``` fsharp
type I =
  abstract NoTuple : unit -> unit // method with no arguments
  abstract Tuple : (unit) -> unit // oops, still no arguments

type T =
  interface I with
    member this.NoTuple() = () // method with no arguments
    member this.Tuple(()) = () // method with one argument of tuple type - causes error
```

This leaves a gap between what can be expressed in a type and what can be expressed in a signature, and has the following unfortunate consequences:
- There are methods which can be defined but which can't be given signatures (e.g. the output from specifying the --sig compiler option will create a signature file that can't be used because the method and its signature don't match)
- Users are confused by the lack of a distinction in the signatures when trying to debug issues where the distinction actually matters.  See #662 for one place where this has caused confusion.

**Comment by dsyme** [comment] 2015-10-08 16:42
I agree with this diagnosis

**Comment by zpodlovics** [comment] 2015-10-08 17:04
Maybe a bit unrelated (except the confusion about signatures and type constraints), but a single argument decomposition also works a bit "weird" as I experienced in  #347 . 

According to the language spec §14.4:
"If ... M has only one candidate method, which accepts only one required argument, ignore the decomposition of arg to tuple form. Instead, arg itself is the only named actual argument."

**Comment by dsyme** [comment] 2015-10-08 17:46
@kbattocchi Can you convert this into a User Voice request please?  Right now we wouldn't consider it a bug but just document it as a limitation, so UV is the right place for this.  However I agree that, in principle, this should be addressed using the syntax you mention so consider it pre-approved :)

**Comment by dsyme** [comment] 2017-06-20 13:04
Closing as this is really a language suggestion. Right now what we have is by design, but has this limitation

**Closed by dsyme** 2017-06-20 13:04 UTC
Labels: Area-Compiler, bug, Urgency-Soon
