### ISSUE TITLE
Could no longer open Fake.sln directly after upgrading to 15.6.2 - projects shown as "incompatible"

### ISSUE THREAD

**Issue by matthid** [Microsoft/visualfsharp#4568] opened 2018-03-18 14:22 UTC
After Updating Visual Studio to 15.6.2 it looks like this:

![image](https://user-images.githubusercontent.com/1866463/37566804-57d430d0-2abe-11e8-99e6-90fcf9b8d87a.png)

#### Repro steps

0. Upgrade Visual Studio

1. git clone https://github.com/fsharp/FAKE.git

2. open `Fake.sln`

#### Expected behavior

At least load the solution as it did before

#### Actual behavior

See the screenshot

#### Known workarounds

Repair Visual Studio, restart and reload all projects.

#### Additional Info

I tried to change between `F2A71F9B-5D33-465A-A702-920D77279786` and `6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705` But I couldn't make it work at all.
(Or possible the problem was that two projects had `F2A71F9B-5D33-465A-A702-920D77279786`, see https://github.com/fsharp/FAKE/pull/1819/commits/96cf8ec88da7a280b97cf61a127cb2f9f31374c7)

The migration report linked to some not useful general migration page.

Please close this if the information is not enough to fix this.

**Comment by Pilchie** [comment] 2018-03-18 18:27
Tagging @jviau.  We've seen at least one report that appeared to happen because VS's MEF cache wasn't updated.  Can you try running `devenv /updateconfiguration` from a developer command prompt, deleting your .vs directory, and then opening again?

**Comment by matthid** [comment] 2018-03-18 19:19
Like I said it is already working again for me by running Visual Studio "repair"

**Comment by cartermp** [comment] 2018-03-19 00:43
@matthid I noticed something similar with VisualFSharp.sln with 15.6.1 - attempting to reload fixed it for me, though, and I haven't seen it since (thus I didn't report since it wasn't reproducible).

**Comment by cartermp** [comment] 2018-03-19 00:54
It loads for me, though with restore errors, and running `dotnet build build.proj` fails...

![image](https://user-images.githubusercontent.com/6309070/37573459-5a4e424e-2ad5-11e8-9ec2-4e1197a544d2.png)

**Comment by matthid** [comment] 2018-03-19 01:20
well, yes maybe I was just caught by surprise. feel free to close if nobody else reports it or we cannot easily reproduce...

**Comment by cartermp** [comment] 2018-03-19 01:21
Let's leave it open for a week or two in case someone does run across it.

**Comment by cartermp** [comment] 2018-07-24 16:23
@matthid I cannot reproduce this with 15.7.5 and latest master of FAKE. I'll close this out. Do ping if you see it again, though.

**Closed by cartermp** 2018-07-24 16:23 UTC
Labels: needs repro
