### ISSUE TITLE
Ctrl+} doesn't work on closing parenthesis in Visual Studio

### ISSUE THREAD

**Issue by wanton7** [Microsoft/visualfsharp#4274] opened 2018-01-26 22:52 UTC
Ctrl+} doesn't work on closing parenthesis in Visual Studio

#### Repro steps

```fsharp
let foo x =
    "foo" + x

let bar x =
    "bar" + x

let tst x =
    "tst" + x

printfn "%s" (bar (foo (tst "foobar")))
```

Copy & paste code to Visual Studio and try using Ctrl + } on last two parenthesis 

#### Expected behavior

Ctrl + } should jump to matching parenthesis

#### Actual behavior

Ctrl + } doesn't do anything and it doesn't seem like parenthesis is select, because it doesn't get highlighted.
First closing parenthesis works but not last two.

#### Known workarounds

None

#### Related information 

Provide any related information 

* Operating system
Window 10 (64bit)
* .NET Runtime, CoreCLR or Mono Version
CoreCLR 2.1.4
* Editing Tools (e.g. Visual Studio Version)
Visual Studio 2017 15.5.5
* Indications of severity
Not severe

**Comment by cartermp** [comment] 2018-01-30 05:19
This is actually a dupe of #3794; or rather, it's the same root cause. I'll close this out and make mention that it also breaks Ctrl+}.

**Closed by cartermp** 2018-01-30 05:19 UTC
