### ISSUE TITLE
Weird XAML designer issue when using Result<_,_> from an F# library referencing a previous FSharp.Core version

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#5655] opened 2018-09-16 18:12 UTC
I have spent some 10–15 hours trying to debug and reduce this problem to a minimal repro solution, and I can reduce it no further. I hope there is a quick fix for this on my end, but for all I know it might also be a bug with FSharp.Core. I am not 100% sure this is the right place; if not, please point me in the right direction.

In short, I experience errors in Visual Studio's XAML designer. Take this with a grain of salt, but the errors seem to occur when running project code at design-time (e.g. when running a design-time view model) for code that returns (or perhaps just uses) `Result<_,_>` in some way, and if the code that uses `Result<_,_>` exists in a library that uses FSharp.Core 4.3.4 or earlier while another intermediary library using that code references FSharp.Core 4.5.0 or higher.

As you can see, it's not easy to explain in general terms, so please see the repro solution and steps below.

Note that I experienced this problem originally with a nuget package depending on FSharp.Core >= 4.1.17 ([Cvdm.ErrorHandling](https://www.nuget.org/packages/Cvdm.ErrorHandling/)). The repro solution below uses paket to force two otherwise identical libraries to depend on different package versions.

### Repro steps

Repro solution:

[Test.zip](https://github.com/Microsoft/visualfsharp/files/2386819/Test.zip)

(As requested by a comment, here is the same with compilation output included: [Test_compiled.zip](https://github.com/Microsoft/visualfsharp/files/2386884/Test_compiled.zip))

Repro steps follow below, but for clarity I'd just like to highlight the projects inside:

* **FSharp450Lib:** A netstandard2.0 library referencing FSharp.Core 4.5.0 containing the following code:

  ```f#
  module FSharp450Lib.Test
  let testResult () = Ok "test"
  let testString () = "test"
  ```

* **FSharp4340Lib:** A netstandard2.0 library referencing FSharp.Core 4.3.4 containing the exact same code:

  ```f#
  module FSharp434Lib.Test
  let testResult () = Ok "test"
  let testString () = "test"
  ```

* **DesignVm:** A netstandard2.0 library containing members that call these four functions and return `"Hello"`:

  ```f#
  type DesignViewModel() =

    member __.v450String =
      FSharp450Lib.Test.testString () |> ignore
      "Hello"

    member __.v450Result =
      FSharp450Lib.Test.testResult () |> ignore
      "Hello"

    member __.v434String =
      FSharp434Lib.Test.testString () |> ignore
      "Hello"

    member __.v434Result =
      FSharp434Lib.Test.testResult () |> ignore
      "Hello"

  ```

* **Test** and **Test2:** net472 WPF apps (**Test** uses the new project format, **Test2** uses the old, otherwise they're identical) that each contains a window displaying the four members of `DesignViewModel` both at design time and runtime.

Repro steps:

1. Unzip
2. Run `.paket\paket restore`
3. If repeating these steps, always remove the `.vs` folder and all `bin` and `obj` folders (I've observed inconsistent behavior otherwise), and if changing project targeting or package references, run `paket update` to ensure as clean a slate as possible.
4. Open the solution in Visual Studio 2017
5. Build the solution
6. Open `MainWindow.xaml` in **Test** or **Test2**, and ensure project code is enabled in the designer

### Expected behavior

![image](https://user-images.githubusercontent.com/7766733/45599352-44a5c300-b9ea-11e8-96ab-59a1a8506c58.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/7766733/45599354-525b4880-b9ea-11e8-9ef2-6d0b12e01b0e.png)

Note 1:  I experienced exceptions in the designer, not just missing members:

![image](https://user-images.githubusercontent.com/7766733/45599358-83d41400-b9ea-11e8-8c37-39d648aacd46.png)

I have however not been able to get this behavior in the minimal repro solution.

Note 2: At run-time, everything works fine:

![image](https://user-images.githubusercontent.com/7766733/45599693-7de13180-b9f0-11e8-970a-a949eebcbcaf.png)

Note 3: In `App.config` in both WPF projects, Paket has inserted an assembly redirect to FSharp.Core 4.4.3.0. I do not know why this is, but in the `obj` and `bin` folders, the redirects are to FSharp.Core 4.5.0.0. I have tried messing around with the redirect, but could not observe a change in behaviour.

### Known workarounds

None (apart from changing the F# version used by the class libraries, but that can't be done in the case of nuget references).

### Related information 

* VS 15.8.4

**Comment by zpodlovics** [comment] 2018-09-16 18:30
Could you also attach (to an another zip package) the binaries (bin/exe) or the binaries ILDASM output?

**Comment by cmeeren** [comment] 2018-09-16 18:41
No idea what ILDASM is, but here is the same zip file but with compilation output included:

[Test_compiled.zip](https://github.com/Microsoft/visualfsharp/files/2386884/Test_compiled.zip)

**Comment by zpodlovics** [comment] 2018-09-16 19:45
ILDASM is a disassembler tool that extracts IL from dll,exe files (https://www.nuget.org/packages/Microsoft.NETCore.ILDAsm/)

Attached the decompiled IL files:

[Test2.txt](https://github.com/Microsoft/visualfsharp/files/2386941/Test2.txt)
[DesignVm.txt](https://github.com/Microsoft/visualfsharp/files/2386938/DesignVm.txt)
[FSharp434Lib.txt](https://github.com/Microsoft/visualfsharp/files/2386939/FSharp434Lib.txt)
[FSharp450Lib.txt](https://github.com/Microsoft/visualfsharp/files/2386940/FSharp450Lib.txt)

**Comment by TIHan** [comment] 2018-09-16 21:37
The exception is quite odd; I don't remember us adding something like that to FSharp.Core, but it was discussed.

Now, I am able to reproduce the issue and of course at runtime it works fine. I suspect this is an issue with the XAML designer not understanding binding redirects; so this would happen not just for FSharp.Core, but any assembly the tries to expect different versions of a dependency.

Here is a short example using `DesignVvm` from the Test.zip.
```csharp
using DesignVm;
using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = new DesignViewModel();
            Console.WriteLine(x.v450Result);
            Console.WriteLine(x.v434Result);
        }
    }
}
```
This is a .NET Framework Console App, and not a .NET Core one, so binding redirects are necessary. By default, it will create a binding redirect for FSharp.Core, and program will print "Hello" twice, which is expected. If I remove the binding redirect, this happens:
```
Hello

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at DesignVm.DesignViewModel.get_v434Result()
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\...\Downloads\Test\ConsoleApp2\Program.cs:line 12
```
It blows up on `x.v434Result` because that method is expecting a different version of FSharp.Core and no binding redirects were used. This is what I think is happening in XAML designer.

**Comment by cmeeren** [comment] 2018-09-17 07:00
@zpodlovics 

> There are no ResultBuilder anywhere in the IL.

As I said, that exception was only in my original problem; I have not been able to reproduce that exact error in my minimal repro solution. I removed the dependency on `Cvdm.ErrorHandling` (where `ResultBuilder` is defined) in order to minimize as much as possible.

**Comment by cmeeren** [comment] 2018-09-25 14:45
I notice this issue has been assigned the label Area-External, but not closed. I am unsure what this means. Should I take this somewhere else (where?) Or is this something that contributors to this repo can investigate and fix?

**Comment by cartermp** [comment] 2018-09-25 15:35
@TIHan did you intend to close this?

@cmeeren Since this seems like a Xaml designer issue, I don't think there is a fix that can be contributed by open source contributors, since the designer is not open source.

**Comment by cmeeren** [comment] 2018-09-25 18:58
I've posted this on [VS developer community](https://developercommunity.visualstudio.com/content/problem/343266/weird-xaml-designer-issue-when-using-result-from-a.html).

**Comment by cmeeren** [comment] 2018-09-25 19:00
In any case: Were there any changes to the `Result` type from 4.3.4 to 4.5.0? While the issue may not be F#'s fault, such a change seems necessary to observe the different behavior.

**Comment by TIHan** [comment] 2018-09-25 19:02
I don't believe we made changes to the Result type.

**Comment by cmeeren** [comment] 2018-09-25 19:05
Can you think of any reasons why this behaviour is observed when referencing a `Result` expression pre- vs. post-4.5.0? Again, while it may not be F#'s fault, surely some kind of change in F# must be a necessary component of this issue?

**Comment by TIHan** [comment] 2018-09-25 20:11
This is most likely a Xaml designer issue unable to understand binding redirects.

**Comment by cartermp** [comment] 2018-09-25 20:15
@cmeeren Thank you for filing the developer community issue. We'll close this and see what investigation from the XAML tools team can yield. If it ends up being an F# issue (which we currently think is unlikely), we'll re-open this bug and investigate further.

**Closed by cartermp** 2018-09-25 20:15 UTC
Labels: Area-External

**Comment by cmeeren** [comment] 2018-09-26 08:15
> This isn't specific to FSharp.Core, but any library.

Sure, but it's just weird that it only happens for members referencing `Result<_,_>` expressions. In any case, we'll see what the developer community issue brings up.

**Comment by KevinRansom** [comment] 2018-12-15 04:04
@cmeeren,

Lutz Roeder of the WPF took a look at this, it appears that this is a conflict between shadow copying pulling FSharp.Core from VisualStudios PublicAssemblies directory, and the Wpf designer pulling fsharp.core from a different location and them not being able to unify them.

Anyway in a future release of VS we will remove FSharp.Core from Common7\IDE\PublicAssemblies

Kevin

**Comment by cartermp** [comment] 2018-12-15 06:09
Linking #6014 as the setup tracking issue

**Comment by cmeeren** [comment] 2018-12-15 13:02
Good to hear!
