### ISSUE TITLE
Vs 2017 Can't see generated by SqlEnumProvider enums in references assembles

### ISSUE THREAD

**Issue by denisnikolayev** [Microsoft/visualfsharp#3088] opened 2017-05-19 15:05 UTC
Hello. We have an issue with using SqlEnumProvider (package FSharp.Data.SqlClient)  in Visual Studio 2017 (tried night builds as well).

lib with `SqlEnumProvider` and another lib referenced on first. In first we define SqlEnumProvider with some enum. But vs says that there is no values.

**Build works fine.**

![image](https://cloud.githubusercontent.com/assets/14340491/26253835/a8f571e8-3c82-11e7-8f30-a9947bbe7d66.png)

![image](https://cloud.githubusercontent.com/assets/14340491/26253844/b05f10f6-3c82-11e7-84e3-588198b3c600.png)

![image](https://cloud.githubusercontent.com/assets/14340491/26253849/b52afcc6-3c82-11e7-9469-75896c22dfe1.png)

**Comment by dsyme** [comment] 2017-05-19 15:08
@denisnikolayev Is it possible for you to you provide a standalone repro of this?

**Comment by denisnikolayev** [comment] 2017-05-19 15:14
@dsyme yes, but the issues is in database. I can use AdventureWorks in a sample. Will it be ok?

**Comment by dsyme** [comment] 2017-05-19 15:18
@denisnikolayev Yes, that's fine.  Please include a link on where to get it (I know I can search, but we just want exact instructions, thanks)

**Comment by isaacabraham** [comment] 2017-05-19 15:22
Linked to #3049?

**Comment by vasily-kirichenko** [comment] 2017-05-19 15:27
I see the same bug in Rider today https://youtrack.jetbrains.com/issue/RIDER-6435. The repro solution is here https://github.com/vasily-kirichenko/RiderTypeProviderTest.git

**Comment by vasily-kirichenko** [comment] 2017-05-19 15:34
![image](https://cloud.githubusercontent.com/assets/873919/26255301/d144adf0-3cc1-11e7-9d00-4ceb988b1521.png)

**Comment by denisnikolayev** [comment] 2017-05-19 15:41
https://github.com/denisnikolayev/enumissueinvs2017
I just put small sql script with one table

**Comment by dsyme** [comment] 2017-06-21 12:25
I suspect this may be the same error as https://github.com/Microsoft/visualfsharp/issues/3234, fixed by https://github.com/Microsoft/visualfsharp/pull/3236

**Comment by dsyme** [comment] 2017-06-21 13:27
@denisnikolayev I haven't been able to run your repro yet (need to install database bits on my machine) but I'm fairly confident that #3236 fixes the problem

**Comment by vasily-kirichenko** [comment] 2017-06-21 13:35
I confirm it's fixed in that PR.

**Comment by dsyme** [comment] 2017-06-21 13:37
Thanks!

**Comment by dsyme** [comment] 2017-06-21 13:37
I'll close this as a duplicate of https://github.com/Microsoft/visualfsharp/issues/3234

**Closed by dsyme** 2017-06-21 13:37 UTC
Labels: Area-TypeProviders, bug, Urgency-Now
