### ISSUE TITLE
automatic triggered completion annoyance: exact match with single result

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2732] opened 2017-03-29 18:06 UTC
My muscle memory is pretty strong on adding `| _ -> None` on a new line and pressing UP-ARROW subsequently to get back at the interesting piece of work.

```fsharp
| _ -> None
           ^
```

When my carret is here, I type UP-ARROW and don't expect to be bogged down by autocompletion since this is an exact match and there is only a single result.

**Comment by vasily-kirichenko** [comment] 2017-04-22 07:04
This is what completion looks like on current master:

![image](https://cloud.githubusercontent.com/assets/873919/25302246/d638f86e-2742-11e7-9bc2-42e0eaee79f2.png)

It looks like a completely right behavior to me.

What do you expect it to do by pressing Up Arrow? It does nothing and it's OK.

**Comment by dsyme** [comment] 2017-06-20 10:06
Closing this discussion since the issue is not clarified

**Closed** 2017-06-20 10:06 UTC
Labels: Area-IDE Language Service, Urgency-Soon
