### ISSUE TITLE
Add new item dialog suggests existing file name

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2892] opened 2017-04-21 07:23 UTC
This is regression for sure. I think it was introduced by @saul 's folder support PR merged yesterday.

![image](https://cloud.githubusercontent.com/assets/873919/25267186/821a53a2-267c-11e7-9b81-f787819b7c36.png)

![image](https://cloud.githubusercontent.com/assets/873919/25267140/632f100e-267c-11e7-9389-b0c748f139f1.png)

![image](https://cloud.githubusercontent.com/assets/873919/25267156/6b7fa52a-267c-11e7-95a7-ae4f1f8d6edd.png)

**Comment by dsyme** [comment] 2017-04-29 13:40
@saul Please take a look when you get the chance? @vasily-kirichenko thinks this may be have been introduced by the folder support PR, which would indicate a more general underlying problem?

**Comment by saul** [comment] 2017-04-29 13:41
Sure - I know there's a function somewhere in the project system that handles this. I'll take a look this weekend

**Comment by saul** [comment] 2017-04-29 21:18
Followed the exact repro steps and I can't reproduce it:

![image](https://cloud.githubusercontent.com/assets/64654/25558984/cf4bb37e-2d29-11e7-91fc-d653556495d2.png)

**Comment by saul** [comment] 2017-04-29 21:33
Fixed in #2956

**Closed** 2017-05-01 17:03 UTC
Labels: Area-IDE Project System, bug, regression, Urgency-Now
