### ISSUE TITLE
VS 2017 15.7.0 Preview 1.0 and 2.0, F# Project property pages always crash

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4603] opened 2018-03-22 12:00 UTC
I'm seeing this when I open a property page of an existing F# project in Visual Studio Professional 2017 Preview 1.0 (15.7.0)

![image](https://user-images.githubusercontent.com/16015770/37769248-a8b46834-2dd0-11e8-8f1b-701a27e7102f.png)

In text:

> An error occurred trying to load the page.
> Could not load file or assembly 'FSharp.ProjectSystem.PropertyPages, Version=15.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### Repro steps

Happens always when opening Properties (right-click project > Properties) of an F# project.

### Known workarounds

Don't know, unless editing the fsproj files by hand or opening in a previous versions of VS.

### Related information 

C# project property pages work just fine.

Seems to happen only with VS 2017 15.7.0 Preview 1.0. For projects with F# 4.0 or F# 4.3, regardless of choice of `FSharp.Core` (choice made in a working VS).

(edit) Just updated to Preview 2.0 and it is still happening.

**Comment by cartermp** [comment] 2018-05-25 16:48
Closing as dupe of #4505

**Closed by cartermp** 2018-05-25 16:48 UTC
