### ISSUE TITLE
UnresolvedPathReferenceNoRange message could be improved

### ISSUE THREAD

**Issue by ForNeVeR** [Microsoft/visualfsharp#2546] opened 2017-03-08 06:19 UTC
#### Repro steps
1. Create new F# project in VS2017.
2. Use `System.ValueTuple` somewhere in code, for example:
    ```fsharp
    [<EntryPoint>]
    let main argv = 
        let origin = struct (0, 0)
        printfn "%A" origin
        0
    ```
3. Remove the reference to `System.ValueTuple` assembly from the project to observe the error message.

#### Expected behavior
Error message that should state the `System.ValueTuple` assembly name, e.g. `You must add a reference to assembly 'System.ValueTuple'`.

#### Actual behavior
```
FSC: error FS0074: The type referenced through 'System.ValueTuple`2' is defined in an assembly that
is not referenced. You must add a reference to assembly 'The system type 'System.ValueTuple`2' was
required but no referenced system DLL contained this type'.
```

Probably it should have assembly name instead of ``The system type 'System.ValueTuple`2' was required but no referenced system DLL contained this type``; the current message is slightly confusing.

#### Known workarounds
Ignore the error message.

#### Related information 
* **Operating system**: Windows 10
* **Branch**: the one included into VS2017 release, "F# 4.1 (FSharp.Core 4.4.1.0)"
* **.NET Runtime, CoreCLR or Mono Version**: Building project for .NET 4.5.2 (the default)
* **Editing Tools (e.g. Visual Studio Version)**: VS 2017 release
* **Indications of severity**: minor

I've tracked down this message through the code. It's probably raised somewhere in [`tast.fs:3644`](https://github.com/Microsoft/visualfsharp/blob/66123c8c162c058c4cf63c6e5ade2b7fabc88bce/src/fsharp/tast.fs#L3644), but I don't know what `CcuReference` is and whether it's possible to get the assembly name from it. Possibly this `CcuReference` type has improper `ToString()` implementation.

**Comment by KevinRansom** [comment] 2017-03-08 18:20
@ForNeVeR 
Hi,

Thanks for the feedback, we appreciate it.  I feel slightly uncomfortable defending this message, because in some ways I agree with you ... however, in the next release of the DotNet framework ValueTuple is going to be in mscorlib, and so teaching the compiler where it lives might be a bit short-term, this happens quite a lot in the dotnet framework, where due to a large refactoring for portable libraries, reference assemblies where created with type definitions in entirely different assemblies from their original framework assembly.

Clearly the compiler can not know which types are in which assembly unless the assembly is presented at compile time, and so a sort of general message saying ... I can't find the type 'Foo' in any of the referenced assemblies, please add a reference to an assembly containing type 'Foo' is going to be the most actionable message.

It's a bit unfortunate that the message is repeated paraphrased, perhaps we should try to do something about that, however, the basic message is probably reasonable, it says what the problem is and how to solve it.

Does that make sense?

Kevin

**Comment by ForNeVeR** [comment] 2017-03-09 03:04
@KevinRansom yes, I understand the issue, and I think that the message will be okay if slightly improved. That's not a major problem.

**Comment by dsyme** [comment] 2017-03-14 13:42
I'll close this as a duplicate of https://github.com/Microsoft/visualfsharp/issues/2547

**Closed by dsyme** 2017-03-14 13:42 UTC
