### ISSUE TITLE
VS debugger doesn't show variable inspector on variables named with a '

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1584] opened 2016-10-06 23:54 UTC
Using Visual Studio Professional 2015, I can't inspect `kv'` in that debugging session:

![image](https://cloud.githubusercontent.com/assets/87944/19174645/30c60d02-8be5-11e6-8970-9662a5282ed2.png)

The variable appears in locals pane.

**Comment by dsyme** [comment] 2016-10-10 10:03
Duplicate of https://github.com/Microsoft/visualfsharp/issues/1521

**Closed by dsyme** 2016-10-10 10:03 UTC
