### ISSUE TITLE
New implicit ref conversion warning does not appear live in IDE

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#515] opened 2015-06-25 20:56 UTC
If you add `/warnon:3180` to the "Other flags" section of project properties, you do not get live squiggles where you would expect to.

Below, I have both `/warnon:3180` (implicit conversion to ref) and `/warnon:1182` (unused variable) enabled in project properties.  Only the latter is producing squiggles:

![image](https://cloud.githubusercontent.com/assets/5943573/8365320/4858ae54-1b41-11e5-9656-bd3103f817ce.png)

After a full build you do get squiggles, though AFAICT these are just populated from the error list:

![image](https://cloud.githubusercontent.com/assets/5943573/8365374/95b79f5c-1b41-11e5-849e-1f07e9b7043e.png)

**Comment by dsyme** [comment] 2015-06-25 22:20
I think we would consider this by design - or at least a known limitation of the tooling,  However perhaps it is not too hard to fix if the appropriate transformation is run in the IDE checking cycle.

**Comment by dsyme** [comment] 2015-07-15 21:48
Closing this as by design for now since it was intentionally this way in F# 4.0.  We can relabel as a suggestion of open a uservoice item on it.

**Closed by dsyme** 2015-07-15 21:48 UTC
Labels: bug
