### ISSUE TITLE
outref<'a> should not allow read access

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5280] opened 2018-07-01 11:29 UTC
As https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1053-span.md reads:

> Semantically outref means "the holder of the byref pointer may only use it to write". It doesn't imply that other threads or aliases don't have read access to that pointer.

`outref` should not allow read access, but the following code compiles:

```fsharp
let changeDate(date: outref<DateTime>) = 
    let d: DateTime = date
    date <- DateTime.Now
```

**Comment by zpodlovics** [comment] 2018-07-01 22:52
Nope. "The out keyword causes arguments to be passed by reference. It is like the ref keyword, except that ref requires that the variable be initialized before it is passed."

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier

**Comment by TIHan** [comment] 2018-07-02 19:44
`outref<'T>` is only considered for documentation purposes only. In the future we may change this by adding some flow analysis.

**Comment by cartermp** [comment] 2018-07-02 20:17
This sounds like a spec bug, then. I think that [the spec definitely implies](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.5/FS-1053-span.md#outreft-for-output-reference-parameters) that `date` cannot be read in the `changeDate` function.

**Comment by cartermp** [comment] 2018-07-02 20:18
As a note if we restrict it as-is today to disallow reads, that would be a breaking change to document

**Comment by cartermp** [comment] 2018-12-03 20:55
Closing as by design; the spec and docs explain this now.

**Closed by cartermp** 2018-12-03 20:55 UTC
Labels: Resolution-By Design
