### ISSUE TITLE
Kill/trivialize special-snowflake "-proto" projects

### ISSUE THREAD

**Issue by SamB** [Microsoft/visualfsharp#712] opened 2015-11-05 22:19 UTC
We should get rid of at least *most* of the code in the following files:

  * src/fsharp/Fsc-proto/Fsc-proto.fsproj
  * src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj
  * src/fsharp/FSharp.Compiler-proto/FSharp.Compiler-proto.fsproj

They are nearly duplicates of the neighboring unsuffixed projects, and serve mostly to:

  * Obscure what's done differently in a Proto build (and whether or not any such differences are intentional)
  * Require many typical project changes to be done separately to each version of the project
  * Make things ever-so-slightly more editable in Visual Studio, at least in theory

Instead, the Proto-dependent stuff should be factored into shared `.targets` files and/or done by parameterizing the main project files.  While VS might not give much help in editing the affected parts of the project files, it can at least leave them intact when modifying other parts of the project files.  (And it's not as though the -proto projects are even in a solution.)

I'm attempting to tackle this in [my build-cleanup branch](https://github.com/SamB/visualfsharp/tree/build-cleanup).

**Comment by dsyme** [comment] 2015-11-05 22:40
Hi @SamB  - Certainly reducing the textual differences is a good thing.

There are some other considerations here which may be helpful to know. 

* IIRC these files are in fact duplicated in some internal build machinery at Microsoft (the actual project files used to build the final Visual F# Tools product). 

* There are also corresponding files in http://github.com/fsharp/fsharp and http://github.com/fsharp/FSharp.Compiler.Service which are kept in line via git merges.

* Tools like Visual Studio and Xamarin Studio do tend to behave grumpily in the presence of some project file factorings.  So ideally we would make the project files as much like vanilla project files as possible.

* The CoreCLR work is coming through the pipeline - which may be very intrusive on some build files due to the need to list .NET dependencies explicitly.  Perhaps this is a good reason to factor. But equally please ensure this commutes with the CoreCLR work.

I know this isn't totally satisfactory.  Perhaps its the right time to clean this up - it's hard to tell.  I just wanted to let you know about the above considerations.

Best regards
Don

**Comment by SamB** [comment] 2015-11-05 23:16
@dsyme: Thanks for the warnings.

Re: internal build machinery at MS, I doubt if that machinery is synchronizing these -proto projects with their normal counterparts, though it may well be synchronizing them with some MS-internal versions of the projects.

As for the http://github.com/fsharp/fsharp and http://github.com/fsharp/FSharp.Compiler.Service versions of these files ... that would be a lot easier to investigate if github considered them to be in the same network as visualfsharp.  Thankfully, they actually do share ancestry, so this could probably be resolved if the right people were to ask GitHub technical support nicely enough to merge the networks?

And I certainly plan to try to avoid using MSBuild constructions that actually confuse Visual Studio, though I seem to have lost track of a document I was looking at earlier that warned against conditionalizing certain grouping constructs in the project file proper, as if the conditions evaluated to false when VS loaded the project, it would never bother to check again.

As for CoreCLR, it certainly won't commute (do I detect some darcs usage in your past, or is it just a coincidence that you used the term "commute" in the context of version control), but one of the reasons I actually want to do this is that then maybe I could get the proto compiler running on CoreCLR, which should allow for less-slow non-admin builds (since crossgen has no reason to demand administrative privileges), so I definitely have that in mind.  I just figured it would be better to start on master so it doesn't make things HARDER to merge between branches.

**Comment by dsyme** [comment] 2015-11-10 14:28
Closing this issue since it's not a bug and we can discuss in the PR thread #713

**Closed by dsyme** 2015-11-10 14:28 UTC
