### ISSUE TITLE
F# Intellisense, Code Navigation and Highlighting is not working

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4295] opened 2018-02-01 17:10 UTC
Open https://github.com/fsharp/FAKE/blob/master/src/Fake-netcore.sln wait until it has loaded
Open Fake.Runtime/FakeRuntime.fs
No intellisense, code help, and only basic highlighting

Build works

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/190803/f-intellisense-code-navigation-and-highlighting-is.html
VSTS ticketId: 559738_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment] 2018-02-01 17:12
cc @matthid 

Since this is a public solution it'll be easier to just look at directly here. If we really need to, we can go back into the VSTS bug and grab the dump file.

**Comment by matthid** [comment] 2018-02-01 17:13
Yes I thought the dumps might help just in case it doesn't reproduce for others :)

**Comment by cartermp** [comment] 2018-02-01 21:47
@Pilchie I noticed this when opening up the solution in 15.6 Preview 3:

![image](https://user-images.githubusercontent.com/6309070/35705093-5502b948-0756-11e8-8f8e-4d23e169c639.png)

Log:

```
=====================
2/1/2018 1:38:45 PM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: '_GetProjectReferenceTargetFrameworkProperties', Actual: 'ResolveProjectReferences'.
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
2/1/2018 1:38:50 PM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'DispatchToInnerBuilds', Actual: '_GetProjectReferenceTargetFrameworkProperties'.
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
2/1/2018 1:39:08 PM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'ResolveProjectReferences', Actual: 'CoreCompile'.
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
2/1/2018 1:39:11 PM
Recoverable
System.InvalidOperationException: Build target stack was corrupted and contain other unfinished targets. Expect: 'DispatchToInnerBuilds', Actual: 'ResolveProjectReferences'.
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
===================
```

Is this expected?

**Comment by cartermp** [comment] 2018-02-01 21:49
Can confirm the lack of language service light-up here - nothing, not even parsing operations, is showing up. I wonder if it's related to the above issue?

**Comment by cartermp** [comment] 2018-02-01 21:58
@matthid Actually I think this is just the lack of multitargeting support in #4084, which should be fixed by #4286. If I change Fake.Runtime project file to to be `<targetframework>` rather than `<targetframeworks>` I get IDE feature light-up:

![image](https://user-images.githubusercontent.com/6309070/35705674-fb834778-0757-11e8-89aa-8b04a45c936c.png)

**Comment by Pilchie** [comment] 2018-02-01 23:20
@lifengl - do you know what's up with the error above?

**Comment by KevinRansom** [comment] 2018-02-01 23:49
@cartermp was correct, this is due to multi-targeting support not working.

In the latest internal build with the fix this project does colouring and intellisense :
![image](https://user-images.githubusercontent.com/5175830/35709435-581d7c56-0767-11e8-8aaf-c6b7a75c7ade.png)

**Comment by matthid** [comment] 2018-02-02 21:26
Yes, thanks a lot for the quick info. Sorry I wasn't up to date with all the remaining issues.

**Comment by cartermp** [comment] 2018-02-02 21:53
No worries! I'll close this out for now. We can re-open if it persists after the multitargeting work ships.

**Closed by cartermp** 2018-02-02 21:53 UTC
Labels: Area-IDE Language Service, bug
