### ISSUE TITLE
FSharpProject Package initialization optimization -

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1038] opened 2016-04-04 22:31 UTC
# Tracking DevDiv BUG#:  203393

This bug is for tracking optimization of FSharpProjectPackage initialization method. This package is identified as one of the packages being loaded for retrieving editor font and colors and if cache is not present, the package will be loaded in first editor open regardless of editor type.

Traces show the costly operation is getting GlobalProjectCollection through MSBuild during package initialize method. If this is not needed for package init or fonts and color, we should defer to the point needed in order to ensure first time an editor is opened is not delayed.
# 

**Note package in question is being loaded because it registers a language service and editor is trying to get fonts and colors from all language services. The code will try to load your language service and cast it to IVsProvideColorableItems.

If you are not implementing that interface, you can modify your language service registration to include RequestStockColors = true so that your package is skipped during this operation.
**

**Comment by saul** [comment] 2017-04-20 18:47
Dupe of #1081

**Closed** 2017-04-20 18:49 UTC
Labels: Area-IDE Project System, bug, Urgency-Later
