### ISSUE TITLE
Seeing Internal Error tcrefOfAppTy and <Note> in the intellisense dropdown box in Visual Studio 2017

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5210] opened 2018-06-18 16:55 UTC
This one was new for me, I just started seeing the following error in the dropdown box (and no other options shown):

![image](https://user-images.githubusercontent.com/16015770/41550374-dd5a287e-7328-11e8-8aeb-edc169817fc2.png)

### Repro steps

~I think this is related to #5003, although that is marked as Mac-only. Perhaps someone can confirm it's the same? In that case this can be closed with no action.~

EDIT: strike that, it is unrelated (see comments from @nosami). A repro is in my second and third comment below.

### Expected behavior

No error, just a list of available members (in this case, just one member should be shown).

### Actual behavior

Error: internal error: tcrefOfAppTy.

### Related information 

Seen on Visual Studio 2017, 15.8 Preview 2.

**Comment by cartermp** [comment] 2018-06-18 17:23
@abelbraaksma Do you have a sample that can demonstrate this? Since the fix is in the language service, it is also now in the VS tools, and in theory this could also be seen in VS without that fix in place.

**Comment by nosami** [comment] 2018-06-18 17:36
I don't think this can be the same issue. My fix was in `GetDeclarationListSymbols` which is used only by VS Mac.

**Comment by abelbraaksma** [comment] 2018-06-18 18:58
Ok, in that case I'll try come up with a small repro. Perhaps something in that DU triggered it

**Comment by abelbraaksma** [comment] 2018-06-18 19:16
@cartermp, looks like I do have one, it took a bit of experimenting, but after stripping and stripping the following still gives me the error, even after copy/pasting it to another solution (to rule out a confused local language service issue):

```f#
type TceRefError = byte -> string * byte

module TceRefError =

    let testMe _ = 42

module Blablabla =
    let foo = TceRefError.<Note>   // the only suggestion in the dropdown, and selectable, is "<Note>"
```

![image](https://user-images.githubusercontent.com/16015770/41557058-be363fd2-733c-11e8-9fa4-2c599690f130.png)

**Comment by abelbraaksma** [comment] 2018-06-18 19:19
in fact, it seems to happen as soon as you use arrow-syntax in the type alias:

```f#
// proper dropdown:
type TceRefError = string * byte

// tcrefOfAppTy error
type TceRefError = int -> int
```

**Comment by cartermp** [comment] 2018-12-14 06:14
Yes, this is not reproducible in 15.9.4 for me either:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/6309070/49986346-68fb3800-ff24-11e8-9b8f-25926940f698.png">

@abelbraaksma Do you still see this?

**Comment by abelbraaksma** [comment] 2018-12-14 17:04
@cartermp, @rojepp: I cannot repro it either anymore. Though not really related, but why do I see the methods `FromConverter`, `InvokeFast`, `op_Implicit` (certainly that should be hidden?), `ToConverter`? Aren't these functions or static methods that are supposed to be used internally mostly?

Though regardless, I think this can be closed.

**Comment by abelbraaksma** [comment] 2018-12-14 17:07
Btw, I didn't test it specifically, but since this is basically the same error thrown by #4825, perhaps that issue has meanwhile been resolved as well?

**Comment by cartermp** [comment] 2018-12-14 20:13
Yes, the issue does seem resolved. I'll close this out and we'll use #4825 as the canonical issue about why a type could get in that state.

**Closed by cartermp** 2018-12-14 20:13 UTC
Labels: needs repro
