### ISSUE TITLE
FSI can't be launched on dev15

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1705] opened 2016-11-04 17:25 UTC
1. Install dev15 rel or prerel with .NET Desktop workload and create a new F# project.
2. Create script file with some code.
3. Alt-enter.

Expected: FSI opens and my code is evaluated.
Actual: Nothing happens.

When I right-click, I also get no option:

![fs-roslyn-no-fsi](https://cloud.githubusercontent.com/assets/6309070/20015483/e24c62ac-a278-11e6-961b-c78503bb86c1.PNG)

**Comment by OmarTawfik** [comment] 2016-11-04 19:00
@cartermp this is a duplicate of #1633

**Closed by OmarTawfik** 2016-11-04 19:00 UTC
Labels: Area-IDE FSI, bug
