### ISSUE TITLE
Visual Studio 2017 RC can't show lists in debugger

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2184] opened 2017-01-07 10:41 UTC
Visual Studio 2015:

![image](https://cloud.githubusercontent.com/assets/57396/21741149/d9bd49d0-d4cd-11e6-909f-de129e1bb83b.png)

Visual Studio 2017 RC:

![image](https://cloud.githubusercontent.com/assets/57396/21741158/0a8a5efe-d4ce-11e6-82bb-224f6f42f194.png)

This is a serious regression and should be fixed before RTM. Debugging F# is a nightmare right now.

@vladima @pilchie @dsyme @kevinransom does anyone know where we would have to look?

**Comment by cartermp** [comment] 2017-01-08 01:31
Looks like `ListDebugView.Items` (which is an array and not a list, hence the array view in DataTips) isn't getting shown since the switch to the new tools?

**Comment by dsyme** [comment] 2017-01-08 22:45
@cartermp @forki I don't know where to look.  I presume there has been a change in the debugger, though comparing the generated IL code for ListDebugView and List would also make sense to make sure everything is absolutely the same.

@forki Can we check you have exactly the same settings in the debugger flags in VS e.g. "Show raw structure of objects"

**Comment by forki** [comment] 2017-01-09 12:46
![image](https://cloud.githubusercontent.com/assets/57396/21766901/54b280d4-d671-11e6-8b68-c726d7d84121.png)

(sorry for german screenshot.) 

Under `Options/Debugging/General` there is a switch which translates to "Use the older C#- and VB-expression evaluators". The good news is: if I turn this on then debugging works again.

So the questions now are:

* Why is it not referencing F#? I suggest to call that switch something like "Use the older expression evaluators" - which would just remove the language dependency.
* Why is it turned off by default?
* What can we do to convert our stuff to whatever is the new way?

/cc @pilchie

**Comment by vasily-kirichenko** [comment] 2017-01-09 12:49
![image](https://cloud.githubusercontent.com/assets/873919/21767095/21583f00-d683-11e6-9e09-c14b6bd5026d.png)

**Comment by forki** [comment] 2017-01-09 12:52
ha, my translation wasn't that bad. thanks @vasily-kirichenko

**Comment by forki** [comment] 2017-01-09 14:37
@KevinRansom @cartermp could you please ask around?

**Comment by cartermp** [comment] 2017-01-09 14:38
Isn't F# supposed to just be on the legacy C#/VB EE, anyways?  At least that's how I understand it.  Could just be a setup issue if that's the case.  cc @brettfo

**Comment by forki** [comment] 2017-01-09 14:46
I mean they explicitely made that a switch so there must be some reason.

**Comment by forki** [comment] 2017-01-11 16:09
ping

**Comment by cartermp** [comment] 2017-01-11 17:07
Long story short is that I doubt we can get a fix for this in by release.

@forki As for your questions:

> Why is it not referencing F#? I suggest to call that switch something like "Use the older expression evaluators" - which would just remove the language dependency.

This is because it actually is the old C#/VB expression evaluator.  EEs aren't language-independent and need to understand arbitrary expressions in a given language.  F# has never had an EE, and only used the legacy one with a few fixes put in to allow things like converting a list to an array for DataTips.  This is why F# has never worked in the Immediate Window, for example.

> Why is it turned off by default?

This is a global setting (you can't control it on a language-by-language basis).  Because C# and VB use the new Roslyn-based EE, it's the default.

>What can we do to convert our stuff to whatever is the new way?

Perhaps @Pilchie could shed some light here, but my understanding is that the [Roslyn EE](https://github.com/dotnet/roslyn/tree/master/src/ExpressionEvaluator) would have to have a small modification to be aware of F# lists and invoke `ListDebugView.Items`.  I don't believe such a thing would be terribly difficult, but we're in division-wide escrow for any changes in VS right now.  The bar for any new fixes to get in now is very high, and I'm not confident that such a fix would make it at release.  Timing would have to be either a Day 1 patch, or Update 1 of VS 2017 - I believe that we'll have to ship with this as a known regression.

That being said, an F# EE based on Roslyn is a high-priority item for us.  Based on feedback from folks at the MVP summit, the impression was that after sitting F# atop the Roslyn project system, writing an F# EE is the top tooling priority for us (Microsoft) to work on.

**Comment by saul** [comment] 2017-04-07 20:35
I've figured out why this is occurring.

The new Roslyn EE support the same DebuggerTypeProxy attributes we're using on our types (Map, List, Set, etc), in the same way that the native EE did. I've stepped through the debugger (with another debugger) and found the exact point that our proxy type is being ignored.

We're failing this conditional in the Roslyn EE in [TypeHelpers.cs@201](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs#L201). Note the comment above about the changed behaviour from the native EE (a-ha!)

If you take a look at (for example) [map.fs@637](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/map.fs#L637), you'll see that the Items property is Public, but the get_Items method is private! It looks like fields don't exhibit this behaviour, so for a quick fix we can swap the Items property to be a public field instead.

Anyway I've got to the bottom of the case, I'm not sure if we need to raise an issue with Roslyn about this, or whether our code gen needs to produce public getter/setter methods for public properties (cc @dsyme)

I'll open a PR that fixes this in due course.

**Comment by Pilchie** [comment] 2017-04-07 21:28
I know nothing about EE's or their requriements, but I'll inoke @cston here :)

**Comment by saul** [comment] 2017-04-07 22:01
I think this is something we need to fix from the F# compiler side. I'm just awaiting @dsyme's comment, as I think we're setting the accessibility of property getter/setter methods incorrectly.

Types in internal modules set the property getter/setter to be private(!), whereas property getter/setter methods on types in public modules have the correct accessibility. I'm very lost in the depths of the compiler so I'm not sure I'm the best person to try and fix it :)

**Comment by dsyme** [comment] 2017-04-12 21:54
@saul Note that another fix is simply to make the debugger proxy types public in FSharp.Core.  I think that's acceptable if Roslyn don't want to make the change. 

However the fix will only be useful for an updated FSharp.Core though - I suppose FSharp.Core 4.4.2.0

**Comment by KevinRansom** [comment] 2017-04-12 21:55
I have a PR making the properties public, it should work.  We need to find out what is stopping it work with this fix.

Kevin

**Comment by saul** [comment] 2017-04-12 22:31
@dsyme it's not entirely acceptable. What happens if you want to debug F# 4.0 or prior in VS 2017? It's still broken.

**Comment by KevinRansom** [comment] 2017-04-12 22:33
We will press the debugger team to fix their issue.  However, we want a way to move forward more quickly.

**Comment by dsyme** [comment] 2017-04-12 22:33
@saul @KevinRansom Yes, agreed

**Comment by saul** [comment] 2017-04-17 18:34
Fixed in Roslyn, see #18648.

**Comment by cartermp** [comment] 2017-04-17 19:52
Nice, thanks for the work @saul!

**Closed by cartermp** 2017-04-17 19:52 UTC
Labels: Area-IDE Language Service, Area-Library, regression, Urgency-Now

**Comment by forki** [comment] 2017-04-18 05:58
Thanks so much for this!

**Comment by bradphelan** [comment] 2017-05-22 06:18
Will this appear in a future VS update or can we download something now?

**Comment by saul** [comment] 2017-05-22 16:58
@bradphelan it should already be the case with the 15.3 Preview - I haven't tried it out myself.

**Comment by cartermp** [comment] 2017-05-24 05:14
Just to confirm what @saul said: this should be in for VS 2017 Update 3.
