### ISSUE TITLE
IncrementalBuild object has already been disposed (again)

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2485] opened 2017-02-24 15:37 UTC
Current master.

A number of this assertions in a row:

![image](https://cloud.githubusercontent.com/assets/873919/23309584/505e5698-fac0-11e6-899d-e62f80b2eef6.png)

then this:

![image](https://cloud.githubusercontent.com/assets/873919/23309619/76ae7fee-fac0-11e6-8a2f-2a422768cc97.png)

then this:

![image](https://cloud.githubusercontent.com/assets/873919/23309628/812a6f78-fac0-11e6-8660-b6f9117b38a3.png)

then repeat all of the above in cycle.

**Comment by cartermp** [comment] 2017-03-05 22:44
Closing as dupe of #2472, which will remain open until this is resolved

**Closed by cartermp** 2017-03-05 22:44 UTC
