### ISSUE TITLE
Nothing works in VS 15.8 pre 3 + dev15.8 branch

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5310] opened 2018-07-08 15:14 UTC
![image](https://user-images.githubusercontent.com/873919/42421221-a295d708-82da-11e8-9bbd-372f1d5a4346.png)

Additionally, Backspace key does not work in F# editor (it does work in C# editor).

**Comment by cartermp** [comment] 2018-07-08 15:46
Was the C# document open when you opened the solution?

**Comment by vasily-kirichenko** [comment] 2018-07-08 15:51
@cartermp yes.

**Comment by cartermp** [comment] 2018-07-08 15:58
Okay. This might be a dupe of https://github.com/Microsoft/visualfsharp/issues/5170 but the stack trace suggests that there's a dependency mismatch going in with System.Collections.Immutable. We recently upgraded SCI across the whole org into 15.8 (#4996), but I don't know how this could affect f5/self-built VSIX 😕

**Comment by cartermp** [comment] 2018-07-08 16:20
@KevinRansom / @pilchie I think as a part of VS IDE test enablement, some of the dependency changes have regressed legacy F# projects. We'll have to verify that things are okay on dev15.8 P4/P5 builds, but if they are not, then existing F# projects using the legacy project system will crash when building in VS.

This issue, #5304, #5303, and #5305 all likely stem from the same problem or set of problems with the legacy project system. @teadrivendev and @isaacabraham have verified that using the latest nightly from master (which has these changes) crashes when building these F# projects.

**Comment by Pilchie** [comment] 2018-07-08 17:51
Also tagging @brettfo and @tmat  to take a look here.

**Comment by cartermp** [comment] 2018-07-27 05:17
Going to close this one on account of the project system bug fixed and infrastructure fully updated to have proper packages in place. It's likely that the issue lied in one or both of those.

**Closed by cartermp** 2018-07-27 05:17 UTC
Labels: Area-IDE Project System, Urgency-Now, regression
