### ISSUE TITLE
Alphabetical file order in VS 15.5 Preview1 for sdk projects

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3738] opened 2017-10-12 09:09 UTC
#### Repro steps

1. git clone https://github.com/SAFE-Stack/SAFE-BookStore.git
1. cd SAFE-BookStore
1. open BookStore.sln

#### Expected behavior

File order as in fspro.

#### Actual behavior

File order is alphabetical,

![image](https://user-images.githubusercontent.com/57396/31488375-c0576304-af3d-11e7-91bc-e19a7e999fe1.png)

**Comment by cartermp** [comment] 2017-10-12 15:32
Closing as a dupe of https://github.com/dotnet/project-system/issues/2793

**Closed by cartermp** 2017-10-12 15:32 UTC
