### ISSUE TITLE
NullReferenceException during solution loading

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2150] opened 2017-01-03 07:45 UTC
1. F5 on current master.
2. Load VisualFSharp.sln in the exp instance.

![image](https://cloud.githubusercontent.com/assets/873919/21602090/8eb97c62-d1a1-11e6-993c-2351c2517f8e.png)

**Comment by abelbraaksma** [comment] 2017-01-03 10:10
This may or may not be related: if the order of the source files is incorrect in any of the `fsproj` project file, this exception is known to be thrown (but I haven't been able to establish it happens in the same method): #2048.

**Comment by cartermp** [comment] 2017-01-03 16:23
Dupe of #1919

**Closed by cartermp** 2017-01-03 16:23 UTC
