### ISSUE TITLE
Running build.cmd file fails 

### ISSUE THREAD

**Issue by LmTinyToon** [Microsoft/visualfsharp#5026] opened 2018-05-29 13:29 UTC
I tried to compile project via running command 

>build.cmd debug

Performing of such comand fails with message 

>\Haskell was unexpected at this time.

I researched problem little bit, such problem arises during performing command (build.cmd file):

>call "%VS_INSTALLATION_PATH%\Common7\Tools\VsDevCmd.bat"

Is my PATH variable source of problem?

UPD: My PATH variable contained substring "\Haskell ", I just removed it before running file and it fixed problem. As I understand, script cannot correcly handle spaces?

**Comment by dsyme** [comment] 2018-05-29 23:34
Closing as I don't think we can do anything about this, the problem is in `VsDevCmd.bat`

**Closed by dsyme** 2018-05-29 23:34 UTC

**Comment by LmTinyToon** [comment] 2018-05-30 08:55
@cartermp , I runned Developer Command Promt for visual studio with administer privileges. Environment was configured properly. It seems like problem within VsDevCmd.bat file.
