### ISSUE TITLE
Wrong error line separators in console build

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4516] opened 2018-03-14 10:27 UTC
It happens consistently across different OS and terminal/console clients.

<img width="940" alt="screen shot 2017-07-18 at 19 06 54" src="https://user-images.githubusercontent.com/3923587/37396665-9a2f6d1e-278a-11e8-82da-8f01225473b0.png">
<img width="766" alt="screen shot 2017-07-18 at 19 09 43" src="https://user-images.githubusercontent.com/3923587/37396663-9a147ebe-278a-11e8-8028-cb618c1e5d08.png">

@vasily-kirichenko found this code that looks related:
https://github.com/Microsoft/visualfsharp/blob/51dac00d62a7f6f6fb714f4cef6cb3912abf58df/src/fsharp/ErrorLogger.fs#L611-L614

**Comment by auduchinok** [comment] 2018-03-14 10:29
Related Rider [issue](https://youtrack.jetbrains.com/issue/RIDER-6829):

![image](https://user-images.githubusercontent.com/3923587/37397010-9887161e-278b-11e8-8771-e9c906e004c6.png)
<img width="730" alt="screen shot 2017-07-18 at 19 12 29" src="https://user-images.githubusercontent.com/3923587/37397011-98a16e7e-278b-11e8-9148-5d32ece4f4ef.png">

**Comment by vasily-kirichenko** [comment] 2018-03-14 11:05
The code that looks responsible for this is
```fsharp
// Code below is for --flaterrors flag that is only used by the IDE

let stringThatIsAProxyForANewlineInFlatErrors = new System.String [|char 29 |]

let NewlineifyErrorString (message:string) = message.Replace(stringThatIsAProxyForANewlineInFlatErrors, Environment.NewLine)
```

**Comment by dsyme** [comment] 2018-03-14 13:52
@auduchinok This is by design I believe - the Fsc task sets `--flaterrors` and has done for at least a couple of years, I think more https://github.com/Microsoft/visualfsharp/blame/master/src/fsharp/FSharp.Build/Fsc.fs#L220

I think you're meant to de-flatten them if you want multi-line in the IDE, search around the VF# code

**Comment by dsyme** [comment] 2018-03-14 13:52
I'll close this since it's by deign

**Closed by dsyme** 2018-03-14 13:52 UTC

**Comment by auduchinok** [comment] 2018-03-14 13:54
@dsyme What about console builds? I don't think it's OK to have wrong line separators when you build without an IDE.

**Comment by dsyme** [comment] 2018-03-14 14:00
@auduchinok I know, I used to think that and it used to work like that in 2006 but the decision was otherwise. I think it's because too many build-output processing tools want single-line error output.  I don't think we should change it now.
