### ISSUE TITLE
Parallel build is broken in 15.8.2

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5576] opened 2018-08-31 13:58 UTC
1. Build a solution with many F# and C# projects.
2. Result:

A lot of the following errors: `Unhandled Exception:MSB0001: Internal MSBuild Error: Already registered for build-time`, build fails.

A work around: 

![image](https://user-images.githubusercontent.com/873919/44916714-1ca63680-ad3f-11e8-96e8-3f5b08de31de.png)

**Comment by cartermp** [comment] 2018-08-31 16:58
Closing as duplicate of #5504

**Closed by cartermp** 2018-08-31 16:58 UTC
