### ISSUE TITLE
Assert when using F# project dialog

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1908] opened 2016-12-01 16:49 UTC
Got this assert when clicking on the Build tab of the project dialog for FSharp.Editor in VisualFSharp.sln when using a debug build of the VIsual F# IDE Tools

![capture11](https://cloud.githubusercontent.com/assets/7204669/20803141/15225a60-b7e6-11e6-98c1-f45c2981fec1.PNG)

**Comment by saul** [comment] 2017-01-06 19:48
Duplicate of #2123 @cartermp

**Comment by cartermp** [comment] 2017-01-06 20:11
Closing in favor of #2123.  Thanks @saul

**Closed by cartermp** 2017-01-06 20:11 UTC
