### ISSUE TITLE
Syntax Colorizer doesn't recognise computation expressions with generic types

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#110] opened 2015-01-26 21:56 UTC
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/88) by [ashtonkj](https://www.codeplex.com/site/users/view/AshtonKJ)

The default syntax highlighter will highlight a computation expression without a generic type parameter, but once a generic type parameter is provided then the syntax highlighter will not colour the computation expression. See the following code for example (In the default Visual Studio dark theme ceBoolBuilder is coloured blue, but ceBuilder<System.DateTimeKind> is not):
```fsharp
type TestCE<'T>() =
    member this.ReturnFrom(value) =
        if System.String.IsNullOrEmpty(value) then
            None
        else
            let typeT = typeof<'T>
            if typeT.IsEnum then
                box (System.Enum.Parse(typeT, value)) |> Some
            else if typeT = typeof<bool> then
                box (bool.Parse(value)) |> Some
            else None

let ceBuilder<'T> = TestCE<'T>()
let ceBoolBuilder = TestCE<bool>()

let exampleIncorrect = ceBuilder<System.DateTimeKind> { return! System.DateTimeKind.Local.ToString() }
let exampleCorrect = ceBoolBuilder { return! "true" }
Image
```
>comments
>coza99 wrote Sep 3, 2014 at 3:54 AM [x] 
>This is also true if the builder function is parameterized. Taking the case from above an example
>```fsharp
type TextCE<'T>(name:string) = 
        ..........
let ceBuilder<'T> name = TestCE<'T>(name)
```

**Comment by latkin** [comment] 2015-01-27 02:51
@ashtonkj do you still have the image from when you originally filed this one? Seems like it's broken now: `http://namelessinteractive.com/media/Example.png`

**Comment by ashtonkj** [comment] 2015-01-29 13:43
Hi @latkin. Image attached.Sorry for the delay, just installed windows 10 and broke everything else (not window's fault, driver issue caused me to have to do a clean install).


![example](https://cloud.githubusercontent.com/assets/1762752/5958477/7efaf0d0-a7cd-11e4-8e62-a7f6252b84f9.png)

**Comment by dsyme** [comment] 2015-01-29 13:50
FWIW this was a known limitation when we implemented this colorization feature.

**Comment by ashtonkj** [comment] 2015-01-29 14:00
@dsyme does that mean it won't be changed?

**Comment by dsyme** [comment] 2015-01-29 16:20
@ashtonkj Not necessarily! It may not be that hard

**Comment by dsyme** [comment] 2015-01-29 16:21
But would reduce the priority

**Comment by dsyme** [comment] 2016-01-09 01:25
Closing this as "by design" - perhaps Visual F# Power Tools can do something here.

**Closed by dsyme** 2016-01-09 01:25 UTC
