### ISSUE TITLE
Debugging – Some values not visible in Locals or mouseover

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#4834] opened 2018-05-04 21:55 UTC
When debugging, values are often missing from the Locals window, and nothing happens when mousing over them. This is most easily reproduced with unused values, but is **by no means limited to unused values**. This happens even in debug builds with *Optimize code* turned off.

![error](https://user-images.githubusercontent.com/7766733/39654473-401d349e-4ff5-11e8-962c-90fbe1478769.gif)

#### Repro steps

[ReproSolution.zip](https://github.com/Microsoft/visualfsharp/files/1975980/ReproSolution.zip)

As seen in the gif above and in the repro solution, a simple console app with the following code will demonstrate the problem.

```f#
let f () =
  let x = 2
  let y = 3
  let z = 4
  let bar = "foo"
  x + y + z  // set breakpoint here

[<EntryPoint>]
let main argv =
  f () |> ignore
  0
```

#### Expected behavior

All local variables are visible in the Locals window and can be inspected by mouseover.

#### Actual behavior

Variables are missing from the Locals window and can not be inspected by mouseover.

#### Known workarounds

Using the problematic values in any manner seems to work most times, e.g. wrapping `problematicValue` in `Ok` seems to make `problematicValue` appear in Locals and react to mouseover (regardless of whether `problematicValue` was used or unused).

```f#
let problematicValue = ...
let foo = Ok problematicValue
```

In the code above, I think also `foo` tends to work correctly even though it's unused.

#### Related information 

I really can't remember this ever working correctly, but this report was made using VS 15.6.4 and Visual F# nightly 15.6.20180504.1.

**Comment by dsyme** [comment] 2018-05-13 01:30
@cmeeren I just tried this.  Yes, `bar` is missing at the breakpoint, but all the others are present

![image](https://user-images.githubusercontent.com/7204669/39962915-6d881a50-5655-11e8-80e4-86e4e5846d14.png)

**Comment by dsyme** [comment] 2018-05-13 01:31
@cmeeren I am assuming the RyuJIT is optimizing these away based on lifetime.  However, I wouldn't expect that to happen in debug code.

It is possible we are somehow setting slightly different flags than C#.  I assume the problem doesn't occur in C#.

**Comment by dsyme** [comment] 2018-05-13 02:53
I looked into this and it seems to me it's a problem with portable debug files.  The debugging 

This gives good results:
```
C:\GitHub\dsyme\visualfsharp>fsc --tailcalls- --debug --optimize- q.fs
Microsoft (R) F# Compiler version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.
```
This gives bad results:
```
C:\GitHub\dsyme\visualfsharp>fsc --tailcalls- --debug:portable --optimize- q.fs
Microsoft (R) F# Compiler version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.
```
where `q.fs` contains the code above

@KevinRansom Do you want to take a look at this?

**Comment by cmeeren** [comment] 2018-05-13 17:26
Hm, I am now unable to reproduce using the repro solution with VS 15.7.1, F# tools 15.7.0.0 commit 16ecf

**Comment by cartermp** [comment] 2018-05-13 17:32
@cmeeren I'll leave this open for now tagged as needs-repro, and after a week or so we can close this out if there isn' a repro.

**Comment by cmeeren** [comment] 2018-05-13 17:34
@dsyme you managed to repro - what versions of VS/F# did you use?

**Comment by dsyme** [comment] 2018-05-13 23:01
I used 15.6.7 
* .NET Core portable symbols (repro) 
*  .NET Framework portable symbols (repro)
* .NET Framework full symbols (no repro)

**Comment by cmeeren** [comment] 2018-05-14 06:29
Could you see if you get similar results using 15.7? If not, then the issue might be fixed. If you can repro on 15.7, then my failure to repro was caused by something else and the issue labels should be reverted.

**Comment by cartermp** [comment] 2018-07-24 16:19
This is no longer reproducible with .NET Core + Portable PDBs with 15.7.5.

![image](https://user-images.githubusercontent.com/6309070/43152127-878abf42-8f22-11e8-84d8-4a88d3e9e920.png)

@cmeeren since you could not reproduce this either, I'll close the issue out.

**Closed by cartermp** 2018-07-24 16:19 UTC
Labels: Area-DotNetCore, needs repro
