### ISSUE TITLE
Seeing weird error messages in VS 15.5 preview 3

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3899] opened 2017-11-07 09:45 UTC
![image](https://user-images.githubusercontent.com/57396/32487026-b68e9f84-c3a8-11e7-847c-a9621e5ccc93.png)

Severity	Code	Description	Project	File	Line	Suppression State
Error	FS3160	Problem reading assembly 'D:\code\Paket\bin\Paket.Core.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1007; Id 1008; Id 1009; Id 1010; Id 1011|], Id 1013,
 false, None)).	Paket.IntegrationTests	D:\code\Paket\integrationtests\Paket.IntegrationTests\BasicResolverSpecs.fs	1	Active

**Comment by cartermp** [comment] 2017-11-07 16:07
Closing as dupe of #3545

**Closed by cartermp** 2017-11-07 16:07 UTC
