### ISSUE TITLE
VS 2019 16.0.0 RC.3/Preview 4.3 freezes frequently when Intellisense active while editing F#

### ISSUE THREAD

**Issue by BentTranberg** [Microsoft/visualfsharp#6341] opened 2019-03-20 08:30 UTC
I updated to VS 2019 Preview 4.3, and also installed the corresponding RC.3. They both permanently froze (hung) typically only a minute or two into editing, so I could not really get much work done.

I turned off the status bar, because I suspected it could be related to issue #6335 that I opened a few days ago. It didn't help, which makes sense, because this behaves differently. There could be some behavioral pattern while I edit, but if so I haven't noticed what it is.

Just like in issue #6335, when the freeze occurs, there is a message in the status bar that reads "Locating the symbol under the caret...". This makes me think Intellisense is involved, so in the Error List pane I changed from "Build + Intellisense" to "Build Only". **I have not had any freezes after that.**

I do not know if this issue belongs here or in some other repo. I mostly work with F# and XAML - very little C# (minimal code behind) and no VB. In earlier previews (edit: and now also once in this latest) I've had freezes while working with XAML. I have not tried reproducing this issue while editing other code than F#.

**Comment by Pilchie** [comment] 2019-03-20 16:23
@TIHan @cartermp ping - can you work with @BentTranberg to get a trace to look at?

**Comment by TIHan** [comment] 2019-03-20 18:08
Hey @BentTranberg , thank you for testing and reporting. There are a couple of things you can do:

If it freezes again, you can try ProcDump, https://docs.microsoft.com/en-us/sysinternals/downloads/procdump, - more info on minidumps: https://www.wintellect.com/how-to-capture-a-minidump-let-me-count-the-ways/

Also, you can use this reg file, https://github.com/dotnet/project-system/blob/master/docs/repo/content/AlwaysSaveDevEnvCrashDumps.reg that will automatically save crash dumps if you get any crashes.

**Comment by BentTranberg** [comment] 2019-03-20 19:40
I have no experience with ProcDump. I see that I can run `procdump devenv.exe devenv.dmp` and get a dump file when VS is ok, but I also see there's a parameter `-h` for hung processes. It looks like it just waits for VS to get hung then. I can't easily test what will produce a dump on a hung VS at the moment, because on my home computer I don't have these hangs frequently enough. I'll be back at work in around 10 hours, and then I guess I'll have some results pretty quickly.

**Comment by TIHan** [comment] 2019-03-20 20:59
Take your time. Let me know if you have more questions.

**Comment by penguid** [comment] 2019-03-21 02:15
I have also experienced freezes while editing F# code in RC.3. Occurs even with status bar turned off. 

It has occurred both:
1. With a "Please wait for an editor command to finish..." dialog whose Cancel button does not respond to input.
2. Without a dialog.

I have taken procdumps of both occurrences. They are about 40 MB files. Let me know if I should do anything with them.

**Comment by BentTranberg** [comment] 2019-03-21 12:04
I switched back to "Build + IntelliSense" in the Error List this morning, and haven't had a single freeze/hang today - around 6 hours editing.

With my limited knowledge, the only possible cause for this that I can think of is that files in the .vs, bin and obj folders can perhaps cause problems when updating VS. Eventually old files will be overwritten, and problems go away. I've experienced that more than once or twice during the years I've been using VS. Not saying this is likely - only a possibility.

**Comment by TIHan** [comment] 2019-03-21 19:02
@penguid You could send the dumps over our way if they don't contain anything what would have to be under NDA, I just don't know where you should upload it. I'll ask around.

@BentTranberg The seems interesting. This is basically what happened to another dev. The first time they used it, it froze, but after that it never froze again, even after 3 weeks of usage.

**Comment by BentTranberg** [comment] 2019-03-21 20:00
Next time somebody experiences this, it might be a good idea to create a backup of not just the source, but also the binaries in `.vs`, `obj` and `bin`. (Any other folders of interest?) Based on what little we know so far, that might give a better chance of reproduce the problem more consistently and _ad infinitum_ for research.

On the bright side, I'm happy the problem is gone on both my development computers now. I am thinking perhaps checking out a clean working copy is an instant workaround slash fix with no drawbacks.

**Comment by penguid** [comment] 2019-03-21 21:48
@TIHan Here is a project that repros fairly consistently on my system even with fresh clone: https://github.com/penguid/vs2019rcfreeze

1. Open Server3.sln
2. Open Giraffe3\Json.fs
3. Click on `okRaw` identifier (line 12)
4. Press CTRL+ENTER -- usually freezes here

If no freeze right away, click around on different identifiers and occasionally hit CTRL+ENTER and CTRL+L to add and delete lines. Try other files too. If no repro within a couple minutes, close VS and start over.

If you/others can't repro then I can send the dumps, no NDA concerns but preferably somewhere private as I don't know what personal info is in there.

**Comment by cartermp** [comment] 2019-03-21 21:54
@penguid I can't speak for the status bar setting, but that sounds like the root issue in #6335

ctrl when the caret is over a symbol will asynchronously find its definition so that when you click on the identifier, it will go to definition. This process posts a message to the VS status bar service saying it is navigating to the definition of the symbol. Due to an issue in the status bar service, this can cause VS to deadlock. #6339 disables all our message posting to just be no-ops, so it should resolve what you have said.

Do you see this under any circumstances when ctrl is _not_ pressed or held down? If so, that would indicate a different issue also occuring.

**Comment by cartermp** [comment] 2019-03-21 22:02
@penguid Can you confirm that you turned this setting off _and_ restarted VS? I can reproduce your freeze as described if it is on, but if I turn it off I cannot reproduce it. I also cleared the .vs folder, forcing a first-time solution load where I first saw it.

![image](https://user-images.githubusercontent.com/6309070/54787868-59a61d80-4bea-11e9-869f-b9d00afb1a8d.png)

**Comment by penguid** [comment] 2019-03-21 22:13
@cartermp Offhand I don't recall it occurring without using ctrl key (but I wasn't paying much attention at first so I can't say for certain).

**Comment by penguid** [comment] 2019-03-21 22:30
@cartermp Yep it is off and restarted (normal restart, not via killing a hung process). To double check, I just now: turned it on, restarted normally, turned it off, restarted normally, verified the setting was off, then tried my repro steps. After two more normal restarts where it didn't repro, a third restart resulted in another repro, with the setting off.
![image](https://user-images.githubusercontent.com/48609714/54788890-bdd2dc80-4bfe-11e9-84cc-668a9bf91471.png)

**Comment by BentTranberg** [comment] 2019-03-23 08:32
Finally got a hang. I'm learning Hopac from scratch this weekend, so this is a very small sample application I just got started, which is ideal for a repro. I was pasting in some more sample code, and then VS froze. Then I ran this: `procdump.exe devenv.exe vs2019.dmp`

**TestHopac.zip** - contains the source and folders .vs, bin and obj. I included the three extra folders in case they can provide any clues.
**vs2019.dmp** - sent as zip partitions zipped. Explanation follows.

To get around the 10 meg limit on GitHub, I used 7z to zip vs2019.dmp into partitions. Then I zipped each partition into a zip again, because the number file extensions are not accepted by GitHub. If there is a better way you want me to use to transfer the dump file, let me know.

[TestHopac.zip](https://github.com/Microsoft/visualfsharp/files/2999147/TestHopac.zip)
[vs2019.zip.001.zip](https://github.com/Microsoft/visualfsharp/files/2999161/vs2019.zip.001.zip)
[vs2019.zip.002.zip](https://github.com/Microsoft/visualfsharp/files/2999162/vs2019.zip.002.zip)
[vs2019.zip.003.zip](https://github.com/Microsoft/visualfsharp/files/2999159/vs2019.zip.003.zip)
[vs2019.zip.004.zip](https://github.com/Microsoft/visualfsharp/files/2999160/vs2019.zip.004.zip)

**Comment by BentTranberg** [comment] 2019-03-23 09:04
Instructions for reproducing hang with repro **TestHopac.zip**.

In file Lesson1.fs, the goal is to add another module at the end. This module should look like this.

```
module Lesson1d =

    type Product = { Id: int; Name: string }

    let getProduct id = job {
        do! timeOutMillis 2000 // Delay in the place of DB query logic for brevity
        return {Id = id; Name = "My Awesome Product"}
    }

    type Review = { ProductId: int; Author: string; Comment: string }

    let getProductReviews id = job {
        do! timeOutMillis 3000 // Delay in the place of an external HTTP API call
        return [
            {ProductId = id; Author = "John"; Comment = "It's awesome!"}
            {ProductId = id; Author = "Sam"; Comment = "Great product"}
            ]
        }
```

I am pasting the code within the module from this page, from the two boxes below the headline "A Real World Example" : https://www.demystifyfp.com/fsharp/blog/concurrent-programming-in-fsharp-using-hopac-part-1/

As you can see, the original code is not formatted in the style I want, and with the indents I need. It is when I try to paste from the boxes and then start to manually reformat (prettify) the code, that VS hangs at some point.

Copy from the first box on the web page, then paste, and then manually reformat. The do the same with the code from the second box on the web page.

I can see from repeatedly trying, that VS hangs at certain points in my editing routine, and I suspect it is always when I edit inside the brackets of the two types.

Manually editing in Notepad, and then pasting, is a workaround.

**Comment by BentTranberg** [comment] 2019-03-29 07:56
Situation report: I've been at 16.0.0 RC.4 from the moment it was available and have had maybe two or three freezes, and they could just as well - or even more likely in fact - be with the XAML hang issue(s) which are more aggressive - difficult to see. Considering how much I code each day, this is very good statistics compared to the situation I had when I first reported this. I am running with "Build + IntelliSense" in the Error List, and with the status bar enabled (that's another issue - temporarily fixed I believe).

**Comment by nhirschey** [comment] 2019-04-27 12:55
Just to add another data point, I'm constantly getting freezes where VS is "waiting for the editor to complete". It happend on 16.1 Preview 1, and I'm getting it on 16.1 Preview 2 as well. Today after installing Preview 2, it is particularly bad. I've had constant freezing for the past 1.5 hours after repeated restarts of VS trying to fix things. 

I turned off the status bar as suggested. Windows gives me a message that the freeze is being reported to the Visual Studio teams, so hopefully you get some debugging information with that.

I'm on a script, using SAS and Csv type providers. I updated to Csv Provider 3.1.1, but that's not helping.

**Comment by cartermp** [comment] 2019-04-27 15:28
The issue with the status bar is resolved via a workaround (we simply don't update it at the moment). When the VS platform side of things resolves it, we can re-enable that on our end.

@nhirschey VS 16.1 preview 1 had issues with F#, and although we think preview 2 resolved them, our final payload of bug fixes and perf improvements is in preview 3. I have two questions:

1. Do you see equivalent issues with VS 16.0.x?
2. Do you see this issue with "normal" F# files, or only script files?

**Comment by nhirschey** [comment] 2019-04-27 15:49
Hi @cartermp, thanks for checking up with me so quickly. 

I think I actually tracked this down to the Csv type provider causing the intellisense and editor to freeze. I was using it in a small script with InferRows = 100_000 for typing the columns. When I comment this out, things seem to work whereas earlier today  I was in a situation where I'd hang VS 2017 also.

I'm working on getting rid of the type provider in this code now--I'll update if it turns out this is not a fix.

I've been experiencing less extreme versions of this behavior on and off with 2019, but it is also in scripts that use the Csv type provider a lot.

**Comment by cartermp** [comment] 2019-04-27 16:22
Thanks, that helps. It's good to know that we're not regressed w.r.t VS 2017 here. I'll close this out and file a new issue about the CSV provider so we can track that separately.

**Comment by cartermp** [comment] 2019-04-27 16:24
Tracking via #6646

**Closed by cartermp** 2019-04-27 16:24 UTC

**Comment by BentTranberg** [comment] 2019-04-27 16:56
@cartermp, #6646 is not related to this issue as originally reported as far as I can understand, so now I'm wondering if you were too hasty in closing this. If not, and it should stay closed, is there some other issue we can watch to check on the status of the workaround mentioned? I assume it's a temporary workaround, and will be permanently fixed later.

This is not a big deal for me. It's just that I like to follow issues where I'm involved until their final resolution, in case I can assist in any way. Actually I have been thinking about suggesting this being closed, so I'm definitely not arguing that it stays open.

**Comment by cartermp** [comment] 2019-04-27 17:28
@BentTranberg See here: https://github.com/Microsoft/visualfsharp/issues/6341#issuecomment-487295192

> The issue with the status bar is resolved via a workaround (we simply don't update it at the moment). When the VS platform side of things resolves it, we can re-enable that on our end.

**Comment by BentTranberg** [comment] 2019-04-27 17:49
Yes, that is your comment that I was referring to - "workaround mentioned". I take it then there's no issue dealing with the status of that workaround. It's ok - thanks. Btw, I haven't had any freezes of any kind since my last report, and VS and F# continues to improve. VS 2019 with corresponding F# was an enormous step forward. Thanks to everyone involved.

**Comment by cartermp** [comment] 2019-04-27 17:51
Gotcha, I thought you were referring to a user workaround. No status update on when the VS Platform addresses this issue and we can go back to updating the status bar at the moment. Thanks for sticking with this here, and I'm glad things are better!
