### ISSUE TITLE
15.3 preview 4: broken tooltip glyphs 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3334] opened 2017-07-14 17:52 UTC
![image](https://user-images.githubusercontent.com/873919/28224039-4e2f5b36-68d6-11e7-8f7f-0e50d8091471.png)

It shows "A" for any kind of symbol.

**Comment by cartermp** [comment] 2017-07-14 18:31
I cannot reproduce this.  Perhaps your install had an issue?  I'm running Preview 4

![no-repro](https://user-images.githubusercontent.com/6309070/28225532-e2ff6b4c-6887-11e7-8bbc-6ceae98008f5.gif)

```
Microsoft Visual Studio Community 2017 Preview
Version 15.3.0 Preview 4.0
VisualStudio.15.Preview/15.3.0-pre.4.0+26711.1
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA444
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA444
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA444
Microsoft Visual F# 4.1

ASP.NET Template Engine 2017   15.0.30629.0
ASP.NET Template Engine 2017

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   4.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
```

**Comment by vasily-kirichenko** [comment] 2017-07-14 19:11
```
Microsoft Visual Studio Enterprise 2017 Preview (2)
Version 15.3.0 Preview 4.0
VisualStudio.15.Preview/15.3.0-pre.4.0+26711.1
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA591
Microsoft Architecture Diagrams and Analysis Tools

Visual Basic 2017   00369-60000-00001-AA591
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA591
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA591
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA591
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.8.00629.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30629.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30629.0
ASP.NET Template Engine 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50601.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30623.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50628.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.3.4.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake
```

**Comment by vasily-kirichenko** [comment] 2017-07-14 19:13
It's broken on Core 2.0 projects only.

**Comment by cartermp** [comment] 2017-07-14 19:16
Yep, that's what I'm using.  I can't repro the issue - tooltips are correct for me.  The 'A' was an issue a while back when we didn't have updated Roslyn references, but that was updated a while ago and I haven't seen it since.

**Comment by vasily-kirichenko** [comment] 2017-07-14 19:44
Ah, that's manually built OSS VSIX installed itself into both 15.2 and 15.3, super nice.

**Comment by cartermp** [comment] 2017-07-14 19:53
Okay.  Closing in favor of #3336

**Closed by cartermp** 2017-07-14 19:53 UTC
Labels: needs repro
