### ISSUE TITLE
MailboxProcessor messages are not recieved when posted via Array.Parallel

### ISSUE THREAD

**Issue by Wkalmar** [Microsoft/visualfsharp#4672] opened 2018-04-03 19:33 UTC
Hi. I've run into several equally confusing issues when running simple console app using F# and .NET core 2.0 which I've created in VS2017. 
Sorry if I'm missing some basic concepts because anyways somebody might run into similar issues and get scared away by the amount of confusion produced
1) Consider the following code
```
open System.IO

let agent = MailboxProcessor.Start(fun inbox ->
    let rec messageLoop() = async {
        let! msg = inbox.Receive()
        File.AppendAllLines("output.txt", [msg])
        return! messageLoop()
    }
    messageLoop()
)

let doStuff() =
    [|1..10|]
    |> Array.Parallel.iter(fun i -> agent.Post (i.ToString()))

[<EntryPoint>]
let main argv =
    doStuff()
    0
```
Expected result:
All 10 digits are written to file
Actual:
Nothing is written to file.
2. Now let's remove those braces:
```
open System.IO

let agent = MailboxProcessor.Start(fun inbox ->
    let rec messageLoop() = async {
        let! msg = inbox.Receive()
        File.AppendAllLines("output.txt", [msg])
        return! messageLoop()
    }
    messageLoop()
)

let doStuff =
    [|1..10|]
    |> Array.Parallel.iter(fun i -> agent.Post (i.ToString()))

[<EntryPoint>]
let main argv =
    doStuff
    0
```
Expected:
Program finishes quickly, all digits are written to the file
Actual:
Program writes some digits and fails to finish

3. Now let's remove do stuff call from main
```
open System.IO

let agent = MailboxProcessor.Start(fun inbox ->
    let rec messageLoop() = async {
        let! msg = inbox.Receive()
        File.AppendAllLines("output.txt", [msg])
        return! messageLoop()
    }
    messageLoop()
)

let doStuff =
    [|1..10|]
    |> Array.Parallel.iter(fun i -> agent.Post (i.ToString()))

[<EntryPoint>]
let main argv =
    0

```
Expected: 
No digits are written, program finishes quickly
Actual:
Some digits are written program fails to finish

Why does this happen? Is main method ignored? Is there any exception due to multiple file access being swallowed inside the agent? 
Looking forward to see some clarifications. Thanks in advance

**Comment by isaacabraham** [comment] 2018-04-03 20:04
I'm pretty sure that this happens because Mailbox Processors run asynchronously i.e. in the background. Posted messages to the mailbox are (by default) fire-and-forget, so your console application finishes executing its entry point function (and thus shuts down the entire process) *before* the mailbox processor has actually had a chance to process the 10 messages.

Try putting some logging in and you'll see what I mean e.g.

```fsharp
open System.IO

let agent = MailboxProcessor.Start(fun inbox ->
    let rec messageLoop() = async {
        let! msg = inbox.Receive()
        printfn "Received: %s" msg
        File.AppendAllLines("output.txt", [msg])
        printfn "Written: %s" msg
        return! messageLoop()
    }
    messageLoop()
)

let doStuff() =
    [|1..10|]
    |> Array.Parallel.iter(fun i ->
        printfn "Sending: %d" i
        agent.Post (i.ToString()))

[<EntryPoint>]
let main argv =
    printfn "Entering main"
    doStuff()
    printfn "Completed doStuff()"
    0
```

You'll find that "Completed doStuff()" will get printed before the "Written..." messages have all been processed.

The second version gets a few lines written because you've removed the `()` from `doStuff`, so it becomes a simple value and gets immediately evaluated before `main` even starts, so in effect, the mailbox processor starts processing messages immediately. As your code shows, you can remove the reference to `doStuff` from main (example 3) and the behaviour is the same.

Example 1 is the "correct" way I would do it, and yhis is actually the whole point of the Mailbox Processor - you send messages without worrying about them completing. Since you're running in a console app though, it's obviously not ideal, but you can "fix" this in a few ways - either you can put some code in `main` after the call to `doStuff()` which blocks for a few seconds, or waits for the keyboard input, or until the MailboxProcessor's queue length is 0 or similar. Or, you can change from calling `Post` to `PostAndReply`, but this effectively hampers your parallelism (or at least the asynchronousity).

Hope that helps.

**Comment by dsyme** [comment] 2018-04-04 13:29
@isaacabraham's reply is correct - closing as by design

**Closed by dsyme** 2018-04-04 13:29 UTC
