### ISSUE TITLE
Migrate fsharpqa Tests to XUnit 2.0 and CoreCLR

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#697] opened 2015-10-22 19:26 UTC

**Comment by KevinRansom** [comment] 2015-10-25 07:08
@enricosada  It's worth investigating the coreclr implementation of nunit.  I doubt that converting the specific test framework will be anywhere near as hard as making the tests work on coreclr.  But nunit is perfectly decent framework.  The main goal is really to get this stuff working cross platform.

**Comment by ctaggart** [comment] 2015-10-25 20:56
I just confirmed that NUnit 3.0.0-beta-5 does not have coreclr support. It looks like it will be in their release candidate. https://github.com/nunit/nunit/issues/575

**Comment by enricosada** [comment] 2015-10-30 10:39
I can do that after #90, using the same approach, converting the perl script in f#
Lots of code already wrote for cambridge suite can be reused (tags, config, exec of fsi/fsc, etc)

**Comment by enricosada** [comment] 2016-01-07 17:18
i'll post something on sunday /cc @otawfik-ms 

it's a wip, common case works, others ( for example these with redirection, rare options or quirks ) not.

same flow as fsharp suite:

- nunit runner
- read test list from test.env
- convert run.pl perl script to fsharp
-, can be run in parallel as old perl runner

**Comment by dsyme** [comment] 2018-02-24 00:41
I'm going to close this.  We need to migrate the fsharpqa suite away from perl but we don't need to track this with an item so specific

**Closed by dsyme** 2018-02-24 00:41 UTC
Labels: Area-DotNetCore, infrastructure
