### ISSUE TITLE
Cannot update FSharp.Core in .NET Standard classlib using VS15.5 Preview 4

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#4028] opened 2017-11-28 14:43 UTC
It doesn't seem possible to propertly update FSharp Core in .NET standard class libraries when using 15.5 Preview 4.

1. Start VS15.5 preview 4
2. Create a new F# .NET Standard 2.0 class library
3. RIght click project -> Manage NuGet packages
4. Update Fsharp.Core (was 4.2.0 in template, available now is 4.2.3)
5. Nothing seems to happen. It still shows as "update available", with 4.2.0 being installed.
6. Note however in the actual fsproj file that there's now a reference to FSharp.Core 4.2.3 (there was no reference at all previously).

Here's a screenshot of the NuGet window in case it's helpful.

![image](https://user-images.githubusercontent.com/7766733/33325838-b3eb52ca-d453-11e7-8698-d06e143e15f9.png)

**Comment by dhwed** [comment] 2017-11-28 15:25
This is a duplicate of #3656

**Closed** 2017-11-28 16:50 UTC
