### ISSUE TITLE
Structuctured printing of DU values with [<RequireQualifiedAccess>] elides DU name

### ISSUE THREAD

**Issue by isaksky** [Microsoft/visualfsharp#2958] opened 2017-04-30 01:30 UTC
Related: https://github.com/Microsoft/visualfsharp/issues/2957

When using `sprintf "%A"` with DU values, the name of the DU is missing.

#### Repro steps
```fsharp
type [<RequireQualifiedAccess>] MyDU = Yes | No
sprintf "%A" MyDU.Yes
```
#### Expected behavior

Including the name of the DU, like we have to do in valid code:

`val it : string = "MyDU.Yes"`

#### Actual behavior

It only prints the case name:

`val it : string = "Yes"`

This also occurs when using `any_to_string` from `sformat.fs`.

#### Discussion

In general, it would be nice if F# structured printing always printed out valid F# syntax, except when there's is a very good reason not to (e.g., like eliding most values in massive lists). This would be very useful when using the REPL, allowing printing out difficult to construct values that one could then paste into source code for unit tests, for example. I've have done this many times, but then have had to clean up all the syntax deviations like the above.

**Comment by dsyme** [comment] 2017-05-02 09:50
This is similar to https://github.com/Microsoft/visualfsharp/issues/2957 which I closed as "too likely to be a breaking change"

@cartermp What do you think about this one?  I feel it is also too likely to be a breaking change.

**Comment by cartermp** [comment] 2017-05-02 16:01
Interesting.  We're saying that people who are relying on the output of `%A` from a `sprintf` or `printf` function to _not_ include the name of the DU could now be broken.  I'm a bit on the fence about this, because this isn't technically breaking the behavior of the format.  If the underlying pretty printer gets smarter, then that's certainly an improvement.  Since I have no data to base a decision on, this is really just a gut call.  @jaredpar, would you have any advice here?

**Comment by isaksky** [comment] 2017-05-02 16:17
A related issue, for which a fix could also be a breaking change:

> sprintf "%A" None;;
val it : string = "<null>"

It would be a bummer to have to live with this forever. Do we need `sprintf2`?

**Comment by jaredpar** [comment] 2017-05-02 16:53
The one scenario that comes to mind for breaking change is code generators.  A code generator could reasonably depend on the format of this outputted string. 

How likely is that though ... I'd say probably fairly unlikely.  But that's just a gut feeling.

**Comment by dsyme** [comment] 2017-05-02 20:11
> How likely is that though ... I'd say probably fairly unlikely. But that's just a gut feeling.

For enums - I'd say very like (think dayOfWeek.ToString()). 

For non RequireQualifiedAccess DUs I'd also say very likely

For RequireQualifiedAccess DUs - still quite likely (too much for my liking ha ha)

**Comment by dsyme** [comment] 2017-05-06 23:57
I'll close this as by design. The likelihood of a breaking change seems too high, and the value is not great enough if we can't address cases such as enums.

**Closed by dsyme** 2017-05-06 23:57 UTC
Labels: Area-Compiler
