### ISSUE TITLE
Build failure building F# OSS codebase with CTP 5 installed

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#135] opened 2015-01-27 01:42 UTC
Fails to build the fsc-proto compiler: with the following spew

__msbuild src\fsharp-proto-build.proj__

CoreCompile:
  ..\..\..\lkg\FSharp-4.0.30319.1\bin\fsc.exe -o:obj\Proto\net40\FSharp.Build-proto.dll -g --noframework --define:DEBUG --define:NO_STRONG_NAMES --de
  fine:NO_STRONG_NAMES --define:NO_STRONG_NAMES --define:BUILDING_WITH_LKG --define:DEBUG --define:NO_STRONG_NAMES --define:OPEN_BUILD --define:FSHAR
  P_CORE_4_5 --define:FX_ATLEAST_45 --define:FX_ATLEAST_40 --define:FX_ATLEAST_35 --define:BE_SECURITY_TRANSPARENT --define:QUERIES_IN_FSLIB --define
  :PUT_TYPE_PROVIDERS_IN_FSCORE --define:FX_ATLEAST_LINQ --doc:..\..\..\Proto\net40\bin\FSharp.Build-proto.xml --optimize+ --resource:obj\Proto\net40
  \FSBuild.resources -r:C:\visualfsharp\lkg\FSharp-4.0.30319.1\bin\FSharp.Core.dll -r:"C:\Program 
  ...

C:\visualfsharp\src\fsharp\FSharp.Build\Fsc.fs(256,14): error FS0034: Module 'Microsoft.FSharp.Build' contains     member Fsc.Sources : '_a     but i
ts signature specifies     member Fsc.Sources<'a0> : 'a0 []     The respective type parameter counts differ [C:\visualfsharp\src\fsharp\FSharp.Build-
proto\FSharp.Build-proto.fsproj]

C:\visualfsharp\src\fsharp\FSharp.Build\Fsc.fs(252,14): error FS0034: Module 'Microsoft.FSharp.Build' contains     member Fsc.Resources : '_a     but
 its signature specifies     member Fsc.Resources<'a0> : 'a0 []     The respective type parameter counts differ [C:\visualfsharp\src\fsharp\FSharp.Bu
ild-proto\FSharp.Build-proto.fsproj]

C:\visualfsharp\src\fsharp\FSharp.Build\Fsc.fs(243,14): error FS0034: Module 'Microsoft.FSharp.Build' contains     member Fsc.References : '_a     bu
t its signature specifies     member Fsc.References<'a0> : 'a0 []     The respective type parameter counts differ [C:\visualfsharp\src\fsharp\FSharp.
Build-proto\FSharp.Build-proto.fsproj]
  Exiting - too many errors
Done Building Project "C:\visualfsharp\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj" (Rebuild target(s)) -- FAILED.

**Comment by KevinRansom** [comment] 2015-01-27 01:45
It's actually caused by not having MSBuild from Visual Studio 2013 installed.

Kevin

**Comment by dungpa** [comment] 2015-01-27 13:12
I installed Microsoft Build Tool 2013 but the build still fails:

> FSC : error FS0082: The primary reference "C:\Windows\Microsoft.Net\assembly\
GAC_MSIL\Microsoft.Build\v4.0_12.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.dll" c
ould not be resolved because it has a higher version "12.0.0.0" than exists in
the current target framework. The version found in the current target framework
 is "4.0.0.0". (Code=MSB3257)

It seems to work on a machine with both VS 2013 and VS 2015 CTP 5 installed.

**Comment by dsyme** [comment] 2015-02-01 16:24
This looks like a duplicate of https://github.com/Microsoft/visualfsharp/issues/182?

**Comment by latkin** [comment] 2015-02-02 18:33
Yes, seems same as #182

**Closed by latkin** 2015-02-02 18:33 UTC
Labels: duplicate, infrastructure
