### ISSUE TITLE
Unhandled Exception: System.TypeInitializationException: when comipled for x64 pltaform

### ISSUE THREAD

**Issue by pramodkumarhk** [Microsoft/visualfsharp#2224] opened 2017-01-10 23:23 UTC
[Program.txt](https://github.com/Microsoft/visualfsharp/files/697635/Program.txt)
Please rename the file from.txt to .fs

#### Repro steps ####

1. Use the F# complier  to compile the file attached "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe" -o:repro.exe  Program.fs --platform:x64 

2. When we run the exe that is generated from the above command it fails with following error

Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$repro>.$Program' threw an exception. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Program.parseFixTo_BigStruct(FieldsWrapper fields)
   at <StartupCode$repro>.$Program..cctor()
   --- End of inner exception stack trace ---
   at Program.main(String[] argv)

#### Expected behavior ####

Exe should run fine without error

#### Actual behavior ####

Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$repro>.$Program' threw an exception. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program

#### Known workarounds #### 

If you set the  platform to X86 then there is no exception as below.

"C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe" -o:repro.exe  Program.fs --platform:x86 

#### Related information 

Provide any related information 

* Operating system: Windows 10 with anniversary update
* .NET Runtime, 4.6.2
* Editing Tools (e.g. Visual Studio Version) - VS2015 Update 3

**Comment by KevinRansom** [comment] 2017-01-10 23:54
This looks like a jit bug, Russel will look at it ... although I don't know his GitHub alias.
I added a repro.exe.config:

@pramodkumarhk  a work around is to use the config below with : uselegacyJit enabled = 1

````
<configuration>
    <runtime>
      <useLegacyJit enabled="1" />
    </runtime>
  </configuration>
````
with uselegacyJit enabled = 0 it goes bang!!!!
with uselegacyJit enabled = 1 it goes harmoniously

I have also attached a built .exe and fsharp.core.dll for Russ.

[repro.zip](https://github.com/Microsoft/visualfsharp/files/697685/repro.zip)


Kevin

**Comment by pramodkumarhk** [comment] 2017-01-13 21:53
Thanks for the update Kevin. The suggested work around does resolves the issue.

I was just wondering whether this will get resolved in the upcoming version of .NET framework? Probably Russel is the one who can address this query better.

**Comment by dsyme** [comment] 2017-06-22 13:47
@cartermp Do we have a tacking .NET JIT bug for this? thanks

**Comment by cartermp** [comment] 2017-06-22 15:57
Not sure.  @KevinRansom have you confirmed that this is being looked at by the JIT team?

**Comment by forki** [comment] 2017-06-27 14:29
can we cc someone or raise it somewhere else?

**Comment by dsyme** [comment] 2017-06-27 16:21
@forki I've opened a bug here: https://github.com/dotnet/coreclr/issues/12480

I'll close this as external

**Closed by dsyme** 2017-06-27 16:21 UTC
Labels: Area-External
