### ISSUE TITLE
Wrong tooltip font

### ISSUE THREAD

**Issue by breyed** [Microsoft/visualfsharp#2756] opened 2017-03-31 15:13 UTC
Installing the nightly Visual F# Tools visx causes tooltip fonts to be lost.

#### Repro steps

1. Install VS2017 RTW.
2. Set Text Editor font to 11 pt Calibri.
3. Install today's Visual F# Tools nightly build.
4. Hover over an error of symbol in an F# file.

#### Expected behavior

Nice looking tooltips.

#### Actual behavior

Big honking tooltips with 11 pt Consolas.

Interestingly, Tools > Options shows the standard (I think - or did I customize it?) 9 pt Segoe UI. In any case, what's shown in Tools > Options definitely doesn't match what's in use.

#### Known workarounds

Change the Editor Tooltip font to something else and then change it back to Segoe UI.

**Comment by cartermp** [comment] 2017-03-31 16:21
@breyed Every once in a while I'd get a blown-up FSI font with the default F# Tools install.  I can't say I know what the cause is.  Perhaps this is related in some way?  I've never seen this happen before.

What happens if you uninstall that VSIX and then reinstall?

**Comment by breyed** [comment] 2017-03-31 17:30
I tried uninstalling the nightly build, but after it was done, when I reopened VS, it still shows the nightly build F# extension. Not sure if it's related to being on the nightly NuGet feed, but it's more time consuming to debug than I can take on right now.

**Comment by cartermp** [comment] 2017-03-31 18:31
If you use VSIXInstaller it should get rid of it for you.  The nightly VSIX is installed in `%AppData%`, and Visual Studio basically uses that one to override the VSIX which is deployed via the Visual Studio Installer.  Running `VSIXInstaller.exe /u:VisualFSharp` should remove the VSIX in `%AppData%`.  You'll have to restart Visual Studio to see the changes, though.

**Comment by majocha** [comment] 2017-03-31 18:35
@breyed try cycling dark/light modes. I've seen this bug in Visual Studio 2017 also without F# Tools.

**Comment by majocha** [comment] 2017-03-31 18:39
I believe it's related to this:
[https://github.com/dotnet/roslyn/blob/45c60edef9ddc10dd2e15c668ea4ab4cec22141b/src/VisualStudio/Core/Def/HACK_ThemeColorFixer.cs#L11-L20](https://github.com/dotnet/roslyn/blob/45c60edef9ddc10dd2e15c668ea4ab4cec22141b/src/VisualStudio/Core/Def/HACK_ThemeColorFixer.cs#L11-L20)

**Comment by breyed** [comment] 2017-03-31 18:42
I had clicked Uninstall on it in the VS Extensions and Updates dialog. This brought up the VS Installer to remove the component.

**Comment by cartermp** [comment] 2017-03-31 18:45
@breyed Ah, yes, that would likely remove the release version of the Visual F# Tools.  Basically:

VSIXINstaller --> remove the nightly
VS Installer or Tools/Extensions --> remove the RTM Visual F# Tools

It's a bit confusing.  There's currently three ways to remove something, only one of which removes the nightly.  Consolidating these setup problems in the VS Installer is an area that the VS Platform as a whole is looking to improve with the next major iteration of the VS Installer.

**Comment by breyed** [comment] 2017-03-31 18:51
I had just discovered as much. I removed nightly, run VS again to verify tooltips are as expected, reinstalled night, ran VS again, and this time the tooltips are still fine. So I'm unable to repro at this point short of a full VS reinstall.

If there is work on the issue that @majocha identified, I think it would make sense to see that through first, and then wait to see if anyone experiences this specific F# font sizing issue again.

**Comment by majocha** [comment] 2017-03-31 19:01
@breyed Repro for this is elusive.
I think It could happen if you manage to make a tooltip appear before the Roslyn's `HACK_ThemeColorFixer` runs.
It also seems to happen only after fresh install(?).

**Comment by breyed** [comment] 2017-03-31 19:02
I happened for me only after a fresh install, but it was a sample size of 2 attempts, one after fresh install, one after nightly reinstall. So it could easily be timing coincidence.

**Comment by breyed** [comment] 2017-04-04 00:43
I just ran into the problem again, and so have a couple new data points:
* It occurred after installing an unrelated extension (AFAIKT - I don't use F# every day).
* Switching the theme from Light to Dark fixed it (no need to go to the Fonts settings).

**Comment by vasily-kirichenko** [comment] 2017-04-22 06:28
I still see this bug time to time, always after reinstalling OSS VSIX.

**Comment by cartermp** [comment] 2017-04-23 00:53
Re-triaged this - I've run into it again as well, though it's so inconsistent and uncommon now that I can't say this is something which should be addressed with any priority.  Kind of annoying, though

**Comment by dsyme** [comment] 2017-06-20 16:55
I've not seen this.  We can probably just close it, I don't believe it is related to the Visual F# addin?

**Comment by cartermp** [comment] 2017-06-20 21:56
Yeah, I'm not convinced that this is an issue we have.  I've also not seen it for quite some time.

**Closed by cartermp** 2017-06-20 21:56 UTC
Labels: Area-External, Flaky, Urgency-Later
