### ISSUE TITLE
IntelliSense is blocked by Find all References on long operations

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2379] opened 2017-02-07 21:51 UTC
1. Open a file with a token references in many places, so that Find All References will take some time
2. Invoke Find All References on the Token
3. Hover over something in the editor, or attempt to get SignatureHelp on something (e.g. `DateTime.`)

**Expected:** I get IntelliSense in the editor
**Actual:** I'm blocked on any IntelliSense until Find All References completes

**Comment by vasily-kirichenko** [comment] 2017-02-08 05:17
This happens because Find all refs checks each of involved projects entirely, as a one fat Reactor operation. See what @dsyme suggests to fix this here https://github.com/Microsoft/visualfsharp/pull/2358#issuecomment-277248643

**Comment by dsyme** [comment] 2017-02-08 08:26
Yes, the way this is currently coded means it is cancellable but not interleaved.  
* We would need to make the 50ms Eventually chunks interleaved with other reactor queue operations
* We should likely use an explicit priority queue for the reactor queue. Currently we rely on a [mailbox processor](https://github.com/Microsoft/visualfsharp/blob/820af622c09067bc30e419af5a1f21ccf96e65a2/src/fsharp/vs/Reactor.fs#L42)

**Comment by vasily-kirichenko** [comment] 2017-02-08 08:32
@cartermp It should not reproduce on master because stale file check results are used if fresh ones are not available in 1 second.

**Comment by cartermp** [comment] 2017-02-08 16:22
@vasily-kirichenko That's good!

**Comment by vasily-kirichenko** [comment] 2017-02-09 11:46
It's not block, but produces no results.

**Comment by dsyme** [comment] 2017-03-14 14:00
Closing since @vasily-kirichenko says fixed on master (or at least not blocking any more)

**Closed by dsyme** 2017-03-14 14:00 UTC
Labels: Area-IDE Language Service, Urgency-Soon
