### ISSUE TITLE
Support dotnet cli preview 3 in VS

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1656] opened 2016-10-25 15:04 UTC
https://github.com/dotnet/cli allows to download preview3 of the dotnet sdk tools.
This versions goes back from project.json to MSBuild, but comes with a new MSBuild ToolsVersion 15.0

@cartermp @KevinRansom  Are there any plans to support this MSBuild version and especially the new projcts.assets.json files that comes with this new tooling?

**Comment by KevinRansom** [comment] 2016-10-26 02:12
@forki 

Yes there are plans.  But it is not yet in a position for us to start on it yet.  As of this morning when I went and found the various stakeholders to figure out whether I could start work on it.

**Comment by forki** [comment] 2016-10-26 06:24
Cool. Please keep us updated about progress so that we can keep the efforts with ionide and paket synced. Thx

**Comment by eriawan** [comment] 2016-11-11 04:07
@KevinRansom 
Now that VS 15 has progressed to Preview 5, is there any update on this dotnet cli support in VS 15, especially Preview 5?

**Comment by KevinRansom** [comment] 2016-12-14 07:45
@enricosada is working with the dotnet sdk team to add templates.

**Comment by enricosada** [comment] 2016-12-14 15:20
@eriawan i can speak only for myself and about the sdk part.

note: `preview3` -> `preview4` -> `preview5` -> etc are the versions of .net core sdk based on msbuild. Instead `preview2`, `preview2.1` are based on project.json

IHMO first we fix the sdk from cli (pratically msbuild run from command line), after that it's possibile to work on VS (because vs use the msbuild to compile/get source files/arguments etc).

So changelog:

### preview3

With `preview3` was already possibile to use fsproj (but no template OOTB in `dotnet new`). The f# was not integrated cleanly inside the msbuild project file but worked ok. That made possibile to start explore how to improve things, and see what was missing.

### preview4 (today)

With preview4 (released two days ago) the f# works OOTB in the .net core sdk (like preview2). I am waiting for the official .net release notes to publish more info about that.

It's not important that all the F# `dotnet new` templates works OOTB like c# (but having `dotnet new -l fsharp -t web` work for asp.net is nice 😄,  ), but is important because the sdk extensibilty for new languages (like F#) was improved and we are using that atm.

Stayin near the current c# sdk is really important because make it times easier to make commands work correctly (a lot of stuff just works). And we can discuss new features/improvements too, so they dont break f# for mistake or how we can use these (like `Sdk` attribute).

Another good stuff is that f# fsprojs are now part of the dotnet/cli (the .net core sdk) test suite, so are checked for all templates. the dotnet/netcorecli-fsc test suite check other use cases.

The result is F# that is 1-1 aligned with all c# templates of `dotnet new`, and commands (build/publish/pack/test) works.

We made good progress, the F# has a nice hook in the sdk (we prepend `FSharp.Sdk` to normal `.NET.Sdk` like `<Project Sdk="FSharp.Sdk;Microsoft.NET.Sdk">`). 

But before VS can use it directly, there is some work to make it easier to use it inside vf#. 

For example i need to fix at least https://github.com/dotnet/netcorecli-fsc/issues/25 to replicate the current way vf# use to read compiler args/source files from msbuild (atm i reuse preview2 dotnet-compile-fsc because works and i had no time to reimplement that). After that it's possibile to start work to see how integrate it inside vf#, because behaviour/code of msbuild will be really similar to current codebase, so less work and more safe.

### preview5 (future, wip now)

The `preview5` will improve the msbuild project file with cleanup, and sdk language extensibility will be a bit better (no need for packagereference of fsharp.net.sdk for example), but it's not that important, because important part are already in place. The new stuff will be incremental enhancement over csproj/fsproj msbuild file (like [that](https://github.com/dotnet/netcorecli-fsc/issues/57) ).

**Comment by enricosada** [comment] 2017-04-26 15:50
@forki or @KevinRansom , can you close this because is old and a dupe of #2316

**Closed** 2017-04-26 15:52 UTC
Labels: Feature Specification
