### ISSUE TITLE
Strange behaviour with member constraints having multiple arguments

### ISSUE THREAD

**Issue by AntonioL** [Microsoft/visualfsharp#1601] opened 2016-10-11 23:08 UTC
Member constraints with multiple non tupled arguments seem to not be working in F#.
#### Repro steps

``` fsharp
let inline foca (x : ^a) c' g' =
    let f' = (^a : (static member DrawL : Color -> Graphics -> unit) (c', g'))
    ()

type Drawer() =
    static member DrawL (color : Color)  (g: Graphics) =
        let r = g.VisibleClipBounds |> Rectangle.Truncate
        g.FillRectangle(Brushes.Orange, r)
        ()

(*Assume that p is an object with the CreateGraphics method but that
is not important in the scope of this ticket.
*)
foca (Drawer()) Color.Black (p.CreateGraphics())
```

I admit that it could be due to my ignorance regarding member constraints, if that is the case please close this report, I have checked the documentation and could not find any information about the matter.
#### Expected behavior

The above should compile as the Drawer class effectively has a member DrawL with the signature:  -> Color -> Graphics -> unit.
#### Actual behavior

Instead it does not compile as it objecting that it could not find a DrawL method in the object.
Which is weird.
#### Known workarounds

The reason I am filing this ticket is the strange workaround.

If I modify the DrawL method in the Drawer class such that the arguments are tupled (see the below code snippet), then it works but it should not.

``` fsharp
type Drawer() =
    static member DrawL (color : Color, g: Graphics) =
        let r = g.VisibleClipBounds |> Rectangle.Truncate
        g.FillRectangle(Brushes.Orange, r)
        ()
```

The reason it should not is that the above has type signature: Color \* Graphics -> unit
#### Related information

Provide any related information 
- Operating system: Windows 10
- .NET Runtime (Framework 4.5)
- F# 4.0 (FSharp.Core 4.4.0.0)

**Comment by gmpl** [comment] 2016-10-15 12:25
See [this](http://stackoverflow.com/questions/39065724/using-statically-resolved-type-parameters-is-it-possible-to-call-class-method-wi/39065821#39065821) and the workaround there mentioned.

**Comment by AntonioL** [comment] 2016-10-15 16:43
Thank you for the workaround.

I will still mark this open because this seriously needs to be fixed.

**Comment by gmpl** [comment] 2016-10-15 16:47
Well, if you follow the link there to the source code it looks like it's by design. Hopefully I'm wrong but I'm afraid you'll be asked to go to the user voice.

**Comment by abelbraaksma** [comment] 2016-10-15 18:46
I played a bit with your code (making it compilable by adding dummy types). This is a repro of your original case:

```
module Test =
    type Foo = Foo

    type Drawer() =
        static member DrawL (color : int)  (g: Foo) =
            let r = color
            printfn "%i" r
            ()
        //static member DrawL color = Drawer.internalDrawL color

    let inline foca (x : ^a) c' g' =
        let f' = (^a : (static member DrawL : int -> Foo -> unit) (c', g'))
        ()

    foca (Drawer()) 15 Foo.Foo
```

And here is one way to solve it, given the current restraints on statically resolvable member constraints:

```
module Test =
    type Foo = Foo

    type Drawer() =
        static member internalDrawL (color : int)  (g: Foo) =
            let r = color
            printfn "%i" r
            ()
        static member DrawL color = Drawer.internalDrawL color  // note that you cannot curry here

    let inline foca (x : ^a) c' =
        let f' = (^a : (static member DrawL : int -> (Foo -> unit)) (c'))
        f'

    foca (Drawer()) 15 Foo.Foo
```

I'm not saying there isn't a bug, I think there is (unless it's a _restriction by design_, @gmpl hinted at).

**Comment by AntonioL** [comment] 2016-10-15 19:09
Actually I found out that there are two proposals with the goal of providing nice syntax for member constraints which are underway.

Even if none of these addresses the specific problem, in the meantime I will use the hack to make a member returning a lambda function.

Thank you for your help!

Good F#ing!

**Comment by KevinRansom** [comment] 2017-01-06 21:53
Closing awaiting improvements from user voice suggestions.

**Closed by KevinRansom** 2017-01-06 21:53 UTC
