### ISSUE TITLE
The fixed keyword (pinning) does not work with struct record types which works with non-struct record types

### ISSUE THREAD

**Issue by zpodlovics** [Microsoft/visualfsharp#3465] opened 2017-08-18 15:15 UTC
I ran into a problem where I tried to use the fixed keyword on a struct record. I was able to recreate the the compilation error based on the F# 4.1 announcement example for fixed. The same problem exists for structs.

https://blogs.msdn.microsoft.com/dotnet/2016/07/25/a-peek-into-f-4-1/
https://gist.github.com/cartermp/68543e43cd237b7567b7129244e7396b#file-fixed-fs

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new dotnet 2.0 console project

```
dotnet new console -lang F#
```

2) Copy the following content to Program.fs

```fsharp
open System.Runtime.CompilerServices
open Microsoft.FSharp.NativeInterop

#nowarn "9"

[<Struct>]
type Point = { mutable x : int; mutable y : int }

let fixPoint() =
    let point = { x = 1; y = 2 }
    use p1 = fixed &point.x
    NativePtr.read<int> p1

[<EntryPoint>]    
let main args =
    printf "readPtr: %d%s" (fixPoint()) System.Environment.NewLine
    0
```
3. Build the project.

```
dotnet build -c Release
```

Please note, the same problem exists if point is mutable:

```fsharp
open System.Runtime.CompilerServices
open Microsoft.FSharp.NativeInterop

#nowarn "9"

[<Struct>]
type Point = { mutable x : int; mutable y : int }

let fixPoint() =
    let mutable point = { x = 1; y = 2 }
    use p1 = fixed &point.x
    NativePtr.read<int> p1

[<EntryPoint>]    
let main args =
    printf "readPtr: %d%s" (fixPoint()) System.Environment.NewLine
    0
```

And the same problem exists for structs:

```fsharp
open System.Runtime.CompilerServices
open Microsoft.FSharp.NativeInterop

#nowarn "9"

[<Struct>]
type Point =
    val mutable X: int
    val mutable Y: int
    new(x,y) = { X=x; Y=y; }    

let fixPoint() =
    let point = Point(1,2)
    use p1 = fixed &point.X
    NativePtr.read<int> p1

[<EntryPoint>]    
let main args =
    printf "readPtr: %d%s" (fixPoint()) System.Environment.NewLine
    0
```

And the same problem exists for structs if point is mutable:

```fsharp
open System.Runtime.CompilerServices
open Microsoft.FSharp.NativeInterop

#nowarn "9"

[<Struct>]
type Point =
    val mutable X: int
    val mutable Y: int
    new(x,y) = { X=x; Y=y; }    

let fixPoint() =
    let mutable point = Point(1,2)
    use p1 = fixed &point.X
    NativePtr.read<int> p1

[<EntryPoint>]    
let main args =
    printf "readPtr: %d%s" (fixPoint()) System.Environment.NewLine
    0
```

#### Expected behavior

Successful build & execution.

#### Actual behavior

```
/tmp/structrecordfixed/Program.fs(11,9): error FS3207: Invalid use of 'fixed'. 'fixed' may only be used in a declaration of the form 'use x = fixed expr' where the expression is an array, the address of a field, the address of an array element or a string' [/tmp/structrecordfixed/structrecordfixed.fsproj]

Build FAILED.

/tmp/structrecordfixed/Program.fs(11,9): error FS3207: Invalid use of 'fixed'. 'fixed' may only be used in a declaration of the form 'use x = fixed expr' where the expression is an array, the address of a field, the address of an array element or a string' [/tmp/structrecordfixed/structrecordfixed.fsproj]
    0 Warning(s)
    1 Error(s)
```

#### Known workarounds

No known workaround.

Please note, the non-struct version (without the ```[<Struct>]``` attribute) of Point works fine (as it was demonstrated in the F# 4.1 announcement). However the non-struct and struct version are **not interchangeable** because the non-struct version will generate huge amount of garbage in a tight loop.

```
In F# 4.1, a record type can be represented as a struct with the [<Struct>] attribute. This allows records to now share the same performance characteristics as structs, without any other required changes to the type definition.
```

#### Related information 

* Operating system: Ubuntu 16.04 x86_64
* Branch: Xenial
* .NET Runtime, CoreCLR or Mono Version: .NET Core 2.0.0 (production release) with built-in F#

**Comment by dsyme** [comment] 2017-08-18 22:06
@zpodlovics Thanks, this looks like a bug indeed.

**Comment by dsyme** [comment] 2017-08-30 14:47
@zpodlovics I believe in all the cases above the expression is already considered fixed, because it is the address of a value on the stack.  

For example, in C# you get the error: ``a.cs(10,22): error CS0213: You cannot use the fixed statement to take the address of an already fixed expression`` for the code

```csharp
unsafe public struct Data
{
    public int x;
};

class Main {
  unsafe public void X()
  {
    Data d = new Data();
    fixed (int* pD = &d.x)
    {
    }
  }
}
```
This indicates to me that you can just take the address of the field directly.  That said, the F# code as follows doesn't currently compile:
```
open System.Runtime.CompilerServices
open Microsoft.FSharp.NativeInterop

#nowarn "9"

[<Struct>]
type Point =
    val mutable X: int
    val mutable Y: int
    new(x,y) = { X=x; Y=y; }    

let fixPoint() =
    let mutable point = Point(1,2)
    let p1 = &&point.X
    NativePtr.read<int> p1

```
where we are here attempting to use a native pointer.  There are other ways to get the native pointer (e.g. don't use a ``let`` binding)  but I do believe the above should be fixed

**Comment by dsyme** [comment] 2017-08-30 16:12
I'll close this as by design since all cases use addresses that are already pinned (the linked issue is really a different thing)

**Closed** 2017-08-30 16:12 UTC
Labels: Area-Compiler, bug, Urgency-Soon
