### ISSUE TITLE
c# f# lambda 

### ISSUE THREAD

**Issue by saadshams** [Microsoft/visualfsharp#6647] opened 2019-04-28 04:53 UTC
Trying to call a f# lambda from C#

#### Repro steps

1. Step A - F# code
```
module ClassLibrary1.Functions

let checkThis item f =
    if f item then
        printfn "HIT"
    else
        printfn "MISS"
```

2. Step B, C# code

```
using System;
using ClassLibrary1;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject3
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestFunctions()
        {
            Converter<int, bool> func = x => x > 1;          
            Functions.checkThis(4, func);
        }
    }
}
```

Following suggestions from SO didn't work either 

1) `var s = FSharpFunc<int, bool>.FromConverter(x => x > 3);` // FromConverter not available

2) 
```
FSharpFunc<int, bool> s = new Func<int, bool>(x => x > 3);
var s = FSharpFunc<int, bool>.FromFunc(x => x > 3
```

#### Related information 

I'm on a mac running .net core 2.2.106 using Rider

**Comment by cartermp** [comment] 2019-04-28 20:57
This is a duplicate of #1847

We'll eventually get this sorted once we drop support for `netstandard1.6` from FSharp.Core. This will likely coincide with the next version of F# (cc @dsyme and @KevinRansom)

**Closed by cartermp** 2019-04-28 20:57 UTC
