### ISSUE TITLE
15.3 preview 3: adding source files via Solution Explorer results with a new ItemGroup in project file

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3265] opened 2017-06-27 08:52 UTC
![image](https://user-images.githubusercontent.com/873919/27579103-084a9252-5b2f-11e7-8286-52152d59a435.png)

**Comment by saul** [comment] 2017-06-27 09:20
It's weird that adding source files also adds them as <None> instead of <Compile>

**Comment by enricosada** [comment] 2017-06-27 10:00
@davkean @srivatsn any clue?

**Comment by srivatsn** [comment] 2017-06-27 13:02
The SDK has a glob for None and that's picking up the fs files. @brettfo fixed this recently (https://github.com/Microsoft/visualfsharp/pull/3212) by making the SDK set `<EnableDefaultNoneItems>false</EnableDefaultNoneItems>` for F# but I guess that change hasn't made it into this build.

**Comment by dsyme** [comment] 2017-06-27 13:09
@srivatsn Is the workaround to add 

    <EnableDefaultNoneItems>false</EnableDefaultNoneItems> 

explicitly to the project file?

**Comment by srivatsn** [comment] 2017-06-27 13:10
Yes that should work.

**Comment by srivatsn** [comment] 2017-06-27 13:14
Also looking at the screenshot, the project doesn't have the dependencies node (and a bunch of other stuff is likely broken) - that needs this fix in the SDK - https://github.com/dotnet/sdk/pull/1350. i.e you need the latest 2.0 SDK to make that work

**Comment by cartermp** [comment] 2017-06-27 13:50
Closing this out as the issue is fixed.  Should be available in preview 4.

**Comment by dsyme** [comment] 2017-06-27 15:56
@cartermp @srivatsn Great to know!

**Comment by cartermp** [comment] 2017-06-27 17:27
Re-opening until we have clarity for Preview 4 - @brettfo can you confirm when this change is inserted into VS?

**Comment by cartermp** [comment] 2017-06-29 22:10
Confirming that this is fixed and inserted.

**Closed by cartermp** 2017-06-29 22:10 UTC
Labels: Area-External, bug
