### ISSUE TITLE
Inlined Tuple'd arguments with byref<> cause Debug builds to crash at runtime

### ISSUE THREAD

**Issue by manofstick** [Microsoft/visualfsharp#820] opened 2015-12-21 22:15 UTC
Another byref<> bug (with #819)

    let inline f (x, r:byref<_>) = r <- x
    let mutable x = Unchecked.defaultof<_>
    f (0, &x)

This crashes at runtime under a debug build as it tried to instantiate a Tuple with a reference type. In the release build that all get optimized away, so it works ok.

**Comment by manofstick** [comment] 2015-12-21 22:19
Related to #127

**Comment by dsyme** [comment] 2016-01-08 22:17
Duplicate of #558 I believe

**Closed by dsyme** 2016-01-08 22:17 UTC
Labels: Area-Compiler, bug
