### ISSUE TITLE
Names resolved to internal types from .NET assemblies in preference to public types from other .NET assemblies

### ISSUE THREAD

**Issue by richardjharding** [Microsoft/visualfsharp#93] opened 2015-01-23 15:07 UTC
I came across an issue recently trying to use the open source openid connect library from thinktecture - Identity server v3 - https://github.com/IdentityServer

They ship a nuget package that I had included into an F# project - the package contains a single dll - as soon as I referenced the dll the f# compiler started complaining about an existing line of code that had previously compiled without errors

After discussion with the thinktecture developers it turns out that their library was post processed with ILMerge - http://research.microsoft.com/en-us/people/mbarnett/ilmerge.aspx

And that is shared a common dependency with my project namely the Newtonsoft Json library

My understanding is that ILMerge generates internal versions of the referenced assemblies and that shouldn't affect other code that references public version of the same type - this works fine in c# but fails in f# - it looks like the compiler may be finding the "hidden" internal version and thats somehow masking the public definition of the constructor - the error reported is

"this type has no accessible object constructors"

I'm happy to try and debug this further but not sure where to start? - when I look at the de-compiled identity server in ilspy the types look to be encapsulated correctly

When I reference the same assembly thats not been processed by ILMerge the error doesn't get raised

I raised an issue on Identity Server - https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/761

and a question on StackOverflow - http://stackoverflow.com/questions/27940765/adding-reference-to-thinktecture-identityserver-3-causes-this-type-has-no-access

**Comment by dsyme** [comment] 2015-01-23 17:07
Yes, it's possible that there is an issue where the presence of an internal C# type with a particular name is affecting name resolution in F#. 

If so, an isolated repro not involving ILMerge would be great please  (please also see the CONTRIBUTING.md about how issues need to have definite repros).

**Comment by latkin** [comment] 2015-01-23 18:21
Marking as 'discussion' for now.  If we can get more clarity on a repro, will change to 'bug'.

**Comment by gaspode44** [comment] 2015-01-23 20:49
Ok have created a small repro here - https://github.com/gaspode44/FSharpILMergeIssue

Steps to reproduce :
1:  clone the git repo above
2. open the solution in VS 2013
3.. Build  - build fails with 2 errors on line 7 of program.fs
4. remove the reference to the thinktecture.identityserver.dll
5. Build - build succeeds

this is with visual f#3.1.2

hope thats enough detail - let me know if I can provide anything else

**Comment by tpetricek** [comment] 2015-01-25 00:43
It might be worth noting that there is also ILRepack (https://github.com/gluck/il-repack), which seems to be more actively developed variant of ILMerge... In case the people behind IdentityServer wanted to try it instead :-)

**Comment by gaspode44** [comment] 2015-01-27 11:16
I'm not sure its an issue with ILMerge as in c# it all works fine

**Comment by dsyme** [comment] 2015-01-27 19:22
This is a bug - name resolution should not prefer an internal type from an assembly (where InternalsVisibleTo is false) over a public type from another .NET assembly.

The repro given is adequate, the fix may be tricky because it depends on the InternalsVisibleTo relation.

I changed the title to reflect this and updated the label.

**Comment by jasonzoladz** [comment] 2015-12-26 19:07
Will this bug be fixed?

**Comment by dsyme** [comment] 2016-01-05 20:38
It's still active, there's no ETA as yet

**Comment by dsyme** [comment] 2016-07-22 00:52
Fixed by the above PR

**Closed by dsyme** 2016-07-22 00:52 UTC
Labels: 2 - Ready, Area-Compiler, bug, Urgency-Soon
