### ISSUE TITLE
Legacy language service tests are not launched on CI

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5020] opened 2018-05-27 07:49 UTC
It seems "legacy" service/editor tests are not launched on CI anymore, for example, I cannot find this one in the output logs of part_1..4:

https://github.com/Microsoft/visualfsharp/blob/8316a799863fffb733a401592f340022ff79a50d/vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.ParameterInfo.fs#L370-L379

Running any of those locally from within VS fails:

> Test Name:	TypeProvider.ConstructorWithOneParam
Test FullName:	Tests.LanguageService.ParameterInfo.UsingMSBuild.TypeProvider.ConstructorWithOneParam
Test Source:	C:\git\visualfsharp\vsintegration\tests\UnitTests\LegacyLanguageService\Tests.LanguageService.ParameterInfo.fs : line 375
Test Outcome:	Failed
Test Duration:	0:00:00.0000001

> Result Message:	
OneTimeSetUp: System.TypeInitializationException : The type initializer for '<StartupCode$VisualFSharp-Salsa>.$VsMocks' threw an exception.
  ----> System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by cartermp** [comment] 2018-05-27 16:34
This is a dupe of #4850 - the rabbit hole goes deep on this one. @KevinRansom is working on this. Bit rot set in for the legacy tests, and for some unknown amount of time they haven't been running.

**Closed by cartermp** 2018-05-27 16:34 UTC
