### ISSUE TITLE
Terrible `raise` performance inside computation expressions

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2516] opened 2017-03-02 12:39 UTC
@eiriktsarpalis post this snippet 4 years ago http://fssnip.net/dP/title/Faster-exception-handling-with-AsyncRaise

```fsharp
type Microsoft.FSharp.Control.Async with
    static member Raise (e : #exn) = 
        Async.FromContinuations(fun (_,econt,_) -> econt e)

#time
async {
    for i in 1 .. 1000000 do
        try
            return raise <| new System.Exception()
        with ex -> ()
} |> Async.RunSynchronously

async {
    for i in 1 .. 1000000 do
        try
            return! Async.Raise <| new System.Exception()
        with ex -> ()
} |> Async.RunSynchronously
```

Results on current master:
```fsharp
> 
Real: 00:00:37.642, CPU: 00:00:37.671, GC gen0: 346, gen1: 6, gen2: 1
val it : unit = ()

> 
Real: 00:00:01.144, CPU: 00:00:01.156, GC gen0: 327, gen1: 2, gen2: 1
val it : unit = ()
```

The difference is so huge that I think we should figure out what's wrong with raising / handling exceptions inside CEs.

**Comment by dsyme** [comment] 2017-03-02 14:16
I think this is by design. The first raises and catches CLR exceptions, passing the result to the exception continuation. The second calls the exception continuation directly.

Like all CLR exception handling I don't think we really care to much about the perf of raising and catching 1,000,000 exceptions, you just have to make exception raising exceptional, not the norm

**Comment by KevinRansom** [comment] 2017-03-02 17:44
@vasily-kirichenko 

I think we could consider a codefix in the IDE to detect the first and suggest a fix.  After all now that we have the ability to detect and fix non-optimal code we can use the ide to guide developers to best practice.

.

**Comment by vasily-kirichenko** [comment] 2017-03-02 18:10
@KevinRansom why not generate `Async.FromContinuations(fun (_,econt,_) -> econt e)` for `raise` inside comp expressions?

**Comment by dsyme** [comment] 2017-03-03 12:43
> why not generate Async.FromContinuations(fun (_,econt,_) -> econt e) for raise inside comp expressions?

@vasily-kirichenko I see, thanks for the suggestion.  Makes more sense now.

It's possible. But if we did do this then shouldn't we allow a builder method for ``raise`` (or ``raise!``) in computation expressions generally?  (nb. it wouldn't apply to ``failwith`` and other exception generators, even if inlined, which disturbs me)

I'm more open to a general solution.  However I'm still not convinced we want to be concerned with this. Exceptions are exceptional in .NET and F# and I don't think we should ever advocate them for control. So why would we be trying to avoid that in F# computation expressions?  Do we really have real-world use cases where we are feeling the pain from this, and where exceptions are not being used for control? 30,000 exceptions/second is still pretty frequent...

**Comment by dsyme** [comment] 2017-03-14 13:46
@vasily-kirichenko @eiriktsarpalis I'll close this as by design, though somewhat reluctantly since I don't think it's a bug as such.  However it's likely we would accept a PR that actually implements this well and cleanly.  I can see the suggestion is sound and sensible, I'm only closing it because exceptions are considered exceptional in .NET and F# programming

**Closed by dsyme** 2017-03-14 13:46 UTC

**Comment by eiriktsarpalis** [comment] 2017-03-14 19:18
@vasily-kirichenko @dsyme An important property lost when using `Async.Raise` instead of `raise` is that debuggers and profilers are unable to detect errors. That said, `Async.Raise` is still useful if you want to raise a caught exception (e.g. the exception result of a task) without wiping its stacktrace. Still, replacing one with the other is not ideal in most cases.
