### ISSUE TITLE
Inconsistent behaviour between FSI/Visual F# and FSC when inlining private constructors/functions

### ISSUE THREAD

**Issue by jakzale** [Microsoft/visualfsharp#3537] opened 2017-09-01 15:54 UTC
It is possible to write a function that is marked as `inline` which is accepted by FSI/Visual F#, but which causes a compilation error when compiled with FSC.

By accepted by FSI I mean that I can load the offending code into FSI without any errors.
By accepted by Visual F# I mean that Visual Studio does not show any errors in the code.

#### Repro steps

1. Write the following code in a .fs file
```fsharp
type 'a Foo = private | Foo of 'a
let inline unFoo (Foo(x)) = x
let inline foo (x) = Foo(x)
```
2. Try loading it to FSI, which works fine.

3. Try compiling it within Visual Studio or try compiling it using fsharpc.exe/msbuild from the commandline, which will fail.

Sample VisualStudio F# project: [Foo.zip](https://github.com/Microsoft/visualfsharp/files/1270763/Foo.zip)

#### Expected behavior

I would expect that the behaviour of compiled code to be consistent with interpreted code.  At least I would expect that Visual F# would notify me of error, when compilation fails.

#### Actual behavior

When compiling In Visual F#, the compilation fails by simply displaying "Build failed" in the status line.  There is no indication of error in neither Error list nor offending code in the source file.

When compiling from the command line the compiler produces the following error:

```
"Foo.fsproj" (default target) (1) ->
(CoreCompile target) ->
  Foo.fs(5,12): error FS1113: The value 'unFoo' was marked inline but its implementation makes use o
f an internal or private function which is not sufficiently accessible [C:\Users\jakub\Foo\Foo.fsproj]
  Foo.fs(6,12): error FS1113: The value 'foo' was marked inline but its implementation makes use of
an internal or private function which is not sufficiently accessible [C:\Users\jakub\Foo\Foo.fsproj]
```

#### Known workarounds

I do not know any workarounds other than removing the `inline` keyword from function definitions.

#### Related information 

Provide any related information 

* Operating system
Windows 10 Pro, Version 1703, Build 15063.540
* .NET Runtime, CoreCLR or Mono Version
.Net Framework 4.6.1 and F# 4.1
* Editing Tools (e.g. Visual Studio Version)
Visual Studio 2017 (15.3.3) and Visual F# 15.4.1.17083104

Similar behaviour observed on

* Operating system
macOS 10.12.6
* Mono Version
5.2.0.215
* Editing Tools
VSCode 1.15.1 and Ionide 2.34.4

* Indications of severity
Low

**Comment by dsyme** [comment] 2017-09-01 16:00
I think this is by design, apart from this:

> When compiling In Visual F#, the compilation fails by simply displaying "Build failed" in the status line. There is no indication of error in neither Error list nor offending code in the source file.

I don't know what's going on there, but I deal with the FSI v. FSC difference first....

The difference between FSI and FSC is that FSI is an "open" program that never produces a finalized, closed assembly, but instead you keep on adding more code.  This means that a set of final checks on the "closed" nature of the inlining information collected during optimization is not performed, and the optimization data is never written to disk.

There are several other differences between FSI and FSC - e.g. in FSI each fragment (delimited by ``;;`` - added implicitly on Alt-Enter or Ctrl-Enter in editing environments) is checked independently, whereas in FSC they are checked as a whole.  So I think we would consider the difference w.r.t. optimization information checking as by design.

With regard to the lack of errors - please open a separate issue on that - I presume you don't see that behaviour when compiling from within Ionide? (if that can even be done?)

**Comment by jakzale** [comment] 2017-09-01 16:22
Ok, now I understand.  Thank you for the explanation.

> With regard to the lack of errors - please open a separate issue on that - or we can recycle and use this issue if you agree that the FSC v. FSI thing is by design. I presume you don't see the error behaviour when compiling from within Ionide? (if that can even be done?)

By "similar behaviour in Ionide and VSCode", I mean that when I edit the offending file in VSCode, the F# Language Service used by Ionide will not find anything wrong with the above code.

I am fine with recycling this issue for missing error information in Visual F#, but I am still wondering why wouldn't Visual F# and Ionide highlight the offending code as incorrect.  I was under the impression that both of them are using the FSC wrapped as a service.

**Comment by dsyme** [comment] 2017-09-01 22:29
> By "similar behaviour in Ionide and VSCode", I mean that when I edit the offending file in VSCode, the F# Language Service used by Ionide will not find anything wrong with the above code.


These errors are only shown when the F# compiler executes to completion, after the optimization phase.  That phase isn't run in the IDE as there are only a couple of rare errors detected in it, and it would be expensive (in CPU time and memory) to run those final phases.

**Closed** 2017-09-04 17:03 UTC
