### ISSUE TITLE
Visual Studio 2017 crash while editing large F# file

### ISSUE THREAD

**Issue by jcoder58** [Microsoft/visualfsharp#2980] opened 2017-05-02 15:05 UTC
Visual Studio 2017 crashes when there are a large number of functions to validate types.

[TestCrash.zip](https://github.com/Microsoft/visualfsharp/files/970821/TestCrash.zip)

#### Repro steps

In the attached solution, 

1. Open the file Dictionary.fs in the Visual Studio editor

2. At line 10, type of the following statement:

    dictionary.Add(s,w)

After the final ')', there is a short pause, then Visual Studio 2017 crashes

Provide any related information 

* Windows OS 8.1
* .Net 4.6.2
* Visual Studio 2017 Version 15.1 Release 26403.7

**Comment by forki** [comment] 2017-05-02 19:47
Did you test this on the nightlies release channel?

**Comment by saul** [comment] 2017-05-02 20:07
@forki I can reproduce this locally on latest nightly

**Comment by cartermp** [comment] 2017-05-02 20:56
Confirmed as well.  @brettfo @Pilchie @KevinRansom This will reliably crash VS.  I'll upload a dump.

**Comment by vasily-kirichenko** [comment] 2017-05-03 08:33
![image](https://cloud.githubusercontent.com/assets/873919/25653090/0c177faa-2ff4-11e7-841a-b70f1a2fd292.png)

```fsharp  	FSharp.Core.dll!Microsoft.FSharp.Collections.SeqModule.Empty<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>()	Unknown
>	FSharp.LanguageService.Compiler.dll!Microsoft.FSharp.Compiler.SourceCodeServices.Structure.parseExpr@207.GenerateNext(ref System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> next = null) Line 371	F#
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.MoveNextImpl()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@269<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange, System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.LazyGeneratorWrappingEnumerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@335<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.GenerateThen<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Seqcore.MoveNextImpl@381<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.GenerateNext(ref System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> next = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.MoveNextImpl()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.LazyGeneratorWrappingEnumerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@335<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.GenerateThen<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Seqcore.MoveNextImpl@381<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.GenerateNext(ref System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> next = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.MoveNextImpl()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.LazyGeneratorWrappingEnumerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@335<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.GenerateThen<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Seqcore.MoveNextImpl@381<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.GenerateNext(ref System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> next = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.MoveNextImpl()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.LazyGeneratorWrappingEnumerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Seqcore.MoveNextImpl@381<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.GenerateNext(ref System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> next = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.MoveNextImpl()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.LazyGeneratorWrappingEnumerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Seqcore.MoveNextImpl@381<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.GenerateNext(ref System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> next = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.MoveNextImpl()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.LazyGeneratorWrappingEnumerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Seqcore.MoveNextImpl@381<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.GenerateNext(ref System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> next = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.MoveNextImpl()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.LazyGeneratorWrappingEnumerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!<StartupCode$FSharp-Core>.$Seqcore.MoveNextImpl@381<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.GenerateNext(ref System.Collections.Generic.IEnumerable<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> next = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.MoveNextImpl()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.Invoke(Microsoft.FSharp.Core.Unit unitVar0 = null)	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.appG<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>(Microsoft.FSharp.Collections.Generator.Generator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange> g = {Microsoft.FSharp.Collections.Generator.LazyGeneratorWrappingEnumerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>})	Unknown
 	FSharp.Core.dll!Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator<Microsoft.FSharp.Compiler.SourceCodeServices.Structure.ScopeRange>.System.Collections.IEnumerator.System-Collections-IEnumerator-MoveNext()	Unknown
	..................
 	The maximum number of stack frames supported by Visual Studio has been exceeded.	
```

**Comment by forki** [comment] 2017-05-03 08:41
I know it's not the reason. but IsSome and then .Value ??

**Comment by forki** [comment] 2017-05-03 08:57
I think since this function is not tail recursive it was only a matter of time until it crashed. We should rewrite to manage our own stack.

**Comment by vasily-kirichenko** [comment] 2017-05-03 09:31
Fixed in https://github.com/Microsoft/visualfsharp/pull/2985

**Closed** 2017-05-05 05:23 UTC
Labels: bug, Urgency-Now
