### ISSUE TITLE
FSC - 15.8 - Not ngen'ed

### ISSUE THREAD

**Issue by TIHan** [Microsoft/visualfsharp#5518] opened 2018-08-16 07:01 UTC
**Edit by @cartermp**:

This affects desktop F# usage on Windows with VS 15.8. .NET Core is unaffected.

**Original issue:**

I updated my home machine to dev15.8 community edition from 15.7 and noticed my compile times are way longer than usual, ex: instead of taking 1.3 seconds to compile, it's now taking 5 seconds on a project of mine. 

I had a thought that it is not ngen'ed, so I went and ngen'ed fsc.exe manually, and now it's back to 1.3 seconds. I don't believe this is intentional.

**Workaround**

Manually run one of these (Depending on Community/Professional/Enterprise):

    ngen "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe"

    ngen "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe"

    ngen "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe"

**Comment by isaacabraham** [comment] 2018-08-16 07:07
How /where can we do this ourselves?

**Comment by TIHan** [comment] 2018-08-16 07:10
Run *Developer Command Prompt for VS 2017*,

Then run this in the prompt (VS install will vary):
```
ngen "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe"
```

**Comment by TIHan** [comment] 2018-08-16 07:11
I don't know if everyone is experiencing this, but it absolutely happened for me when I updated.

**Comment by nikonthethird** [comment] 2018-08-16 09:12
@TIHan thank you, I was wondering why compilation was taking so long. Running your command totally fixed that.

Rebuild solution with 18 projects before running `ngen`: ca 30s

Rebuild solution with 18 projects after running `ngen`: ca 9s

**Comment by isaacabraham** [comment] 2018-08-16 09:27
I can confirm the same as @nikonthethird here.

**Comment by dustinmoris** [comment] 2018-08-16 10:32
What about people who only updated the .NET SDK to 2.1.400 and not Visual Studio for Mac?

**Comment by forki** [comment] 2018-08-16 10:33
Do you even ngen on Mac?

Dustin Moris Gorski <notifications@github.com> schrieb am Do., 16. Aug.
2018, 12:32:

**Comment by cartermp** [comment] 2018-08-16 15:40
@dustinmoris @forki .NET Core uses cross-gen, not ngen, which happens in the build lab for .NET Core. So F# on .NET Core shouldn't be affected.

**Comment by forki** [comment] 2018-08-16 16:04
Good to hear. I'm only doing core anyway these days...

Phillip Carter <notifications@github.com> schrieb am Do., 16. Aug. 2018,
17:41:

**Comment by cartermp** [comment] 2018-08-16 16:27
Note: this will still affect Visual Studio users who are targeting .NET Core, but if you're not using VS and using `dotnet build`/etc, then there's no regression.

**Comment by KevinRansom** [comment] 2018-08-16 17:17
FSC should be ngened.  Historically when VS installs the ngen activity is queued and run when ngen get's around to it.  Typically this is within 24 hours.

We have changed the way we deploy the compiler, however, I wouldn't have expected it to change this aspect of the install.

I will investigate to see if there is an issue, however, I don't expect there to be.

The dotnet cli deployment of F# is native compiled using crossgen.

**Comment by KevinRansom** [comment] 2018-08-16 17:35
The ngen flag for the deployed files are I believe correctly set here :  https://github.com/Microsoft/visualfsharp/blob/master/setup/Swix/Microsoft.FSharp.Compiler/Files.swr

But my deployment on my main desktop also appeared to not be ngened.  More digging is required.

**Comment by KevinRansom** [comment] 2018-08-16 17:55
Yes it looks to me like we are not ngening The FSharp bits on install.

**Comment by nikonthethird** [comment] 2018-08-16 18:57
Could it possibly be that it's not just F# that's not ngened? The Nuget pages in VS also seem much slower than usual and take way longer to install/update a package.

**Comment by cartermp** [comment] 2018-08-17 15:48
@nikonthethird After a new VS installation it takes time for NGEN to run for everything in VS, so it may be that some slowness you're observing is due to that

**Comment by cartermp** [comment] 2018-08-17 16:06
This is fixed in #5525. Next steps are to get a signed build and plumb it through the pipes to try and get into a servicing release.

**Comment by KevinRansom** [comment] 2018-08-17 17:13
@cartermp … Not fixed yet … the process is long, I merged it into a new branch so that we can get a validation build of VS.

**Comment by Thorium** [comment] 2018-08-20 07:10
> Compiling assembly FSharp.Core, Version=4.5.0.0

Does this mean that every project using the nuget-package should be ngened to compile the FSharp.Core because FSharp.Core itself in the nuget package is not ngened? And does this decrease the performance of typeproviders?

**Comment by goswinr** [comment] 2018-08-24 14:01
I have the impression the performance of VS IDE tooling is also affected. apart form `fsc.exe` and ` fsi.exe` are thet any other assemblies that i need to ngen to fix this on my PC ?

**Comment by cartermp** [comment] 2018-08-24 16:28
@goswinr You can look [here](https://github.com/KevinRansom/visualfsharp/blob/2c577dbc0f8f51556681b7be3a469f76ed710d46/setup/Swix/Microsoft.FSharp.Compiler/Files.swr) for a full set, though I believe it should also NGEN the relevant dependencies (e.g., `FSharp.Compiler.Private`), which is used by the editor.

**Comment by cartermp** [comment] 2018-09-20 20:05
The fix for this is in VS 15.8.5, which is now shipped.

**Closed by cartermp** 2018-09-20 20:05 UTC
Labels: Area-Compiler, Tenet-Performance, Urgency-Now, regression

**Comment by humhei** [comment] 2018-12-26 12:57
> The dotnet cli deployment of F# is native compiled using crossgen.


Q: Is core sdk ngened now by default?
If so , why does the fsc.exe is not ended with `.ni.exe`  as [doc](https://github.com/dotnet/coreclr/blob/master/Documentation/building/crossgen.md) metioned

**Comment by KevinRansom** [comment] 2018-12-28 01:39
@humhei 

we do not ship the .msil images merely the native images, so we get to use the good name :-)

We do the bold bit:
<snip  from: [here](https://github.com/dotnet/coreclr/blob/master/Documentation/building/crossgen.md#using-native-images) >
Running CrossGen on an assembly creates a "native image" file, with the extension of .ni.dll or .ni.exe. You should include the native images in your app, either by **replacing the original MSIL assemblies with the native images** or by putting the native images next to the MSIL assemblies. When the native images are present, the CoreCLR runtime will automatically use it instead of the original MSIL assemblies.
</snip>

Kevin
