### ISSUE TITLE
Visual Studio locking access to xml doc files

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#57] opened 2015-01-19 12:07 UTC
This is a common annoyance when using Visual Studio together with FAKE. Running a FAKE build while the solution is open in Visual Studio invariably results in the following error:

```FSC : error FS0193: Access to the path 'path_to_bin_folder\project.XML' is denied. ['path_to_project\project.fsproj']```

The error persists even if the solution is closed from within Visual Studio. The IDE needs to be restarted in order for the problem to go away.

**Comment by forki** [comment] 2015-01-19 12:08
yes this is a major annoyance

**Comment by theimowski** [comment] 2015-01-19 12:31
:+1:

**Comment by forki** [comment] 2015-01-19 12:41
any ideas where we need to look?

**Comment by braden** [comment] 2015-01-19 17:42
I have noticed this also happens occasionally when project files change externally an VS reloads them, unrelated to FAKE. I had suspected F# Power Tools, maybe there is something in common?

**Comment by dsyme** [comment] 2015-01-19 18:21
I'd love to see this fixed, I've seen it somewhat randomly when compiling quite a range of F# projects.

**Comment by ovatsus** [comment] 2015-01-19 21:21
I've also seen this. On F# Data I went to some trouble to try to not lock the .dll files, but then the .xml file is still locked :/
https://github.com/fsharp/FSharp.Data/commit/8734a17c3cfb8d8be27b2881c878baf09460e046

**Comment by latkin** [comment] 2015-01-21 20:04
Curious - does this seem to affect only F#, or has anyone experienced it with C#, too? Would also be good to know if this is a long-standing problem, or has this been the case for multiple VS releases?

**Comment by ovatsus** [comment] 2015-01-21 21:31
This problem has existed at least since VS2012, and I never saw it in C#

**Comment by dungpa** [comment] 2015-01-22 00:32
Accorrding to this answer http://stackoverflow.com/questions/6515795/why-is-my-xml-doc-file-always-getting-locked, this code fragment supposes to fix the bug https://github.com/Microsoft/visualfsharp/blob/fac44095a8dbc7303efa9866e0e2d9dddbdeae5d/vsintegration/src/vs/FsPkgs/FSharp.Project/Common.Source.CSharp/Project/ProjectConfig.cs#L1877-L1896. I'm not sure there is any regression here.

For now, this answer seems like a reasonable workaround http://stackoverflow.com/a/3969978.

**Comment by rojepp** [comment] 2015-01-26 13:47
@dungpa If I understand that fix correctly, it fixes for for building in VS only:
When a build starts, ask intellisense to stop locking xml doc. After build is finished, tell intellisense that its ok to lock this file again. This means building from command line will never work properly. How can we tell intellisense to never lock this file?

**Comment by dungpa** [comment] 2015-01-26 20:02
@rojepp 
> How can we tell intellisense to never lock this file?
No idea. I don't understand why it needs to lock xml files in the first place.

@vladima @KevinRansom @latkin Any pointer to investigate this further?

**Comment by latkin** [comment] 2015-01-26 23:05
Ok, just investigated a bit. This repros for C#, as well, at least as far back as VS 2013.

Steps:
- Create C# library project, add some XML doc comments, make sure project setting to generate doc file is enabled
- Build, then close VS
- Create new VS C# project, reference built binary from earlier.
- Use editor to view XML doc comments via intellisense
- Try re-building original project on command line via MSBuild
  - This fails due to XML doc file locked

So at least F# is not doing anything *worse* than C# here.

That's not to say this couldn't in theory be fixed (for all languages).  Seems that project systems don't actually touch the XML doc files themselves, they rely on VS platform to handle this (lots of complexities around path to localized XML files, etc). Code [here](https://github.com/Microsoft/visualfsharp/blob/fac44095a8dbc7303efa9866e0e2d9dddbdeae5d/vsintegration/src/vs/FsPkgs/FSharp.LanguageService/XmlDocumentation.fs#L30) is using [IVsXMLMemberIndexService](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsxmlmemberindexservice.aspx). So the bug (and the fix) is somewhere in the VS platform/SDK, not in the F# codebase.

Maybe I will log a bug on the platform team to look at this.

**Comment by rojepp** [comment] 2015-01-27 14:22
@latkin Please do file a bug and report any progress back here. :)

**Comment by forki** [comment] 2015-03-12 14:37
@latkin any news about from the platform team?

**Comment by dnauck** [comment] 2015-03-12 14:39
+1

**Comment by Arcitectus** [comment] 2015-03-12 23:42
:+1:

**Comment by latkin** [comment] 2015-03-12 23:59
I've found an old internal bug tracking thing. It ended up getting closed, I think just because it was close to a deadline and nobody had a chance to follow up.

I can bring that bug back to life, but first I'd like to know when the issue was introduced. If would help if someone could give positive confirmation whether this repros in VS 2012 and VS 2010, if you have those installed. My steps here https://github.com/Microsoft/visualfsharp/issues/57#issuecomment-71557706 should be valid to repro.

**Comment by yukitos** [comment] 2015-03-13 02:46
I tried VS 2008, 2010, 2012, and this repros in all of them :cry:

**Comment by dsyme** [comment] 2015-03-17 12:44
I hit this problem yesterday (I had to restart VS to update some nuget packages due to XML file locking)

**Comment by latkin** [comment] 2015-03-21 00:46
FYI, @KevinRansom is poking the VS platform people about this, hopefully more updates next week

**Comment by KevinRansom** [comment] 2015-03-21 01:17
The team that owns this code has been identified and a bug raised.  We will keep you posted as to progress.
Just to set expectations you should recognize that this behavior has been substantially the same since Whidbey without this bug getting a lot of attention and so they may not be inclined to change it at this time.

**Comment by forki** [comment] 2015-03-21 06:37
Thanks for opening the issue. Is this a private Microsoft issue tracker or can we see progress/discussion?

**Comment by forki** [comment] 2015-03-21 06:57
Regarding activity: maybe it wasn't a big issue at the time when the bug got introduced, but since NuGet is used everywhere people see this issue all the time (at least that's what my twitter stream is suggesting for a couple of years)

**Comment by latkin** [comment] 2015-03-21 16:36
@forki it's in a private bug database

**Comment by KevinRansom** [comment] 2015-03-22 01:43
We'll keep y'all in the loop as my southern wife would say.

**Comment by latkin** [comment] 2015-04-15 21:00
This got discussed a bit with platform people over the past few weeks. It's almost surely not going to be fixed for VS 2015 RTM, but it's on their radar perhaps for an early VS update after that.  No guarantees , though.

Just wanted to let you know this hasn't totally disappeared into a black hole.

**Comment by forki** [comment] 2015-09-04 08:24
Ping. Any news on this? It's still no. 1 annoyance for me. Working with cmd line tools like FAKE or git and having solution open is not possible.

**Comment by forki** [comment] 2015-09-22 13:17
ping

**Comment by eiriktsarpalis** [comment] 2015-09-22 13:18
ping++

**Comment by TWith2Sugars** [comment] 2015-09-22 13:43
pong++

**Comment by cdrnet** [comment] 2015-10-04 16:56
ping - was just blocked once more where VisualStudio failed to compile an F# project because it was locking the xml file itself (sic).

**Comment by KevinRansom** [comment] 2015-10-16 17:48
Lol with the pings.  This was fixed in the VS platform, and will be part of VS 2015 Update 1.

Kevin

**Closed** 2015-10-16 17:54 UTC
Labels: bug, pri-1

**Comment by eiriktsarpalis** [comment] 2015-10-16 19:27
I just tried the CTP, and can confirm that the problem has gone away. This has easily saved me 20 minutes of work every day. :smiley:

**Comment by rojepp** [comment] 2015-10-16 19:42
Lovely!

**Comment by vasily-kirichenko** [comment] 2015-10-16 20:00
:+1:

**Comment by rodrigovidal** [comment] 2015-10-17 04:01
\o/ What a day, what a lovely day!

**Comment by forki** [comment] 2015-10-17 06:38
Wow. That's great to hear. Thanks so much.

**Comment by forki** [comment] 2015-10-27 08:49
@KevinRansom could you please ask if this was also resolved for dll file locking? Can we switch branches from cmd line when VS is open?

**Comment by hmemcpy** [comment] 2015-10-27 08:56
Is the CTP containing this fix publicly available? If not, is there an ETA?

**Comment by khellang** [comment] 2015-10-27 08:57
@hmemcpy http://blogs.msdn.com/b/visualstudio/archive/2015/10/08/visual-studio-2015-update-1-ctp.aspx :smile:
