### ISSUE TITLE
Internal FCS error is shown on SRTP pattern for struct tuple

### ISSUE THREAD

**Issue by Liminiens** [Microsoft/visualfsharp#6062] opened 2019-01-04 11:02 UTC
#### Repro steps

1. Write this code

```
let inline test (arg: ^T when ^T : struct) = 
    (^T : (member Item1: _) (arg))

[<EntryPoint>]
let main argv =
    let a = test struct (1, 2)
    0 // return an integer exit code
```

#### Expected behavior

Pattern works as `ValueTuple` has `Item1` (?)

#### Actual behavior

```
FS0192	internal error: tcrefOfAppTy
FS0073	internal error: tcrefOfAppTy (Failure)
FS0073	internal error: tcrefOfAppTy (Failure)
FS0073	internal error: tcrefOfAppTy (Failure)
FS0073	internal error: tcrefOfAppTy (Failure)
FS0073	internal error: tcrefOfAppTy (Failure)
```

#### Related information 

.NET Core SDK 2.2.101

**Comment by cartermp** [comment] 2019-01-04 16:52
There is no current ability to use `ItemX` properties on struct tuples. There is an approved RFC out to do this here: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1064-struct-tuple-equivalence.md

We'd certainly welcome the PR, but I don't think it's a priority for us given that pattern matching/deconstruction is the idiomatic way to work with tuples in F#.

That said, I'm labeling this as a regression since the error message did appear to _not_ be an internal error at one point:

`/Users/phillip/scratch/bar/Program.fs(54,13): error FS0001: A generic construct requires that the type 'struct ('a * 'b)' is a CLI or F# struct type`

Though what it really should be saying is that `struct (1, 2)` does not support `Item1` as a property

**Comment by auduchinok** [comment] 2019-01-05 08:11
Just to add a bit of context: the initial [issue](https://youtrack.jetbrains.com/issue/RIDER-23276) mentions it's happening in Rider 2018.3.1 that uses FCS built from `dev15.9` branch (with few additional patches) so the regression seems to not have appeared after recent changes in `master`.

**Comment by TIHan** [comment] 2019-01-10 23:08
When I was implementing this: https://github.com/Microsoft/visualfsharp/pull/6064 there was an issue with struct tuples that might be similar to this one.

**Comment by TIHan** [comment] 2019-01-11 22:58
Closing issue as we have resolved the internal error and now receive a proper error. Also fixes struct tuples and struct constraints in general.

**Closed by TIHan** 2019-01-11 22:58 UTC
Labels: Area-Compiler, regression
