### ISSUE TITLE
Cannot lazy-install F# into RC2

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2001] opened 2016-12-13 09:58 UTC
1) Install VS2017 RC2 with desktop feature set (Note F# is not enabled by default) without F#.
2) Open F# solution and follow lazy installer.

=> Lazy installer fails because "VS ist already open". ¯\_(ツ)_/¯ 

![image](https://cloud.githubusercontent.com/assets/57396/21135777/41208a1a-c123-11e6-96ac-3c5a41834894.png)

**Comment by forki** [comment] 2016-12-13 10:06
unfortunately even when I start the installer directly (without having VS open) the install fails.

**Comment by forki** [comment] 2016-12-13 10:18
ok so I uninstalled VS2017 RC2 completely and reinstalled with F# flag selected. Still no F# support.
I give up. Can I please have my VS2013 installer back?

**Comment by vasily-kirichenko** [comment] 2016-12-13 10:20
I can give you RC installer which I haven't deleted (a very wise decision).................

**Comment by isaacabraham** [comment] 2016-12-13 10:21
I guess s one way of fixing the issues with F# and VS2017 is to replace all of them with just one bug - can't install F# ;-)

**Comment by forki** [comment] 2016-12-13 10:42
So everytime I install I get:

    [5d1c:001c][2016-12-13T11:33:50] Package 'Microsoft.PortableLibrary.TargetingPack.Msi,version=15.0.26004.1' failed to install. MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.PortableLibrary.TargetingPack.Msi,version=15.0.26004.1\portablelibrary_dtp_sfx.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7"  VSEXTUI="1"  EXTUI="1" , Return code: 1620, Details: Dieses Installationspaket konnte nicht geöffnet werden. Wenden Sie sich an den Hersteller der Anwendung, um sicherzustellen, dass es sich um ein gültiges Windows-Installationspaket handelt.
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab3.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab4.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab5.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab6.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab7.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab8.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab9.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab10.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab11.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904
    [5d1c:0017][2016-12-13T11:34:45] Error 0x80070002: 
    Package payload not found: cab12.cab, package: Microsoft.Net.CoreSDK.50,version=1.0.23904

**Comment by forki** [comment] 2016-12-13 11:14
This is really annoying. I wished C# and VB would have been treated the same as F#. Then this bug would have been found before. Also why can't I uncheck C# and VB from the installation. This was promised multiple times.

**Comment by forki** [comment] 2016-12-13 13:46
needles to say that after VS2017 RC2 uninstall my VS2015 is broken and I can't build VF# compiler anymore...

**Comment by vasily-kirichenko** [comment] 2016-12-13 13:47
@forki perform "Restore" action for VS 2015, it should help.

**Comment by isaacabraham** [comment] 2016-12-13 15:22
@forki I only pray that you don't have VS2013 installed as well.

**Comment by cartermp** [comment] 2016-12-13 16:40
@forki Can you try this again, then run the [vscollect](https://www.microsoft.com/en-us/download/details.aspx?id=12493) tool, and email them to me, @KevinRansom, or @brettfo?  This will snag all the detailed logs we need so we can either address the issue ourselves our route it to the appropriate person.

It looks like PCL targeting packs are the culprit based on what you logged above, but that could also be because something else failed.  The logs will tell all.

**Comment by forki** [comment] 2016-12-13 16:51
104MB that's too big. Are you on skype? I'm forki23

**Comment by cartermp** [comment] 2016-12-13 16:53
Yup, done

**Comment by brettfo** [comment] 2016-12-13 18:22
There may be some stale packages on your machine.  Can you navigate to "`%appdata%\Microsoft\VisualStudio\Packages\_Channels`"?  In that directory will be one or more directories that the VS installer uses as it's staging location before installing and I've seen similar issues in the past when upgrading between internal builds.  It's safe to delete the directories under `_Channels`, but unfortunately it's not immediately obvious which one corresponds to the current installer.  On my machine it's `F8B28931`, but that may be machine-dependent.

Once those directories are cleaned, try running the installer again.

**Comment by forki** [comment] 2016-12-13 18:43
I didn't have VS installed before, so I'm not switching between builds.

Am 13.12.2016 19:22 schrieb "Brett V. Forsgren" <notifications@github.com>:

**Comment by forki** [comment] 2016-12-14 08:42
@brettfo after deleting that folder I get a nice and clean view of the installer:

![image](https://cloud.githubusercontent.com/assets/57396/21175235/964be778-c1e1-11e6-9e9b-8bd31b459732.png)

;-)

**Comment by forki** [comment] 2016-12-14 08:53
1) I uninstalled the installer. 
2) downloaded the installer again
3) tried to install again 

=> same error. So it seems it was not cache related.

**Comment by vasily-kirichenko** [comment] 2016-12-14 09:30
I confirm that F# is not selected by default in ".NET desktop development" group:

![image](https://cloud.githubusercontent.com/assets/873919/21176693/f9604270-c1f8-11e6-912c-91608f5df4b8.png)

**Comment by forki** [comment] 2016-12-14 09:51
the best thing: my debugger in VS2013 and VS2015 is now broken. Everytime I want to inspect a binding at a breakpoint it crashes VS. Nice one.

**Comment by vasily-kirichenko** [comment] 2016-12-14 10:01
@forki try to run the installer again and, press "modify", then select F#.

**Comment by forki** [comment] 2016-12-14 10:02
which installer?

**Comment by vasily-kirichenko** [comment] 2016-12-14 10:02
web installer, if it works for you.

**Comment by vasily-kirichenko** [comment] 2016-12-14 10:03
About breakpoints issue, "restore" VS 2015. I have both 2015 and 2017 RC2 on my machine working OK.

**Comment by forki** [comment] 2016-12-14 10:05
the installer bug is unrelated to F# - I can't even install vanilla .NET desktop package,

**Comment by forki** [comment] 2016-12-14 11:59
when trying to use the offline installer I get

    [285c:0003][2016-12-14T12:58:55] Package 'Microsoft.PortableLibrary.TargetingPack.Msi,version=15.0.26004.1' failed to install. MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.PortableLibrary.TargetingPack.Msi,version=15.0.26004.1\portablelibrary_dtp_sfx.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7"  VSEXTUI="1"  EXTUI="1" , Return code: 1620, Details: Dieses Installationspaket konnte nicht geöffnet werden. Wenden Sie sich an den Hersteller der Anwendung, um sicherzustellen, dass es sich um ein gültiges Windows-Installationspaket handelt.

**Comment by forki** [comment] 2016-12-14 12:08
after deleting that msi the installer seems to run fine. 

![image](https://cloud.githubusercontent.com/assets/57396/21181442/3818458a-c1fe-11e6-80f5-4657bb4824bc.png)

**Comment by forki** [comment] 2016-12-14 12:08
of course VS2017 is still completely unusable because something unreported went wrong

**Comment by forki** [comment] 2016-12-14 12:16
ok yet another uninstall + install and now it actually seems to be installed. That was too easy,

**Comment by cartermp** [comment] 2016-12-14 14:28
FYI @forki we're looking into the Portabl PCL MSI install failure.

**Comment by forki** [comment] 2016-12-14 14:51
there is still that issue that F# is not checked by default and that lazy install doesn't work at all.

**Comment by cartermp** [comment] 2016-12-14 14:58
Those are two other issues to look at.  The first one isn't a bug (but your feedback can affect it).  The second is a bug.

**Comment by cartermp** [comment] 2016-12-14 15:04
Okay, for the lazy install (we call it In-Product Acquisition), I noticed two bugs:

1. VS did not prompt me to install F# when opening a solution with an F# project.  It should do that.
2. Upon installing F# (right-click -> Install Missing Feature(s), close VS, install, open solution again), the projects are now "Incompatible".  I get this error message in the Migration Report:

```
src\fsharp\FSharp.LanguageService.Compiler\FSharp.LanguageService.Compiler.fsproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=659597&projecttype=F2A71F9B-5D33-465A-A702-920D77279786
```

**Comment by forki** [comment] 2016-12-14 15:06
also please try to make sure opening an fsx without fsproj triggers F# install. this is reported since VS2015 RTM and hurts many of the FAKE users

**Comment by isaacabraham** [comment] 2016-12-14 15:07
@cartermp What about opening naked fs or fsx files? This was a big issue with the surprise VS2015 changes and we were assured it would be fixed for VS2017.

**Comment by cartermp** [comment] 2016-12-14 15:08
@brettfo Can answer about the ability for VS to recognize file types and prompt for an install.

**Comment by forki** [comment] 2016-12-14 15:08
![fire](https://cloud.githubusercontent.com/assets/57396/21187254/9845e2aa-c217-11e6-84bb-ca7f7456a968.gif)

**Comment by forki** [comment] 2016-12-14 15:29
@brettfo @cartermp @KevinRansom in all seriousness. you should really see the fsx install thing as a bug. It's maybe one of the most important bugs in whole F# story.
FAKE is used as a gateway drug for F# in many many C# shops. For these shops it's actually the only place where F# is used at all. And since 2015 RTM the ootb install is just broken. 
It worked since the first release of F#. It's now broken for 2 years - and nobody really cares?

**Comment by forki** [comment] 2016-12-14 15:37
![image](https://cloud.githubusercontent.com/assets/57396/21188391/8e97cba2-c21b-11e6-8513-3efdf1832534.png)

**Comment by 0x53A** [comment] 2016-12-14 16:35
If you don't want to enable F# by default and can't trigger on file extensions (I think this was mentioned in another issue as a limitation), what about implementing something similar to the powershell workaround?

https://github.com/Microsoft/visualfsharp/issues/1040#issuecomment-206986679

**Comment by cartermp** [comment] 2016-12-14 16:49
So to be clear, it's not that we do not want F# installed by default.  We definitely want it installed by default.  This isn't our decision to make, though.

As for recognizing file extensions, I simply don't know if it's a capability of VS or if it's something we must implement ourselves.  If it's the latter, we need to evaluate if it's possible to build and test that capability in time for release in addition to fixing bugs and accepting contributions.

**Comment by KevinRansom** [comment] 2016-12-14 18:42
@forki .FSX based install ought to work ... the team who own making it work know that, but they have a ton of other firestorms they are working on.  The whole setup experience has been completely reworked this release, and they haven't gotten it done yet.

We want to see it happen at least as much as you do, and we raised it as a serious issue before vs2015 was released.   It has only not happened yet because of priorities, that is all.  I expect it too happen eventually.

Kevin

**Comment by forki** [comment] 2016-12-14 18:54
2 years Kevin.

**Comment by KevinRansom** [comment] 2016-12-14 18:56
I know ... it makes me sad ... and reminds me how little influence I have.  I however, remain optimistic that the right thing will be done eventually.

Kevin

**Comment by isaacabraham** [comment] 2016-12-14 19:18
Kevin, there's an easy fix. Undo the change between RC2 and RC1 so that F# is turned on by default. It's a check box for heaven's sake. Surely within the depths of devdiv and the power of Microsoft there's someone that can do that.

**Comment by dsyme** [comment] 2016-12-27 19:52
So to be clear, the bug here is currently characterised by this https://github.com/Microsoft/visualfsharp/issues/2001#issuecomment-267056667

i.e.

1. VS did not prompt me to install F# when opening a solution with an F# project. It should do that.

2. Upon installing F# (right-click -> Install Missing Feature(s), close VS, install, open solution again), the projects are now "Incompatible". I get this error message in the Migration Report...

Is that correct?  Both seem pretty disastrous :/

**Comment by cartermp** [comment] 2016-12-27 19:55
Yep.  @brettfo is addressing the setup authoring which affects this.  This is one of the key behavioral features of acquisition in vs2017, so it's a high priority fix.

**Comment by dsyme** [comment] 2017-01-28 14:40
@cartermp I notice this is labelled "Urgency Now" - Could you possibly take a quick scan through all the [Urgency Now](https://github.com/Microsoft/visualfsharp/issues?q=is%3Aissue+is%3Aopen+label%3AUrgency-Now) and [Regression](https://github.com/Microsoft/visualfsharp/issues?q=is%3Aopen+is%3Aissue+label%3Aregression) bugs and close out the ones we know are fixed in RTM please?  Thanks!

**Comment by cartermp** [comment] 2017-01-28 16:51
@dsyme I'll make another round; however aside from this issue (which I'll test again) I believe they're all unfixed.

**Comment by dsyme** [comment] 2017-01-29 22:04
@cartermp OK, thanks

**Comment by cartermp** [comment] 2017-02-02 19:48
So I _believe_ this is fixed; there's an internal build we can use to verify sometime soon.  There were actually two places where this was busted:

1. In the context of having a .NET workload installed, which included Roslyn Workspaces
2. In the context of _just_ having F#, and no .NET Workload

The first was fixed by @brettfo with some setup changes that should appear in the next update to RC.  The latter was discovered recently - the F# component also now requires Roslyn Workspaces to be pulled in (an additional handful of MB), but setup authoring did not reflect that change.  So there are some circumstances where you can successfully get F# detected, but fail to have it work because there isn't a Roslyn workspace underneath.  @brettfo fixed that bug yesterday.

**Comment by dsyme** [comment] 2017-02-03 13:20
@cartermp Thanks for the update

> 2.	In the context of just having F#, and no .NET Workload

That setup combination should be pretty rare I think.

**Comment by cartermp** [comment] 2017-03-06 16:05
@forki Have you been able to repro this with later RCs?  We've done some more setup work and I believe this should be fixed.  With RC4 I did:

Uninstall F# from VS Installer ---> Open VS and try to load F# project ---> prompted to install F# as the VS installer opens --->Installed F# (checked for me) ---> Load F# project successfully

**Comment by forki** [comment] 2017-03-07 06:58
No sorry I didn't try it again.

**Comment by cartermp** [comment] 2017-03-15 04:43
Okay.  Closing this as fixed for now, since we addressed some issues here and it seems to have been fixed since RC4.

**Closed by cartermp** 2017-03-15 04:43 UTC
Labels: Area-Setup, regression, Urgency-Now
