### ISSUE TITLE
UnusedOpensDiagnosticAnalyzer does not catch System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by jmarolf** [Microsoft/visualfsharp#2769] opened 2017-04-01 18:36 UTC
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.VisualStudio.FSharp.Editor.UnusedOpensDiagnosticAnalyzer' threw an exception of type 'System.Threading.Tasks.TaskCanceledException' with message 'A task was canceled.'.	PerfStore		1	Active	Analyzer 'Microsoft.VisualStudio.FSharp.Editor.UnusedOpensDiagnosticAnalyzer' threw the following exception:
'System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.Executor.<ComputeDocumentDiagnosticAnalyzerDiagnosticsAsync>d__12.MoveNext()
-----
'.

```

**Comment by saul** [comment] 2017-04-01 19:39
Dupe of #2100

**Closed** 2017-04-01 23:40 UTC
