### ISSUE TITLE
FSI generates internal error: Index not found with Struct DU

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2363] opened 2017-02-03 16:36 UTC
1. Open FSI via command line or F# Interactive
2. Enter the following:

```fsharp
[<Struct>]
type Shape =
    | Circle of radius: float
    | Square of side: float
    | Triangle of height: float * width: float
```

**Expected:** FSI executes and the type is registered.
**Actual:** `error FS0193: internal error: Index not found. (Exception from HResult: 0x80131124`

![internal-error-struct-du](https://cloud.githubusercontent.com/assets/6309070/22599437/d4ea6c52-e9eb-11e6-838e-f3c9898b86ec.PNG)
![internal-error-struct-du-fsi](https://cloud.githubusercontent.com/assets/6309070/22599441/d79993a6-e9eb-11e6-92dd-89c814b06381.PNG)

**Comment by kbattocchi** [comment] 2017-02-03 19:20
Are multi-case struct DUs supposed to work?  I thought only single-case DUs could be represented as structs.  (That is, I thought the expected behavior would be a compile-time error, not runtime success)

**Comment by cartermp** [comment] 2017-02-03 19:22
@kbattocchi Multicase DUs are now supported in F# 4.1, although there is currently a bug with them: #1678

**Comment by kbattocchi** [comment] 2017-02-03 19:31
I see; it looks like the [RFC](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.1/FS-1014-struct-discriminated-unions.md) states

> For multi-case struct unions, each case must have a unique name.

but presumably this was supposed to say _unique type_ instead?  In which case this would again be expected to fail at compile-time.

(As an aside, I had trouble finding the RFC because several of the links to it are dead since it was moved from /RFCs to /FSharp4.1)

**Comment by cartermp** [comment] 2017-02-03 19:58
@dsyme could comment further, but the intention to my understanding is that they simply require unique names.  They shouldn't also require unique types.

**Comment by KevinRansom** [comment] 2017-02-03 21:40
@kbattocchi 
Well .. it works fine if it's not a struct so it seems like it should work for struct DUs to

Works in FSI
````
type StructShape =
    | Circle of radius: float
    | Square of side: float
    | Triangle of height: float * width: float
````

Fails in FSI
````
[<Struct>]
type StructShape =
    | Circle of radius: float
    | Square of side: float
    | Triangle of height: float * width: float

````

**Comment by KevinRansom** [comment] 2017-02-03 22:02
@cartermp 

The compiler doesn't like it either:

````
// Learn more about F# at http://fsharp.org
// See the 'F# Tutorial' project for more help.

[<Struct>]
type StructShape =
    | Circle of radius: float
    | Square of side: float
    | Triangle of height: float * width: float

[<EntryPoint>]
let main argv = 
    printfn "%A" argv
    0 // return an integer exit code
````
Fails with:
````
1>FSC: error FS2014: A problem occurred writing the binary 'C:\Users\kevinr\Documents\Visual Studio 2017\Projects\ConsoleApplication31\ConsoleApplication31\obj\Debug\ConsoleApplication31.exe': Error in pass2 for type Program, error: Error in pass2 for type StructShape, error: duplicate entry '.ctor' in method table
1>Done building project "ConsoleApplication31.fsproj" -- FAILED.
````

**Comment by cartermp** [comment] 2017-02-03 22:05
Same underlying issue as #1678 then.  Bah.

**Comment by dsyme** [comment] 2017-02-04 13:19
Yes, my apologies for https://github.com/Microsoft/visualfsharp/issues/1678. We will address it in F# 4.2 (or next update of F# 4.1)  For now we have to list it as a known limitation.

**Comment by dsyme** [comment] 2017-02-04 13:20
I'll close this as a duplicate of https://github.com/Microsoft/visualfsharp/issues/1678

**Closed by dsyme** 2017-02-04 13:20 UTC
Labels: Area-FSI, bug, Urgency-Soon
