### ISSUE TITLE
What happens when you introduce parenthesis around tuple declaration in f# signature file? 

### ISSUE THREAD

**Issue by wallymathieu** [Microsoft/visualfsharp#1344] opened 2016-07-12 09:51 UTC
While trying out things looking at [RFC FS-1004 Result type](https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1004-result-type.md)
in the following [repository](https://github.com/wallymathieu/FSharp.Results/), I stumbled on something.

The following compiles (together with an implementation):

```
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Result =
...
  [<Class>]
  type ResultBuilder =
...
    member Combine : (Result<'T,'TError>)* (Result<'T,'TError>) -> Result<('T list),('TError list)>
```

The implementation:

```
    member __.Combine (a: Result<'T,'TError>, b:Result<'T,'TError>) : Result<'T list,'TError list>= 
        match a,b with
        | Ok v1,Ok v2 -> Ok [v1;v2]
        | Error e1,Error e2 -> Error [e1;e2]
        | Error e1, _ -> Error [e1]
        | _, Error e2 -> Error [e2]
```

However, the following does not:

```
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module Result =
...
  [<Class>]
  type ResultBuilder =
...
    member Combine : ((Result<'T,'TError>)* (Result<'T,'TError>)) -> Result<('T list),('TError list)>
```

Note the extra parenthesises around the parameters. 

I've tested the behaviour on f# bundled with Mono 4.4.1 and F# 4.0 (F# Compiler version 14.0.23413.0). The .net version used: 4.5.

**Comment by dsyme** [comment] 2016-07-12 16:46
@wallymathieu This is by design - the extra parentheses indicate that the method takes an actual tuple value, rather than two arguments.

**Comment by dsyme** [comment] 2016-07-12 16:47
@wallymathieu Thanks for the report. Since this is by design, I'll close it.

**Closed by dsyme** 2016-07-12 16:47 UTC

**Comment by wallymathieu** [comment] 2016-07-12 17:37
Aaa, thanks!
