### ISSUE TITLE
Values/ constants with LiteralAttribute become null or numeric zero when read in C# (!!), in recent production VS versions

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4617] opened 2018-03-23 14:01 UTC
From one version of VS to another tests started failing and after some digging, much to my surprise, the values of `[<Literal>]` constants had become `null` (!).

This happens at least in VS 15.6.1 to 15.6.4. It doesn't happen somewhere before that. I can confirm this from my build server which has a previous edition.

#### Repro with strings

In an F# project:

```f#
module Constants =
    let [<Literal>] Foobar = "tst"
    let Barrr = "bar"
```

From a C# project:

```c#
[Test]
public void TestConstant()
{
    var x = Constants.Foobar;
    var y = Constants.Barrr;
    Assert.AreEqual("tst", x);   // fails with x being null (!!!)
    Assert.AreEqual("bar", y);   // succeeds
}
```

#### Repro with numeric values

In an F# project:

```f#
module Constants =
    let [<Literal>] NumericLiteral = 42
    let NumericNormal = 42
```

From a C# project:

```c#
[Test]
public void TestConstantNumeric()
{
    var x = Constants.NumericLiteral;
    var y = Constants.NumericNormal;
    Assert.AreEqual(42, x);   // fails, x == 0
    Assert.AreEqual(42, y);   // succeeds
}
```

### Expected behavior

The value of the constants should not be different within F# or C#. Furthermore, it should not be different from what is declared.

### Actual behavior

* Literal string values become `null`.
* Literal numeric values become numeric zero.

### Known workarounds

I wish I knew of a workaround. I cannot declare these non-literal, as they are used both in patterns and in C#. For now I'll let the build server run an older version and during development I'll ignore the failing tests.

### Related information 

Looking at the IL, the generated code appears normal. I tried running the tests with several test runners in case some instrumentation gets wrongly added, but it appears to *happen always*.

```ilasm
.field public static int32 NumericLiteral = int32(0x2a)
{
    .custom instance void [FSharp.Core]Microsoft.FSharp.Core.LiteralAttribute::.ctor()
    .custom instance void [mscorlib]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggerBrowsableState) = { valuetype [mscorlib]System.Diagnostics.DebuggerBrowsableState::Never }
}
```

* Windows 7, fully updated
* Visual Studio 15.6.1, - 15.6.4
* Visual Studio 15.7.0 Preview 2
* Does *not* happen on older VS versions in 15.x range
* Severity: probably very high, this may break a lot of code...

**Comment by abelbraaksma** [comment] 2018-03-23 14:52
This is the ILASM of VS 2015 with F#. 

```ilasm
.field public static literal int32 NumericLiteral = int32(0x2a)
{
    .custom instance void [FSharp.Core]Microsoft.FSharp.Core.LiteralAttribute::.ctor()
    .custom instance void [mscorlib]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggerBrowsableState) = { valuetype [mscorlib]System.Diagnostics.DebuggerBrowsableState::Never }
}
```

I don't see any difference. So I looked up C#'s code. 

This is the **decompiled** code in VS2015 (of earlier VS2017 versions):

```c#
[Test]
public void TestConstantNumeric()
{
    int actual = 0x2a;
    int numericNormal = Constants.NumericNormal;
    Assert.AreEqual(0x2a, actual);
    Assert.AreEqual(0x2a, numericNormal);
}
```

And this is the **decompiled** code now (VS 15.6.4)

```c#
[Test]
public void TestConstantNumeric()
{
    int numericLiteral = Constants.NumericLiteral;
    int numericNormal = Constants.NumericNormal;
    Assert.AreEqual(0x2a, numericLiteral);
    Assert.AreEqual(0x2a, numericNormal);
}
```

There's a clear difference here. Now I'm wondering whether the C# compiler made a change and didn't respect the `LiteralAttribute` or `const` flag anymore, or the change was that constants shouldn't be copied statically (a big change with 15 years of C# compiling). 

But even so, if the IL is to call  the field, then why is the field uninitialized? From looking at the compiled IL I don't think this should fail.

**Comment by cartermp** [comment] 2018-03-23 14:54
@abelbraaksma #4519 is a regression which got slurped into the 15.7 previews and older nightlies, but it's also since been fixed in later nightlies. Could that perhaps be the cause?

**Comment by abelbraaksma** [comment] 2018-03-23 15:12
> got slurped into the 15.7 previews

If that's the case, it also got slurped into anything beyond 15.6.1, not only previews. Unless having both Previews and Production editions on one machine means I'm sharing some of the Preview edition's libraries with other editions?

And if that is true, why do I see the same IL for both members in VS15 and VS17? But I agree, that bug report looks much like mine, except for the affected versions.

**Comment by abelbraaksma** [comment] 2018-03-23 15:18
@cartermp, on second thought, I think you are right (but still, 15.6 non-preview editions were affected, apparently).

When comparing by hand, I must have missed this:

My original post had this for compiled ILASM:

    .field public static int32 NumericLiteral = int32(0x2a)

My comment, which showed VS15 ILASM had:

    .field public static literal int32 NumericLiteral = int32(0x2a)

Which means that my conclusions were out of place, there *is* a difference and you are correct, it is the same thing as #4519.

May I suggest that not only Preview 3 gets an update, but also the production release of 15.6.x?

**Comment by cartermp** [comment] 2018-03-23 15:32
@KevinRansom @jaredpar @brettfo I thought I remember mentioning something about the compiler installed via 15.7 showing this issue in 15.6 as well. Is that still the case?

@abelbraaksma This definitely isn't in the 15.6 release because the cutoff for it was far before the change which caused this issue was merged. I believe there's an environmental issue with using a later F# compiler as a part of a preview where you're observing it both.

**Comment by abelbraaksma** [comment] 2018-03-23 17:34
@cartermp, so, if your scenario is: having two instances of VS, one Preview, one normal, then installing a new Preview edition also updates (parts of) the normal VS instance? I thought these were meant to be separate?

It's one of the reasons why I compile production code in the normal VS version, and use the Preview editions to try out new things. But if there isn't any difference, I might as well stick to one version.

I believe on VS's website, somewhere it says that they can coexist and don't touch each other. Not true?

**Comment by KevinRansom** [comment] 2018-03-23 17:38
@abelbraaksma , we still use an MSI to install the compiler, we have a plan to move that to a VSIX, when that happens we will be properly and fully side by side.  I believe it's close to the next thing on Brett's plate.  I'm hoping Dev15.8 will have the compiler properly vsixed.

**Comment by abelbraaksma** [comment] 2018-03-23 17:49
@KevinRansom, thanks, but maybe I misunderstand: an MSI cannot distinguish between what update service of VS is calling it, and install in whatever domain / version of VS it needs to? Or is it simply that in the "old situation" (pre VS17) only one VS instance needed to be targeted ever and the options are now to improve the MSI, or to go to VSIX, but if we are going to VSIX, it's a waste to work on the MSI?

**Comment by abelbraaksma** [comment] 2018-03-23 17:51
But to come back to my question: do I understand your (@KevinRansom) comment correctly if I say that each time I install a new version of VS, parts of it maybe shared with any other instance, which at this time includes F#?

Because, if that's the case, I have to be much more careful with updating the Preview instances.

**Comment by cartermp** [comment] 2018-03-23 18:11
@abelbraaksma You are correct - the MSI install for the F# compiler is a singleton. Until we move to VSIX, it's not truly side-by-side.

**Comment by KevinRansom** [comment] 2018-03-23 18:46
@abelbraaksma Visual Studio actually does an amazing job of being side by side.  The F# compiler is really the only component that I know of that is not correctly side by side for previews.  As I said, for sure we intend to fix it, and I believe that it will fixed in the VS2017.8 release.

**Comment by abelbraaksma** [comment] 2018-03-23 23:02
@KevinRansom, @cartermp, thanks. I was working on a batch file to target a single instance of Visual Studio for commandline installing extensions. It's already pretty feature-rich. One important part is to force-override an extension installation (i.e. not just copy-if-newer), which can be used to rollback a version. This has already come in very handy to test alpha releases of an extension.

It is written quite generically, so I was hoping to use it for F# too to make it trivial to temporarily check the fix to a bug by using a nightly build, but I think I should hold off until VS2018.8 comes about. I can't wait! But very glad it's on the roadmap! :+1:

**Comment by abelbraaksma** [comment] 2018-03-23 23:03
Sorry for going a bit OT ;). I understand a fix is underway, should I close this?

**Comment by cartermp** [comment] 2018-03-23 23:06
Yep, I think this is safe to close. Thanks for looking into all of this and the patience 😄

**Comment by abelbraaksma** [comment] 2018-03-23 23:14
You're welcome, thanks for taking the time to explain :)

**Comment by KevinRansom** [comment] 2018-03-24 06:12
I think using this to track the feature is probably the way to go.

@brettfo we will use this to track moving the compiler to a vsix.

**Comment by KevinRansom** [comment] 2018-03-24 06:14
Oh I thought this was the compiler thing. closing again.

**Closed by KevinRansom** 2018-03-24 06:14 UTC

**Comment by abelbraaksma** [comment] 2018-03-24 21:59
@KevinRansom: doesn't that already have an issue? If not, should I, or you, perhaps create one to track input?
