### ISSUE TITLE
.fsx file not colourized with latest bits.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1642] opened 2016-10-19 20:05 UTC
Observe:

![untitled](https://cloud.githubusercontent.com/assets/5175830/19535438/7f337058-95fc-11e6-944f-9fc6b70d4b4f.png)

**Comment by OmarTawfik** [comment] 2016-10-19 20:06
Are you sure it is not a duplicate of #1590?

**Comment by OmarTawfik** [comment] 2016-10-19 20:07
@KevinRansom  The fix is not inserted into VS yet. To test it, you've to F5 the vsix locally.

**Comment by KevinRansom** [comment] 2016-10-19 21:02
Sweet ... Thanks

**Closed** 2016-10-19 21:02 UTC
Labels: Area-IDE Language Service, bug
