### ISSUE TITLE
Create a F# .net core/standard project, the dependencies nodes occurs warning signs due to nuget package "System.ValueTupe".

### ISSUE THREAD

**Issue by Xiu-Li** [Microsoft/visualfsharp#4412] opened 2018-03-01 09:42 UTC
#### Repro steps
Create a **F# .net core/standard** project, restore finished without any errors and warnings, but the dependencies nodes occurs warning signs due to nuget package **System.ValueTupe(4.3.1)**.
Build and run the project succeeded.
![image](https://user-images.githubusercontent.com/24784908/36836942-c59120e8-1d75-11e8-8565-8382f4431abc.png)
#### Related information 
VS build: **d15.7stg/27428.3003** (15.7 Preview 1) 
dotnet --info:
```
.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54


```

**Comment by Xiu-Li** [comment] 2018-03-09 09:46
**Not repro** on latest **d15.7**/27508.00. 
But **repro** on latest **d15.7stg**/27508.3006.

**Comment by Xiu-Li** [comment] 2018-03-13 08:29
**Repro** on latest **d15.7/27512.00**.

**Comment by cartermp** [comment] 2018-03-13 13:28
@KevinRansom you and I talked about this in the hall and you said you know why this is reproducing. I don't quite recall the reason why...

**Comment by cartermp** [comment] 2018-05-08 16:48
For posterity: @KevinRansom looked into this and it's awfully tricky with no quick fix. I don't recall the proposed solution. @KevinRansom?

**Comment by KevinRansom** [comment] 2018-05-08 16:52
Yes, it is awful.  I think I had a fix in mind, but then get randomized ... It will take a while to get back to it, I need to focus on F# 4.5 for a while.  I will try to get a fix in for Dev 15.8.  No promises though.

**Comment by baltie** [comment] 2018-05-09 22:00
It might seem benign, and it is in many ways I guess, but it makes VS show yellow triangles on dependencies in all projects that reference an F# project right now. Which makes the yellow triangle pretty useless for tracking down actual dependency issues. I really hope you can get this fixed before 15.8, which is probably months away.

**Comment by karataliu** [comment] 2018-05-25 07:37
Also saw this issue. Please help address it.
```
VS 15.7.2
F# Tools 10.1 for F# 4.1
```

**Comment by cartermp** [comment] 2018-05-25 14:39
This should now be fixed with #4990

@KevinRansom is this pending a CLI insertion to light in the tools?

**Closed by cartermp** 2018-05-25 14:39 UTC
Labels: Area-IDE Language Service, Urgency-Soon

**Comment by YunWeiaa** [comment] 2018-06-12 09:17
Repro on **d15.7/27703.2031**.

**Comment by cartermp** [comment] 2018-06-12 09:31
@YunWeiaa I would expect this to continue to reproduce with 15.7 builds, as I don't think we've serviced the fix. It should no longer repro on d15.8 builds, though.

**Comment by YunWeiaa** [comment] 2018-06-12 09:48
Got it. Thanks.

**Comment by BenjaminHolland** [comment] 2018-06-12 16:10
Is there a fix for this, or do we just have to wait for a VS update?

**Comment by KevinRansom** [comment] 2018-06-12 17:19
@BenjaminHolland , it's fixed in VS2017.8 preview 3.   We will not be patching vs2017.7.
