### ISSUE TITLE
Erroneous 'open' statement simplification

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#4046] opened 2017-12-01 18:24 UTC
I have the following code in an F# file that uses SQL:

```f#
open System
open System.Data // "System." is marked as unnecessary
open System.Data.SqlClient // "System.Data." is marked as unnecessary
```

#### Expected behavior

Open statements should should never be simplified.

#### Actual behavior

Namespace is simplified, resulting in:

```
FS0893: This declaration opens the namespace or module 'System.Data.SqlClient' through a partially qualified path. Adjust the code to use the full path of the namespace. This change will make your code more robust as new constructs are added to the F# and CLI libraries.
```

#### Known workarounds

Ignore the simplification

**Comment by saul** [comment] 2017-12-01 18:25
Whoever gets around to looking at this - it's worth pointing out that if you have:

```f#
namespace Foo.Bar

open Foo
```

then the `Foo` in the `namespace` statement is marked as being unnecessary - the code fixer tries to simplify the namespace statement!

**Comment by vasily-kirichenko** [comment] 2017-12-01 18:36
Unacceptable. Just unacceptable :)

**Comment by TIHan** [comment] 2017-12-05 19:53
@saul could you provide a full sample or sample project?

**Comment by cartermp** [comment] 2017-12-05 20:30
@saul with the following class library project I don't see what you're reporting:

```fsharp
namespace Testy

open System
open System.Data
open System.Data.SqlClient

module Foo =
    let f() =
        use conn = new SqlConnection()
        ()
```

`System` and `System.Data` are greyed out, but I would expect that.

![testy](https://user-images.githubusercontent.com/6309070/33629206-16eafce0-d9b8-11e7-8359-8dddf0ed1450.PNG)

**Comment by saul** [comment] 2017-12-05 22:16
Of course because they aren’t being used... try using something from System and System.Data.

**Comment by cartermp** [comment] 2017-12-05 22:23
Works for me:

![works](https://user-images.githubusercontent.com/6309070/33633990-8a2ee216-d9c7-11e7-8b6d-cba64487410e.PNG)

If I fully qualify, then I get the suggestion to remove the unused namespace, but that's it. No option to simplify.

**Comment by vasily-kirichenko** [comment] 2017-12-06 05:11
@cartermp have you turned on the feature?

**Comment by cartermp** [comment] 2017-12-06 05:52
Yes, it's on.

**Comment by vasily-kirichenko** [comment] 2017-12-06 18:15
I can reproduce it on 15.5 preview 5

![image](https://user-images.githubusercontent.com/873919/33676863-f7d9c4b0-dac7-11e7-82b0-3035743f5b2a.png)

**Comment by vasily-kirichenko** [comment] 2017-12-06 18:15
Fixed in https://github.com/Microsoft/visualfsharp/pull/4068

**Comment by TIHan** [comment] 2017-12-06 19:16
I was able to reproduce. When you turn on the feature, it doesn't immediately reflect. You have to close the window and re-open.

**Closed** 2017-12-06 19:30 UTC
