### ISSUE TITLE
Display current parameter type in tooltip for generic function usage

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#158] opened 2015-01-27 21:42 UTC
opened on [CodePlex](https://visualfsharp.codeplex.com/workitem/172) by [TeaDrivenDev](https://www.codeplex.com/site/users/view/TeaDrivenDev)

The C# editor in Visual Studio displays the actual parameter types involved in the tooltips for generic class instances and method invocations. The F# editor only does that for objects and methods, but oddly not for F# types/functions; shouldn't this information be quite readily available? 

Having this kind of information at hand would especially make it quite a bit easier to follow the transformation of data through pipe chains, even more so as this type of display is also completely absent for lambdas at this time.

**Comment by TeaDrivenDev** [comment] 2015-12-26 22:25
As I just updated the corresponding issue in [FSharp.Compiler.Service](https://github.com/fsharp/FSharp.Compiler.Service/issues/268), I'll put this here too:

This is the tooltip for an *invocation* of a generic method in F# code in Visual Studio 2015:

![screenshot - 26 12 2015 22_42_22](https://cloud.githubusercontent.com/assets/2247219/12008035/4e9f0e52-ac23-11e5-8bcd-a85ee6dea655.png)

The compiler knows the types for `'TObj` and `'TRet`, but they are not shown anywhere.

This is what the C# editor shows for an equivalent invocation of the same method:

![screenshot - 26 12 2015 22_47_11](https://cloud.githubusercontent.com/assets/2247219/12008048/e3361330-ac23-11e5-814c-bf6d3883d06a.png)

In Visual Studio 2013, it's not as pretty (which I guess may be something that uses Roslyn), but it also shows the generic types for the current invocation:

![screenshot - 26 12 2015 22_46_54](https://cloud.githubusercontent.com/assets/2247219/12008053/20ff4c4a-ac24-11e5-8232-4d3057a7dce8.png)

There is also another kind of tooltip in the C# editor that I'm not sure how to trigger or when it appears; it more or less looks like this:

    public TOut M<TIn, TOut>(TIn value)
    Does something with the input value and returns the output value
    
    TIn is string
    TOut is int

I'm not sure if this information the compiler currently doesn't offer, or if it does, and the IDE tools don't use it.

**Comment by vasily-kirichenko** [comment] 2017-04-30 07:11
Implemented in https://github.com/Microsoft/visualfsharp/pull/2929

**Comment by cartermp** [comment] 2017-04-30 16:48
Closing as dupe of #2905

**Closed by cartermp** 2017-04-30 16:48 UTC
Labels: Feature Specification
