### ISSUE TITLE
F# intellisense errors even when the code builds just fine

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [Microsoft/visualfsharp#2550] opened 2017-03-08 13:47 UTC
Build compiles and runs fine. However on opening the solution, F# intellisense errors come up into the error list. Intellisense is lost in those areas, and I get red underlining. Many of the errors only show up when a file is open. So far in trying to look around at the code that causes this, it's been consistently around Type Provider provided types.

#### Repro steps

Have a type provider provided type and a locally defined record type with some similar property names/types

1. Step A

2. Step B

#### Expected behavior

Intellisense works, no red underlines for things that aren't errors and compile just fine
things that aren't errors at least would stop showing up in the error list when the file was closed
opening new files doesn't add to the error list, when there aren't actually any errors.

#### Actual behavior

Intellisense doesn't work, red underlines, errors accumulate while working with the solution that never go away
Warning	AD0001	Analyzer 'Microsoft.VisualStudio.FSharp.Editor.SimplifyNameDiagnosticAnalyzer' threw an exception of type 'System.Threading.Tasks.TaskCanceledException' with message 'A task was canceled.'.

#### Known workarounds

None, slight improvement from closing the solution and opening again, since the errors accumulate from opening more .fs files

#### Related information 

Provide any related information 

* Windows 10
* Branch? What branch? branch of what?
* .NET 4.5.2
* VS 2017 (Vs 2015 works fine)

**Comment by vasily-kirichenko** [comment] 2017-03-08 13:52
This is fixed in master.

**Comment by ImaginaryDevelopment** [comment] 2017-03-08 13:54
@vasily-kirichenko so yesterday, I tried to install some version from here over top of the VS2017 one, and it broke far worse, is there some additional information or specific downloads that do or don't work?
It appears the fake/intellisense errors eventually do go away

**Comment by majocha** [comment] 2017-03-08 14:05
@ImaginaryDevelopment  What you tried to install yesterday was OK, you only missed the step of dealing with unsigned dlls. Hopefully this one won't be needed once we have official signed builds.

> To install the Visual F# IDE Tools from Jenkins, first run sn.exe (Strong Name Tool) from the Visual Studio developer command prompt to turn off strong name checking on your machine:
> `sn -Vr *,*`

**Comment by ImaginaryDevelopment** [comment] 2017-03-08 14:40
what's the eta on that?

**Comment by asik** [comment] 2017-03-08 19:50
> Warning AD0001 Analyzer 'Microsoft.VisualStudio.FSharp.Editor.SimplifyNameDiagnosticAnalyzer' threw an exception of type 'System.Threading.Tasks.TaskCanceledException' with message 'A task was canceled.'.

Is this also fixed? It pops up constantly even on the simplest projects.

**Comment by smoothdeveloper** [comment] 2017-03-08 20:02
I've seen that message as well, a bit of time after opening a solution while waiting for colorization.

It did so on `FSharpDocumentDiagnosticAnalyzer`.

**Comment by vasily-kirichenko** [comment] 2017-03-08 20:26
Duplicate of https://github.com/Microsoft/visualfsharp/issues/2100. It marked to be fixed in RTM, so it's fixed you guys just cannot see it.

**Comment by BentTranberg** [comment] 2017-03-13 21:28
I believe there are at least three issues here. One of them is described only in the title itself, and is a duplicate of #2548. Then there is #2100. But I believe the rest of the report deals with "frenetic IntelliSense activity", which can pretty much cripple work with F# in VS 2017, but is fixed in the latest VSIX. I feel it important this be known. Thanks goes to Vasily Kirichenko for helping me with the installation (see #2548).

**Comment by cartermp** [comment] 2017-03-13 22:14
There is a related issue in VS feedback here: https://developercommunity.visualstudio.com/content/problem/24309/vs2017-fsharp-intellisense-across-projects.html

I'm looking at this today/tomorrow (busy around here for me right now...).  It's difficult to tease out the specific problems, but I think they should be much better once we get our nightly builds up.

**Comment by ImaginaryDevelopment** [comment] 2017-03-28 21:29
getting a ton of errors that aren't errors continues to plague after switching to nightly builds even. It makes it REALLY tough to find real errors when they exist.

**Comment by cartermp** [comment] 2017-03-28 22:27
@ImaginaryDevelopment Could you post a screenshot?

**Comment by BentTranberg** [comment] 2017-03-29 05:41
I used to have this problem, but it was fixed more than a week ago. I also configured nightly builds, and todays version of Visual F# Tools is 15.4.1.17032701. @ImaginaryDevelopment , which version do you have?

List of versions, with dates: https://dotnet.myget.org/feed/fsharp/package/vsix/VisualFSharp

**Comment by nethatix** [comment] 2017-03-29 11:50
Indeed the build issues are laid to rest with 15.4.1.17032701 and a **big thank you** for the nightly builds! But for those who don't want to burden their C# comrades with extra install requirements for F# are waiting for the IDE update :) Any ETA for that?

**Comment by cartermp** [comment] 2017-03-29 13:24
@nethatix Still TBD.  We haven't announced update times yet.  That said, the update model for VS 2017 is different than before.  We'll have an official update before the traditional "Update 1" timeframe.

**Comment by ImaginaryDevelopment** [comment] 2017-03-29 14:22
![image](https://cloud.githubusercontent.com/assets/121276/24459298/2eccd726-1469-11e7-9455-b31cf9d19c33.png)

FSharp tools version: 15.4.1.17032701 
![image](https://cloud.githubusercontent.com/assets/121276/24459352/51a41f0c-1469-11e7-8514-b419162bcc4a.png)

![image](https://cloud.githubusercontent.com/assets/121276/24459371/67193d04-1469-11e7-89c2-836be0c27158.png)

![image](https://cloud.githubusercontent.com/assets/121276/24459414/7f3f3cda-1469-11e7-8a59-ca269e61e51d.png)

All the fake errors appear to be related to using a type provider. Accessing fields of erased types.

packages\FSharp.Data.TypeProviders.5.0.0.2\lib\net40\FSharp.Data.TypeProviders.dll

**Comment by BentTranberg** [comment] 2017-03-29 15:01
The latest is VisualStudio/15.0.0+26228.10 which I noticed myself in "Updates" only this morning before my previous post, but I have no clue whether it can help with your case, @ImaginaryDevelopment.

**Comment by vasily-kirichenko** [comment] 2017-03-29 15:16
Is there an error squiggle at the left upper corner of the file? A very short one, at the first open statement? If it's there, what it says?

**Comment by ImaginaryDevelopment** [comment] 2017-03-29 15:43
@vasily-kirichenko  I don't have any red squiggles at the left upper corner of the files, in any open statements. Also I updated @BentTranberg that right after making the screenshots. There was no change in behavior.

**Comment by nethatix** [comment] 2017-03-29 20:32
Unfortunately, after a few hours, the intelligence errors came back on my combined c# (asp.net mvc)/f# 4.6.1 solution but not in the all f# 4.6.1 solution (sharing 2 f# projects). With this improved stability comes the challenge to replicate this now... This is with FSharp tools version: 15.4.1.17032701 installed.

**Comment by jmecosta** [comment] 2017-04-03 15:16
same problem here, and those annoying squiggle lines dont disappear from the source code after setting build only 

![image](https://cloud.githubusercontent.com/assets/1041352/24616365/99e02d4a-1899-11e7-8cb1-745e71150b99.png)

it happens when using type providers. and using latest nightly build

**Comment by dsyme** [comment] 2017-05-13 10:29
I've split out one specific problem with the error list here: https://github.com/Microsoft/visualfsharp/issues/3047

**Comment by dsyme** [comment] 2017-05-17 19:47
I'm going to close this until we have better repros for problems with the error list.  #3407 captures a very major source of bugs, and a fix is in progress (slowly because it requires a Roslyn fix), but I think there are other bugs too.

@jmecosta Can you isolate out that case as a specific bug report please?

**Comment by jmecosta** [comment] 2017-05-17 20:14
@dsyme i think its fine now from my side, ive upgraded to latest also also upgraded all fsharp.data packages and everything works as expected. thanks anyway

**Comment by BentTranberg** [comment] 2017-05-17 20:47
@dsyme, I think you meant #3047. (Please don't respond. I'll delete this later, to reduce noise.)

**Closed** 2017-05-18 01:01 UTC
Labels: Area-IDE Language Service, bug, Urgency-Now
